### ISSUE TITLE
[Bug]: Android 12 Geofencing fails with Exception

### ISSUE THREAD

**Issue by csharpcoder198** [shinyorg/shiny#1006]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

First off ios 15 (GeoFencing) is working brilliantly. Android 12 is the problem.
Steps to reproduce:

Second: I hope I have the desire nugets (2.51) for this report is what I have. Latest version on nuget is (3.0.0 Alpha)

1. Do a git clone of Samples repo
2. Open the GeoFencing ample solution
3. Ignore the Project not found dialogs
4. Ensure all Shiny nugets are at  2.51
5. Ensure that Android Target Framework is 12.
6. Build - Verify success
7. Attach Pixel 5 device running Android 12
8. Run App on device
9. Create a Geofence Record
11. Check Geofence Status is available
12.  Set Current location
13. give Geofence Row an identifier
14. Press upper right save button in toolbar
15. The application fails with: **"Targeting S+ (version 31 and above) requires that one of FLAG 
IMMUTABLE or FLAG MUTABLE be specified when creating a PendingIntent, Strongly consider using
FLAG IMMUTABLE, only use
FLAG MUTABLE If some...."**

![Screenshot_20220514-235248 (1)](https://user-images.githubusercontent.com/105575743/168482744-dc3bcba3-e845-4f3a-a910-6c6120d26225.png)

### Expected Behavior

The Geofence should be created and listed on main screen on Android 12

### Actual Behavior

The Geofence was not created or listed on main screen on Android 12. PendinIntentException was thrown

### Exception or Log output

**Sorry for the difficult formatting below. I was using OCR Tools on the Exception Dialog.**

ERROR: Java Lang Illeg

alArgumentException:

com.shiny.geofences:

Targeting S+ (version 31 and above) requires that one of FLAG IMMUTABLE or FLAG MUTABLE be specified when creating a PendingIntent, Strongly consider using

FLAG IMMUTABLE, only use

FLAG MUTABLE If some

functionality depends on the

PendingIntent being mutable,

e.g. if it needs to be used with

inline replies or bubbles.

at Java Interop. IniEnvironm ent+StaticMethods.CallStati cObjectMethod (Java. Inter op.JniObjectReference type, Java.Interop.JniMethodInfo

method, Java.Interop.JniArgu

mentValue* args) [0x0006e] in

<1921523bc22e4071a9a0855b

dae29335>:0 at Java Interop IniPeerMemb ers+JniStaticMethods.Invoke ObjectMethod (System.String

encodedMember, Java.in

terop. JniArgumentValue*

parameters) [0x00018] in

<1921523bc22e407fa9a0855b

dae29335>:0

at Android App Pendi ngintent GetBroadcast (Android.Content.Context context, System.Int32 requestCode,

Android.Content.Intent intent, A

ndroid. App.PendingintentFlags flags) [0x00070] in <1f18ef20dc 7d4d4196739d809db4caa6> 0 at Shiny Locations.GeofenceM anagerImpl.GetPendingIntent() [0x00035] in <a4558ebdaeef43 94b7f2e082eecba47e>:0

at Shiny Locations.GeofenceM

anagerImpl.Create (Shiny.Loca

tions.GeofenceRegion region)

[0x0009b] in <a4558ebdaeef43

94b712e082eecba47e>:0

at Shiny Locations.Geofence

ManagerImpl.StartMonitoring

(Shiny Locations.Geofence

Region region) [0x000f2] in

<a4558ebdaeef4394b7f2e082e ecba47e>:0 at Sample CreateViewModel+<>c_ DisplayClass0 0.<,.ctor>b 4 ()

[0x0073d] in <7184ff3dd49c44

808213b8deec638e4g>:0

-End of managed Java Lang

IllegalArgumentException stack

trace

java.lang.Illegal ArgumentExc

eption: com.shiny.geofences:

Targeting S+ (version 31

and above) requires that one

of FLAG_IMMUTABLE or

FLAG MUTABLE be specified

when creating a Pendingintent.

Strongly consider using

FLAG IMMUTABLE, only use

FLAG MUTABLE if some

functionality depends on the

Pendingintent being mutable,

e.g. if it needs to be used with

### Code Sample

instructions above and github provided
[](https://github.com/csharpcoder198/samples.git)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I just tested v2.5.1 in the samples and it works fine.  It is best not to use the samples for issues since sometimes they are on older versions.  The nuget packages also don't update with the standard nuget manager.

**Comment by aritchie** [comment]
You can upgrade Shiny packages look normal in your code.  My comment is with relation to the samples.  They are setup to debug local code or nuget packages.  You can't just use the nuget manager to update nuget packages in them.

I updated the sample to use 2.5.1, ran the test on my pixel without issue.

**Comment by csharpcoder198** [comment]
I do see that the Packages are likely the smoking gun on my system as  i see redundant packages after using the ide Pm tool.

I am only aware of 3 ways to update packages
1. in ide tool
2. using Package manager console 
3. using dotnet command line

What does it mean?
"You can upgrade Shiny packages look normal in your code."

**Comment by csharpcoder198** [comment]
Oh maybe i understand now.... Bring the source into the libs folder for 5 csproj files
1. Shiny.Core
2. Shiny.Jobs
3. Shiny.Locations
4. Shiny.Locations.Common
5. Shiny.Notifications

Is that your meaning?
