### ISSUE TITLE
[Bug]: Shiny.AndroidExtensions namespace and methods are not accesible in Android project on release v2.5.1

### ISSUE THREAD

**Issue by gsgou** [shinyorg/shiny#1010]
### Component/Nuget

Shiny.Core (Settings, Startup)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Add <PackageReference Include="Shiny" Version="2.5.1" /> in netstandard and android project.
Shiny.AndroidExtensions namespace and methods are not accesible in Android project. For example:

public static void ShinyOnCreate(this Application application, IShinyStartup? startup = null)
public static void ShinyOnRequestPermissionsResult(this Activity activity, int requestCode, string[] permissions, Permission[] grantResults)
are not found to bootstrap the project properly. In iOS everything works as before.

### Expected Behavior

Shiny.AndroidExtensions namespace and methods are found in assembly in Android project.

### Actual Behavior

Shiny.AndroidExtensions namespace and methods are not found in assembly in Android project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please read release notes, other issues, and check the nuget package targets before filing bugs like this.

You aren't targeting Android 12 as your major target if this is happening

**Comment by gsgou** [comment]
Thanks a lot @aritchie for your feedback. Targeting Android 12 fixed it.
