### ISSUE TITLE
[Bug]: Geofencing sample crashes after a few seconds

### ISSUE THREAD

**Issue by philwith** [shinyorg/shiny#1019]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [X] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

- Clone the geofencing sample
- Edit startup.cs to UseGpsDirectGeofencing
- Run sample on device
- Create Geofence

### Library Version

2.5.1

### Expected Behavior

App monitors location in real-time

### Actual Behavior

The app crashes after a few seconds

### Exception or Log output

[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.shiny.geofences, PID: 8789
[AndroidRuntime] android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{998086b u0 com.shiny.geofences/crc6461f3faed59cf0423.ShinyGpsService}
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2269)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:246)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8653)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
**Android.Util.AndroidRuntimeException:** 'Loading...'

### Code Sample

 // if you need some very real-time geofencing, you want to use below - this will really hurt your user's battery
services.UseGpsDirectGeofencing<GeofenceDelegate>();

### Code of Conduct

- [X] My reproducible sample is not from the Shiny samples repository
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Because I don't setup everything end to end.  There's a lot of functionality in Shiny.

This is why I ask users not to file issues with the samples.  If you can't be bothered to follow the rules (like checking the box that says "My reproducible sample is not from the Shiny samples repository" than please don't come back.

**Comment by philwith** [comment]
I won't
