### ISSUE TITLE
[Feature Request]: Support multiple file uploads in Shiny.Net.Http

### ISSUE THREAD

**Issue by rhinohq** [shinyorg/shiny#1026]
### Summary

The ability to upload multiple files with `Shiny.Net.Http` would be very useful in cases where a user selects multiple files/images to upload or when uploading a video and thumbnail together.

If there is an appetite for this feature, I do not mind picking up the work.

### API Changes

 I would suggest separating the `HttpTransferRequest` constructor into separate overloads for upload and download:

`public HttpTransferRequest(string uri, string localDownloadFilePath) : this(uri, new FileInfo(localDownloadFilePath)) { }`
`public HttpTransferRequest(string uri, FileInfo localDownloadFile)`
`{`
`    this.Uri = uri;`
`    this.LocalDownloadFile = localDownloadFile;`
 `   this.IsUpload = false;`
`}`

`public HttpTransferRequest(string uri, string[] localUploadPaths)`
`{`
`    this.Uri = uri;`
`    this.LocalUploadPaths = localUploadPaths;`
 `   this.IsUpload = true;`
`}`

This is, of course, open to discussion.

### Intended Use Case

See summary for some intended use cases but the many useful applications of this should be clear. Spinning up the handset's NIC for multiple individual uploads is power hungry and means extra server side logic to keep the uploads grouped. 

A single request with all necessary files would be very useful in cases such as a messaging app where the IM metadata is also held in the request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This isn't something that is well supported really at all by the platforms and isn't a feature I want to support
