### ISSUE TITLE
[Bug]: GPS IGpsDelegate.OnReading not fired realtime

### ISSUE THREAD

**Issue by Igor-ZA** [shinyorg/shiny#1028]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

[TestGPS.zip](https://github.com/shinyorg/shiny/files/8837333/TestGPS.zip)
![image](https://user-images.githubusercontent.com/56849652/171992418-42e352f3-b7a5-4057-9a93-e3969cd42c8b.png)
Not is fired when the gps reading has changed.

### Expected Behavior

When GPS data changes you fired events.

### Actual Behavior

Not is fired when the gps reading has changed.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
It's working fine for me.  Make sure your dataset is firing every second.

**Comment by Igor-ZA** [comment]
The my example is launched on a virtual device and there I set up fake GPS motion then it doesn't firing event.

**Comment by aritchie** [comment]
Your sample doesn't have the application icon (or a notification icon set) for the android foreground service to start.  Other than that, it works fine
