### ISSUE TITLE
[Bug]: If BeaconRanging isn't stopped by scanner.?Dispose() the BeaconService seems to continue in Background

### ISSUE THREAD

**Issue by michaelreinprecht** [shinyorg/shiny#1031]
### Component/Nuget

Beacons (Shiny.Beacons)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

Please note that I did not select an operation system since I had to use an **Android Samsung Galaxy S6** for testing, I know it is not supported. The library still seems to mostly work fine, ranging works properly. Also please note that I did NOT want to include Prism and ReactiveUI and this is why I used my own scheduler (it's the same as ReactiveUIs scheduler) and broke up the SubOnMainThread() method.

1. Create a new Xamarin Forms application with lastest Xamarin Nugets.
2. Create a rangingManager, a region for ranging (used default estimote), a scanner, start Ranging:
3. Debug the Application and start ranging.
4. Close Application, without stoping the scan beforehand.

I would be really thankful if you could help me out, and I'd also like to apologize beforehand, in case I'm wasting your time with this problem.

### Expected Behavior

The app stop ranging for beacons. The ranging process is either disposed or disposed by android after a while.

### Actual Behavior

The ranging process doesn't seem to stop. It keeps logging the following very frequently: 
[ScanRecord] Not a Multi Manu data
[ScanRecord] first manudata for manu ID
[ScanRecord] parseFromBytes

This even gets started up again if I uninstall the Application and restart the phone.
This also gets logged as debug while ranging in foreground (maybe android7 related?), even though it actually does find the beacons.

### Exception or Log output

I am very sorry for only including parts of the logs, but it would simply be a huge log file, because the [ScanRecord] gets logged extremly often, since I did not notice this problem while testing everything out and debugging. And after spending alot of time looking through the device logs, this was the only stuff I found that seems relevant to the problem.

DeviceLog keeps sending this even after a long time, uninstalling app and several restarts of my phone:

[ScanRecord] Not a Multi Manu data
[ScanRecord] first manudata for manu ID
[ScanRecord] parseFromBytes

DeviceLog after I restart my device, BeaconManager seems to start up a scan:

Time | Device Name | Type | PID | Tag | Message
-- | -- | -- | -- | -- | --
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 42040100, Mask:fffffd6c
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 42090104000200000021,   Mask:ffffffff0002000000a1
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 010002000001,   Mask:ffffff0000ff
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 010002000001,   Mask:ffffff0000ff
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - mLcdOnScanInterval: 2
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BleScanHelper.startBleScan - Start filter Scan(SCREEN_ON)
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BleScanHelper.directStopLeScan - call BleScanner.stopScan()
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.MSG_CALL_START_LESCAN -   ($)isFilterScanFailed/discovering:false/true
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BleScanHelper.startBleScan - startBleScan
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - ($)On Filter: 4, Off Filter: 2
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - Manager Type = 5, On Filter = 42040100,   On MASK = FFFFFD6C, Off filter = 4204010200, Off MASK = FFFFFDEE40, Interval   type = 2, working state = 3
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - Manager Type = 3, On Filter =   42090104000200000021, On MASK = FFFFFFFF0002000000A1, Off filter =   42090104000200000021, Off MASK = FFFFFFFF0002000000A1, Interval type = 2,   working state = 3
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - Manager Type = 2, On Filter =   010002000001, On MASK = FFFFFF0000FF, Off filter = null, Off MASK = null,   Interval type = 2, working state = 1
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.checkBeaconScanMode - Update BLE Scan
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.checkBeaconScanMode - mScanInfo  is{5=Manager Type = 5, On Filter =   42040100, On MASK = FFFFFD6C, Off filter = 4204010200, Off MASK = FFFFFDEE40,   Interval type = 2, working state = 3, 3=Manager Type = 3, On Filter =   42090104000200000021, On MASK = FFFFFFFF0002000000A1, Off filter =   42090104000200000021, Off MASK = FFFFFFFF0002000000A1, Interval type = 2,   working state = 3, 2=Manager Type = 2, On Filter = 010002000001, On MASK =   FFFFFF0000FF, Off filter = null, Off MASK = null, Interval type = 2, working   state = 1}
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconManager.BeaconManagerWorkHandler - MSG_UPDATE_SCAN_OPTION
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback - Manager:5
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback - Type:5
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | TvControlManager.registerBeaconListener - -- data --
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | TvControlManager.changeScanOption - filter Set to ALL_SCAN
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | TvControlManager.changeScanOption - old: 1 >> new :3
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | TvControlManager.MSG_TV_DISCOVERY_CHECK -
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | TvControlManager.ControlTvHandler    - handleMessage :2
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)mServiceConnection   mServiceStateCallback .onServiceConnected
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | TvControlManager.registerIntentProxy - Registered : count : 0
06.10.2022 11:26 | Samsung SM-G920F | Error | 9404 | BeaconManager | RegisterTvDBHelper.getRegisteredTvList    - Count:0
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | TvControlManager.registerIntentProxy - Ref Count / List size / ScanOption   :: 1 / 1 / SCAN_ALL_TV(2)
06.10.2022 11:26 | Samsung SM-G920F | Error | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)registerTvCallback   success : tvCallbackcom.samsung.android.oneconnect.net.BleHelper$5@1adc99f
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)mServiceConnection   onServiceConnected
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)BleScanManager   Handler bind *****
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)BleScanManager bind   ID com.samsung.android.library.beaconmanager.BleScanManager$1@404273e
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconService.onBind - mHasBindServices (true?): true
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconService.onBind - intent : com.samsung.android.oneconnect
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)BleScanManager   bindService
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)BleScanManager   Handler create *****
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9748 | BeaconManager | BleScanManager(160607)(com.samsung.android.oneconnect)BleScanManager bind   sendMessage
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconService.onStartCommand - intent : Intent {   cmp=com.samsung.android.beaconmanager/.BeaconService   launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9748 | oneconnect[1.0.00-49][100000049] | BleHelper.startScanByBeaconManager - new BleScanManager()
06-10 11:26:25.029 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 4204010200, Mask:fffffdee40
06-10 11:26:25.029 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 42090104000200000021,   Mask:ffffffff0002000000a1
06-10 11:26:25.029 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 010002000001,   Mask:ffffff0000ff
06-10 11:26:25.029 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - Filter: 010002000001,   Mask:ffffff0000ff
06-10 11:26:25.029 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.printFilterCondition - mLcdOnScanInterval: 2
06-10 11:26:25.029 | Samsung SM-G920F | Info | 9404 | BeaconManager | BleScanHelper.startBleScan - Start filter Scan(SCREEN_ON)
06-10 11:26:25.022 | Samsung SM-G920F | Info | 9404 | BeaconManager | BleScanHelper.directStopLeScan - call BleScanner.stopScan()
06-10 11:26:25.022 | Samsung SM-G920F | Info | 9404 | BeaconManager | FeatureUtil.isBleScanFilterSupported - isOffloadedFilteringSupported() :   enabled
06-10 11:26:25.014 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.MSG_CALL_START_LESCAN -   ($)isFilterScanFailed/discovering:false/false
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BleScanHelper.startBleScan - mLeRadioState is NONE
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BleScanHelper.startBleScan - startBleScan
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - ($)On Filter: 4, Off Filter: 2
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - Manager Type = 5, On Filter =   4204010200, On MASK = FFFFFDEE40, Off filter = 4204010200, Off MASK =   FFFFFDEE40, Interval type = 2, working state = 3
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - Manager Type = 3, On Filter =   42090104000200000021, On MASK = FFFFFFFF0002000000A1, Off filter =   42090104000200000021, Off MASK = FFFFFFFF0002000000A1, Interval type = 2,   working state = 3
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BleScanHelper.updateScanFilter - Manager Type = 2, On Filter =   010002000001, On MASK = FFFFFF0000FF, Off filter = null, Off MASK = null,   Interval type = 2, working state = 1
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.checkBeaconScanMode - Start BLE Scan
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.checkBeaconScanMode - mScanInfo  is{5=Manager Type = 5, On Filter =   4204010200, On MASK = FFFFFDEE40, Off filter = 4204010200, Off MASK =   FFFFFDEE40, Interval type = 2, working state = 3, 3=Manager Type = 3, On   Filter = 42090104000200000021, On MASK = FFFFFFFF0002000000A1, Off filter =   42090104000200000021, Off MASK = FFFFFFFF0002000000A1, Interval type = 2,   working state = 3, 2=Manager Type = 2, On Filter = 010002000001, On MASK =   FFFFFF0000FF, Off filter = null, Off MASK = null, Interval type = 2, working   state = 1}
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconManager.BeaconManagerWorkHandler - MSG_UPDATE_SCAN_OPTION
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback  - size is 0 or blocked:true
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback - Type:5
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | TvControlManager.registerBeaconListener - -- data --
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | TvControlManager.changeScanOption - filter Set to OOBE_SCAN
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | TvControlManager.changeScanOption - old: 0 >> new :1
06.10.2022 11:26 | Samsung SM-G920F | Warning | 9404 | BeaconManager | TvControlManager.changeScanOption    - need not. 0
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | TvControlManager.MSG_TV_DISCOVERY_CHECK -
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | TvControlManager.ControlTvHandler    - handleMessage :2
06-10 11:26:24.006 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BeaconManager.unregisterBeaconCallback - no info of managerType:4
06-10 11:26:24.006 | Samsung SM-G920F | Debug | 9404 | BeaconManager | RouterControlManager.changeScanOption - isOCFAvailable : false
06-10 11:26:24.004 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback  - size is 0 or blocked:true
06-10 11:26:24.003 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback - Type:3
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconService.onStartCommand - intent : Intent {   cmp=com.samsung.android.beaconmanager/.BeaconService   launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | RouterControlManager.init -
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | EasySetupManager.init -
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | TvControlManager.initalize - --
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BeaconManager.unregisterBeaconCallback - no info of managerType:1
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | AppControlManager.checkDiscoveryOption - stop scan for App Install
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | AppControlManager.isScanForAppInstall - Account is null
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback  - size is 0 or blocked:true
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.registernUpdateBeaconCallback - Type:2
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | AppControlManager.registerBeaconListener - -- data --
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | AppControlManager.checkDiscoveryOption - filter Set to WEARABLE
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | AppControlManager.init - init mCheckAppList.size() =1
06.10.2022 11:26 | Samsung SM-G920F | Error | 9404 | BeaconManager | AppControlManager.getAcoountHash - no samsung account
06.10.2022 11:26 | Samsung SM-G920F | Error | 9404 | BeaconManager | BeaconManager. init -  -- init --
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconManager.getInstance - make new instance   com.samsung.android.beaconmanager.a@af64651
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconManager.register observer -    --
06.10.2022 11:26 | Samsung SM-G920F | Error | 9404 | BeaconManager | wifiutils.hasSharableConfig - WPA_EAP
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | TvControlManager.TvControlManager    - mMyID is 32
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | AudioHelper.AudioHelper -
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BleScanHelper.BleHelper - Constructor
06.10.2022 11:26 | Samsung SM-G920F | Error | 9404 | BeaconManager | BeaconManager. mBeaconManagerWorkHandler - make beacon manager...
06.10.2022 11:26 | Samsung SM-G920F | Error | 9404 | BeaconManager | wifiutils.hasSharableConfig - WPA_EAP
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconManager.create -  --
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | BeaconManager | BeaconService.CreateBeaconManager    - create new Beacon Manager.
06.10.2022 11:26 | Samsung SM-G920F | Verbose | 9404 | BeaconManager | BeaconService.onCreate -
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BeaconBroadcastReceiver.onReceive - beaconmanager start
06.10.2022 11:26 | Samsung SM-G920F | Debug | 9404 | BeaconManager | BeaconBroadcastReceiver.onReceive - android.intent.action.BOOT_COMPLETED
06.10.2022 11:26 | Samsung SM-G920F | Warning | 9404 | System | ClassLoader referenced unknown path:   /system/priv-app/BeaconManager/lib/arm64
06.10.2022 11:26 | Samsung SM-G920F | Info | 3653 | ActivityManager | DSS on for com.samsung.android.beaconmanager and scale is 1.0
06.10.2022 11:26 | Samsung SM-G920F | Info | 9404 | SELinux | SELinux: seapp_context_lookup: seinfo=platform, level=s0:c512,c768,   pkgname=com.samsung.android.beaconmanager
06.10.2022 11:26 | Samsung SM-G920F | Info | 3653 | ActivityManager | Start proc 9404:com.samsung.android.beaconmanager/5006 for broadcast   com.samsung.android.beaconmanager/.BeaconBroadcastReceiver
06.10.2022 11:26 | Samsung SM-G920F | Debug | 3653 | MountService | getExternalStorageMountMode : final mountMode=1, uid : 5006, packageName   : com.samsung.android.beaconmanager

### Code Sample

In MainActivity OnCreate:
`this.Application.ShinyOnCreate(new ShinyBeaconStartup());`

In AppDelegate OnFinishedLaunching:
`this.ShinyFinishedLaunching(new ShinyBeaconStartup(), options);`

My Startup:
```
    public class ShinyBeaconStartup : FrameworkStartup
    {
        public override void ConfigureApp(Application app, IContainerRegistry containerRegistry)
        {
        }

        public override Task RunApp(INavigationService navigator) 
        {
            return null;
        }

        protected override void Configure(ILoggingBuilder builder, IServiceCollection services)
        {
            services.UseBeaconRanging();
        }
    }
```

My class used for ranging:
```
public static class MyBeaconService
{
    static readonly IBeaconRangingManager rangingManager;
    static BeaconRegion rangingRegion;
    static IDisposable scanner;

    // Logger for BeaconService.
    private static NLog.ILogger Log = LogManager.GetCurrentClassLogger();

    static MyBeaconService()
    {
        if (rangingManager == null)
        {
            rangingManager = ShinyHost.ServiceProvider.Resolve<IBeaconRangingManager>();
            rangingManager.RequestAccess();
        }
    }

    public static void SetRangingRegion(string identifier, string guid, ushort major, ushort minor)
    {
        rangingRegion = new BeaconRegion(identifier, Guid.Parse(guid), major, minor);
    }
    public static void SetRangingRegion(string identifier, string guid)
    {
        rangingRegion = new BeaconRegion(identifier, Guid.Parse(guid));
    }


    // Starts the beacon ranging. After you&#39;re done you should stop the scan with &lt;see cref=&quot;StopScan&quot;/&gt;
    public static void StartRanging()
    {
        if (rangingRegion != null)
        {
            try
            {
                if (scanner == null)
                {
                    scanner = rangingManager.WhenBeaconRanged(rangingRegion).ObserveOn(RxApp.MainThreadScheduler).Subscribe(
                    x =>
                    {
                        if (beacons.ContainsKey(x.Minor))
                        {
                            beacons[x.Minor] = new CustomBeacon(x, DateTime.UtcNow);
                        }
                        else
                        {
                            beacons.Add(x.Minor, new CustomBeacon(x, DateTime.UtcNow));
                        }
                        Log.Info("Ranging for beacons: " +x.Uuid + ", " +x.Major + ", " +x.Minor + ", " +x.Rssi);
                    },
                    ex => Log.Warn(ex.ToString(), "Beacon Scan Error")
                    );
                }
            }
            catch (Exception ex)
            {
                Log.Warn("Failed to scan for beacons, there might be something wrong with the beaconManager or your region settings.") ;
            }
        }
    }

    public static void StopRanging()
    {
        scanner?.Dispose();
        scanner = null;
    }
}
```

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
You have to cancel the ranging scan with dispose.  I don't do that for you.  There are ways I can do this by monitoring the app state but this isn't something I'm going to do.

The only way scanning would resume on a reboot is if you had a beacon being monitored.  Have you registered the monitor service as well?  Is the foreground serviced in Android starting?

**Comment by michaelreinprecht** [comment]
Ok thank you I can just make sure I allways call dispose you're right, I just didn't do it while testing it out.

And yes I did indeed register for monitoring aswell at some point. But calling await monitoringManager.StopAllMonitoring() does not stop it from logging. Am I right when I'm guessing that thats because it's another instance that I can not find once the app has been closed?

**Comment by aritchie** [comment]
I just don't have enough info.  The only way Shiny starts anything up automatically is with a ShinyStartupTask.  For beacons, that only on the monitoring side.  If the foreground service on droid is starting (an icon for your application in the tray), then monitoring is running.

If that foreground service isn't starting, then it is something you are doing in your code during a boot request.  I need more context in order to point you in any direction.  I tried commenting out the dispose in my apps.  The scan does keep going which is expected, but stops after a reboot.

**Comment by aritchie** [comment]
No.  You can't be certain at all monitoring is running.  You have to check if the android foreground service is running as I mentioned

**Comment by michaelreinprecht** [comment]
Since I'm at home right now I do not have access to the exact same code and I do not have the beacons nor the specific device with me, so I can not currently check if the foreground service is running. I am pretty sure I did not see any tray or notification though. I will try with a different android device as well to see if that might make a difference.

**Comment by aritchie** [comment]
Without a reproducible sample or additional info, this issue will have to be closed.

**Comment by michaelreinprecht** [comment]
After some more work: It was indeed monitoring that kept on running in the background. But as long as I do properly dispose of it it's not an issue.
