### ISSUE TITLE
[Bug]: No background GPS updates on IOS when app is closed

### ISSUE THREAD

**Issue by AndyCaignie** [shinyorg/shiny#1037]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

Deploy test app on IOS (test phone = iPhone SE)
Click on 'Start listening' and allow location rights
Change location rights in settings to 'always'
Click on Refresh to show GPS updates
Close app
After a few seconds the location icon disappears from the status bar
Reopen the app
Click on Refresh to show GPS updates -> no updates between close of app and restart
[Test Shiny GPS.zip](https://github.com/shinyorg/shiny/files/8999440/Test.Shiny.GPS.zip)

### Expected Behavior

GPS updates during time the app is closed

### Actual Behavior

No updates during app is closed

### Code of Conduct

- [x] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Also, what do you mean by "Close App"?  Do you mean "move it to the background" by going to the home screen or actually swiping it away?  If you are actually swiping it away, this will shutdown location.

**Comment by AndyCaignie** [comment]
OK I swipe it away, not move it to the background.
Of swiping it way stops the location then this explains it. Doing the same on Android does work.
I suppose there is no way to continue sending locations if the app is swiped away?

**Comment by aritchie** [comment]
No.  This is the way the platform works.  I would encourage you to take a look at the iOS documentation before filing bugs like this in the future as it will save us both time.
