### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 420tech** [shinyorg/shiny#1040]
### Component/Nuget

Jobs (Shiny.Jobs)

### What operating system(s) are effected?

- [X] iOS 12
- [X] iOS 13
- [X] iOS 14
- [X] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

Project was working as expected. Customer decided to lock down their Firebase Storage and add FCM Push Notifications. After adding those libraries, on iOS (not Android), Shiny job returns this error (non-fatal):
System.TypeLoadException: Could not load type of field 'CivicMobile.Services.TicketBackJob+<SendTicketBack>d8:<task>511' (14) due to: Could not resolve type with token 010001aa from typeref (expected class 'Firebase.Storage.FirebaseStorageTask' in assembly 'Firebase.Storage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Firebase.Storage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Firebase.Storage.FirebaseStorageTask member:(null)
  at CivicMobile.Services.TicketBackJob.Run (Shiny.Jobs.JobInfo jobInfo, System.Threading.CancellationToken cancelToken) [0x0019f] in /Users/timbelvin/Projects/css-mobile/CivicMobile/Services/TicketBackJob.cs:68 
  at Shiny.Jobs.AbstractJobManager.RunJob (Shiny.Jobs.JobInfo job, System.Threading.CancellationToken cancelToken) [0x000de] in <0aaa87f4327c44d1a84b5aac2261313b>:0

NOTE: we have been using FirebaseStorage.net all along - just added Firebase.Auth so we could login and retrieve custom claims.

### Expected Behavior

Expected it to just work (as all the Shiny stuff does so well!)

### Actual Behavior

Job never ran. Exception below

### Exception or Log output

System.TypeLoadException: Could not load type of field 'CivicMobile.Services.TicketBackJob+<SendTicketBack>d8:<task>511' (14) due to: Could not resolve type with token 010001aa from typeref (expected class 'Firebase.Storage.FirebaseStorageTask' in assembly 'Firebase.Storage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Firebase.Storage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Firebase.Storage.FirebaseStorageTask member:(null)
  at CivicMobile.Services.TicketBackJob.Run (Shiny.Jobs.JobInfo jobInfo, System.Threading.CancellationToken cancelToken) [0x0019f] in /Users/timbelvin/Projects/css-mobile/CivicMobile/Services/TicketBackJob.cs:68 
  at Shiny.Jobs.AbstractJobManager.RunJob (Shiny.Jobs.JobInfo job, System.Threading.CancellationToken cancelToken) [0x000de] in <0aaa87f4327c44d1a84b5aac2261313b>:0

### Code Sample

       public async Task Run(JobInfo jobInfo, CancellationToken cancelToken)
        {
            var runJob = false;

            var runDifference = DateTime.Now - settings.LastStatusJob;
            if (runDifference.Milliseconds > 200)
            {
                runJob = true;
                settings.LastStatusJob = DateTime.Now;
            }

            if (runJob)
            {
                MessagingCenter.Send<TicketBackJob, string>(this, "Job Started", $"{jobInfo.Identifier} Started");
                var loginResult = await RefreshToken();
                if (!loginResult)
                {
                    MessagingCenter.Send<TicketBackJob, string>(this, "Job Started", $"{jobInfo.Identifier} Delayed");
                    return;
                }
                var payload = jobInfo.GetParameter<Ticket>("Payload");
                await SendTicketBack(payload);
                var ticketBackResult = await ticketBackService.PostTicket(payload);
                var contractId = payload.Tickets[0].MaintenanceItems.FirstOrDefault()?.ContractId ?? 0;

                await Ticket.ClearTicket();
                var resultString = ticketBackResult.IsSuccessStatusCode ? "Success" : "Failure";
                MessagingCenter.Send<TicketBackJob, string>(this, "Job Finished", $"{jobInfo.Identifier} Finished with {resultString}");
                if (ticketBackResult.IsSuccessStatusCode)
                {
                    MessagingCenter.Send<TicketBackJob>(this, "Clear Ticket");
                    await ShowAlert();
                    await Ticket.ClearTicket();

                    var activityStatusPayload = new ActivityStatusPayload
                    {
                        ActivityStatusType = ActivityStatusType.ReturnedToDataStage,
                        ContractId = contractId
                    };

                    await activityStatusService.SendStatusJob(activityStatusPayload);
                }
            }
        }

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Not a bug with Shiny
