### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KAZUTO208** [shinyorg/shiny#1049]
### Component/Nuget

Other (Message Bus, Startup Task, NPC Persistence)

### What operating system(s) are effected?

- [X] iOS 12
- [X] iOS 13
- [X] iOS 14
- [X] iOS 15
- [X] Mac Catalyst
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [x] Android 12

### What platform(s) are effected?

- [X] MAUI
- [ ] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

Through NuGet I installed the following packages:
Shiny.Hosting.Maui
Shiny.Notification
SQLite
sqlite-net-pcl
Xamarin.AndroidX.Core
Xamarin.AndroidX.Lifecycle.Common
Xamarin.AndroidX.Lifecycle.Process
Xamarin.AndroidX.Work.Runtime
Xamarin.Firebase.Messaging
Xamarin.GooglePlayServices.Location

Then I tried to do the same with Shiny.Core but I got returned an error.

### Expected Behavior

The normal installation of Shiny.Core

### Actual Behavior

The installation of Shiny.Core returns an error

### Exception or Log output

Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Core da 1.8.0.1 a 1.7.0.2. Fare riferimento al pacchetto direttamente dal progetto per selezionare una versione diversa. 
 MauiApp2 -> Shiny.Core 3.0.0-alpha-0172 -> Xamarin.AndroidX.Core (>= 1.8.0.1) 
 MauiApp2 -> Xamarin.AndroidX.Core (>= 1.7.0.2)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Lifecycle.Common da 2.4.1.2 a 2.4.1.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Core 3.0.0-alpha-0172 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.2) 
 MauiApp2 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Lifecycle.Process da 2.4.1.2 a 2.4.1.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Core 3.0.0-alpha-0172 -> Xamarin.AndroidX.Lifecycle.Process (>= 2.4.1.2) 
 MauiApp2 -> Xamarin.AndroidX.Lifecycle.Process (>= 2.4.1.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.GooglePlayServices.Location da 119.0.1.1 a 119.0.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Notifications 3.0.0-alpha-0172 -> Shiny.Locations 3.0.0-alpha-0172 -> Xamarin.GooglePlayServices.Location (>= 119.0.1.1) 
 MauiApp2 -> Xamarin.GooglePlayServices.Location (>= 119.0.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Core da 1.8.0.1 a 1.7.0.2. Fare riferimento al pacchetto direttamente dal progetto per selezionare una versione diversa. 
 MauiApp2 -> Shiny.Notifications 3.0.0-alpha-0172 -> Xamarin.AndroidX.AppCompat 1.4.2.1 -> Xamarin.AndroidX.Core (>= 1.8.0.1) 
 MauiApp2 -> Xamarin.AndroidX.Core (>= 1.7.0.2)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Lifecycle.Process da 2.4.1.2 a 2.4.1.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Notifications 3.0.0-alpha-0172 -> Xamarin.AndroidX.AppCompat 1.4.2.1 -> Xamarin.AndroidX.Emoji2 1.1.0.2 -> Xamarin.AndroidX.Lifecycle.Process (>= 2.4.1.2) 
 MauiApp2 -> Xamarin.AndroidX.Lifecycle.Process (>= 2.4.1.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Lifecycle.Common da 2.4.1.2 a 2.4.1.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Notifications 3.0.0-alpha-0172 -> Xamarin.AndroidX.AppCompat 1.4.2.1 -> Xamarin.AndroidX.Lifecycle.Runtime 2.4.1.2 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.2) 
 MauiApp2 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Lifecycle.Common da 2.4.1.2 a 2.4.1.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Notifications 3.0.0-alpha-0172 -> Xamarin.AndroidX.AppCompat 1.4.2.1 -> Xamarin.AndroidX.SavedState 1.1.0.8 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.2) 
 MauiApp2 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Lifecycle.Common da 2.4.1.2 a 2.4.1.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Notifications 3.0.0-alpha-0172 -> Xamarin.AndroidX.AppCompat 1.4.2.1 -> Xamarin.AndroidX.Fragment 1.4.1.2 -> Xamarin.AndroidX.Lifecycle.LiveData.Core 2.4.1.2 -> 
Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.2) 
 MauiApp2 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: È stato rilevato il downgrade del pacchetto Xamarin.AndroidX.Lifecycle.Common da 2.4.1.2 a 2.4.1.1. Fare riferimento al pacchetto direttamente dal progetto per selezionare una 
versione diversa. 
 MauiApp2 -> Shiny.Notifications 3.0.0-alpha-0172 -> Xamarin.AndroidX.AppCompat 1.4.2.1 -> Xamarin.AndroidX.Activity 1.4.0.4 -> Xamarin.AndroidX.Lifecycle.ViewModelSavedState 2.4.1.2 -> 
Xamarin.AndroidX.Lifecycle.LiveData.Core 2.4.1.2 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.2) 
 MauiApp2 -> Xamarin.AndroidX.Lifecycle.Common (>= 2.4.1.1)
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Ripristino dei pacchetti non riuscito. Verrà eseguito il rollback delle modifiche per 'MauiApp2'.
In riga:1 car:1
+ Install-Package Shiny.Core -Version 3.0.0-alpha-0172
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

### Code Sample

None

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
PLEASE READ THE ISSUE TEMPLATE:  Please only file issues against the LATEST STABLE version of Shiny from Nuget.

The MAUI support is still alpha.  If you don't know how to work with it, don't.
