### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jerry1177** [shinyorg/shiny#1050]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [X] MAUI
- [ ] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

Install Shiny.BluetoothLE in new .Net MAUI project.

### Expected Behavior

I expect no errors from installation of nuget package.

### Actual Behavior

I get an androidX.Core  1.7.0.2 library is not compatible with .net6.0 platform errors.

### Exception or Log output

![shinyBLEErrors](https://user-images.githubusercontent.com/36937542/180622003-ffa16415-8662-4de2-84ae-d573b4e8ed26.PNG)

I get this androidX.Core  1.7.0.2 library is not compatible with .net6.0 platform errors.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
There is no alpha support.  Please read the issue template!!
