### ISSUE TITLE
[Bug]: Build / Run Issues

### ISSUE THREAD

**Issue by Goksly** [shinyorg/shiny#1058]
### Component/Nuget

Jobs (Shiny.Jobs)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

Add the latest stable packages to platform and share solutions.

Follow the quick start guide.

**Try to build android and get the following:**
'MainActivity' does not contain a definition for 'ShinyOnNewIntent' and no accessible extension method 'ShinyOnNewIntent' accepting a first argument of type 'MainActivity' could be found (are you missing a using directive or an assembly reference?)	'MainActivity' does not contain a definition for 'ShinyOnActivityResult' and no accessible extension method 'ShinyOnActivityResult' accepting a first argument of type 'MainActivity' could be found (are you missing a using directive or an assembly reference?)
'MainActivity' does not contain a definition for 'ShinyOnRequestPermissionsResult' and no accessible extension method 'ShinyOnRequestPermissionsResult' accepting a first argument of type 'MainActivity' could be found (are you missing a using directive or an assembly reference?)
'MainApplication' does not contain a definition for 'ShinyOnCreate' and no accessible extension method 'ShinyOnCreate' accepting a first argument of type 'MainApplication' could be found (are you missing a using directive or an assembly reference?)

**Try to run ios (builds successfully) and get the following:**
Could not load file or assembly 'Microsoft.VisualStudio.DesignTools.TapContract

If I undo the commented out code in the appdelegate / mainactivity, and remove the assembly reference in each - apps both load up fine.

I tried different versions and whilst I get different errors - none of the 3 I tried worked (I went with the versions in the samples etc - still no dice).

### Expected Behavior

The build and hit breakpoint in Shiny.Startup.

### Actual Behavior

Build error on Android.

Crash on iOS

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Shiny 2.5 targets android 12 as shown in the nuget targets.  You have to update your targets in your android head project.

Please don't send "no dice" with the samples.... send a reproducible sample.  Those samples compile and run just fine for me and I use jobs all over the place without issue.  You need to give me details if you want help with your issue.

**Comment by Goksly** [comment]
@aritchie thanks for coming back so quickly. After attempting to run with 2.55 I dropped back to 2.4.3.3024 and whilst the issues were different it still resulted in a crash. 

The "no dice" was purely down to the fact that I cloned and tried to run - unable to compile by what looked like nuget clashes. And then I read the notes on the repository and assumed that it was acceptable the samples didn't work due to all of the reasons in the readme.

I will put together some runnable examples as I'm sure that will be more helpful; what is the best way for you to receive such samples?

**Comment by aritchie** [comment]
I updated the jobs sample a few hours ago.  The only reason the samples don't often compile is because people have the wrong SDK's installed, they use an old version of VS, etc.  I also include the actual source of the current version as a submodule which people don't know how to clone.  They assume because the projects are missing (and thus not compiling) that the samples won't compile & run.... they will.

The best way to send a sample is to either a) create another github repo with it or 2) upload as a zip file

**Comment by aritchie** [comment]
This can be reopened when a proper reproducible sample has been submitted with a stack trace.
