### ISSUE TITLE
[Bug]: Cannot use Android hooks for startup in 2.5.x (non-alpha)

### ISSUE THREAD

**Issue by pellet** [shinyorg/shiny#1059]
### Component/Nuget

Other (Message Bus, Startup Task, NPC Persistence)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [X] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

Upgrade shiny from 2.4.x to 2.5.x(non pre-release)

### Expected Behavior

Calls to ShinyOnCreate from MainApplication will compile.

### Actual Behavior

Calls to ShinyOnCreate will no longer work.
This may be due to a change needed in nuget packaging.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Set your major target to android 12.  Please check the nuget packages in the future for their targets.

**Comment by pellet** [comment]
Thanks for the advice @aritchie do you know how I can check the package for it's android target?  Is this info on the nuget.org website or do I need to look at the source code?

**Comment by aritchie** [comment]
https://www.nuget.org/packages/Shiny.Core/2.5.5#supportedframeworks-body-tab

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/1431555/181663416-a73b24fc-58b0-4307-a93a-8d99ee1dbc87.png">

**Comment by pellet** [comment]
thanks, it wasn't showing up for me because of a bug in Rider 2022.2 EAP.  All sorted now.  Would be nice if there was a some sort of error message in the IDE or the build/nuget logs - I didn't notice any.
