### ISSUE TITLE
[Feature Request]: Scan without RequestAccess

### ISSUE THREAD

**Issue by salarcode** [shinyorg/shiny#1060]
### Summary

Currently the Scan method of BleManager is doing a RequestAccess all the time. The problem is it is asking for all bluetooth permissions, location included.
In my case I don't need location I only need scan and connect. But this requirement causes my app to have unnecessary permissions. 
And according to the [docs](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions) we can have the bluetooth without location permission in android 31 and later. 

I've created a permission class for MAUI that only requests the ones I want in Android:
https://gist.github.com/salarcode/da8ad2b993e67c602db88a62259d0456

### API Changes

Remove `RequestAccess` from `Scan` method. (or make it optional)

### Intended Use Case

Custom permissions for buetooth.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I certainly update the permission request.  It's been on my todo list for a while.  However, I won't be removing RequestAccess from Scan for a couple of reasons. 

* iOS essentially asks permissions immediately without RequestAccess getting involved
* Too many people just expect things to "work" immediately.

**Comment by salarcode** [comment]
I understand, how about making `RequestAccess` optional without breaking current behaviour?
for example
`IObservable<ScanResult> Scan(ScanConfig? config = null, bool requestAccess = true)`

**Comment by aritchie** [comment]
This still doesn't put things inline with iOS behaviour which is why I don't want to take it out.

Why do you want it removed if the permissions are adjusted?

**Comment by salarcode** [comment]
if permissions are adjusted so that we can choose which one want and don't want then yes it solved the problem.

**Comment by aritchie** [comment]
This is already available in v3-alphas and the shiny 2.6 when it is released

**Comment by salarcode** [comment]
Thanks 👍
