### ISSUE TITLE
[Bug]: Exception on startup: Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by gsgou** [shinyorg/shiny#1061]
### Component/Nuget

Other (Message Bus, Startup Task, NPC Persistence)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1. Create Xamarin Forms project with Shiny Core
2. 
```
Application.ShinyOnCreate(new XYZStartup()
            {
                RegisterPlatformServices = services =>
                {
                    services.AddSingleton<ISomeService, SomeService>();
                }
            });
```
called in MainActivity.cs in Android project

### Expected Behavior

No exception thrown

### Actual Behavior

sporadically Exception thrown
relates maybe to https://github.com/shinyorg/shiny/issues/447

### Exception or Log output

System.Exception: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'ApplicationContext' with type 'Android.App.Application'. Path 'Delegate.DrawerToggleDelegate.ActionBarThemedContext.ApplicationContext'. at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00107] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContainerContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonContract& memberContract, System.Object& memberValue) [0x000cd] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x0023a] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00007] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value) [0x00000] in <e292b62c6c6f46c0b1420af55423b3df>:0 at Shiny.Infrastructure.ShinySerializer.Serialize (System.Object value) [0x00000] in <f2a68061753f4b12a859f92e72574ee6>:0 at Shiny.Stores.SettingsKeyValueStore+<>c__DisplayClass11_0.<Set>b__0 (Android.Content.ISharedPreferences prefs, Android.Content.ISharedPreferencesEditor edit) [0x000b6] in <f2a68061753f4b12a859f92e72574ee6>:0 at Shiny.Stores.SettingsKeyValueStore.Do (System.Action`2[T1,T2] doWork) [0x0001f] in <f2a68061753f4b12a859f92e72574ee6>:0 at Shiny.Stores.SettingsKeyValueStore.Set (System.String key, System.Object value) [0x0001b] in <f2a68061753f4b12a859f92e72574ee6>:0 at Shiny.StoreExtensions.SetOrRemove (Shiny.Stores.IKeyValueStore store, System.String key, System.Object value) [0x00011] in <f2a68061753f4b12a859f92e72574ee6>:0 at Shiny.Stores.ObjectStoreBinder.OnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs args) [0x0007e] in <f2a68061753f4b12a859f92e72574ee6>:0 at MediaManager.NotifyPropertyChangedBase.OnPropertyChanged (System.String propertyName) [0x00012] in <9ae0f5d6d3c1400a9291bd3345e2b7ba>:0 at MediaManager.NotifyPropertyChangedBase.SetProperty[T] (T& storage, T value, System.String propertyName) [0x0001c] in <9ae0f5d6d3c1400a9291bd3345e2b7ba>:0 at MediaManager.MediaManagerImplementation.set_Context (Android.Content.Context value) [0x00000] in <9ae0f5d6d3c1400a9291bd3345e2b7ba>:0 at MediaManager.MediaManagerExtensions.Init (MediaManager.IMediaManager mediaManager, Android.Content.Context context) [0x00007] in <9ae0f5d6d3c1400a9291bd3345e2b7ba>:0 at Demo.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0004d] in <5a02bf6041e54e55ac86adee6ff2b02c>:0 at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <674c5335675348a7b53b6aea93c98613>:0 at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0) [0x00005] in <674c5335675348a7b53b6aea93c98613>:0

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is not an acceptable filing.  You need to give a reproducible sample, not something random that I have to guess with.

Read your stack trace
