### ISSUE TITLE
Tapping on Android Notification always re-starts running singleTask MainActivity

### ISSUE THREAD

**Issue by cpraehaus** [shinyorg/shiny#107]
First of all a big thank you for all your great projects. I especially like BluetoothLE and Notifications.
The issue reported here is not a bug in Shiny.Notifications but a special case of Android.

Thanks in advance for looking at it.
Kind regards,
Christian.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

https://stackoverflow.com/questions/28258404/singletask-and-singleinstance-not-respected-when-using-pendingintent

 - [ ] iOS
 - [ x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.357-beta / master (SHA b02f006848bd0de7fae7d1b997cc7eec8eaef6ff)
## Version of OS(s) listed above with issue
Android 5.1.1

## Steps to Reproduce
1. Create a simple Xamarin Android App with a single MainActivity with LaunchMode = LaunchMode.SingleTask 
2. Send a notification at app start using Shiny with LaunchActivityFlags = AndroidActivityFlags.NewTask
   (Note: in this example we do not want the default of AndroidActivityFlags.NewTask | AndroidActivityFlags.ClearTask)
3. Launch the app and tap on the notification

## Expected Behavior
For the MainActivity with LaunchMode.SingleTask I would expect that 
the notification intent is delivered to the running MainActivity through its OnIntentReceived() method
bringing the App (MainActivity) to foreground if required (e.g. if user changed to Home screen in the meantime).

## Actual Behavior
Android always starts a new activity (MainActivity) and destroys the old one.

The reason is that the TaskStackBuilder used by NotificationManager always adds the following flags
to the launch intent: NEW_TASK | CLEAR_TASK | TASK_ON_HOME
This behaviour does not work well with singleTask/singleInstance activities.

I added a work-around in Shiny which works for me but I'm not sure about possible side-effects for other users.

```
// TaskStackBuilder always clears an existing task stack, i.e. it implicitly adds
// the ClearTask flag (besides NewTask), thereby creating a new activity.
// This is not always what the notification user expects.
// For example, if the target activity is marked with launch mode SingleTask in the
// Android manifest and the notification LaunchActivityFlags only contains NewTask, the client
// would expect that an existing instance of the target activity is re-used (not re-started)
// by sending the intent using Activity.OnNewIntent(). However, if we'd use TaskStackBuilder
// in this scenario than a new activity is created and the old one is destroyed (details
// may vary depending on other intent flags).
// The following is used as simple heuristic that should fit most situations:
// If ClearTask is set in LaunchActivityFlags (or left at default) we can assume
// that this behaviour is OK.
// If the user explicitly does not want ClearTask, e.g. by setting LaunchActivitiyFlags = NewTask,
// we better don't use TaskStackBuilder and fall-back to PendingIntent.GetActivity().
PendingIntent pendingIntent; 
if ((notification.Android.LaunchActivityFlags & AndroidActivityFlags.ClearTask) != 0)
{
	pendingIntent = TaskStackBuilder
		.Create(this.context.AppContext)
		.AddNextIntent(launchIntent)
		.GetPendingIntent(notification.Id, PendingIntentFlags.OneShot);
	//.GetPendingIntent(notification.Id, PendingIntentFlags.OneShot | PendingIntentFlags.CancelCurrent);
}
else
{
	pendingIntent = PendingIntent.GetActivity(this.context.AppContext, notification.Id, launchIntent, PendingIntentFlags.OneShot);
}
```

**Comment by aritchie** [comment]
You can configure the LaunchActivityFlags to be whatever you want in the notification object that you pass to send.  You can also set them globally using 
Shiny.Notifications.AndroidOptions.DefaultLaunchActivityFlags = whatever you want

**Comment by aritchie** [comment]
I see your fix.  You should send PRs

**Comment by cpraehaus** [comment]
Hi Allan,

Thanks, it works for me now (tested with 1.0.0.391-beta).

Kind regards,
Christian.
