### ISSUE TITLE
[Bug]: Beacons: Accuracy is always -1 on Android

### ISSUE THREAD

**Issue by salibi-chemrade** [shinyorg/shiny#1070]
### Component/Nuget

Beacons (Shiny.Beacons)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1. Use the provided sample code
2. Start scanning for a valid UUID 
3. The app prints information (including accuracy) of found beacons

### Expected Behavior

Accuracy is a value representing distance in meters

### Actual Behavior

Accuracy is always -1 

### Code Sample

[BeaconTest.zip](https://github.com/shinyorg/shiny/files/9300187/BeaconTest.zip)

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by salibi-chemrade** [comment]
Looking into the source code, I wonder if the following conditional is causing the issue

https://github.com/shinyorg/shiny/blob/803d50a2857ccd6df02ac99b030d9e39be05c855/src/Shiny.Beacons/BeaconExtensions.cs#L78

Isn't rssi always represented as a negative integer?

**Comment by aritchie** [comment]
This is fixed as part of the next major version
