### ISSUE TITLE
[Bug]: ScanForUniquePeripherals not detecting available peripherals on some Android devices [LEGACY]

### ISSUE THREAD

**Issue by DieselSoup** [shinyorg/shiny#1072]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [X] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

1. Install Shiny.Core and Shiny.BluetoothLE 2.0.0.2655 in Core and Android projects
2. Install MvvmCross in Core and Android projects.
3. Create `ShinyStartup.cs` class containing `UseBleClient()` reference.
4. Register `IBleManager`using `IMvxIoCProvider.LazyConstructAndRegisterSingleton(() => Shiny.ShinyHost.Resolve<IBleManager>());`
5. Create Service class that takes IBleManager as a constructor argument.
6. Invoke `IBleManager.ScanForUniquePeripherals()` in Service class.

### Expected Behavior

`IBleManager.ScanForUniquePeripherals()` returns a set of discoverable peripherals for all device types.

For example, the method should return an `IObservable<IPeripheral>` when the code runs on the following device types:

- Samsung Galaxy S10
- Samsung Galaxy A53
- Google Pixel 3A XL

### Actual Behavior

IBleManager.ScanForUniquePeripherals only returns an `IObservable<IPeripheral>` on the Galaxy S10. When the code runs on the other two devices, no peripherals are found.

All devices are running the same version of Android (12).

Has this issue ever come up before? Has it been fixed in a later release? 

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
1. Please be respectful of the code of conduct that clearer states the latest STABLE version!

2.
> Has this issue ever come up before? Has it been fixed in a later release?
Check the github issues!

3. You need to provide samples and do some of your own investigation since I don't have access to said devices.  In this case, if you look at the source code for what ScanForUniquePeripherals, you'll notice hardly does anything accept performing a distinct on the peripheral UUID.

**Comment by DieselSoup** [comment]
@aritchie Your third point actually led me to source of the problem. It turns out the two devices that weren't detecting peripherals did not have their location services turned on. Apologies, and many thanks.
