### ISSUE TITLE
[Feature Request]: Kindly provide support for Bluetooth and BLE with Shiny packages for MAUI

### ISSUE THREAD

**Issue by yoganathan55** [shinyorg/shiny#1073]
### Summary

Kindly include support for Bluetooth BLE package for MAUI

### API Changes

None

### Intended Use Case

Most of the user have bluetooth BLE,it will be very good if shiny provide support for bluetooth BLE so that my BLE supported app can run seamlessly across android/ios/mac/windows.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Check the readme - there has been an alpha for NET6 & MAUI for 2 months now.  You can follow the release notes here: http://shinylib.net/release-notes/mobile/vnext.html
