### ISSUE TITLE
[Bug]: Android Permission Issue, 

### ISSUE THREAD

**Issue by salarcode** [shinyorg/shiny#1078]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [X] MAUI
- [ ] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

BleManager "Scan" throws exception on Android 8 and later, but works fine in Android 12.

Scan works in Shiny.BluetoothLE version "3.0.0-alpha-0181" but all versions after that has this problem. I've also tested the recent version "3.0.0-alpha-0283"

(All permissions mentioned in the exception are defined in "AndroidManifest.xml")

### Expected Behavior

Scan working.

### Actual Behavior

Exception is thrown

### Exception or Log output

Exception log
```
System.InvalidOperationException: Invalid Status: NotSetup - Ensure you have the following permissions in your AndroidManifest.xml - android.permission.ACCESS_FINE_LOCATION, android.permission.BLUETOOTH_SCAN, & android.permission.BLUETOOTH_CONNECT
   at Shiny.BluetoothLE.BleManager.<>c__DisplayClass9_0.<Scan>b__0(AccessState access)
   at System.Reactive.Linq.ObservableImpl.Do`1.OnNext._[[Shiny.AccessState, Shiny.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].OnNext(AccessState value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:line 38
--- End of stack trace from previous location ---
   at BluetoothService.<>c__DisplayClass31_0.<<ScanAndConnect>g__ScanIt|0>d.MoveNext() in ...
```

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I just tried it and it runs fine other.  Only the message is wrong.  Please follow the code of conduct of this library.  I am not supporting the alphas at this time.

**Comment by salarcode** [comment]
This is not a support request! this is bug report on a alpha version

Anyway, checking the code I found that you've added a new permission "BLUETOOTH_PRIVILEGED", adding that and now it is `RequestAccess` that is complaining. Removing "RequestAccess" in the code seems to be working

I'm attaching the sample project here.
[ShinyBleTest.zip](https://github.com/shinyorg/shiny/files/9436496/ShinyBleTest.zip)

**Comment by aritchie** [comment]
I am not taking issues for anything not in the stable release.  It says that right in the issue template.  I haven't finished a ton of things within the alpha.  Please be respectful of this.
