### ISSUE TITLE
[Bug]: BluetoothPrivileged permission always denied resulting in ble Scan not working on Android 9 

### ISSUE THREAD

**Issue by tentom** [shinyorg/shiny#1088]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [X] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

Set up scan for ble device and start a scan on a device running Android 9. 

```
var bleManager = Shiny.ShinyHost.Resolve<Shiny.BluetoothLE.IBleManager>();
accessStatus = await bleManager.RequestAccess();
```

### Expected Behavior

Everything works and nearby devices are returned in the OnScanResult method when executing: 

```
var bleManager = Shiny.ShinyHost.Resolve<Shiny.BluetoothLE.IBleManager>();
accessStatus = await bleManager.RequestAccess();
var bleAdapterScan = bleAdapter.Scan(new SensorConfig()).Subscribe(OnScanResult);
```

### Actual Behavior

Nothing is returned and when asking for permissions they are denied. 

Running 

```
var bleManager = Shiny.ShinyHost.Resolve<Shiny.BluetoothLE.IBleManager>();
accessStatus = await bleManager.RequestAccess().Timeout(TimeSpan.FromMilliseconds(ConnectionTimeoutInMs));
```
returns denied.

The following code execute as expected but is only a workaround Android. 
```
var managerCtxt = Shiny.ShinyHost.Resolve<Shiny.BluetoothLE.Internals.ManagerContext>();
var bleAdapterScan = managerCtxt.Scan(new SensorConfig()).Subscribe(OnScanResult);
```

Checking what permissions that is not given to us by executing a call to `managerCtxt.Android.RequestPermissions()` gave true for all of the permissions in the following list except for the BluetoothPrivileged permission
```
list.AddRange(new[] {
                Manifest.Permission.Bluetooth,
                Manifest.Permission.BluetoothPrivileged,
                Manifest.Permission.BluetoothAdmin,
                Manifest.Permission.AccessFineLocation
            });
```

I found #202 That got me wondering if this permission is ever needed. Google also have this permission as "Not for use by third-party applications" but I could not figure out what exactly what that implies.

If the BluetoothPrivileged is not needed I would think that removing it from the check should fix this issue.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by ExelorAG** [comment]
Having same problem on Android 10. What is the reason to have BLUETOOTH_PRIVILEGED here? Looking at Android docs I think it does not need to be in library code as most use cases do not need it and it is not for third-party apps. [Manifest Permission Reference](https://developer.android.com/reference/android/Manifest.permission.html#BLUETOOTH_PRIVILEGED)

**Comment by aritchie** [comment]
It is needed for pairing operations.  I already have removed the permission check on the 2.6 branch.  I'll try to push out a release today.

**Comment by ExelorAG** [comment]
Oh, ok, then I must have looked into the wrong branch. Didn't see that. Thank you very much. Concerning us, no need to hurry for the release.

**Comment by aritchie** [comment]
Part of 2.6.3
