### ISSUE TITLE
System.ArgumentNullException thrown in BluetoothLE library

### ISSUE THREAD

**Issue by Heisenbergz** [shinyorg/shiny#109]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [X] Core
 - [X] BluetoothLE
 - [X] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.375 - beta

## Version of OS(s) listed above with issue
Android 9.0

## Steps to Reproduce
1. Fire method `builder.UseBeacons<BeaconDelegate>();` in the `ConfigureServices` method in `Startup` class

## Expected Behavior
Service is started

## Actual Behavior
`System.ArgumentNullException` is thrown in library. Looks like the issue is in this line of commit: 33ad78f#diff-ad5986548930ef13a0073f9a490ee6acR17 as we are push null parameter into `AddSingleton` method and this is exactly the issue description Im getting in the stack trace. Full stack trace can be found below:

`at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton[TService] (Microsoft.Extensions.DependencyInjection.IServiceCollection services, TService implementationInstance) [0x00016] in <32c7da0bde3e4433b1fa3a6000248638>:0 at Shiny.BluetoothLE.Central.BleCentralShinyModule.Register (Microsoft.Extensions.DependencyInjection.IServiceCollection services) [0x00008] in d:\a\1\s\src\Shiny.BluetoothLE\Central\Platforms\Android\BleCentralShinyModule.cs:17 at Shiny.ServiceExtensions.RegisterModule (Microsoft.Extensions.DependencyInjection.IServiceCollection services, Shiny.IShinyModule module) [0x00000] in d:\a\1\s\src\Shiny.Core\Extensions_Services.cs:145 at Shiny.ServiceCollectionExtensions.UseBleCentral (Microsoft.Extensions.DependencyInjection.IServiceCollection builder, Shiny.BluetoothLE.Central.BleCentralConfiguration config) [0x00000] in d:\a\1\s\src\Shiny.BluetoothLE\Platforms\Shared\ServiceCollectionExtensions.cs:26 at Shiny.ServiceCollectionExtensions.UseBeacons (Microsoft.Extensions.DependencyInjection.IServiceCollection builder) [0x00000] in d:\a\1\s\src\Shiny.Beacons\Platforms\Shared\ServiceCollectionExtensions.cs:23 at Shiny.ServiceCollectionExtensions.UseBeacons[T] (Microsoft.Extensions.DependencyInjection.IServiceCollection builder, Shiny.Beacons.BeaconRegion[] regionsToMonitorWhenPermissionAvailable) [0x0000d] in d:\a\1\s\src\Shiny.Beacons\Platforms\Shared\ServiceCollectionExtensions.cs:46 at ShinyBeaconsTest.Startup.ConfigureServices (Microsoft.Extensions.DependencyInjection.IServiceCollection builder) [0x00001] in /Users/lukasz.szczerbinski/Projects/ShinyBeaconsTest/ShinyBeaconsTest/Startup.cs:21 at Shiny.ShinyHost.InitPlatform (Shiny.IShinyStartup startup, System.Action1[T] platformBuild) [0x00006] in d:\a\1\s\src\Shiny.Core\ShinyHost.cs:84
at Shiny.AndroidShinyHost.Init (Android.App.Application androidApp, Shiny.IShinyStartup startup, System.Action1[T] platformBuild) [0x00014] in d:\a\1\s\src\Shiny.Core\Platforms\Android\AndroidShinyHost.cs:24 at Shiny.ShinyAndroidApplication1[T].OnCreate () [0x00006] in d:\a\1\s\src\Shiny.Core\Platforms\Android\ShinyAndroidApplication.cs:33
at ShinyBeaconsTest.Droid.MainApplication.OnCreate () [0x00001] in /Users/lukasz.szczerbinski/Projects/ShinyBeaconsTest/ShinyBeaconsTest.Android/MainApplication.cs:16
at Android.App.Application.n_OnCreate (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in :0
at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr)`

**Comment by aritchie** [comment]
Fixed in latest nuget beta
