### ISSUE TITLE
[Feature Request]: Find devices with BluetoothDeviceType.Unknown

### ISSUE THREAD

**Issue by Codelisk** [shinyorg/shiny#1095]
### Summary

At the moment for BleManager.GetPairedPeripherals and GetConnectedPeripherals there is this Where condition:
`x => x.Type == BluetoothDeviceType.Dual || x.Type == BluetoothDeviceType.Le`

Unfortunately some printers we connect with in our Application (Sunmi) have the BluetoothDeviceType.Unknown.

If it would be okay I would create a PR for the possibiliy to add DevicesTypes to check for.

### API Changes

Either a static variable AdditionalDeviceTypesToCheckFor somewhere
```
Or public override IObservable<IEnumerable<IPeripheral>> GetConnectedPeripherals(string? serviceUuid = null, params BluetoothDeviceType[] additionalDeviceTypesToCheck)
public IObservable<IEnumerable<IPeripheral>> GetPairedPeripherals()
```

### Intended Use Case

Find Sunmi Bluetooth devices

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I can definitely open this up, however, are you sure that it is going to allow connections?  It is odd that it isn't advertising properly.

**Comment by Codelisk** [comment]
Yeah for this specific device it was possible to connect and print on it.

**Comment by Codelisk** [comment]
Okay tested it unfortunately I can connect to it.

I can only write to it like that.

_public async Task PrintOnUnknownBondedDeviceAsync(string deviceName, byte[] bytes)
        {
            using (BluetoothAdapter bluetoothAdapter = BluetoothAdapter.DefaultAdapter)
            {
                BluetoothDevice device = (from bd in bluetoothAdapter?.BondedDevices
                                          where bd?.Name == deviceName
                                          select bd).FirstOrDefault();
                try
                {
                    using (BluetoothSocket bluetoothSocket = device?.
                        CreateRfcommSocketToServiceRecord(
                        Java.Util.UUID.FromString("00001101-0000-1000-8000-00805f9b34fb")))
                    {
                        int addition = 60;
                        bluetoothSocket?.Connect();
                        for (int i = 0; i < bytes.Length; i = i + addition)
                        {
                            if (bytes.Length < i + addition)
                            {
                                addition = bytes.Length - i;
                            }
                            bluetoothSocket?.OutputStream.Write(bytes, i, addition);
                            await Task.Delay(100);
                        }
                        bluetoothSocket.Close();
                    }
                }
                catch (Exception exp)
                {
                    throw exp;
                }
            }
        }_

**Comment by aritchie** [comment]
And that is actually a classic bluetooth connection which is only supported on Android, Windows, and somewhat through the "made for iphone/ipad" program. It isn't something that will be part of Shiny.
