### ISSUE TITLE
IsConnectable Issue

### ISSUE THREAD

**Issue by fryette** [shinyorg/shiny#11]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [x] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.172

## Expected Behavior
Not to crash

## Actual Behavior
Crash

I checked Bluetooth LE in Shiny and figured out that if you try to use `IsConnectable` property you have a crash on Android 7-. So, it would be better if the library can handle it. 
Also, users need to spend time to realize the root cause. I Found a comment in the source code that this property supported only in Android 8+
https://github.com/shinyorg/shiny/blob/1d8d4f97b961a6e5b42105df7678adf6ea95f747/src/Shiny.BluetoothLE/Central/Platforms/Android/AdvertisementData.cs
It would be better to have the description in order to be able to see that this property supported only for several android versions.

**Comment by aritchie** [comment]
Thanks for the help
