### ISSUE TITLE
[Bug]: Foreground jobs not started until application switched between Background and Foreground modes

### ISSUE THREAD

**Issue by borninmusic** [shinyorg/shiny#1105]
### Component/Nuget

Jobs (Shiny.Jobs)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1. Wire things up as per README.
2. Create new `JobInfo` with `RunOnForeground` prop set to `TRUE` in `Configure` method of Startup.cs class
3. Register new job using `services.RegisterJob`

### Expected Behavior

Job starts running in a while in a repeated fashion (f.i. gets called every 30 seconds)

### Actual Behavior

Job is not started until you put an app in Background mode, then in Foreground

### Code Sample

```
    public class Startup : FrameworkStartup
    {
        // use the navigator to go to your starting page
        public override async Task RunApp(INavigationService navigator)
        {
            await navigator.NavigateAsync(nameof(MainPage));
        }

        public override void ConfigureApp(Application app, IContainerRegistry containerRegistry)
        {
            // configure all of your Prism navigation and foreground only services here!
            containerRegistry.RegisterForNavigation<MainPage, MainPageViewModel>();
        }

        protected override void Configure(ILoggingBuilder builder, IServiceCollection services)
        {
            // register all of your Shiny services and background infrastructure here

            var job = new JobInfo(typeof(ProcessPendingTranscriptionsJob), ProcessPendingTranscriptionsJob.JobName)
            {
                //works only on Android and UWP
                PeriodicTime = TimeSpan.FromSeconds(30),
            
                RunOnForeground = true,
                RequiredInternetAccess = InternetAccess.Any
            };
            
            services.RegisterJob(job, true);
        }
    }

    public class ProcessPendingTranscriptionsJob : IJob
    {
        public static readonly string JobName = nameof(ProcessPendingTranscriptionsJob);

        public async Task Run(JobInfo jobInfo, CancellationToken cancelToken)
        {
             Console.WriteLine("This is a message from ProcessPendingTranscriptionsJob");
        }
    }
}
```

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is fixed in 2.7
