### ISSUE TITLE
[Bug]: Geofencing events not triggered without Google maps running in foreground on Android

### ISSUE THREAD

**Issue by dinonovak** [shinyorg/shiny#1113]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [x] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

Using latest Shiny.Net Geofencing Sample
Run it on actual device
 

### Expected Behavior

OnEnter, OnExit should be triggered without Google Maps running in the foreground

### Actual Behavior

Running Geofencing sample on. actual device (Samsung Galaxy A03s), geofencing events OnEnter, OnExit are not triggered.
When running Google Maps app in foreground (where location is constantly updated while moving), OnEnter, OnExit are triggered

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
It's clear you're new to open source and mobile dev, but you need to follow the code of conduct for this project.  There is a checkbox that specifically says "My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!"

This is not a bug.  Geofences are not real time and they only fire when the device gets a GPS hit which will be happening real time when google maps is on

**Comment by aritchie** [comment]
> I am running 2 geofencing apps in parallel on the device, your Shiny Geofencing sample and myTestApp (created with latest nuggets, ... so fully in line with Code of Conduct)
Your defect is filed against the sample - I have no repro case from you, so no - YOU ARE NOT fully inline with the coc.  

GPS works just fine in the background on all of my devices.  What device are you having this issue on?

I won't be changing the geofence mechanism, since it just uses the standard flow from Google.  If you need "forced" GPS geofencing, there is this: https://github.com/shinyorg/shiny/blob/260-dev/src/Shiny.Locations/GpsGeofenceManagerImpl.cs

**Comment by dinonovak** [comment]
hi @aritchie 
here is the sample https://gitlab.com/dn-misc/imotageolocation
and to make things easy I am attaching GPX file so it can be tested in simulator as is.

Also please note that there is location part in the app, but is currently not enabled (is commented out)

[activity_jarun.gpx.zip](https://github.com/shinyorg/shiny/files/9735257/activity_jarun.gpx.zip)

**Comment by aritchie** [comment]
I appreciate you're having an issue, but there is nothing here I can test with because these scenarios are working fine for me.  This sample is basically a copy of my sample, so that's not helpful either.  

I've given you a suggestion you can try, but other than that - that's as far as I can go.

**Comment by dinonovak** [comment]
I put location part and service in the same sample because location updates are not triggering also.
GPS is active, realtime mode with shiny service started and same behaviour.
OnReading(IGpsReading reading) not triggered unless google maps is in foreground.
so there is some link here
