### ISSUE TITLE
[Bug]: Java.lang.NoSuchFieldError: No field No_Options at com.google.android.gms.location.GeoFencingClient

### ISSUE THREAD

**Issue by alamzaib-farooq** [shinyorg/shiny#1114]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1. Add Shiny
2. Integrate with Prism
3. Add geogencing service.

### Expected Behavior

The app should start. 

### Actual Behavior

The app is crashing. 

### Exception or Log output

![Screenshot 2022-10-08 155409](https://user-images.githubusercontent.com/25901497/194703928-0a48c936-c637-48de-a1df-4886c0adf401.png)

### Code Sample

Permissions:

`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
	<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
	<uses-feature android:name="android.hardware.location.gps" android:required="false" />
	<uses-feature android:name="android.hardware.location.network" android:required="false" />`

My Startup class (I am using Prism): 
 ' public class Startup : ShinyStartup
    {

        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
           
            services.UseGeofencing<GeofenceDelegate>();
            services.UseNotifications();
            services.UseGps();
            Console.WriteLine("Shiny Added");
        }

        public override IServiceProvider CreateServiceProvider(IServiceCollection services)
        {
            ContainerLocator.SetContainerExtension(() => new DryIocContainerExtension());
            var container = Prism.Ioc.ContainerLocator.Container.GetContainer();
            DryIocAdapter.Populate(container, services);
            return container.GetServiceProvider();
        }
    } '

OnCreate Function in MainApplication:

`        public override void OnCreate()
        {
                        this.ShinyOnCreate(new Startup());
                        base.OnCreate();
                        RegisterActivityLifecycleCallbacks(this); }
`

I have also attached the packages file. 
[ProjectPackages.txt](https://github.com/shinyorg/shiny/files/9739049/ProjectPackages.txt)

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
So this is something I can be involved in fixing since it simply isn't a bug in the library.  Your issue is due to a couple of things:
1) A mix between the old android support libs and the newer androidx
2) Old versions of the androidx libs - shiny 2.6.3 uses mostly the latest androidx libs
