### ISSUE TITLE
Getting exception at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException when I try to intergrate Shiny with Prism

### ISSUE THREAD

**Issue by alamzaib-farooq** [shinyorg/shiny#1115]
### Component/Nuget

Other (Message Bus, Startup Task, NPC Persistence)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1. Add Shiny to your project
2. Try to integrate Prism with Shiny see [Integrate with Prism](https://github.com/shinyorg/samples/tree/main/Integration-Prism)
See the detailed code below.

### Expected Behavior

The app should run.

### Actual Behavior

App is crashing.The app

### Exception or Log output

![Screenshot 2022-10-09 005813](https://user-images.githubusercontent.com/25901497/194754179-6ef3ae4b-7eda-4185-a635-fab3e01768de.png)

### Code Sample

It's been 2 weeks since I have been trying to add Shiny to my application. It's an excellent library providing so many great features out of the box. I am stuck integrating my app with Prism.  I do not know if it's a bug or something wrong with my app.

There is not much help on the internet most of the blog posts about integrating Shiny with Prism are outdated. There is only one helpful sample [Integrate Shiny with Prism](https://github.com/shinyorg/samples/tree/main/Integration-Prism)

I am using:
DryIoc.Microsoft.DependencyInjection 5.1.0
Prism.DryIoc.Forms 8.1.97
Prism.Forms.Extended 8.0.62
and latest Shiny libraries.

My other packages:
[ProjectPackages.txt](https://github.com/shinyorg/shiny/files/9741447/ProjectPackages.txt)

My main activity:

```
[assembly: ShinyApplication(
    ShinyStartupTypeName = "SampleApp.Startup",
    XamarinFormsAppTypeName = "SampleApp.App"
)]
namespace SampleApp.Droid
{
    [Activity(Label = "Sample", Icon = "@mipmap/ic_launcher", Exported = true, Theme = "@style/MainTheme", ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]


    public partial class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity, IMessageSender
    {
    
        protected override async void OnCreate(Bundle savedInstanceState)
        {
           

            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);
            LoadApplication(new App(new AndroidInitializer()));
        }

        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {

    
            base.OnActivityResult(requestCode, resultCode, data);
            this.ShinyOnActivityResult(requestCode, resultCode, data);
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            this.ShinyOnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }


    public class AndroidInitializer : IPlatformInitializer
    {
        public void RegisterTypes(IContainerRegistry containerRegistry)
        {
            // Register any platform specific implementations
        }
    }
}
```

MainApplication:

```
namespace SampleApp.Droid
{
    [Application]
    public partial class MainApplication : Application, Application.IActivityLifecycleCallbacks
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
            : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            this.ShinyOnCreate(new Startup());
            base.OnCreate();
            RegisterActivityLifecycleCallbacks(this);
        
            //A great place to initialize Xamarin.Insights and Dependency Services!
        }
}
}
```

Startup class:

```
using System;
using DryIoc.Microsoft.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Prism.DryIoc;
using Prism.Ioc;
using Shiny;
    public class Startup : ShinyStartup
    {

        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            services.UseGeofencing<GeofenceDelegate>();
            services.UseNotifications();
            services.UseGps();
            Console.WriteLine("Shiny Added");
        }
        
        
        public override IServiceProvider CreateServiceProvider(IServiceCollection services)
        {
            ContainerLocator.SetContainerExtension(() => new DryIocContainerExtension());
            var container = Prism.Ioc.ContainerLocator.Container.GetContainer();
            DryIocAdapter.Populate(container, services);
            return container.GetServiceProvider();
        }
   } 
```
I also added in the App.cs class:
`    public partial class App : Prism.DryIoc.PrismApplication`

Here is how I am registering types in App.cs:
```
 protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
        
            containerRegistry.RegisterForNavigation<NotificationArea, NotificationViewModel>();
            containerRegistry.RegisterForNavigation<ServerRegion>();
        
}
```

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is a 3rd party integration and has nothing to do with this library.  I use prism, shiny, & dryioc with every single app I write without issue.  

There are samples here: https://github.com/shinyorg/samples & Shiny Framework which brings Prism+Shiny together: https://github.com/shinyorg/framework 

Also, if you want help with anything in the future, you must supply a FULL REPRODUCIBLE sample otherwise your issue will be closed without comment.

**Comment by aritchie** [comment]
No reproducible sample has been supplied and based on the code snippet provided as well as the project references, there is obviously a lot missing.
