### ISSUE TITLE
[Bug]: Getting AccessState.NotSetup from bleManager.RequestAccess on Android 12

### ISSUE THREAD

**Issue by munkii** [shinyorg/shiny#1132]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

var accessState = await this.bleManager.RequestAccess();

### Expected Behavior

accessState == AccessState.Available

### Actual Behavior

accessState == AccessState.NotSetup

### Code Sample

- Shiny 2.7.0
- Xamarin Forms 5.0.0.2401

This same codebase works fine with and Android 9 device.

I realise that the permissions needed for Android 12+ changed. Prior to switching to use Shiny.BleManager when we were using Plugin.BluetoothLE we did the permission requesting ourselves for Android 12. Same Android config including Manifest.

I've looked through the code in [BleManager ](https://github.com/shinyorg/shiny/blob/bc633e3005c470ea1aabe6bea8de3f57a51dd00b/src/Shiny.BluetoothLE/Platforms/Android/BleManager.cs) and I can see that the [platform permissons](https://github.com/shinyorg/shiny/blob/bc633e3005c470ea1aabe6bea8de3f57a51dd00b/src/Shiny.BluetoothLE/Platforms/Android/BleManager.cs#L107), are [being checked here](https://github.com/shinyorg/shiny/blob/bc633e3005c470ea1aabe6bea8de3f57a51dd00b/src/Shiny.BluetoothLE/Platforms/Android/BleManager.cs#L59).

I have written some debugging code in our `MainApplication `that gets all the RequestedPermissions
and checks they are available. In a similar way to BleManager

```
var permissions = this.PackageManager.GetPackageInfo(this.PackageName, Android.Content.PM.PackageInfoFlags.Permissions).RequestedPermissions;

foreach (var p in  permissions)
{
	if (p.Equals(Manifest.Permission.BluetoothScan, StringComparison.InvariantCultureIgnoreCase))
	{
		Debug.WriteLine("Found BT Scan: " + p);
	}
	else if (p.Equals(Manifest.Permission.BluetoothConnect, StringComparison.InvariantCultureIgnoreCase))
	{
		Debug.WriteLine("Found BT Connect:" + p);
	}
	else
	{ 
		Debug.WriteLine(p);
	}
}
```

I can confirm that we do have Permission.BluetoothConnect and Permission.BluetoothScan and that debug output confirms it. What is unusual about our AndroidManifest is that our app uses a third party SDK for talking to another BT device. That SDK wraps up the BT calls and it  causes entries to be added to our AndroidManifest for BT permissions. All these permissions meant we ended up with an AndroidManifest that could not be ingested into Google Play. 

GooglePlay reported 

> Duplicate declarations of permission android.permission.ACCESS_COARSE_LOCATION with different maxSdkVersions. Duplicate declarations of permission android.permission.ACCESS_FINE_LOCATION with different maxSdkVersions.

To solve those issues I had to use some unusual permission statements in our AndroidManifest, here are our permission statements

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.WAKE_LOCK" />

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission
	android:name="android.permission.BLUETOOTH"
	tools:node="replace"
	android:maxSdkVersion="30" />

<uses-permission
	android:name="android.permission.BLUETOOTH_ADMIN"
	tools:node="replace"
	android:maxSdkVersion="30" />

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

<uses-permission-sdk-23
	android:name="android.permission.ACCESS_COARSE_LOCATION"
	tools:node="remove"
	android:maxSdkVersion="30" />

<uses-permission-sdk-23
	android:name="android.permission.ACCESS_FINE_LOCATION"
	tools:node="remove"
	android:maxSdkVersion="30" />

<uses-permission
	android:name="android.permission.BLUETOOTH_CONNECT"
	tools:node="replace"
	tools:targetApi="31" />

<uses-permission
	android:name="android.permission.BLUETOOTH_SCAN"
	tools:node="replace"
	android:usesPermissionFlags="neverForLocation"
	tools:targetApi="31" />
```

It is worth noting thought that the previously mentioned debug code does see the pemissions in this.PackageManager.GetPackageInfo(this.PackageName, Android.Content.PM.PackageInfoFlags.Permissions).RequestedPermissions.

I really tried to get a sample together but I could not get a simple Shiny\XF app template to deploy nor could I get the BLE Client sample to work.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I copied this manifest into my sample and it works fine.  Are you sure your manifest is valid?

Did you include the tools xmlns?  Are you seeing any console errors?

You can put the following in your code and see which permission it thinks is missing because NotSetup only comes back for a missing manifest item

```cs
    public static bool IsInManifest(this IPlatform platform, string androidPermission)
    {
        var permissions = platform
            .AppContext!
            .PackageManager!
            .GetPackageInfo(
                platform.AppContext!.PackageName!,
                PackageInfoFlags.Permissions
            )
            ?.RequestedPermissions;

        if (permissions != null)
        {
            foreach (var permission in permissions)
            {
                if (permission.Equals(androidPermission, StringComparison.InvariantCultureIgnoreCase))
                    return true;
            }
        }
        return false;
    }
```

**Comment by aritchie** [comment]
I have updated the sample here: https://github.com/shinyorg/samples/tree/main/BluetoothLE-Client with the manifest above.  Try it, debug with it - there is solution that uses a submodule to v2 source.  I've tried it on all of my test devices and I cannot reproduce it.

**Comment by munkii** [comment]
I took a look at the BluetoothLE_Client sample and that reports correctly on the Android 12 device I am using. I clearly need to get source versions of Ble, Core and BleCommon connected to our project and debug there. I'm going to assume it is something stupid I am doing but i cannot think what.

The "submodules" solution is pointing at empry folders. When you want to use that version I assume you simply copy and paste the 3 source projects into "submodules" folder and build, yes?

If I try that I get 

> MSB4044	The "ResolvePackageAssets" task was not given a value for the required parameter "TargetFramework".	Shiny.Core

I'm assuming this is less a Shiny issue and more to do with my lack of understanding of Build targets. Can you give me a ny pointers?

**Comment by aritchie** [comment]
The submodules are just git submodules.  Depending on what git client you use, they usually ask if you want to restore them.

You can also just pull in the source anywhere on your drive, include in the project, and adjust the directory.build.props here:

https://github.com/shinyorg/samples/blob/main/BluetoothLE-Client/Directory.build.props - Set UseNuget to false and set the DebugDirectory

**Comment by aritchie** [comment]
There was a bug in the initial 2.6.0 release that was fixed around this.  In any case, glad you got things figured out
