### ISSUE TITLE
[Notifications] Allow to use system default sound on Android

### ISSUE THREAD

**Issue by cpraehaus** [shinyorg/shiny#114]
## Summary
Allow to use system default notification sound. Some platforms like Android have a default
system sound associated with notifications. Currently, Shiny.Notifications only supports
playing custom sounds shipped with the application (as far as I can see).  

I can submit a PR with the API change and implementation for Android if this request is accepted.

## API Changes

Add new SoundType to Notification class.

```
// Play the default notification sound used by the system
new Notification()
{
	SoundType = SoundType.SystemDefault,
	...
}

// Play a custom sound
new Notification()
{
	// Note: Custom is the default for SoundType (backwards compatibility)
	SoundType = SoundType.Custom,
	Sound = "myCustomSoundFile",
	...
}
```

## Intended Use Case
Often it is desirable to just use the system default notification sound (selected by the user).
E.g. if a notification is generated from an App running in the background. At least
on Android 6 the system does not play the default notification sound (by default). Therefore 
the above change would make sense.

I personally find it annoying if each App uses its own notification sound (at least on mobile platforms).

**Comment by aritchie** [comment]
I haven't decided yet if sound is staying or going.  It may just be set to the system default without an on/off switch.

Thanks for the suggestion though

**Comment by cpraehaus** [comment]
I understand. Maybe you want to look at my current topic branch for this issue: https://github.com/shinyorg/shiny/compare/master...cpraehaus:notify-with-system-default-sound

Until you have decided on the sound API: would it be possible to add ``builder.setDefaults(NotificationCompat.DefaultSound)`` for Android like shown [here](https://github.com/cpraehaus/shiny/blob/13d787529c54ebc8127e16272ef3cf582d8bbedb/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs#L171). With this flag the default notification sound is played on Android if the priority of the notification is high enough.

Thanks and kind regards,
Christian.
