### ISSUE TITLE
[Bug]:  Please add a reference to Mono.Android.Export.dll when using ExportAttribute or ExportFieldAttribute.

### ISSUE THREAD

**Issue by jis248** [shinyorg/shiny#1163]
### Component/Nuget

Other (Message Bus, Startup Task, NPC Persistence)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

I have installed Packages
1. Shiny
2. Shiny.Jobs
3. Shiny.Core

IDE:- JetBrains Rider

### Expected Behavior

Shiny packages after instal should run without error in Android.

### Actual Behavior

After install on Android it gives this Error, on iOS its working.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/84921389/208827259-69c62676-bed7-4857-a615-ec10841ac1d3.png">

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Not a bug.  Do exactly what it says to do

**Comment by jis248** [comment]
yes I have added that now I am getting this
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/84921389/208897291-16afac91-745b-462e-a465-9ce6c28ef276.png">

**Comment by jis248** [comment]
On a new project I am not getting any issue but on an existing project above error occurs.

**Comment by aritchie** [comment]
That has absolutely nothing to do with shiny.  I don't reference the classic support packages.
