### ISSUE TITLE
[Bug]: Jobs are not executing periodically - Android

### ISSUE THREAD

**Issue by pkvaranasi** [shinyorg/shiny#1164]
### Component/Nuget

Jobs (Shiny.Jobs)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1. Installed Shiny framework to all 3 projects in the solution.
2. Followed Shiny documentation to add required methods to call in MainApplication.cs, MainActivity.cs and AppDelegate.cs
3. Updated info.plist to add keys for background modes.
4. Created a Startup.cs class as mentioned the Sample github repo.
5. Added SQLiteConnection class and registered with Shiny.
6. Followed the same steps as per documentation and cross verified with Sample app.

### Expected Behavior

1. When the app is in foreground and in use, expected to have the job to perform for every 30 seconds. It's working.
2. When the app is in closed state, and Periodic Time is set to 20 minutes, the job was supposed to execute for every 20 minutes. It's NOT working.

### Actual Behavior

1. When the app is in foreground and in use, expected to have the job to perform for every 30 seconds. It's working.
2. When the app is in closed state, not in foreground or background, the job execution is happening very intermittently. Sometimes in 10 minutes and sometimes for hours. There is consistency in execution.
3. Added PeriodicTime option to Job to 20 minutes explicitly, as the default is 15 minutes in Android.
4. But still the job is execution is not periodic. 

### Code Sample

Startup.cs
public class Startup: ShinyStartup
	{
		public override void ConfigureServices(IServiceCollection services, IPlatform platform)
		{
			services.AddSingleton<MydataSyncJobLoggerTask>();
			services.AddSingleton<MydataSyncJobSqliteConnection>();

			services.UseJobs(true);
			services.UseNotifications(); 
		
			services.RegisterJob(new JobInfo(typeof(MydataSyncJob), "MyData")
			{
				PeriodicTime = new TimeSpan(0,20,0),
				RequiredInternetAccess = InternetAccess.Any,
				RunOnForeground = true,
				DeviceCharging = false,
				BatteryNotLow = true,
				Repeat = true
			});
		}
	}

MydataSyncJobSqliteConnection.cs
public class MydataSyncJobSqliteConnection : SQLiteAsyncConnection
	{
		public MydataSyncJobSqliteConnection(IPlatform platform) : base(Path.Combine(platform.AppData.FullName, "MyDataLog.db"))
		{
			GetConnection().CreateTable<MyDataLogEvent>();
		}

		public AsyncTableQuery<MyDataLogEvent> MyDataLogEvents => Table<MyDataLogEvent>();
	}

MydataSyncJobLoggerTask.cs
public class MydataSyncJobLoggerTask: IShinyStartupTask
	{
		readonly IJobManager mJobManager;
		readonly MydataSyncJobSqliteConnection myDataSQliteConn;

		public MydataSyncJobLoggerTask(IJobManager jobManager, MydataSyncJobSqliteConnection mydataSQLiteConn)
		{
			mJobManager = jobManager;
			myDataSQliteConn= mydataSQLiteConn;
		}

		public void Start()
		{
			mJobManager.JobStarted.SubscribeAsync(job => myDataSQliteConn.InsertAsync(new MyDataLogEvent
			{
				Title = $"{job.Identifier} Started",
				Message = $"{job.Identifier} Started",
				Timestamp = DateTime.Now,
			}));

			mJobManager.JobFinished.SubscribeAsync(result => myDataSQliteConn.InsertAsync(new MyDataLogEvent
			{
				Title = result.Job?.Identifier + " " + (result.Success ? "Completed" : "Failed"),
				Message = result.Exception?.ToString() ?? "",
				Timestamp = DateTime.Now
			}));
		}
	}

MydataSyncJob.cs
public class MydataSyncJob : IJob
	{
		readonly INotificationManager notificationManager;
		public MydataSyncJob(INotificationManager notificationManager)
		{
			this.notificationManager = notificationManager;
		}
		public async Task Run(JobInfo jobInfo, CancellationToken cancelToken)
		{
			//	await Task.Delay(5000);
		}
	}

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
They aren't scheduled.  They are periodic.  Android factors in other things before determining if you can run every 20mins.

**Comment by pkvaranasi** [comment]
[MyDataLogs20221223194747.txt](https://github.com/shinyorg/shiny/files/10295671/MyDataLogs20221223194747.txt)
Attached the logs for your reference.

Thanks for the reply.

Can you explain the difference between Periodic and Scheduled.
And, what would be the factors Android would determine if it can consider this PeriodicTime.

**Comment by pkvaranasi** [comment]
Do you have any suggestion to help me, of how to achieve this requirement of running some tasks in foreground, background and even when is not running, periodicially, if Shiny Jobs isn't supported.

**Comment by aritchie** [comment]
Jobs will execute in the background.  You just have to be patient.  Android & iOS run them when conditions are right.

For documentation, you can lookup the Android WorkManager
