### ISSUE TITLE
[Feature Request]: Integration with Community Toolkits

### ISSUE THREAD

**Issue by stacyh3** [shinyorg/shiny#1200]
### Summary

It would be great to see some of the features like Jobs, Startup Tasks, Download Manager, etc. integrated into the MVVM and MAUI community toolkits. Since these toolkits already have RelayCommand and other extensions, using both causes some duplication of features.

### API Changes

I'm not sure which APIs would change, but they'd likely include Reactive vs RelayCommand, built-in DI container, integration with Messenger, and a few others.

### Intended Use Case

Use some of the great features of Shiny alongside the Microsoft Community Toolkits.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
The community toolkits and Shiny are two different things.  Shiny does have DI and v3 prerelease directly integrates with MAUI, but Shiny itself doesn't really touch front end code other than permission requests.  Shiny doesn't have any MVVM or reactive/Icommand implementations, so I'm not really sure what it is that you're looking for here.

**Comment by stacyh3** [comment]
Thanks. I'll explore further. It didn't look like I could pull specific capabilities from Shiny without bringing the whole framework. I wanted to be able to add Jobs, Startup Tasks, and Download management to an existing application with minimal changes. We can close this while I investigate my options.

**Comment by aritchie** [comment]
Shiny.Framework is nothing more than additional tools to work with Shiny, Prism, & ReactiveUI.  It is not a requirement for Shiny to be used at all, nor is it required to work with any of the other 3rd party packages I mentioned.
