### ISSUE TITLE
[Bug]: BLUETOOTH_PRIVILEGED is not grant on Android 10 and 11 

### ISSUE THREAD

**Issue by MichalPeterek** [shinyorg/shiny#1202]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [X] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [X] MAUI
- [ ] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

Start scanning on Android API 30

### Expected Behavior

Work without BLUETOOTH_PRIVILEGED 

### Actual Behavior

Not work and showing privileges ERROR

### Code Sample

Now :

```
static string[] GetPlatformPermissions()
    {
        var list = new List<string>();

        if (OperatingSystemShim.IsAndroidVersionAtLeast(31))
        { 
            return new[]
            {
                Manifest.Permission.BluetoothScan,
                Manifest.Permission.BluetoothConnect
            };
        }
        return new[]
        {
            Manifest.Permission.Bluetooth,
            Manifest.Permission.BluetoothPrivileged,
            Manifest.Permission.BluetoothAdmin,
            Manifest.Permission.AccessFineLocation
        };
    }
```

Working : 

```
static string[] GetPlatformPermissions()
    {
        var list = new List<string>();

        if (OperatingSystemShim.IsAndroidVersionAtLeast(31))
        { 
            return new[]
            {
                Manifest.Permission.BluetoothScan,
                Manifest.Permission.BluetoothConnect
            };
        }
        return new[]
        {
            Manifest.Permission.Bluetooth,
            Manifest.Permission.BluetoothAdmin,
            Manifest.Permission.AccessFineLocation
        };
    }
```

### Code of Conduct

- [ ] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [ ] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I'll fix this in a future preview, but please follow the rules for posting here!
