### ISSUE TITLE
MauiAppBuilder does not contain a definition for UseShiny

### ISSUE THREAD

**Issue by jrahma** [shinyorg/shiny#1205]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [X] MAUI
- [ ] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

I have just created a blank MAUI app and added Shiny nuget.

Here is my MauiProgram.cs:

```
using Microsoft.Extensions.Logging;
using Shiny;

namespace ShinyBackgrounding;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
            .UseShiny()
            .ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});

#if DEBUG
		builder.Logging.AddDebug();
#endif

		return builder.Build();
	}
}

```

### Expected Behavior

It should not show error.

### Actual Behavior

Error CS1061: 'MauiAppBuilder' does not contain a definition for 'UseShiny' and no accessible extension method 'UseShiny' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?) (CS1061) (ShinyBackgrounding)**

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Alphas are only supported for sponsors under the sponsorconnect discord channel.  Please read the checkboxes you are clicking in the future and provide an ACTUAL reproducible sample because the sample in this repo compiles just fine
