### ISSUE TITLE
[Bug]: IGattCharacteristic.Notify Finally exception handling

### ISSUE THREAD

**Issue by ShannonKasperNoesis** [shinyorg/shiny#1206]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

I don't have a reproducible sample to give you but I ran into a situation where I have a bluetooth device where the recommended way to disconnect is to send a command to the device and it essentially resets itself. With the way I was using Shiny this caused my application to crash and the culprit was using the IGattCharacteristic.Notify extension method. The "finally" operator contains an action that can throw an exception. In my case the exception was "Failed to write to descriptor". Unfortunately (and news to me) any unhandled exception in a "finally" operator will throw an exception on the ThreadPool and crash the process (see stackoverflow link below). I've worked around this by not using Shiny's "Notify" extension method but figured you might want to take a look as it was a difficult issue to diagnose.

https://stackoverflow.com/questions/69815945/how-to-implement-a-better-finally-rx-operator

IGattCharacteristic.Notify "finally" location: https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Extensions_Characteristics.cs#L70

This issue will likely exist for all platforms and operating systems but I have only been testing with Xamarin Forms on Android 12.

### Expected Behavior

Handle exception within a "finally" operator so application does not crash.

### Actual Behavior

Action within "finally" operator throws an exception and crashes the application.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Thanks for the report

**Comment by ShannonKasperNoesis** [comment]
Thanks for the quick fix!
