### ISSUE TITLE
[Bug]: Missing mandatory option(s) for the template 'Shiny MAUI Application': '--ApplicationId'.

### ISSUE THREAD

**Issue by ianpowell2017** [shinyorg/shiny#1208]
### Component/Nuget

Other (Message Bus, Startup Task, NPC Persistence)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [X] MAUI
- [ ] Xamarin Native
- [ ] Xamarin Forms

### Steps To Reproduce

1. Install templates
2. `dotnet new shinymaui`
- Missing mandatory option(s) for the template 'Shiny MAUI Application': '--ApplicationId'.

### Expected Behavior

Create a new MAUI application

### Actual Behavior

Error `Missing mandatory option(s) for the template 'Shiny MAUI Application': '--ApplicationId'.`

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This isn't a bug.  ApplicationId is a required parameter.

**Comment by ianpowell2017** [comment]
Hi, This template works fine in Visual Studio for Mac, but not in JetBrains Rider 2022.3.3
<img width="798" alt="Screenshot 2023-03-30 at 07 51 07" src="https://user-images.githubusercontent.com/30384636/228753650-bf370267-962f-4c33-8eb0-e8d82108ed8a.png">

**Comment by aritchie** [comment]
It's a standard template.  My main focus is vs4mac and VS4win, not cli or any other ide.  Use the template in one of those than open it in rider
