### ISSUE TITLE
[Bug]:   GPS does not update

### ISSUE THREAD

**Issue by papnak** [shinyorg/shiny#1211]
### Component/Nuget

GPS or Geofencing (Shiny.Locations)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Visual Studio 17.6.0 Preview 3 
iPhone 14 iOS 16.2 (Simulation)
Android 12 (HW)

### What platform(s) are effected?

- [X] MAUI
- [ ] Native
- [ ] Classic Xamarin
- [ ] Other

### Steps To Reproduce

Android
- Compile sample.maui and start
- StartListener()
- OnReading() in the GpsDelegate is only called once

iOS
sample.maui does  compile with error

### Expected Behavior

Android
- OnReading() is called cyclic

iOS
- sample.maui should compile without error

### Actual Behavior

Android
OnReading() is only called once

iOS
compiles with error

### Exception or Log output

iOS:
MessagingRemoteException: An error occurred on client Build1622054 while executing a reply for topic xvs/build/16.2.2054/execute-task/{AppName}/99cb0fc002fDetectSdkLocations
ArgumentNullException: Value cannot be null.
Parameter name: path2
	Sample.Maui	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.2.2054\tools\msbuild\iOS\Xamarin.Shared.targets	1738

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Attach a reproducible sample or this will be closed

**Comment by papnak** [comment]
Its your sample.maui from github

**Comment by aritchie** [comment]
Read the checkboxes of the issue template!!!
