### ISSUE TITLE
[Bug]: [Beta] GetAllCharacteristics not working

### ISSUE THREAD

**Issue by rodrigoavots** [shinyorg/shiny#1217]
### Component/Nuget

BluetoohLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X ] Android (8+ supported)

### Version(s) of Operation Systems

Sorry if there's something wrong with my writing.

My last version was 3.0.0-alpha-0532 and after upgrading to Beta (3.0.0-beta-0015) I made necessary changes but Characteristics stopped working.

Testing in version 3.0.0-alpha-0532 the method brings me the expected result.
await peripheral.GetAllCharacteristics().Timeout(TimeSpan.FromSeconds(20));

But not in version 3.0.0-beta-0015.

### What platform(s) are effected?

- [X ] MAUI
- [ ] Native
- [ ] Classic Xamarin
- [ ] Other

### Steps To Reproduce

var test1 = await peripheral.GetAllCharacteristics().Timeout(TimeSpan.FromSeconds(20));

### Expected Behavior

-		test1	Count = 4	System.Collections.Generic.List<Shiny.BluetoothLE.IGattCharacteristic>
+		[0]	{Shiny.BluetoothLE.GattCharacteristic}	Shiny.BluetoothLE.GattCharacteristic
+		[1]	{Shiny.BluetoothLE.GattCharacteristic}	Shiny.BluetoothLE.GattCharacteristic
+		[2]	{Shiny.BluetoothLE.GattCharacteristic}	Shiny.BluetoothLE.GattCharacteristic
+		[3]	{Shiny.BluetoothLE.GattCharacteristic}	Shiny.BluetoothLE.GattCharacteristic

### Actual Behavior

-		test1	Count = 0	System.Collections.Generic.List<Shiny.BluetoothLE.BleCharacteristicInfo>
+		Raw View	

### Code Sample

https://github.com/rodrigoavots/MauiShinyTest

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by rodrigoavots** [comment]
Sorry, I don't know why it lost the data formatting!
I hope this helps to identify if there is a problem.

**Comment by aritchie** [comment]
Thank you for the report.  This will be fixed for beta 3

There was a lot of API changes between the alpha & beta - the upgrade process there is not relevant going forward.
