### ISSUE TITLE
[Bug]: NotifyCharacterisitic does not working

### ISSUE THREAD

**Issue by mwswt** [shinyorg/shiny#1220]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Windows 10 Pro latest Update (OS Build 19045.2846)
Android 12 (Samsung Galaxy S10)

### What platform(s) are effected?

- [X] MAUI
- [ ] Native
- [ ] Classic Xamarin
- [ ] Other

### Steps To Reproduce

1.  Enable the Characterisitic Notification
2. At the next step i tried to write another characteric async

### Expected Behavior

Every time i call the WriteCharacteristicAsync command, there should be a response after a short delay on the characteristic notification (This is implement in my routine on the BLE Host)

### Actual Behavior

I get an exception that i can not write the characteristic. If i remove the Notification then everything is working as expected

### Exception or Log output

[BluetoothGatt] refresh() - device: 24:6F:28:F6:11:DD
[BluetoothGatt] discoverServices() - device: 24:6F:28:F6:11:DD
[BluetoothGatt] onConnectionUpdated() - Device=24:6F:28:F6:11:DD interval=6 latency=0 timeout=500 status=0
[BluetoothGatt] onSearchComplete() = Device=24:6F:28:F6:11:DD Status=0
[BluetoothGatt] onConnectionUpdated() - Device=24:6F:28:F6:11:DD interval=36 latency=0 timeout=500 status=0
Resolved pending breakpoint at 'Peripheral_Characteristics.cs:70,1' to void Shiny.BluetoothLE.Peripheral.<>c__DisplayClass39_1.<<NotifyCharacteristic>b__2>d.MoveNext () [0x0018a].
[BluetoothGatt] setCharacteristicNotification() - uuid: 41ceed4b-e348-4a17-b1e9-6ac02daa1ecf enable: true
Resolved pending breakpoint at 'Peripheral_Descriptors.cs:33,1' to void Shiny.BluetoothLE.Peripheral.<>c__DisplayClass57_1.<<WriteDescriptor>b__1>d.MoveNext () [0x00089].
Resolved pending breakpoint at 'Peripheral_Descriptors.cs:36,1' to void Shiny.BluetoothLE.Peripheral.<>c__DisplayClass57_1.<<WriteDescriptor>b__1>d.MoveNext () [0x000d5].
**Shiny.BluetoothLE.BleException:** 'Failed to write to characteristic: 41ceed4b-e348-4a17-b1e9-6ac02daa1eda'

### Code Sample

`this.dispose = this.InstancePeripheral.NotifyCharacteristic(FlasherUuids.UPDATER_SERVICE_UUID.ToString(), FlasherUuids.UPDATER_STATE_CHARACTERISTIC_UUID.ToString()).Subscribe(x => count++);

await InstancePeripheral.WriteCharacteristicAsync(FlasherUuids.UPDATER_SERVICE_UUID.ToString(), FlasherUuids.UPDATER_LENGTH_CHARACTERISTIC_UUID.ToString(), lengthAndMtuSize.ToArray(), false, default, 10000);`

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
This is not enough of a sample to do anything with.  Your error is to do with the write characteristic, not the actual notification characteristic.  You need to hook the error in the notification subscription if you think there is an issue there.

**Comment by jaredballen** [comment]
I am running into a similar issue with `NotifyCharacteristic` on Android. There appears to be a TimeoutException that is occurring:

```
System.TimeoutException: The operation has timed out.
   at Shiny.BluetoothLE.Peripheral.<>c__DisplayClass39_1.<<NotifyCharacteristic>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Shiny.BluetoothLE.Intrastructure.OperationQueueExtensions.<>c__DisplayClass0_1`1.<<QueueToObservable>b__1>d[[Android.Bluetooth.BluetoothGattCharacteristic, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext()
--- End of stack trace from previous location ---
   at Shiny.BluetoothLE.Intrastructure.SemaphoreOperationQueue.Queue(Func`1 task)
   at Shiny.BluetoothLE.Intrastructure.OperationQueueExtensions.<>c__DisplayClass0_0`1.<<QueueToObservable>b__0>d[[Android.Bluetooth.BluetoothGattCharacteristic, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext()
```

This same notification is being received in the iOS version of my App as well as via nRF Connect (Android, iOS , Mac).

**Comment by rodrigoavots** [comment]
Hi!
I have the same problem

Error:
	ex	{System.TimeoutException: The operation has timed out.
   at Shiny.BluetoothLE.Peripheral.<>c__DisplayClass39_1.<<NotifyCharacteristic>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Shiny.BluetoothLE.Intrastructure.OperationQueueExtensions.<>c__DisplayClass0_1`1.<<QueueToObservable>b__1>d[[Android.Bluetooth.BluetoothGattCharacteristic, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext()
--- End of stack trace from previous location ---
   at Shiny.BluetoothLE.Intrastructure.SemaphoreOperationQueue.Queue(Func`1 task)
   at Shiny.BluetoothLE.Intrastructure.OperationQueueExtensions.<>c__DisplayClass0_0`1.<<QueueToObservable>b__0>d[[Android.Bluetooth.BluetoothGattCharacteristic, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].MoveNext()}	System.TimeoutException

My code:
            this.watcher = DeviceSelected
                .NotifyCharacteristic(this.Characteristic.Service.Uuid, this.Characteristic.Uuid)
                .Timeout(Constants.OperationTimeout)
                .SubOnMainThread(
                    x =>
                    {
                        //faz a leitura do sensor
                        this.SetReadValue(x, fromUtf8);
                    }
                    , ex =>
                    {
                        App.loggingService.Error(ex, "DoNotifyAsync");
                    }
                );

**Comment by aritchie** [comment]
Please ensure you are adding value to the issue when replying.  I am looking for FULL reproducible samples for betas to be inline with the code of conduct.  "Me toos" simply become noise.  Please remember v3 is a beta, so things aren't fully finished either!

**Comment by rodrigoavots** [comment]
Sorry @aritchie, updated the test app with this issue.
Hope it helps to find out.

https://github.com/rodrigoavots/MauiShinyTest
