### ISSUE TITLE
[Bug]: Crash on Android when passing generic ConnectionConfig to Connect method

### ISSUE THREAD

**Issue by TPitman-mindfiretechnology** [shinyorg/shiny#1223]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Android 13

### What platform(s) are effected?

- [X] MAUI
- [ ] Native
- [ ] Classic Xamarin
- [ ] Other

### Steps To Reproduce

Create a project that scans for and then connects to a device on Android. Make sure to pass in a ConnectionConfig object. My test app sets AutoReconnect to false, but that shouldn't be relevant to the crash.

### Expected Behavior

App should connect to the device.

### Actual Behavior

App Crashes with a null reference exception in the Connect method.

I have identified the problem in the Android Platform code in the Peripheral.cs file. You can see that on line 82 a reference is made to the variable "cfg" that is null if you passed in a ConnectionConfig that isn't of type AndroidConnectionConfig.

I believe the correct change is to change line 82 to use config instead of cfg.

### Exception or Log output

`[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.`
`[mono-rt]    at Shiny.BluetoothLE.Peripheral.Connect(ConnectionConfig config)`
`[mono-rt]    at ShinyBLETest.MainPage.ScanClicked(Object sender, EventArgs e) in /Users/tpitman/Projects/Mindfire/Examples/ShinyBLETest/ShinyBLETest/MainPage.xaml.cs:line 36`
`[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)`
`[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36`
`[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36`
`[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84`
`[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22`

### Code Sample

https://github.com/TPitman-mindfiretechnology/ShinyBLETest

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
No that's fine.  If the bug isn't filed and it isn't working in the current nuget, this issue should definitely exist for tracking.

**Comment by aritchie** [comment]
This was the defect I fixed a few days ago and will be part of the next beta release
