### ISSUE TITLE
[Feature Request]: Return GATT status/codd on exception from WriteCharacteristic method

### ISSUE THREAD

**Issue by jaredballen** [shinyorg/shiny#1228]
### Summary

When the native write characteristic fails, a `BleEception` is thrown. The exception only contains a string message. This does not provide high enough fidelity for more advanced scenarios where peripherals take advantage of application-specific GATT status codes.

### API Changes

No changes to the public API. This request would extend the `BleException` class. Perhaps a more specific class, `BleCharactisticWriteException`. This new exception type would expose an additional int parameter that would allow the GATT status (Android) or the error code (Apple) to the be bubble up to the application layer.

### Intended Use Case

The BLE spec allows application-specific statuses to be returned from a peripheral to respond to a characteristic write with a response.  Currently, there is no way for the library to return these statuses to the application layer. In some instances, these statuses may not necessarily be treated as error conditions by the application and should be exposed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaredballen** [comment]
I think the approach suggested is sound and I am more than happy to submit a PR for this feature request. Let me know if this is an acceptable apprach.

**Comment by aritchie** [comment]
This will done as part of the next beta.  Thank you for the offer of doing a PR, but I'll do this since it will need to work its way into a windows release as well.  I also want to apply it to reads.
