### ISSUE TITLE
'[Plugin.SpeechRecognition] No platform plugin found. Did you install the nuget package in your app project as well?'

### ISSUE THREAD

**Issue by scascalespAV** [shinyorg/shiny#1230]
### Component/Nuget

Speech Recognition (Shiny.SpeechRecognition)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Hello

From your old repo get error '[Plugin.SpeechRecognition] No platform plugin found. Did you install the nuget package in your app project as well?'
[speechrecognition-master.zip](https://github.com/shinyorg/shiny/files/11569409/speechrecognition-master.zip)
Thx

### Hosting Model

- [ ] MAUI
- [X] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

Simple run the project

### Expected Behavior

work well when push the sample

### Actual Behavior

not working

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
This sample is old and the original plug-in.  It hasn't been worked on in years and isn't expected to work out of the box with shiny.  It's clear you don't seem to care about my time or the code of conduct here.
