### ISSUE TITLE
sample not working

### ISSUE THREAD

**Issue by scascalespAV** [shinyorg/shiny#1231]
### Component/Nuget

Other

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

win10  + VS 2022

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

Hello

download samples

Open in visual studio

Run and error:  error NETSDK1004: Assets file 'D:\VSProjs\P\shiny\src\Shiny.Core\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "Shiny.Core.csproj" -- FAILED.

![image](https://github.com/shinyorg/shiny/assets/110404394/f943b025-51aa-493a-97f8-d390e078d0dc)

Thx

### Expected Behavior

working samples

### Actual Behavior

not working

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Seriously… READ the issue template!!!
