### ISSUE TITLE
[Feature Request]: Set iOS BLE queue

### ISSUE THREAD

**Issue by alex-dubatov** [shinyorg/shiny#1245]
### Summary

Is it possible to add in Shiny.BluetoothLE (2.7.2) the ability for Xamarin.IOS to run off the main queue?

![image](https://github.com/shinyorg/shiny/assets/72652374/ba1c7636-cc93-42f4-8730-7b118355bcc3)

### API Changes

Configure it in ShinyStartup or somewhere else

### Intended Use Case

Xamarin.Ios

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Sure - this is simple enough to add.  I'm curious as to the reasoning though?

**Comment by aritchie** [comment]
This has been added to v3 betas.  It will not be part of v2

**Comment by alex-dubatov** [comment]
> Sure - this is simple enough to add. I'm curious as to the reasoning though?

Bluetooth connection was not stable with our device, so I just tried to found reason.

And I found. The reason was that I must send bluetooth message wihout waiting for 
func peripheralIsReady(toSendWriteWithoutResponse: CBPeripheral)
