### ISSUE TITLE
[Bug]: Shiny.Notifications version 3.0.0-alpha-0266 - Can not send multiple notifications with RepeatInterval on the same day on Android device

### ISSUE THREAD

**Issue by hoangonpattern** [shinyorg/shiny#1257]
### Component/Nuget

Notifications (Shiny.Notifications)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target)

### Version(s) of Operation Systems

Android

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

Create 3 notification (more than 1) with Shiny Notifications library and using RepeatInterval on the same day with different times.

### Expected Behavior

3 notifications will show up on the device at the defined time, on the same day.

### Actual Behavior

on **Android** OS, **only one** notification shows up at the defined time.
on iOS it works as expected, 3 notifications show up.

### Code Sample

var notificationTimesList = new List<TimeSpan>() { new TimeSpan(10, 5, 0), new TimeSpan(10, 10, 0), new TimeSpan(10, 15, 0), };
foreach (var notificationTime in notificationTimesList)
{
      var sampleNotification = new Notification
      {
	      Title = "Sample Title",
	      Message = "Sample notification message",
	      RepeatInterval = new IntervalTrigger
	      {
		      DayOfWeek = DayOfWeek.Monday,
		      TimeOfDay = notificationTime 
	      },						 
      };
      await _notificationManager.Send(sampleNotification);
}

//the sample code above will create 3 notifications in same day Monday, at 10:05 AM, 10:10 AM and 10:15 AM

//the result is **only one notification** will be showed up on the **Android** device, the others 2 notification would not send out. 
//on iOS device it will send 3 of them as expected.

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Use the latest version!

**Comment by aritchie** [comment]
Look at nuget.org

**Comment by hoangonpattern** [comment]
> Look at nuget.org

@aritchie 
the version 3.0.0-beta-0124 from nuget is compatible with .net 7, our project is using .net 6
