### ISSUE TITLE
I can't install Shiny version 3 from NugetPackage using Visual Studio for Blazor Maui app 

### ISSUE THREAD

**Issue by scsJames** [shinyorg/shiny#1259]
### Component/Nuget

Other

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)
- [ ] Windows (.NET 7 Target)

### Version(s) of Operation Systems

Blazor Maui Android

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

I can't install Shiny version 3 from NugetPackage using Visual Studio for Blazor Maui app 

### Expected Behavior

I can't install Shiny version 3 from NugetPackage using Visual Studio for Blazor Maui app 

### Actual Behavior

I can't install Shiny version 3 from NugetPackage using Visual Studio for Blazor Maui app 

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Please be respectful and don't waste my time.  Give details!!

* what's the error message
* what's the actual packages you're using?

I created a new MAUI blazor app in vs4mac latest version and installed Shiny.Core without issue.

**Comment by scsJames** [comment]
Hello,
Thank you for you time, in my case when i try to install Shiny.Core or any Shiny package from NugetPackage for Maui Blazor Android Project using Visual Studio latest version, i got an error : 

- Package restore failed. Rolling back package changes for 'MauiApp1'.
- NU1107 Version conflict detected for Xamarin.AndroidX.Core. Install/reference Xamarin.AndroidX.Core 1.9.0.1 directly to project MauiApp1 to resolve this issue. 
 MauiApp1 -> Xamarin.AndroidX.Navigation.Fragment 2.5.2.1 -> Xamarin.AndroidX.Fragment.Ktx 1.5.3.1 -> Xamarin.AndroidX.Fragment 1.5.3.1 -> Xamarin.AndroidX.ViewPager 1.0.0.15 -> Xamarin.AndroidX.Core (>= 1.9.0.1) 
 MauiApp1 -> Shiny.Core 2.7.2 -> Xamarin.AndroidX.Core (>= 1.6.0.5 && < 1.7.0).	MauiApp1	C:\Users\Hamza\source\repos\MauiApp1\MauiApp1\MauiApp1.csproj	1	
 
 i tried to created a new project but the same error persiste.
 OS : Windows 10
 Visual Studio 2022 - version 17.6.2
 Project Type :  .NET MAUI Blazor ( Android ) 

![8](https://github.com/shinyorg/shiny/assets/47700345/8178a6f6-942c-4321-ba13-0a7013cd764c)

**Comment by aritchie** [comment]
Shiny 2.7.2 support xamarin ios & xamarin android.  Shiny v3 beta supports MAUI.  Look at nuget.org for the compatibility
