### ISSUE TITLE
[Bug]: peripherial.NotifyCharacteristic seems to only work once in lifecycle of Android app

### ISSUE THREAD

**Issue by mjphillips1981** [shinyorg/shiny#1266]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

android 13

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

1. scan and connect to device 
2. subscribe to peripheral.NotifyCharacteristic
3. navigate back - device disconnects when leaving the page and all disposables are disposed of
4. repeat process without closing app or powering down the device - on the second time around the peripheral.NotifyCharacteristic does not seem to start

I tried following the bleclient sample as best I could.  I am probably missing something to cause this issue on my end.

### Expected Behavior

on iOS - this process seems to work fine.  I expect every time I connect to a device is can subscribe to the NotifyCharacteristic

### Actual Behavior

does not subscribe after first time.

### Exception or Log output
------------FIRST TIME THROUGH PROCESS--------------------
[BluetoothGatt] connect() - device: F9:40:54:9F:A8:66, auto: true
[BluetoothGatt] registerApp()
[BluetoothGatt] registerApp() - UUID=56beaf07-3b9c-466d-8ed9-5cc4a9795a99
[BluetoothGatt] onClientRegistered() - status=0 clientIf=7
[BluetoothGatt] requestConnectionPriority() - params: 0
Thread started:  #13
[BluetoothGatt] onClientConnectionState() - status=0 clientIf=7 device=F9:40:54:9F:A8:66
[0:] MyBleDelegate: BLE Device Status Connected
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
Thread started:  #14
[BluetoothGatt] setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
[0:] got rx
[0:] Mtu: 20
[BluetoothGatt] configureMTU() - device: F9:40:54:9F:A8:66 mtu: 60
[0:] got tx
[Choreographer] Skipped 69 frames!  The application may be doing too much work on its main thread.
[BluetoothGatt] onConfigureMTU() - Device=F9:40:54:9F:A8:66 mtu=60 status=0
[0:] result: 60
[0:] Writing: SM=1
[apps.spartanble] Explicit concurrent copying GC freed 35451(1627KB) AllocSpace objects, 4(208KB) LOS objects, 83% free, 4701KB/28MB, paused 22us,15us total 9.879ms
[BluetoothGatt] onPhyUpdate() - status=0 address=F9:40:54:9F:A8:66 txPhy=2 rxPhy=2
[0:] Writing: RS=1
[0:] ContentRegionViewModel RegionNavigationCallback
[0:] key: page--value: T5800 DataPage
[0:] WriteWithoutResponse
[0:] WriteWithoutResponse
Thread started: <Thread Pool> #15
Thread started: <Thread Pool> #16
[0:] Writing: RS=1
[0:] WriteWithoutResponse
[0:] Writing: RS=1
[0:] WriteWithoutResponse
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=36 latency=0 timeout=42 status=0
[OnBackInvokedCallback] OnBackInvokedCallback is not enabled for the application.
[OnBackInvokedCallback] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.TraceSource.dll
Loaded assembly: /data/data/com.canconapps.spartanble/files/.__override__/System.Diagnostics.TraceSource.dll [External]
[0:] ContentRegionViewModel OnNavigatedFrom
[BluetoothGatt] setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: false
[BluetoothGatt] close()
[BluetoothGatt] unregisterApp() - mClientIf=7
[0:] ScanViewModel OnNavigatedTo
[OnBackInvokedCallback] OnBackInvokedCallback is not enabled for the application.
[OnBackInvokedCallback] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[0:] ScanViewModel OnNavigatedFrom
[OnBackInvokedCallback] OnBackInvokedCallback is not enabled for the application.
[OnBackInvokedCallback] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[apps.spartanble] Explicit concurrent copying GC freed 21440(959KB) AllocSpace objects, 3(212KB) LOS objects, 83% free, 4725KB/28MB, paused 23us,19us total 11.688ms

------------------SECOND TIME THROUGH PROCESS---------------------
[0:] ScanViewModel OnNavigatedTo
[0:] key: device
[0:] timer started
[BluetoothAdapter] isLeEnabled(): ON
[BluetoothLeScanner] onScannerRegistered() - status=0 scannerId=5 mScannerId=0
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: SW-091C
[0:] BLE Device Found: T5800_1234
[0:] BLE Device Found: SW-091C
[BluetoothAdapter] isLeEnabled(): ON
[0:] timer stopped
[0:] Callback Cleared
[OnBackInvokedCallback] OnBackInvokedCallback is not enabled for the application.
[OnBackInvokedCallback] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[0:] ScanViewModel OnNavigatedFrom
[0:] key: Peripheral--value: crc642f3fa550470a3813.Peripheral@2ce7f45
[0:] key: deviceType--value: T5800
[0:] ContentRegionViewModel OnNavigatedTo
[0:] key: Peripheral--value: crc642f3fa550470a3813.Peripheral@2ce7f45
[0:] key: deviceType--value: T5800
[BluetoothGatt] connect() - device: F9:40:54:9F:A8:66, auto: true
[BluetoothGatt] registerApp()
[BluetoothGatt] registerApp() - UUID=fd3e0a12-08d7-4791-b350-ece5bee7c7f7
[BluetoothGatt] onClientRegistered() - status=0 clientIf=7
[BluetoothGatt] requestConnectionPriority() - params: 0
[BluetoothGatt] onClientConnectionState() - status=0 clientIf=7 device=F9:40:54:9F:A8:66
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[0:] MyBleDelegate: BLE Device Status Connected
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
[0:] got rx
[0:] Mtu: 60
[BluetoothGatt] configureMTU() - device: F9:40:54:9F:A8:66 mtu: 60
[0:] got tx
[Choreographer] Skipped 62 frames!  The application may be doing too much work on its main thread.
[BluetoothGatt] onConfigureMTU() - Device=F9:40:54:9F:A8:66 mtu=60 status=0
[0:] result: 60
[0:] Writing: SM=1
[0:] Writing: RS=1
[0:] ContentRegionViewModel RegionNavigationCallback
[0:] key: page--value: T5800 DataPage
Thread started: <Thread Pool> #17
[BluetoothGatt] onPhyUpdate() - status=0 address=F9:40:54:9F:A8:66 txPhy=2 rxPhy=2
[0:] The operation has timed out.
[0:] The operation has timed out.
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=39 latency=0 timeout=42 status=0
Thread finished: <Thread Pool> #6

### Code Sample

https://github.com/mjphillips1981/spartanble.git

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
The tests are all passing and I've verified this in one of my projects.  You need to provide MUCH smaller reproducible samples if you want any sort of help especially with a beta

**Comment by mjphillips1981** [comment]
I will see what I can do. Thanks Allan!

**Comment by mjphillips1981** [comment]
here is a more basic sample...  

https://github.com/mjphillips1981/myshinysample

let me know if this will work for you.  I am going to paste the output log in the next comment.

**Comment by mjphillips1981** [comment]
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//first connection
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[BluetoothGatt] connect() - device: F9:40:54:9F:A8:66, auto: true
[BluetoothGatt] registerApp()
[BluetoothGatt] registerApp() - UUID=84f1774e-be96-4a6f-b83e-0c7c577cbc51
[BluetoothGatt] onClientRegistered() - status=0 clientIf=7
[BluetoothGatt] requestConnectionPriority() - params: 0
[BluetoothGatt] onClientConnectionState() - status=0 clientIf=7 device=F9:40:54:9F:A8:66
Thread started:  #16
[0:] Shiny.BluetoothLE.IPeripheral: Debug: GATT Connection State Change: Success - Connected
[0:] MyBleDelegate: BLE Device Status Connected
[companyname.app] Accessing hidden method Landroid/bluetooth/BluetoothGatt;->refresh()Z (unsupported, reflection, allowed)
[BluetoothGatt] refresh() - device: F9:40:54:9F:A8:66
[0:] Shiny.BluetoothLE.IPeripheral: Warning: Clear Internal Cache Refresh Result: True
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=6 latency=0 timeout=500 status=0
[BluetoothGatt] onPhyUpdate() - status=0 address=F9:40:54:9F:A8:66 txPhy=2 rxPhy=2
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
Thread started:  #17
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=39 latency=0 timeout=500 status=0
[BluetoothGatt] refresh() - device: F9:40:54:9F:A8:66
[0:] Shiny.BluetoothLE.IPeripheral: Warning: Clear Internal Cache Refresh Result: True
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=6 latency=0 timeout=500 status=0
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=39 latency=0 timeout=500 status=0
[0:] Shiny.BluetoothLE.IPeripheral: Debug: Char InstanceID: 18
[0:] Shiny.BluetoothLE.IPeripheral: Information: Subscribing to Notification Characteristic 6e400001-b5a3-f393-e0a9-e50e24dcca9e / 6e400003-b5a3-f393-e0a9-e50e24dcca9e
[BluetoothGatt] setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
[0:] got rx
[0:] Shiny.BluetoothLE.IPeripheral: Information: Subscribed to Notification Characteristic 6e400001-b5a3-f393-e0a9-e50e24dcca9e / 6e400003-b5a3-f393-e0a9-e50e24dcca9e
[BluetoothGatt] configureMTU() - device: F9:40:54:9F:A8:66 mtu: 60
[0:] got tx
[BluetoothGatt] onConfigureMTU() - Device=F9:40:54:9F:A8:66 mtu=60 status=0
[0:] result: 60
[0:] Writing: SM=1
[0:] WriteWithoutResponse

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//on disconnect
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[0:] DataViewModel OnNavigatedFrom
[BluetoothGatt] setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: false
[0:] Shiny.BluetoothLE.IPeripheral: Debug: Cleaned up characteristic subscription: 6e400001-b5a3-f393-e0a9-e50e24dcca9e / 6e400003-b5a3-f393-e0a9-e50e24dcca9e
[BluetoothGatt] close()
[BluetoothGatt] unregisterApp() - mClientIf=7
Thread started: <Thread Pool> #19
Thread started: <Thread Pool> #20

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//after trying to reconnect
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[BluetoothGatt] connect() - device: F9:40:54:9F:A8:66, auto: true
[BluetoothGatt] registerApp()
[BluetoothGatt] registerApp() - UUID=fb6c4efb-2b2d-483f-8158-c96811fcb528
[BluetoothGatt] onClientRegistered() - status=0 clientIf=7
[BluetoothGatt] requestConnectionPriority() - params: 0
[BluetoothGatt] onClientConnectionState() - status=0 clientIf=7 device=F9:40:54:9F:A8:66
[0:] Shiny.BluetoothLE.IPeripheral: Debug: GATT Connection State Change: Success - Connected
[0:] MyBleDelegate: BLE Device Status Connected
[0:] Shiny.BluetoothLE.IPeripheral: Warning: Clear Internal Cache Refresh Result: True
[BluetoothGatt] refresh() - device: F9:40:54:9F:A8:66
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=6 latency=0 timeout=500 status=0
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
Thread started:  #28
[BluetoothGatt] refresh() - device: F9:40:54:9F:A8:66
[0:] Shiny.BluetoothLE.IPeripheral: Warning: Clear Internal Cache Refresh Result: True
[BluetoothGatt] discoverServices() - device: F9:40:54:9F:A8:66
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=39 latency=0 timeout=500 status=0
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=6 latency=0 timeout=500 status=0
[BluetoothGatt] onSearchComplete() = Device=F9:40:54:9F:A8:66 Status=0
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=39 latency=0 timeout=500 status=0
[0:] got rx
[0:] result: 60
[0:] Writing: SM=1
[0:] got tx
[BluetoothGatt] onConnectionUpdated() - Device=F9:40:54:9F:A8:66 interval=39 latency=0 timeout=42 status=0
[0:] The operation has timed out.
[0:] Writing: RS=1
[0:] The operation has timed out.

**Comment by mjphillips1981** [comment]
this only happens if I never leave the app.  

If I close the app and remove it from my recent, and then try the process it works fine.

**Comment by mjphillips1981** [comment]
Did the smaller sample work for ya?  I'm not sure what else to do here.  Let me know if there is anything else I can provide.

**Comment by aritchie** [comment]
There is still a lot of unnecessary noise in your sample, but the basic principle is disconnect/reconnect/call notifitycharacteristic.   I have a device unit test passing on this for android.  I don't run your sample beyond looking the code. 

Check your peripheral to ensure it is unhooking & rehooking.  You're getting timeouts from something which isn't related to the notification peripheral.
