### ISSUE TITLE
Provide IoC Abstractions

### ISSUE THREAD

**Issue by candidodmv** [shinyorg/shiny#128]
# Provide IoC Abstractions for implement others IoC containers providers

## Summary
Similarly as other great solutions the IoC implementation that came from abstractions to offers the possibility of plug any other container from providers.

## API Changes
Need depth investigation about what will affects

## Intended Use Case
This feateure is necessary because it's hightly recomended not use two IoC container in the same application due at least two facts:

- Performance
- Code legibility / maintainability

Each Xamarin MVVM framework has your own Ioc Implementations/providers and currently Microsoft.Extensions.DependencyInjection doesn't has your own provider because it's not eligible for this responsability, which the main cause is the fact of it's container is Immutable.

In the my context I could cite the Prism (the library that i use), where @brianlagunas says the difficult to left this requirement: https://github.com/PrismLibrary/Prism/issues/1654#issuecomment-450943385

I think this one the biggest difficult for a widely adoption of Shiny, because of its difficult to integrate with the existing codebase. The last point is reflect, how many popular MVVM frameworks currently provide integrations with Microsoft.Extensions.DependencyInjection.

**Comment by aritchie** [comment]
I use Microsoft.Extensions specifically because you can use whatever container you want that implement IServiceProvider if you don't like the built-in one.  It is the abstraction point.
