### ISSUE TITLE
[Feature Request]: Stop Android Foreground Service when user closes the app

### ISSUE THREAD

**Issue by berhir** [shinyorg/shiny#1290]
### Summary

We are using the Shiny GPS Foreground Service on Android to track the GPS location. Our users reported that the GPS tracking service continues to run even when they "close" the app (swipe out the app from the recent apps screen).

I tried to implement the expected behavior of our users but failed so far.
The most reliable way I found to achieve this is to override the [onTaskRemoved](https://developer.android.com/reference/android/app/Service.html#onTaskRemoved(android.content.Intent)) method of the service.
Unfortunately, there is no way to create a custom implementation of the GPS service and tell Shiny to use it instead of the default service.

Another option I tried is to subscribe to the [Window.Destroying Event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.window.destroying?view=net-maui-7.0) and stop the service from there. But this event gets not called in MAUI on Android because of a bug (https://github.com/dotnet/maui/issues/6993, fixed in .NET 8). Also, as far as I understand, this is not as reliable as the first option because the event may not be called in all cases.

### API Changes

I think it makes sense to have this feature in the `ShinyAndroidForegroundService` base class.

```cs
public abstract class ShinyAndroidForegroundService<TService, TDelegate> : Service
{
    // ...
    protected bool StopWithTask { get; private set; }

    public override StartCommandResult OnStartCommand(Intent? intent, StartCommandFlags flags, int startId)
    {
        var action = intent?.Action ?? AndroidPlatform.ActionServiceStart;
        switch (action)
        {
            case AndroidPlatform.ActionServiceStart:
                this.StopWithTask = intent?.GetBooleanExtra("StopWithTask", false) ?? false;
                this.Start(intent);
                break;

            case AndroidPlatform.ActionServiceStop:
                this.Stop();
                break;
        }

        return StartCommandResult.Sticky;
    }

    public override void OnTaskRemoved(Intent? rootIntent)
    {
        if (this.StopWithTask)
        {
            this.Stop();
        }
    }

    // ...
}
```

In the `AndroidPlatform` class we must add a new param to allow setting the value. It's not ideal because `stopWithTask` is only relevant for foreground services, but I hope it's fine.

```cs
public class AndroidPlatform : IPlatform, IAndroidLifecycle.IOnActivityRequestPermissionsResult, IAndroidLifecycle.IOnActivityResult
{
    // ...

    public void StartService(Type serviceType, bool stopWithTask = false)
    {
        var intent = new Intent(this.AppContext, serviceType);
        if (OperatingSystemShim.IsAndroidVersionAtLeast(26) && this.IsShinyForegroundService(serviceType))
        {
            intent.SetAction(ActionServiceStart);
            intent.PutExtra("StopWithTask", stopWithTask);
            this.AppContext.StartForegroundService(intent);
        }
        else
        {
            this.AppContext.StartService(intent);
        }
    }
}
```

And then the `AndroidGpsRequest` needs an additional `StopForegroundServiceWithTask` property as well and the `AbstractGpsManager` must pass it to the `StartService` method.

### Intended Use Case

As described in the summary, our users expect that the GPS foreground service gets stopped when they "close" the app by swiping it out from the recent apps screen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This will be part of the next release
