### ISSUE TITLE
[Android] Transfer-Encoding: chunked' header can not be used when content object is not specified.

### ISSUE THREAD

**Issue by tuyen-vuduc** [shinyorg/shiny#130]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [x] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.400-beta

## Version of OS(s) listed above with issue
All

## Steps to Reproduce
1. Create an Android app with Shiny
2. Try to download a file

## Expected Behavior
File should be downloaded

## Actual Behavior
Error thrown as title

**Comment by aritchie** [comment]
Please provide the entire stack trace as well as a device & android version.  I use the android download manager, so this likely isn't a bug, but I would like to be sure.

**Comment by tuyen-vuduc** [comment]
Hi @aritchie ,

I created an instance of `HttpClientHttpTransferManager`, and my sample code was use TransferJob, not the Android download manager.

Regards.

**Comment by aritchie** [comment]
That isn't even done or documented.  You should be using the default stuff for now.  Please make sure to include these details in the future.
