### ISSUE TITLE
[Bug]: Android PushDelegate methods never called when app launches from background by tapping push notification

### ISSUE THREAD

**Issue by MGohil** [shinyorg/shiny#1300]
### Component/Nuget

Push - Azure Notification Hub (Shiny.Push.AzureNotificationHubs)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

nuget: 
Shiny.Push.AzureNotificationHubs - 3.0.0-beta-0245
Shiny.Hosting.Maui - 3.0.0-beta-0245

I tested in Android 9 and 12 - both gives same issue.

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

1. Download the sample attached to this bug from code samples section.
2. Replace dummy values (ApplicationId and Hub connections) with actual values you have.
3. Run the app in Android device.

**App is in Foreground:**
1. While app is active, send the following payload to app from Azure push hub. The app will show alert with the notification title and body.
```
{
	"notification":{
		"title":"Notification Hub Test Notification",
		"body":"This is a sample notification delivered by Azure Notification Hubs."
	},
	"data":{
		"property1":"value1",
		"property2":42
	}
}
```
All good till now.
2. Now move app to background and send the same payload from Azure push hub.
3. Notification will arrive in device in notification tray.
4. Tap on this notification
5. App will come back to foreground state but No any methods called from PushNotificationDelegate

**App is not running (Killed)**
1. Kill the app if its active.
2. Send the above push notification.
3. Notification is not reached to the device with Android 9 and hence its not displayed in notification tray. However Azure hub says its sent successfully.
4. For Android 12 I saw it reaches after some time but clicking on notification does not execute any methods in PushNotificationDelegate.

FYI: I have posted comment on one similar issue here: https://github.com/shinyorg/shiny/issues/656#issuecomment-1673274435

### Expected Behavior

When app is in the background and if we tap on the push notification, the method from PushNotificationDelegate should be called to process the tapped notification data.
This should also call any one method from PushNotificationDelegate, when app is fresh launched (from killed state) via push notification to process the data. ``

### Actual Behavior

**App is in Foreground:**
- Tapping on the push notification brings the app back to foreground without calling any method from PushNotificationDelegate 

**App is not running (Killed)**
- Android 9 - Push notification is not displayed in notification tray.
- Android 12 - Tapping on the push notification launches the app without calling any method from PushNotificationDelegate 

### Code Sample

[ShinyTestSample.zip](https://github.com/shinyorg/shiny/files/12318960/ShinyTestSample.zip)

In this sample I have placed 
- dummy googleservices.json in Platforms/Android folder
- dummy values in appsettings.development.json for Hub connection
- AndroidManifest permissions with dummy ApplicationId = com.mycompany.myapp
So, while testing this, Kindly replace them with actual id and hub connection values according to your testing environment.

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
You need a click_action in your notification payload.  This is a requirement for android to know how to launch the notification.  It isn't something I can set for you.

If the app is killed, there is nothing I can do platform wise.

**Comment by aritchie** [comment]
No reply - closing.
