### ISSUE TITLE
[Bug]: Apple Background Push Notification terminates app

### ISSUE THREAD

**Issue by cburns-pw** [shinyorg/shiny#1301]
### Component/Nuget

Push - Native (Shiny.Push)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

iOS 16.6

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

Send background sync push notification (content-available: 1)

### Expected Behavior

Run background code

### Actual Behavior

Causes the app to crash/terminate. Alert notifications work without problem.

### Exception or Log output

```
[0:] Shiny.Hosting.IosLifecycleExecutor: Information: Shiny.Push.PushManager handling lifecycle event for Shiny.Hosting.IIosLifecycle+IRemoteNotifications
[0:] OnReceived
The app has been terminated.
``` 

### Code Sample

https://github.com/cburns-pw/shinytest

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Include a reproducible sample or it didn't happen

**Comment by cburns-pw** [comment]
How do you suggest I include a reproducible sample that includes Apple certificates to send push notifications?
If I change this delegate:
```
[Export("application:didReceiveRemoteNotification:fetchCompletionHandler:")]
    public void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler) 
        => Host.Lifecycle.OnDidReceiveRemoteNotification(userInfo, completionHandler);
```
to
```
[Export("application:didReceiveRemoteNotification:fetchCompletionHandler:")]
public void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler) 
{
    Debug.WriteLine(userInfo);
}
```
The app prints userInfo and the app does not crash.

**Comment by aritchie** [comment]
You don't have to include the certs.  I don't need them.  If you don't file a repro, I will close this though.  Please be respectful of the issue template.

**Comment by cburns-pw** [comment]
> You don't have to include the certs. I don't need them. If you don't file a repro, I will close this though. Please be respectful of the issue template.

I updated with a repo.
