### ISSUE TITLE
[Bug]: BLE operation lock not released when cleaning up characteristic notify subscriptions before closing connection

### ISSUE THREAD

**Issue by jaredballen** [shinyorg/shiny#1308]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

Android 13

*This issue was tested against a device running iOS 15.7.7 and was NOT reproducible.

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

1. Connect to BLE peripheral
2. Subscribe to Characteristic that supports Notify
3. App operation
4. Start "disconnecting" from the device
    a. Dispose subscription to characteristic notify
    b. Call CancelConnection on peripheral
5. Attempt to reconnect to the device
6. Peripheral reconnects
7. Subsequent attempts to read/write to and characteristic timeout because BLE operation lock cannot be obtained

### Expected Behavior

BLE operational lock is released, regardless of temporal proximity to canceling connection on a peripheral

### Actual Behavior

BLE operational lock is NOT released if called immediately before canceling connection on a peripheral

### Exception or Log output

Clean connection to peripheral:
![image](https://github.com/shinyorg/shiny/assets/7902566/f21e28fe-04b0-4a6b-8a35-5c2cd086894e)

Disconnection WITH delay between disposal and canceling connection:
![image](https://github.com/shinyorg/shiny/assets/7902566/f59a4786-037c-47ac-84a6-cad69ae0a095)

Disconnect WITHOUT delay between disposal and canceling connection:
![image](https://github.com/shinyorg/shiny/assets/7902566/afb454a9-2fe9-435b-9924-8a7b36d78f60)
*NOTE: BLE operation lock was not released before close().

Failed "connection" to peripheral AFTER disconnecting WITHOUT delay between disposal and canceling connection:
![image](https://github.com/shinyorg/shiny/assets/7902566/ef1c7f3f-9faa-4915-b1e8-a0a842abd52c)
*NOTE: BLE operation lock is not obtained, then characteristic write operation times out.

### Code Sample

A code sample not applicable as a connection to BLE peripheral with a notifiable characteristic is required for the reproduction of this issue.

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Thank you for thorough report.  I have a test failing likely due to this.  Should be easy enough to fix

**Comment by jaredballen** [comment]
Awesome! Thank you.

**Comment by jaredballen** [comment]
Confirmed this evening that the problem is resolved! Thanks!
