### ISSUE TITLE
[Bug]: Shiny.Notifications 2.7.2 blocks upgrade of Xamarin.Forms 5.0.0.2612

### ISSUE THREAD

**Issue by clnorris** [shinyorg/shiny#1311]
### Component/Nuget

Notifications (Shiny.Notifications)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

Android 13.0 (API Level 33)

### Hosting Model

- [ ] MAUI
- [X] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

1. Rt click the Android csproj, Manage Nuget Packages.
2. Navigate to Updates
3. Click Xamarin.Forms, observe on Aug 23 that my current/old is 5.0.0.2578, and next should be 5.0.0.2612.
4. Place check on Xamarin.Forms, Click Update
5. Forms tries to upgrade, but then it gives the restore failed / rolling back changes error.

### Expected Behavior

Xamarin.Forms upgrades like usual.

### Actual Behavior

It complains that Shiny.Notifications is wanting Xamarin.AndroidX.AppCompat (>= 1.3.0 && < 1.4.0) while forms wants Xamarin.AndroidX.AppCompat > 1.6.

If I manually add Xamarin.AndroidX.AppCompat, it starts failing on others.  Thinking Shiny v2.7.2 needs a bump to work with all the latest stuff.

Google Play store is requiring Android SDK 33 by Aug 31 so looking to refresh all components.

### Exception or Log output

Restoring packages for C:\Users\clnorris\source\repos\xxx\xxx.Android\xxx.Android.csproj...
NU1107: Version conflict detected for Xamarin.AndroidX.AppCompat. Install/reference Xamarin.AndroidX.AppCompat 1.6.0 directly to project siMobileApp.Android to resolve this issue. 
 siMobileApp.Android -> Xamarin.Forms 5.0.0.2612 -> Xamarin.AndroidX.AppCompat (>= 1.6.0 && < 1.7.0) 
 siMobileApp.Android -> Shiny.Notifications 2.7.2 -> Xamarin.AndroidX.AppCompat (>= 1.3.0 && < 1.4.0).
Package restore failed. Rolling back package changes for 'siMobileApp.Android'.

### Code Sample

I created a fresh Xamarin.Forms solution from the wizard at https://github.com/FlatironsElectronics/ShinyUpgradeIssues

After adding Shiny.Notifications to the Android project, Xamarin.Forms in Android won't upgrade.

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
I have removed the version lock and will be out in the next 2.7.x build that is publishing as I type this.

Beware that it is hard to test with all of the variants of androidx in classic Xamarin

**Comment by clnorris** [comment]
Hi @aritchie Thanks much for the quick fix to the nuget!  Was able to upgrade forms, and so far the Android app still works.  I am currently using portions of BluetoothLE, Notifications, Location, Jobs, and HTTP Transfer.  Our test resources perform at least a partial regression test every release on Android 8 thru 13.  I anticipate we will be catching regressions before we deploy.  Cheers!

**Comment by aritchie** [comment]
Oh wow.  You're using most of Shiny.  Great to hear!  Thanks for being a sponsor.
