### ISSUE TITLE
[Bug]: Push Notification IntentFilter on Android is not working

### ISSUE THREAD

**Issue by LarryOlsen** [shinyorg/shiny#1315]
### Component/Nuget

Push - Azure Notification Hub (Shiny.Push.AzureNotificationHubs)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

Android 13

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Uno
- [ ] Manual

### Steps To Reproduce

1. Run the ShinyPushTest project on an Android device.
2. Tap Register.
3. Minimize the app and send a push notification, such as:
`{
    "notification": {
        "title": "New Activity",
        "body": "A new activity is ready for review",
        "click_action": "SHINY_PUSH_NOTIFICATION_CLICK"
    }
}`
4. The push notification appears on the Android device, however when tapped nothing happens.

### Expected Behavior

When a push notification is tapped while the app is in the background or closed, the app should be opened and OnEntry should be called.

### Actual Behavior

When a push notification is tapped while the app is in the background or closed, nothing happens.

### Code Sample

https://github.com/LarryOlsen/ShinyPushTest

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
That's not where the click_action goes in the payload. Please review the firebase documentation.  This case was just recently tested and works fine

**Comment by MGohil** [comment]
You need to set Categories too in the intent filter of your MainActiity.
[IntentFilter(new[] { ShinyPushIntents.NotificationClickAction }, Categories = new[] { "android.intent.category.DEFAULT" })]

Also, in your OnCreate method, as a work around call this:
Host.Lifecycle.OnNewIntent(this, this.Intent);
This will call the OnEntry method when your app is Freshly launched by Push notification.

**Comment by aritchie** [comment]
@MGohil This is a beta.  Please don't advertise workarounds as it will eventually be tested and fixed.  I have not reproduced the issue with your workaround yet anyhow.  The fact is that the push payload on this issue is wrong

**Comment by aritchie** [comment]
The log is telling you the issue though.  I don't create a default channel with push for you.  I don't have a good answer to this and it isn't something I've documented yet because it is something that is still being considered how best to handle.

**Comment by LarryOlsen** [comment]
> You need to set Categories too in the intent filter of your MainActiity. `[IntentFilter(new[] { ShinyPushIntents.NotificationClickAction }, Categories = new[] { "android.intent.category.DEFAULT" })]`
> 
> Also, in your OnCreate method, as a work around call this: `Host.Lifecycle.OnNewIntent(this, this.Intent);` This will call the OnEntry method when your app is Freshly launched by Push notification.

@MGohil that solved the issue, thank you!

The log entry was not the issue. It is just a warning. Android uses a channel named "Miscellaneous" if a default isn't specified.

**Comment by aritchie** [comment]
This has been added to the docs and templates
