### ISSUE TITLE
[Bug]: ScanResult.AdvertisementData.ManufacturerData.Data is Empty

### ISSUE THREAD

**Issue by fekberg** [shinyorg/shiny#1319]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

iOS 16
iOS 17

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

Setup a scanner:

```
bleManager.Scan()
            .ObserveOn(RxApp.TaskpoolScheduler)
            .Subscribe
            ((scanResult) => {
                    // scanResult.AdvertisementData.ManufacturerData.Data is empty in the latest version
            }, ex => {});
```

### Expected Behavior

ManufacturerData.Data should contain the data from the advertisement package

### Actual Behavior

ManufacturerData.Data is empty

### Code of Conduct

- [X] I have supplied a reproducible sample is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v2.7.1 stable - ALPHAS are not taking issues)
- [X] My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Provide a repro and/or some logging of the manufacturer pocket or this will be closed.  Manufacturer data is parsed in company id and data

**Comment by fekberg** [comment]
Company Id comes through fine, but none of the manufacturer data from any device comes through.

I'll have to setup a small sample then, that'll take some time.

I rolled back to 3.0.0-beta-0210 and that works just fine.

**Comment by aritchie** [comment]
I have looked at a past PR that has the issue.  In the future, file the repro from the start or you'll be removed from filing issues here.  Please be respectful of the rules

**Comment by fekberg** [comment]
@aritchie I thought the steps to reproduce was a good enough sample, but I guess not. Apologise for that, I don't contribute much on github..

Anyways, sent you $500 for the trouble, thanks.

**Comment by aritchie** [comment]
Thank you for the sponsorship.  Much appreciated.

The steps are never enough and it sets the bar low for others to "send whatever".  The average report to actual issue is like 2/10.  A lot of the times I get "it doesn't work".  People often don't understand permissions or async/rx programming.  You're also often expected to play the role of documentation for every platform.  This is why I push back instantly when I don't get every piece of information.
