### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by mattalanskas** [shinyorg/shiny#1327]
### Summary

I use the IScanResult from plugin.bluetoothLE a lot in my project. Where is this located in this library?

### API Changes

N/A

### Intended Use Case

Need rssi, device and manufacturer data

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is not a support channel.  Please be respectful of our code of conduct.

ScanResult is available from BleManager.Scan and contains what you are looking for
