### ISSUE TITLE
[Feature Request]: Allow configuration of iOS foreground notification presentation options

### ISSUE THREAD

**Issue by jcsnider** [shinyorg/shiny#1334]
### Summary

As of now any push notifications received on iOS while the app is in the foreground are [handled here](UNNotificationPresentationOptions).

The hardcoded presentation options for these notifications are Banner and List.

It would be nice to set our own preferences for the presentation of these notifications.

### API Changes

Not sure, maybe an optional iOS presentation options class when adding a push notification service, or otherwise allow us to set our own handler method so we can choose the presentation options on a notification by notification basis.

### Intended Use Case

Just provide developers with more control over presentations in-app while the app is running.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is now in the beta channel and released to nuget under v3.1.  You can check out the release notes here: https://shinylib.net/release-notes/client/v30/ for an example of how to use it.

Would love any additional feedback here.  I'll close this issue for now as complete though

**Comment by jcsnider** [comment]
@aritchie works great. Thank you!
