### ISSUE TITLE
[Bug]: The operation have time out while NotifyCharacteristic function call

### ISSUE THREAD

**Issue by rajansmk** [shinyorg/shiny#1335]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

android 12,13

### Hosting Model

- [ ] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1.scanning
2.connecting
3.fetching service  and notify (while notifying -the operation has time out 
4 writing command

### Expected Behavior

i want get response when i am writing command
var chsResults = await peripheral.GetServices(true);
        string hexString = "4944454e543f0d";
        byte[] byteArray = new byte[hexString.Length / 2];

        for (int i = 0; i < byteArray.Length; i++)
        {
            byteArray[i] = Convert.ToByte(hexString.Substring(i * 2, 2), 16);
        }

        string originalStringss = Encoding.UTF8.GetString(byteArray);
        byte[] command = Encoding.UTF8.GetBytes(originalStringss);
        var wr = await peripheral.WriteCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe", command, true);

But always it returning the command only not response .

### Actual Behavior

suppose if i write command
 var wr = await peripheral.WriteCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe", command, true);

i need the exact value :D5-56-57-59 like that

### Code Sample

using MauiShinyTest.Extension;
using MauiShinyTest.Popup;
using Microsoft.Maui.Controls;
using ReactiveUI;
using ReactiveUI.Fody.Helpers;
using Shiny;
using Shiny.BluetoothLE;
using Shiny.Hosting;
using Shiny.BluetoothLE.Managed;
using System.Diagnostics;
using System.Reactive.Linq;
using System.Reactive.Threading.Tasks;
using System.Text;

namespace MauiShinyTest;

public partial class MainPage : ContentPage
{

    public MainPage(IBleManager _bleManager)
    {
        InitializeComponent();
        BindingContext = this;
        bleManager = _bleManager;
    }

    
    [Reactive] public List<BleCharacteristicInfo> Characteristics { get; private set; }
    

    public string SensorConnectionStatus { get; set; } = "Disconnected";
    public string SensorScanStatus { get; set; } = "Not found";
    public string SensorCharacteristicStatus { get; set; } = "Disconnected";

    readonly IBleManager bleManager;
    
    public IPeripheral peripheral;
    public IDisposable scanner, chsResult, wscObserver;
    public Guid uuid;
    public ScanResult scanResult;
    public BleCharacteristicInfo sensorCharacteristic;
    public BleServiceInfo blservice = null!;
    public List<byte> messageBytes;

    private bool hasDeviceStatusSubscription = false;

    async void OnScanClicked(object s, EventArgs e)
    {
        var access = await bleManager.RequestAccess();
        Console.WriteLine("Shiny Access: " + access);

        Stopwatch watch = Stopwatch.StartNew();

        scanner = bleManager.Scan().Subscribe(scanResult =>
        {
            SensorScanStatus = "Scanning...";
            OnPropertyChanged(nameof(SensorScanStatus));

            Debug.WriteLine("Found a device with name " + scanResult.Peripheral.Name);

            var adv = scanResult.AdvertisementData;

            if (adv.LocalName != null  && adv.LocalName.Contains("AN8150"))
            {
                watch.Stop();
                SensorScanStatus = "Device found: " + scanResult.Peripheral.Name.ToString();
                OnPropertyChanged(nameof(SensorScanStatus));
                var elapsed = watch.ElapsedMilliseconds;
                Debug.WriteLine("Stopping scan after " + elapsed + " mS");
                peripheral = scanResult.Peripheral;
                scanner?.Dispose();
                
            }
        });
        
    }
    async void OnServiceClicked(object s, EventArgs e)
    {
        var chsResults = await peripheral.GetServices(true);
        string hexString = "4944454e543f0d";
        byte[] byteArray = new byte[hexString.Length / 2];

        for (int i = 0; i < byteArray.Length; i++)
        {
            byteArray[i] = Convert.ToByte(hexString.Substring(i * 2, 2), 16);
        }

        string originalStringss = Encoding.UTF8.GetString(byteArray);
        byte[] command = Encoding.UTF8.GetBytes(originalStringss);
        var wr = await peripheral.WriteCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe", command, true);
        ////var managed = peripheral.(RxApp.MainThreadScheduler); // schedule 
        ////managed.StartRssi();
        //if (peripheral.Status == ConnectionState.Disconnected) // .IsDisconnected())
        //    await peripheral.ConnectAsync();

        ////var ss = await peripheral.GetAllCharacteristics();
        //var teste = await peripheral.GetServices(true);
        //foreach (var serv in teste)
        //{
        //    //var rssi = await device.Gatt.ReadRssi();
        //    Debug.WriteLine($" {serv.Uuid} ");

        //    //Debug.Indent();

        //    foreach (var chars in await peripheral.GetCharacteristics(serv.Uuid))
        //    {
        //        Debug.WriteLine($"{chars.Uuid} Properties:{chars.Properties}");

        //        Debug.Indent();

        //        foreach (var descriptors in await peripheral.GetDescriptors(serv.Uuid, chars.Uuid))
        //        {
        //            Debug.WriteLine($"Descriptor:{descriptors.Uuid} Value:{descriptors.GetValue}");

        //            //var val2 = await descriptors.ReadValueAsync();

        //            //if (descriptors.Uuid == GattDescriptorUuids.ClientCharacteristicConfiguration)
        //            //{
        //            //    Debug.WriteLine($"Notifying:{val2[0] > 0}");
        //            //}
        //            //else if (descriptors.Uuid == GattDescriptorUuids.CharacteristicUserDescription)
        //            //{
        //            //    Debug.WriteLine($"UserDescription:{ByteArrayToString(val2)}");
        //            //}
        //            //else
        //            //{
        //            //    Debug.WriteLine(ByteArrayToString(val2));
        //            //}

        //        }

        //        Debug.Unindent();
        //    }

        //    Debug.Unindent();
        //}

        

        //byte[] command = Encoding.UTF8.GetBytes("MODEL?\r\n"); // Replace "YourBinaryData" with your actual binary data

        //// string base64String = Convert.ToBase64String(command);
        //var rd= await peripheral.ReadCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe");
        //var wr = await peripheral.WriteCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe", command,true);
        //var rds = await peripheral.ReadCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe");
        //var rds1 = await peripheral.ReadCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe");
        //var rds2 = await peripheral.ReadCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe");
        //var rds3 = await peripheral.ReadCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-6daa-4d02-abf6-19569aca69fe");
        //string originalString = Encoding.UTF8.GetString(wr.Data);
        //Debug.WriteLine($"Notifying:{originalString}");

        //string originalString1 = Encoding.UTF8.GetString(rds1.Data);
        //Debug.WriteLine($"Notifying:{originalString1}");

        //string originalString2 = Encoding.UTF8.GetString(rds2.Data);
        //Debug.WriteLine($"Notifying:{originalString2}");

        //string originalString3 = Encoding.UTF8.GetString(rds3.Data);
        //Debug.WriteLine($"Notifying:{originalString3}");

        ////GetCharacteristics
        ////var kk = await peripheral.GetService("0000aaa0-0000-1000-8000-aabbccddeef");

    }

    async void OnConnectClicked(object s, EventArgs e)
    {
        if (!hasDeviceStatusSubscription)
        {
            try
            {
                //
                //await peripheral.WithConnectIf().Timeout(TimeSpan.FromSeconds(30)).ToTask();
                //await peripheral.ConnectAsync();
                //*** Test All Characteristics
                //var teste = await peripheral.GetAllCharacteristics().Timeout(TimeSpan.FromSeconds(20));
                
                
                    
                

                wscObserver = peripheral.WhenStatusChanged().Subscribe(connectionState =>
                {
                    hasDeviceStatusSubscription = true;
                    Debug.WriteLine("Connected to " + connectionState.ToString());
                    switch (connectionState)
                    {
                       

                        case Shiny.BluetoothLE.ConnectionState.Connected:
                            Debug.WriteLine("Device connected OK");
                            SensorConnectionStatus = "Connected to " + peripheral.Name.ToString();
                            OnPropertyChanged(nameof(SensorConnectionStatus));
                            break;

                        case Shiny.BluetoothLE.ConnectionState.Disconnected:
                            Debug.WriteLine("Device disconnected");
                            SensorConnectionStatus = "Disconnected";
                            OnPropertyChanged(nameof(SensorConnectionStatus));
                            break;

                        case Shiny.BluetoothLE.ConnectionState.Connecting:
                            Debug.WriteLine("Device in connecting state");
                            SensorConnectionStatus = "Connecting...";
                            OnPropertyChanged(nameof(SensorConnectionStatus));
                            break;

                        default:
                            Debug.WriteLine("break...");

                            break;

                    }

                });

                //*** Get Characteristc - ChBattery
                //sensorCharacteristic = await peripheral.GetCharacteristic(AppSettings.GetServiceUuid, AppSettings.ChBattery).Take(1)
                //      .Timeout(TimeSpan.FromSeconds(10));
            }
            catch (Exception ex)
            {
                await DialogServices.SnackBarMsg(ex.Message);
            }
        }

        Debug.WriteLine("Connecting...");
        Debug.WriteLine("Connected to " + peripheral.Status.ToString());
        //peripheral.Connect(new ConnectionConfig
        //{
        //    AutoConnect = true,

        //});
        if (peripheral.Status == ConnectionState.Disconnected) // .IsDisconnected())
        {
            await peripheral.ConnectAsync();
        }
        else
        {
            
        }
            

        

        //sensorCharacteristic = await peripheral.GetAllCharacteristics();
        //                .WithConnectIf()
        //                .Select(x => x.GetServices())
        //                .Switch()
        //                .ToTask();

        var ss = await peripheral.GetAllCharacteristics();
        //var teste = await peripheral.ReadCharacteristicAsync(AppSettings.GetunknownServiceUuid.ToString(), AppSettings.ChunknownNotifyVib.ToString());
    }

    async void OnStartNotify(object s, EventArgs e)
    {
        sensorCharacteristic = null;
        string hexString = "4944454e543f0d";
        byte[] byteArray = new byte[hexString.Length / 2];

        for (int i = 0; i < byteArray.Length; i++)
        {
            byteArray[i] = Convert.ToByte(hexString.Substring(i * 2, 2), 16);
        }

        string originalStringss = Encoding.UTF8.GetString(byteArray);
        byte[] command = Encoding.UTF8.GetBytes(originalStringss);

        //string seriveUUID = AppSettings.ServiceUUID;
        //string charUUID = AppSettings.ChNotifyVib;

        string seriveUUID = AppSettings.GetunknownServiceUuid;
        string charUUID = AppSettings.ChunknownNotifyVib;
        var chsResults = await peripheral.GetServices(true);
        sensorCharacteristic = await peripheral.GetCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-1e4d-4bd9-ba61-23c647249616");
        sensorCharacteristic.AssertWrite(true);
        sensorCharacteristic.AssertNotify();
        peripheral
            //.WriteCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-1e4d-4bd9-ba61-23c647249616",command,true)
            .NotifyCharacteristic("49535343-fe7d-4ae5-8fa9-9fafd205e455", "49535343-1e4d-4bd9-ba61-23c647249616",false,true)
            .Timeout(TimeSpan.FromSeconds(30))
            .SubOnMainThread(
                //x =>
                //{
                //    //read
                //    this.SetReadValue(x, false);
                //    chsResult.Dispose();
                //}
                //, ex =>
                //{
                //    _ = DialogServices.SnackBarMsg("Erro DoNotifyAsync!\n" + ex.Message);
                //    chsResult.Dispose();
                //}
                async x =>
                {
                    // Read the value and set it
                    this.SetReadValue(x, false);
                    //await chsResult.DisposeAsync(); // Assuming DisposeAsync is an asynchronous method
                },
        async ex =>
        {
            _ = DialogServices.SnackBarMsg("Erro DoNotifyAsync!\n" + ex.Message);
            //await chsResult.DisposeAsync(); // Assuming DisposeAsync is an asynchronous method
        }
        );

        if (sensorCharacteristic != null)
        {
            Debug.WriteLine("Characteristic discovered: " + sensorCharacteristic.Uuid.ToString());
            SensorCharacteristicStatus = "Listening...";
            OnPropertyChanged(nameof(SensorCharacteristicStatus));
        }
        
    }
    void SetReadValue(BleCharacteristicResult result, bool fromUtf8) => Application.Current.Dispatcher.Dispatch(() => //Device.BeginInvokeOnMainThread(() =>
    {
        var testeResult = fromUtf8
                ? Encoding.UTF8.GetString(result.Data, 0, result.Data.Length)
                : BitConverter.ToString(result.Data).Replace("-", " ");
    });

    async void OnDisconnect(object s, EventArgs e)
    {

        if (sensorCharacteristic != null)
        {
            if (sensorCharacteristic.IsNotifying)
            {
                SensorCharacteristicStatus = "Not listening";
                OnPropertyChanged(nameof(SensorCharacteristicStatus));

                chsResult?.Dispose();
                wscObserver?.Dispose();
                sensorCharacteristic = null;
                hasDeviceStatusSubscription = false;
            }
        }

        if (peripheral.Status == ConnectionState.Connected) //.IsConnected())
        {
            peripheral.CancelConnection();
            SensorConnectionStatus = "Disconnected";
            OnPropertyChanged(nameof(SensorConnectionStatus));

        }

    }

}

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
I'm not sure what you're asking me here?

* The title says you're getting a timeout, but where is that timeout happening?  On the Notify function?  
* In your expected behaviour you state: But always it returning the command only not response .    <= Shiny doesn't change the data that is being sent back to you.  Did you check your actual peripheral.

Please reduce your code as well.  The intent of a reproducible sample is small & focused with commented code being removed.

**Comment by rajansmk** [comment]
await peripheral
            .NotifyCharacteristic(notifyCharacteristic,false,false)
            .Timeout(TimeSpan.FromSeconds(60));
while calling this function i am getting error "the operation has timed out"
I have implemented through SubOnMainThread but no use same error.
When I am writing command I need response. (it is working on the nrf connect application but i don't know how to get from NotifyCharacteristic function)
Please guide me..

**Comment by rajansmk** [comment]
This is my byte array :4d4f44454c3f0d          string value :MODEL?
Nrf response(debug) from var wr = await peripheral.WriteCharacteristic(notifyCharacteristic, command,true);  is 0D0A32303035303132330D0A3E  
when i write the command i am getting this byte code only return(wr.data) "4d4f44454c3f0d" not  this expected result 0D0A32303035303132330D0A3E

**Comment by rajansmk** [comment]
my code file
https://github.com/rajansmk/ble

**Comment by aritchie** [comment]
Ok you've still given me almost 400 lines of code to look at, so I'm going to bypass that for now.

I don't know if there is a bug here, but you've put a timeout on a streaming characteristic.  NotifyCharacteristic is a continuous stream, so you don't want it to timeout.  You just want to wait/listen on it.  

As for your write - shiny doesn't do anything weird with the data.  You need to figure out your peripheral and writes.  

You really have to point me towards a bug in Shiny or I'll have to close this one off

**Comment by rajansmk** [comment]
if i code very simple method then also i am facing timeout error..
var noti = await peripheral.NotifyCharacteristic(notifyCharacteristic, false, false);

**Comment by aritchie** [comment]
> i have given the github link https://github.com/rajansmk/ble
Yes, but as I've said - it is too large and doesn't actually frame an issue I can fix with this library

> var noti = await peripheral.NotifyCharacteristic(notifyCharacteristic, false, false);
You can't do this.  It is a continuous stream.  You need to research how your peripheral works for TX/RX and how to properly use reactive extensions as part of this library.

> Then how to get response from ble device through write command(WriteCharacteristic) .can you pls give any sample code..
There is a sample app as part of this repo and there is documentation on shinylib.net .  This isn't tech support and I simply don't know your peripheral. 

This appears to be a misunderstanding with how things work and not the library.  I am closing this for now.  If you can provide an actual issue with a repro, I'm happy to take a look
