### ISSUE TITLE
[Feature Request]: Android Local Notifications - Categories

### ISSUE THREAD

**Issue by wesoos** [shinyorg/shiny#1346]
### Summary

Be able to set the notification category, i.e., `.SetCategory(NotificationCompat.CategoryCall)`

### API Changes

Add ability to add categories to the AndroidNotification object..

### Intended Use Case

The call category allows for the heads up notification to display fully opened by default, for incoming phone/video calls...

Would love for the ability to have the heads up stay on the screen until the user clicks it, but that's a different topic..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Will be available in the next release
