### ISSUE TITLE
Make Shiny Sample look pretty!

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#136]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Do the title

## API Changes
Don't change the API :)

## Intended Use Case
It causes an "OOOOOH" effect when opened

**Comment by DanielCauser** [comment]
I think I can do that <3
