### ISSUE TITLE
[Bug]:  Issue with foreground service starts not

### ISSUE THREAD

**Issue by magtimmermans** [shinyorg/shiny#1361]
### Component/Nuget

GPS or Geofencing (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

Windows 10, Microsoft Visual Studio Community 2022 (64-bit) - Version 17.8.3

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

Press Start GPS in the App

### Expected Behavior

Andriod foreground service will started and gps updates will be send to OnGpsReadingAndroid

### Actual Behavior

foreground service not started (sorry I am new and the documentation was not yet finished, maybe I made a mistake)

### Exception or Log output

none

### Code Sample

https://github.com/magtimmermans/TestLocations

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Your sample link doesn't work

Please add more info so I don't actually have to compile and spin up the sample.  Is there an error, what about the logs, etc?

**Comment by magtimmermans** [comment]
Sorry about that. I have made it public now so that it should be visible.

No I havent found any errors in the logfiles. So I expect I do something wrong here.

`      
           if (this.gpsManager == null)
            {
                return;
            }

            await gpsManager.StopListener();

            GpsRequest gpsRequest = new GpsRequest
            {
                Accuracy = GpsAccuracy.Highest,
                BackgroundMode = GpsBackgroundMode.Realtime,
                DistanceFilterMeters = 10
            };

            AccessState access = await gpsManager.RequestAccess(gpsRequest);

            if (access == AccessState.Available)
            {
                await gpsManager.StartListener(gpsRequest);

            }
 `

This code I am using to spin up the foreground service for android. Even when I make background standard it doesn't work as well. I have used your templates to generate the project (great work!)

**Comment by aritchie** [comment]
Fixed in 3.2.1
