### ISSUE TITLE
[Bug]: MAUI iOS token not working with Firebase. (Previously under issue #1377)

### ISSUE THREAD

**Issue by Yahya0007** [shinyorg/shiny#1382]
### Component/Nuget

Push - Native (Shiny.Push)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

iOS 17.2.1

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

Sample project repository attached. Running sample project will come up with a token. Using this token does not work with sending Push.

### Expected Behavior

Push token should work when sending push notifications to iOS devices using Firebase.

### Actual Behavior

Sending push notifications to iOS devices comes up with below exception;

FirebaseMessagingException: The registration token is not a valid FCM registration token

### Exception or Log output

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The registration token is not a valid FCM registration token)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XFFCMPushNotificationsSample.Send.Program.Main(String[] args) in F:\Projects\....\Program.cs:line 39

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FirebaseMessagingException: The registration token is not a valid FCM registration token

### Code Sample

Sample app repository link: https://github.com/Yahya0007/Shiny-Issue-1377-Sample

Invite to join this private reposiorty sent.

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Please make the link public

**Comment by Yahya0007** [comment]
Link to public repository: https://github.com/Yahya0007/Shiny-Issue-1377-Sample3

Thanks

**Comment by aritchie** [comment]
You aren't using the firebase messaging plugin which is necessary for iOS if you want it to use firebase

https://shinylib.net/client/push/providers/

**Comment by Yahya0007** [comment]
HI Allan

 

Thanks a lot. Very embarrassed at wasting your time.

 

Regards

 

Yahya
