### ISSUE TITLE
[Bug]: IBleDelegate::OnAdapterStateChanged is not called

### ISSUE THREAD

**Issue by sleushunou** [shinyorg/shiny#1388]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

Android 13 (tested on Pixel 4a)

### Hosting Model

- [ ] MAUI
- [X] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1. Run application
2. on/off bluetooth on device

### Expected Behavior

IBleDelegate::OnAdapterStateChanged calls with actual state

### Actual Behavior

IBleDelegate::OnAdapterStateChanged is not called

### Exception or Log output

instead of logs.
seems like problem is here:
`
ShinyBleAdapterStateBroadcastReceiver.Process = async intent =>
        {
            if (intent?.Action != BluetoothAdapter.ActionStateChanged)
                return;

            var newState = (State)intent.GetIntExtra(BluetoothAdapter.ExtraState, -1);
            if (newState == State.Connected || newState == State.Disconnected)
            {
                var status = newState == State.Connected
                    ? AccessState.Available
                    : AccessState.Disabled;

                await this.services
                    .RunDelegates<IBleDelegate>(
                        del => del.OnAdapterStateChanged(status),
                        this.logger
                    )
                    .ConfigureAwait(false);
            }
        };
`
        
because when i on/off bluetooth, newState changed between State.On/State.Off, not State.Connected/State.Disconnected

### Code Sample

`
    public sealed class BleClientDelegate : BleDelegate, IBleStatusProvider
    {
        private readonly Subject<AccessState> _adapterStateSubject;

        public BleClientDelegate()
        {
            _adapterStateSubject = new Subject<AccessState>();
        }

        public IObservable<AccessState> AdapterStateObservable => _adapterStateSubject
            .DistinctUntilChanged()
            .Synchronize();

        public override Task OnAdapterStateChanged(AccessState state)
        {
            _adapterStateSubject.OnNext(state);

            return Task.CompletedTask;
        }
    }
    `

`
            var host = HostBuilder.Create();
            host.Services.AddBluetoothLE<BleClientDelegate>();
            host.Build().Run();`
            
            

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Thank you for the report.  Please feel free to submit PR's in the future
