### ISSUE TITLE
[Bug]: App in background or not running. No any event fires under Android

### ISSUE THREAD

**Issue by msrockswell** [shinyorg/shiny#1390]
### Component/Nuget

Push - Azure Notification Hub (Shiny.Push.AzureNotificationHubs)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)
- [ ] Windows (.NET 7 Target - only Core is currently supported, BLE is coming)

### Version(s) of Operation Systems

NET 7 | Shiny.Hosting.Maui 3.1.2 | Shiny.Push.AzureNotificationHubs 3.1.2

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

App is in Background (Android):
No any event fires and I can't handle the push when I tap on push notification.

App is Not running (Android):
No any event fires and I can't handle the push when I tap on push notification.

On iOS workes fine.

### Expected Behavior

-

### Actual Behavior

-

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
You did not follow any of requirements for posting issues here.
