### ISSUE TITLE
net8.0 support for Maui

### ISSUE THREAD

**Issue by lancer1977** [shinyorg/shiny#1394]
### Summary

I want to use this library in my Maui app but I have a lot of code within the Maui project that has unit tests that run on it. I haven't figured out a way to execute unit tests against platforms without running the platform explicitly, and it kind of defeats the purpose of Unit Testing. I haven't had a chance to look into the code to see how "easy" this would be, but would be invaluable to my project if we can get it supported.

### API Changes

net-8.0 compatibility, I understand that this is platform specific libraries but I think fakes would be sufficient. Something to the effect if someone tried to access Shiny code outside of a platform an exception would throw regarding that its not supported outside of platforms.

### Intended Use Case

Unit testing Maui code. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I'm not really sure what you're requesting.  All of the modules support base net8.0 and have interfaces for the services already.

**Comment by lancer1977** [comment]
Thanks for the prompt response. So I'm trying to integrate Push Notifications into a port I'm working on to Maui for iOS and Android but unit tested with net-8.0, Shiny.Hosting.Maui, Shiny.Extensions.Configuration, maybe others dont list dependencies for net8.0 (plain). 

If I attempt to compile with them I get errors such as this:

Error	NU1202	Package Shiny.Extensions.Configuration 3.2.4 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Shiny.Extensions.Configuration 3.2.4 supports:
  - monoandroid13.0 (MonoAndroid,Version=v13.0)
  - net8.0-android34.0 (.NETCoreApp,Version=v8.0)
  - net8.0-ios17.2 (.NETCoreApp,Version=v8.0)
  - net8.0-maccatalyst17.2 (.NETCoreApp,Version=v8.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)	shinytest	D:\ecode\shinytest\shinytest.csproj

**Comment by aritchie** [comment]
Shiny.Hosting.Maui has no direct functionality so compiler flag the UseShiny out

Shiny.Extensions.Configuration is an implementation of IConfiguration from Microsoft.Extensions.Configuration

**Comment by NishiokaTakeo** [comment]
Same problem. It sounds like `Shiny `library only supports Device Unit testing? I want to make unit test on non-device.

**Comment by aritchie** [comment]
@NishiokaTakeo 

The package named "Shiny" is 2.7.x and no longer used.

The rest of the packages listed above have been answered.
