### ISSUE TITLE
AndroidShinyHost and iOsShinyHost not available

### ISSUE THREAD

**Issue by TopperDEL** [shinyorg/shiny#14]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [X] UWP
 - [X] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Locations
 - [X] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.187 and 1.0.0.0.8 (check only those two)

## Expected Behavior
AndroidShinyHost and iOsShinyHost are included in the Nuget Shiny.Core

## Actual Behavior
Both classes are not available and I don't know why. Am I missing a nuget package?

**Comment by aritchie** [comment]
What is your android and iOS major targets?  Are you using packages.config?  Can you provide a repo?

**Comment by TopperDEL** [comment]
Android-MinTarget is 4.1 (16), Target is 8.0 (26). Is this, what you Need?
I'm wondering that everything is included, but those two classes not. I should add that I try to use your library with the uno-platform.

**Comment by DevEddy** [comment]
You also need to set the android compile target framework:
![image](https://user-images.githubusercontent.com/7648336/58547151-2776f480-8207-11e9-9c08-e0f2aea957e6.png)

**Comment by aritchie** [comment]
Yes - that is what I need.  

The classes definitely are included.  I'm already actively using Shiny libs in several projects.  They are also used here: https://github.com/shinyorg/shinysamples 

https://www.nuget.org/packages/Shiny.Core/1.0.0.187-beta (break down dependencies to see support major targets)

If you aren't seeing the iOSShinyHost - you'll need to provide some additional info like a reproducible sample.

**Comment by TopperDEL** [comment]
Ok, at least for Android it is working with Setting "Android compile target framework" from Oreo to Pie.
Did not test iOs yet, but might be something similar.

Didn't know this. Thanks for helping out so quickly!
