### ISSUE TITLE
[Bug]: Shiny not working with Azure Notification Hub and FCM V1

### ISSUE THREAD

**Issue by South2AK** [shinyorg/shiny#1418]
### Component/Nuget

GPS or Geofencing (Shiny.Locations)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)

### Version(s) of Operation Systems

Android 14 API 34

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

Set up Azure Notification Hub with FCM
Setting up the project the same as in the documentation

### Expected Behavior

Device should show a message which has been send via Azure Portal

### Actual Behavior

Nothing happens when using FCM.

GCM works fine (will be wrk

### Exception or Log output

Hi,

I´ve been trying to set up Azure Notification Hub with FCM V1.

I did add a Push Delegate and everything works fine for GCM, but when using FCM I get no response from the device (azure test shows no device received the message)

Is there anything to consider when using FCM instead of GCM?

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by South2AK** [comment]
builder.Services.AddPushAzureNotificationHubs<Helpers.Delegates.MNotificationDelegate>(
    "My UrL",
    "MyNotificationHub"
);


 public class MNotificationDelegate : IPushDelegate
 {
     public Task OnEntry(PushNotification notification)
     {
         return Task.CompletedTask;

     }

     public Task OnReceived(PushNotification notification)
     {

     Console.WriteLine(notification.data.ToString());
         return Task.CompletedTask;
     }

     public Task OnTokenRefreshed(string token)
     {
         return Task.CompletedTask;
     }
 }

**Comment by aritchie** [comment]
No reproducible sample

**Comment by aritchie** [comment]
This is the second time you haven't produced a reproducible sample.  Please respect my time and this repo or you'll be removed from it.  Please note that this is also not meant as a support forum.  You can see the integration with azure is light, so server details are something you should follow OUTSIDE of this repo
