### ISSUE TITLE
Geofencing on android triggers all zones after creation of these zones

### ISSUE THREAD

**Issue by F0rc0sigan** [shinyorg/shiny#142]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.454-beta
## Version of OS(s) listed above with issue
Android 8

## Steps to Reproduce
1. Create few geofences with await _geofenceManager.StartMonitoring(reg);
2. Set Notify Enter and Exist = True

## Expected Behavior
It does not call delegate method until we enter geofence point

## Actual Behavior
It calls delegate method with Shiny.Locations.GeofenceState.Exited status for every geofence point that was added

**Comment by aritchie** [comment]
This is simply how some flavours of android behave.  It isn’t anything I’m triggering.

**Comment by F0rc0sigan** [comment]
Thanks for quick reply. There is a way to avoid initial trigerring. Here is good explanation https://stackoverflow.com/a/46773123/604790 
`GeofencingRequest.Builder().setInitialTrigger(NO_INITIAL_TRIGGER)`

What do you think?

**Comment by aritchie** [comment]
It isn't that simple.  I need the initial values for checking current state.  I'll look into this for a future release.
