### ISSUE TITLE
WhenStatusChanged broken for Android

### ISSUE THREAD

**Issue by ThumbGen** [shinyorg/shiny#145]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [x] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
master

## Version of OS(s) listed above with issue
any Android

## Steps to Reproduce
1. Try to subscribe to WhenStatusChanged() for the IPeripheralManager
2. 
3.

## Expected Behavior
The Observer should work as before.

## Actual Behavior
Crash

[Problematic file](https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Peripherals/Platforms/Android/PeripheralManager.cs
)

The WhenStatusChanged observable is always null.

**Comment by aritchie** [comment]
It wasn't finished yet
