### ISSUE TITLE
[Bug]: BLE CharacteristicInfo Discovery 

### ISSUE THREAD

**Issue by RobSchein** [shinyorg/shiny#1462]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Android 14

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

I believe I whittled down my application to a minimal working framework that simply lists a device, lists its services, and lists characteristics.  You will see classes that represent collections of devices, a device, collections of services, a single service, a collection of characteristics, and a single characteristic.  All the scanning work is done in the collections classes and is handled in a few lines of code each.  

1. Edit the Constants.cs file and change DeviceUuid to the Uuid of a service on the device being used to test.  Here you will also see the Uuids of the services and characteristics I have programmed into my peripheral.
2. Build and execute project on android phone
3. There is a Scan button, a Connect button, then three picker controls to select a device, a service on that device, then list the characteristics associated with the selected service.
4. Once running, click Scan button to start Peripheral scanner (ScanConfig(OneOfMyServicesUuid) (I have only 1 device and it is found.
5. Click Connect (connects to device and populates "Select a device" picker control
6. Click on "Select a device" from the picker control - this action scans for and populates the "Select a service" picker control
7. Click on "Select a service" from the picker control - This action scans for characteristics using the selected ServiceInfo.Uuid obtained from this step.
8. Click on "Select a Characteristic" from the picker control.  This action displays the characteristics, HOWEVER, all the characteristics on my Peripheral are displayed, not just the ones for the selected service.

### Expected Behavior

After successfully scanning for a Perpheral, and then scanning for its services, I call

var CharacteristicListReadOnly = await Peripheral.GetCharacteristicsAsync(ServiceInfo.Uuid);
I presume that by calling this function with a ServiceInfo.Uuid, CharacteristicListReadOnly would return the list of characteristics that are assoicated with the supplied service.

### Actual Behavior

CharacteristicListReadOnly returns the list of ALL characteristics that are implemented on the Peripheral.  I have to manually filter only the characteristics that I have knowledge that belong to that ServiceInfo.Uuid.

### Exception or Log output

None.

### Code Sample

https://github.com/RobSchein/ShinyTest.git

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
> Edit the Constants.cs file and change DeviceUuid to the Uuid of a service on the device being used to test. Here you will also see the Uuids of the services and characteristics I have programmed into my peripheral.

You need to read the docs about the device UUID - https://shinylib.net/client/ble/best-practices/

> https://github.com/RobSchein/ShinyTest.git
There is no source code here

**Comment by RobSchein** [comment]
So sorry, Allan.  My bad.  Repository now has code.

 

I’ll re-read the reference you sent.

 

Thanks in advance,

-Rob

**Comment by aritchie** [comment]
Getting 404 on the repo now

**Comment by RobSchein** [comment]
Hi Allan,

Urg, my bad again.  The repo is public now.  Pls try again.

 

Oh, after re-reading the best practices, I want to clarify that the DeviceUuid in the Constants.cs file is the UUID of one of my services on the device (as mentioned in the docs, scanning for My Peripheral should be done using one of the custom Service UUIDs).  I believe I am following the other guidelines (at least in the short term until I develop out some more).

 

Thanks for persisting with my failures 😉

-Rob

**Comment by aritchie** [comment]
> I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)

```xml
		<PackageReference Include="Shiny.BluetoothLE" Version="3.2.4" />
		<PackageReference Include="Shiny.Hosting.Maui" Version="3.2.4" />
		<PackageReference Include="Shiny.Logging.Sqlite" Version="3.3.0" />
```

Version 3.3.3 is the latest.  

https://shinylib.net/release-notes/client/v30/ - read 3.3.1 & https://github.com/shinyorg/shiny/commit/0d7831f4aa88411e85db9e0f86ebc2834b12d430

Please follow the guidelines in the template in the future!!!!


As an FYI, abstracting and abstraction is something I don't review and you will run into problems in the future doing stuff like this going forward

**Comment by RobSchein** [comment]
Hi Allan,

 

Oh, that’s good news.  It’s rare to find someone out there with a great software library, ESPECIALLY who is so dedicated and supportive to spending time to reply and to do so almost immediately.  I do appreciate those individual qualities, so much so, that I just sent over a $100 donation.

 

Short background…

 

I’ve got a patent in progress for a consumer device (this is not my real job).  I’ve got 40 years of C++ development experience, and only started with C# in January (yeah, this year), so I have a ton of tricks to learn.  I will never burden you with those questions since I value researching new skills highly.

 

Again, your ethics and quality align with my developer view, so I wanted to reward you with a little token of appreciation.  Hopefully, my little gizmo will be sellable, and I will be able to provide more incremental tokens of my appreciation.

 

Sincerely,

-Rob
