### ISSUE TITLE
[Bug]: System.ObjectDisposedException: ObjectDisposed_Generic ObjectDisposed_ObjectName_Name, Android.OS.PowerManager

### ISSUE THREAD

**Issue by mattgagnon2** [shinyorg/shiny#1465]
### Component/Nuget

Jobs (Shiny.Jobs)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

13

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1. Start the app
2. Wait for the battery info to change

### Expected Behavior

App should not crash

### Actual Behavior

App crashes getting the energy saver status

### Exception or Log output

05-06 15:41:14.602   882   882 E AndroidRuntime: FATAL EXCEPTION: main
05-06 15:41:14.602   882   882 E AndroidRuntime: Process: com.companyname.objectdisposedsample, PID: 882
05-06 15:41:14.602   882   882 E AndroidRuntime: android.runtime.JavaProxyThrowable: [System.ObjectDisposedException]: Cannot access a disposed object.
05-06 15:41:14.602   882   882 E AndroidRuntime: Object name: 'Android.OS.PowerManager'.
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Java.Interop.JniPeerMembers.AssertSelf(/Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:153)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod(/Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:146)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Android.OS.PowerManager.get_IsPowerSaveMode(/Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.OS.PowerManager.cs:934)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Microsoft.Maui.Devices.BatteryImplementation.get_EnergySaverStatus(D:\a\_work\1\s\src\Essentials\src\Battery\Battery.android.cs:45)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at ObjectDisposedSample.MainViewModel.Battery_BatteryInfoChanged(/Users/t004490/Projects/ObjectDisposedSample/ObjectDisposedSample/MainViewModel.cs:33)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Microsoft.Maui.Devices.BatteryImplementation.OnBatteryInfoChanged(D:\a\_work\1\s\src\Essentials\src\Battery\Battery.shared.cs:167)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Microsoft.Maui.Devices.BatteryImplementation.OnBatteryInfoChanged(D:\a\_work\1\s\src\Essentials\src\Battery\Battery.shared.cs:157)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Microsoft.Maui.Devices.BatteryImplementation.OnBatteryInfoChanged(D:\a\_work\1\s\src\Essentials\src\Battery\Battery.shared.cs:160)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Microsoft.Maui.Devices.BatteryBroadcastReceiver.OnReceive(D:\a\_work\1\s\src\Essentials\src\Battery\Battery.android.cs:167)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Android.Content.BroadcastReceiver.n_OnReceive_Landroid_content_Context_Landroid_content_Intent_(/Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Content.BroadcastReceiver.cs:480)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLL_V(/Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:198)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at crc640a8d9a12ddbf2cf2.BatteryBroadcastReceiver.n_onReceive(Native Method)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at crc640a8d9a12ddbf2cf2.BatteryBroadcastReceiver.onReceive(BatteryBroadcastReceiver.java:30)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-06 15:41:14.602   882   882 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Code Sample

[https://github.com/mattgagnon2/ObjectDisposedSample](url)

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
There is not a single thing in the exception that shows Shiny is even involved.  Your crash shows the MAUI battery implementation which I don't touch

**Comment by mattgagnon2** [comment]
I understand that the exception doesn't show Shiny involved. You can confirm with the sample app attached that the exception is thrown when the energy saver status changes and if you comment out the line that registers the job to run, the exception doesn't happen. 

The BatteryImplementation of maui gets a reference to the power manager with
```		
static PowerManager? powerManager;

static PowerManager? PowerManager =>
	powerManager ??= Application.Context.GetSystemService(Context.PowerService) as PowerManager;
```
and when the EnergySaverStatus is retrieved, PowerManager ends up being a disposed object
```
public EnergySaverStatus EnergySaverStatus
{
	get
	{
		var status = PowerManager?.IsPowerSaveMode ?? false;
		return status ? EnergySaverStatus.On : EnergySaverStatus.Off;
	}
}
```
Line 59 of Shiny.Jobs/Platforms/Android/JobManager.cs has the line 
`using var pm = this.platform.GetSystemService<Android.OS.PowerManager>(Context.PowerService);`
and I thought it possible that is getting disposed of there.

**Comment by aritchie** [comment]
I just ran your sample on Android 10, 13, & 14 without issue.  

Update your workloads and MAUI version.

**Comment by aritchie** [comment]
That's what I'm running

**Comment by mattgagnon2** [comment]
When you ran the app, did you have the usb cable unplugged? I forgot to list that in my reproduction steps.

**Comment by mattgagnon2** [comment]
Do you have any other suggestions because like I said, if I don't register the job, the exception doesn't occur.

**Comment by aritchie** [comment]
Don't use a foreground service, use shiny's battery implementation, or submit a fix to MAUI

**Comment by RsZoli** [comment]
@aritchie Hey Allen! I have a very similar problem to this:

Error setting up task - getsts_process

System.ObjectDisposedException: ObjectDisposed_Generic
ObjectDisposed_ObjectName_Name, Android.OS.PowerManager+WakeLock
  ?, in void JniPeerMembers.AssertSelf(IJavaPeerable)
  ?, in void JniInstanceMethods.InvokeVirtualVoidMethod(string, IJavaPeerable, JniArgumentValue*)
  ?, in void WakeLock.Release()
  File "JobManager.cs", line 72, in async void JobManager.RunTask(string taskName, Func<CancellationToken, Task> task)
    wakeLock.Release();

I'm using your solution like this:

`Shiny.Hosting.Host.GetService<IJobManager>().RunTask("getsts_process", async (c) =>
{
        await RestoreStsAsync();
});`

Is this not related as well? Thank you!

**Comment by aritchie** [comment]
Probably.  It's the same mechanism.  The bug in MAUI and I sent a fix already.  It came out I believe as part of 8.0.60

**Comment by RsZoli** [comment]
@aritchie Well, thats a problem! :(

![image](https://github.com/shinyorg/shiny/assets/28480037/57e1651c-096e-4c39-ab2f-31b4e8a0299e)

**Comment by aritchie** [comment]
You can update the version of MAUI in your csproj

```xml
<PropertyGroup>
    <MauiVersion>8.0.60</MauiVersion>
</PropertyGroup>
```
