### ISSUE TITLE
Ble Get Name of characteristics

### ISSUE THREAD

**Issue by hudaIT** [shinyorg/shiny#148]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Would be amazing if we could read the name of a characteristic.

Below is an example of the https://github.com/xabre/xamarin-bluetooth-le Plugin, would be cool to have this functionality in the Shiny BLE plugin too

```
var device = await Plugin.BLE.CrossBluetoothLE.Current.Adapter.ConnectToKnownDeviceAsync(CurrentConnectedDevice.Uuid);
            var services = await device.GetServicesAsync();
            foreach (var item in services)
            {
                var chars = await item.GetCharacteristicsAsync();
                    foreach (var characteristic in chars)
                    {
                        if (characteristic?.CanRead == true)
                        {
                                //HERE THE IMPORTANT PART we check the name of the characteristic
                                if (characteristic?.Name.StartsWith("Serial Number") == true)
                                {
                                    var serialNr = await characteristic?.ReadAsync();
                                    if (serialNr?.Count() > 0)
                                    {
                                        SerialNumber = Encoding.Unicode.GetString(serialNr);
                                        var dictionary = new Dictionary<string, string>();
                                        dictionary.Add(" SerialNumber: ", SerialNumber);
                                        Microsoft.AppCenter.Analytics.Analytics.TrackEvent("SerialNumber: ", dictionary);
                                        return;
                                    }
                                }
                    }
                }
            }
```

The code above reads the name of the characteristic, if the name is Serial Number it is saved.
As far as i have seen we can only read the value and the description of the characteristics. However not the name.

## API Changes

ICharacteristic would get an additional Property:
`public string Name { get; set; }`

## Intended Use Case
Read the names of characteristics

**Comment by aritchie** [comment]
There is no such thing as a "name" on a characteristic.  There is only a description of the characteristic based on it's UUID.  Some UUID's are standardized and that is what I return on description

**Comment by hudaIT** [comment]
Is it possible that not all Description to the characteristics are red? Because like mentioned i can find a flag "Serial Number" in the plugin i mentioned above. However i am not able to find this flag with your plugin.

**Comment by aritchie** [comment]
Yes - the list changes all the time.  https://www.bluetooth.com/specifications/gatt/characteristics/

Feel free to send a PR https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Central/Dictionaries.cs

**Comment by hudaIT** [comment]
Oh, thank you very much did not know. I am a little bit to stupid to get it.
I want to add the characteristic "Serial Number String" with the Assigned Number "0x2A25", how do i get the Guid from the assigned number ? :')
