### ISSUE TITLE
Push: OnEntry / OnReceived not fired when running in background / or closed

### ISSUE THREAD

**Issue by mitedo** [shinyorg/shiny#1483]
### Summary

Hi,

I am new to Shiny.
I am using Push for notifictions.
When the app is running in foreground, and a notification is received, it comes to OnReceived of the PushDelegate.

If the app is running in background or closed, Neither OnReceived or OnEntry are being called.

I followed all the steps in the guidelines.

### API Changes

unknonw

### Intended Use Case

Push notofications

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This does not follow our guidelines for submitting issues
