### ISSUE TITLE
[Bug]: Push notification iOS simulator

### ISSUE THREAD

**Issue by IeuanWalker** [shinyorg/shiny#1498]
### Component/Nuget

Push - Native (Shiny.Push)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)

### Version(s) of Operation Systems

Hi, starting with xcode 14 iOS simulators now support push notifications - 
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes#Simulator:~:text=Simulator%20now%20supports,these%20tokens.%20(60974170)

Looking at the code it always returns 'NotSupported' if its a simulator - https://github.com/shinyorg/shiny/blob/1b4138d42835a71447cee7b4134c7b0ef25b2f21/src/Shiny.Push/Platforms/Apple/PushManager.cs#L95C9-L96C72

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

I have a 'Mac mini (M1)' running a 'iPhone 15 Pro 17.5' simulator and getting `NotSupported` result from `await push!.RequestAccess();`

### Expected Behavior

Behave like a normal device and let me setup notifications

### Actual Behavior

NotSupported

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
While the simulator may support it, .NET iOS doesn't always properly push through the entitlements for the simulator.  I don't want the support that comes with opening this up right now.
