### ISSUE TITLE
Crash in iOS when sending notification with a payload set.

### ISSUE THREAD

**Issue by kpespisa** [shinyorg/shiny#15]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [X] Notifications
 - [ ] Sensors

## Version of OS(s) listed above with issue
iOS 12.2

## Version of Library
1.0.0.193

## Expected Behavior
Payload can be set without crashing

## Actual Behavior
Sending a notification with a payload leads to a crash:

|ERROR: Objective-C exception thrown.  Name: NSUnknownKeyException Reason: [<__NSDictionary0 0x600001c380d0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key Payload.

**Comment by aritchie** [comment]
Fixed for next beta release - please provide a test case and the entire exception in the future.  Thanks for letting me know.
