### ISSUE TITLE
[Bug]: BLE Android peripheral renaming does not update peripheral advertisement name

### ISSUE THREAD

**Issue by matthiasleonhardt** [shinyorg/shiny#1503]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Android 14 - API 34

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1. Pair to BLE Device
2. Rename the Device (through the application)
3. disconnect the device
4. stop / restart scan
5. Device advertises still with the old name

### Expected Behavior

after renaming the device it should advertise with the new name.

### Actual Behavior

after renaming the device it still advertises with the old name. after restarting the application I can see the device with the changed name. Before upgrading to MAUI things worked as expected.

### Code Sample

As the app is customer specific and not public I am not able to provide a repo.

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
> I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
