### ISSUE TITLE
[Bug]: Click on notification poppup => 'This window is already associated with an active Activity (MauiShinyJobNotify.MainActivity). 

### ISSUE THREAD

**Issue by TersaCA** [shinyorg/shiny#1505]
### Component/Nuget

Notifications (Shiny.Notifications)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Andriod 14.0 api 34

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

- use vs2022 Shiny Maui App Template to create project with jobs and local notifcations
- make code changes given below
- run/debug app in andriod emulator
- click on "Job Complete" notification poppup

### Expected Behavior

clicking on app should open or focus app

### Actual Behavior

clicking causes exception

### Exception or Log output

System.InvalidOperationException: 'This window is already associated with an active Activity (MauiShinyJobNotify.MainActivity). Please override CreateWindow on MauiShinyJobNotify.App to add support for multiple activities https://aka.ms/maui-docs-create-window or set the LaunchMode to SingleTop on MauiShinyJobNotify.MainActivity.'

### Code Sample

- change MyLocalNotificationDelegate;

```
	public class MyLocalNotificationDelegate : INotificationDelegate
	{
		readonly INotificationManager notificationManager;


		public MyLocalNotificationDelegate(INotificationManager notificationManager)
		{
			this.notificationManager = notificationManager;
		}


		public async Task OnEntry(NotificationResponse response)
		{
			notificationManager.Send("Note Click", $"Poppup Clicked at {DateTime.Now}");
		}
	}
```

- change MyJob;

```
	public class MyJob : Job
	{
		readonly INotificationManager notificationManager;
		readonly ILogger<MyJob> logger;


		public MyJob(ILogger<MyJob> logger, INotificationManager notificationManager) : base(logger)
		{
			this.logger = logger;
			this.notificationManager = notificationManager;
			MinimumTime = TimeSpan.FromSeconds(60);
		}


		protected override Task Run(CancellationToken cancelToken)
		{
			notificationManager.Send("Job Event", $"Job Completed at {DateTime.Now}" );
			return Task.CompletedTask;
		}
	}
```

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Share the solution please.  People often tend to use old versions of the template or the library.

You can find the answer here on how this can be solved:
https://github.com/dotnet/maui/issues/18692#issuecomment-2016524388

**Comment by TersaCA** [comment]
I believe everything is update. 
VS2022  was update yesterday.
I uninstalled and reinstalled the shiny project template today and generated a new test project before posting the issue. 

[MauiShinyJobNotify.zip](https://github.com/user-attachments/files/16334640/MauiShinyJobNotify.zip)

**Comment by munkii** [comment]
@TersaCA 

I was about to comment that we are also seeing this issue. 

However I did some searching and came across others with a [similar issue and a reply from @aritchie](https://github.com/dotnet/maui/issues/18692#issuecomment-2016524388). Implementing his suggestion of setting an explicit LaunchActivityFlag worked for us,

**Comment by aritchie** [comment]
MAUI is talking about how they want to shift those flags around.  I defaulted the flags to SingleTop in dev, but I'm not ready to release that right now

Please stick with the workaround listed above.  You'll likely need to hard set this if MAUI shifts the flags in any case.
