### ISSUE TITLE
[Bug]: OnNewToken repeatadly called

### ISSUE THREAD

**Issue by IeuanWalker** [shinyorg/shiny#1508]
### Component/Nuget

Push - Native (Shiny.Push)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Android 14

Nuget version: 3.3.3

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

I just started to look at implementing the OnNewToken method in the `IPushDelegate`. But when I call `PushAccessState result = await _pushManager.RequestAccess();`, `OnNewToken` is then repeatedly called and hangs the app.

Here is a video showing the issue - 

https://github.com/user-attachments/assets/09dd003e-f34b-49ed-a9f9-695f4bf5fae5

### Expected Behavior

`OneNewToken` to be called once

### Actual Behavior

Its repeatedly called and I have to force close the app

### Code Sample

I will create repo if needed, hoping I'm just misunderstanding something.

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by IeuanWalker** [comment]
Might be my issue, so ignore for now _(sorry)_

**Comment by IeuanWalker** [comment]
Dont understand why it was happening but implemented a work around an its all working as expected now

**Comment by aritchie** [comment]
Always include a full sample or the issue is closed.  Please don't file anything as "hoping it is a misunderstanding".  

You shouldn't need a workaround.

**Comment by IeuanWalker** [comment]
@aritchie you are right, here is the repo - 

I've slimmed down our app as much as I can to repo the issue - 
[OnNewTokenRepo.zip](https://github.com/user-attachments/files/16362285/OnNewTokenRepo.zip)

Here is an updated video showing the same issue in the repo project - 

https://github.com/user-attachments/assets/6245d55c-fbe5-4140-aa86-86db7aa31b07

Think the issue is in `Features > PushNotifications > Handlers > HandleDeviceRegistration > RegisterOrUpdate()` I'm recalling `await _pushManager.RequestAccess()` that's causing a loop between OnNewToken and my code. 

But I did look into your code and see you have checks in place to only call `OnNewToken` when there is a change that you are tracking, so not sure why that's not taking effect - https://github.com/shinyorg/shiny/blob/1b4138d42835a71447cee7b4134c7b0ef25b2f21/src/Shiny.Push/Platforms/Android/PushManager.cs#L117C13-L117C72

The workaround I've done was to update the code in `OnNewToken` to fire the update on a background thread an ignore it _(not sure why this works, but this does stop OnNewToken being recalled)_ - 
```csharp
public Task OnNewToken(string token)
{
	try
	{
		_pushNotificationFeature.HandleDeviceRegistration.RegisterOrUpdate(token).SafeFireAndForget();
	}
	catch(Exception)
	{
		// intentionally left blank
	}

	return Task.CompletedTask;
}
```

**Comment by aritchie** [comment]
I need smaller samples in the future please.  I've got stuff to do too.  I'm happy to help, but I fix the library, not all the code around it.  In this case, you've identified your issue quite well.  You're calling RequestAccess downstream from the OnNewToken which is causing a loop.  This isn't something I would fix or implement a guard against.

**Comment by IeuanWalker** [comment]
@aritchie Thanks, no prob, will restructure the code.
