### ISSUE TITLE
[Bug]: Delegate's OnEntry method has null Notification Title and Message

### ISSUE THREAD

**Issue by batmanwannabe** [shinyorg/shiny#1518]
### Component/Nuget

Push - Native (Shiny.Push)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Windows, Tested with Shiny.Push latest stable and beta version

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1. Clone the test app [https://github.com/batmanwannabe/ShinyPushTest](https://github.com/batmanwannabe/ShinyPushTest)
2. Update the Android config in MauiProgram.cs
3. Run the app and trigger notification from Firebase
4. Click on the notificatio
5. OnEntry is triggered but it does not have the Notification Title and Message. But it has the Data Dictionary

### Expected Behavior

OnEntry should have the  Notification Title and Message

### Actual Behavior

OnEntry is triggered but it does not have the Notification Title and Message. But it has the Data Dictionary

### Code Sample

[https://github.com/batmanwannabe/ShinyPushTest](https://github.com/batmanwannabe/ShinyPushTest)

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
That data is not made available by the platform at that stage.

**Comment by batmanwannabe** [comment]
@aritchie thanks for commenting. Is there any way to get the notification title and message when app is in background?

**Comment by aritchie** [comment]
Not really.  If you want to manage things properly in the background, work with the data args
