### ISSUE TITLE
[Bug]: iOS Push Notification not working.

### ISSUE THREAD

**Issue by archergod** [shinyorg/shiny#1523]
### Component/Nuget

Push - Native (Shiny.Push)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [ ] Android (8+ supported)

### Version(s) of Operation Systems

iOS Anyversion.

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1. Use Shiny.Push for push notification in Maui App (Single Project).
2. Make it for Android and iOS. 
3. Send Push Notification from Firebase Console. 
4. Android will recieve the push notification, but iOS won't

### Expected Behavior

Push notification should be recieved. 

### Actual Behavior

No push notification is recieved. I am not sure if I miss something for iOS, but I have Entitlement.plist added for production, as well have certificates enable for it. I upgrade my app from Xamarin to Maui. previously I was using the other library that was not getting compiled now, due to large path. So I opt for Shiny.Push. It was working fine for me but stop working all of sudden from last 2 months. I make and recompile multiple times, but nothing make it works again. It always work on Android without issue though.

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by archergod** [comment]
I just want to add that I am not 100% sure if it is bug or It is something I miss in code. I have PushDelegate.cs file  and PushRegistration file both in code and I was able to capture the Token provided by Shiny on iOS and store it properly in DB without issue.

**Comment by aritchie** [comment]
Shiny.Push.Firebase needs a binding update to support push.  I haven't had time to do this.

**Comment by archergod** [comment]
I am not very good at it, but can you guide or share plan how you plan to do that. I can try my hand for binding.

**Comment by aritchie** [comment]
I have my own stuff to do.  You'll need to read docs if you're going to use firebase otherwise you have to wait until I update firebase myself which I have no timeline on since this is free time and I don't use firebase for anything beyond Android
