### ISSUE TITLE
[Bug]: Scan Button causes endless loop

### ISSUE THREAD

**Issue by mcourter** [shinyorg/shiny#1530]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

Pixel 4a Android 11

### Hosting Model

- [ ] MAUI
- [X] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1. Startup app in Visual Studio on Windows 11. 
2. Tap the Scan button. 
App stays in an endless loop until button is tapped again. It doesn't stop on any break points.

### Expected Behavior

It should find a printer then allow the user to print a hard coded text string.

### Actual Behavior

Goes into an endless scan loop looking for devices.

### Code Sample

The code can be found here:
https://www.xamboy.com/2020/04/20/bluetooth-printing-in-xamarin-forms-using-shiny/

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
I didn't write that article, so I have no idea.  This repo is for reporting actual bugs in Shiny.
