### ISSUE TITLE
[Bug]: .NET Maui 8 - Trying to add job in MauiProgram.cs fails to compile

### ISSUE THREAD

**Issue by fooberichu150** [shinyorg/shiny#1533]
### Component/Nuget

Jobs (Shiny.Jobs)

### What operating system(s) are effected?

- [X] iOS (13+ supported)
- [ ] Mac Catalyst
- [X] Android (8+ supported)

### Version(s) of Operation Systems

.NET Maui 8; attempting on Android 33, Android 34, iOS 16; using Shiny v3.3.3

Maui workload versions:
```
Installed Workload Id      Manifest Version       Installation Source
--------------------------------------------------------------------------------
android                    34.0.145/8.0.100       SDK 8.0.400, VS 17.11.35431.28
aspire                     8.2.2/8.0.100          SDK 8.0.400, VS 17.11.35431.28
ios                        18.0.8314/8.0.100      SDK 8.0.400, VS 17.11.35431.28
maccatalyst                18.0.8314/8.0.100      SDK 8.0.400, VS 17.11.35431.28
maui-windows               8.0.83/8.0.100         SDK 8.0.400, VS 17.11.35431.28
```

### Hosting Model

- [X] MAUI
- [ ] Native/Classic Xamarin
- [ ] Manual

### Steps To Reproduce

1. added nuget packages (Shiny, Shiny.Jobs)
2. registered everything in MauiProgram
3. Tried to add a job using build.Services.AddJob(typeof(MyJob))
4. Tried to compile

### Expected Behavior

App would compile

### Actual Behavior

Cannot compile 

I have tried adding `Shiny` in a GlobalUsings, adding at the top of my MauiProgram, etc. 

### Exception or Log output

error CS1061: 'IServiceCollection' does not contain a definition for 'AddJob' and no accessible extension method 'AddJob' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

### Code Sample

```
namespace MauiApp2
{
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
				.UseMauiApp<App>()
                .UseShiny()
                .ConfigureFonts(fonts =>
                    {
                        fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    });

            builder.Services.AddMauiBlazorWebView();

#if DEBUG
			builder.Services.AddBlazorWebViewDeveloperTools();
            builder.Logging.AddDebug();
#endif

            builder.Services.AddJob(typeof(MyJob));

            return builder.Build();
        }
    }
}
```

### Code of Conduct

- [X] I have supplied a reproducible sample that is NOT FROM THE SHINY SAMPLES!
- [X] I am a Sponsor OR I am using the LATEST stable/beta version from nuget (v3.0 stable - ALPHAS are not taking issues - Sponsors can still send v2 issues)
- [X] I am Sponsor OR My GitHub account is 30+ days old
- [X] I understand that if I am checking these boxes and I am not actually following what they are saying, I will be removed from this repository!

**Comment by aritchie** [comment]
Please supply a reproducible sample as per the issue template if you want help with this

**Comment by fooberichu150** [comment]
> Please supply a reproducible sample as per the issue template if you want help with this

https://github.com/[fooberichu150/shiny-breaky](https://github.com/fooberichu150/shiny-breaky)

Specifically the MauiApp2 project in the solution. 

![image](https://github.com/user-attachments/assets/35f803e1-4c58-4a79-aeec-c2658f260a19)

![image](https://github.com/user-attachments/assets/b4ed84f1-5483-4e2f-80d9-cf317e529261)

**Comment by aritchie** [comment]
Your link doesn't work, but your intellisense is telling you exactly what isn't compiling.  Shiny doesn't support Windows

**Comment by fooberichu150** [comment]
> Your link doesn't work, but your intellisense is telling you exactly what isn't compiling. Shiny doesn't support Windows

Oh good hell, sometimes I hate MS Edge. https://github.com/fooberichu150/shiny-breaky 

Also... yeah, I know it doesn't work on Windows. So... why does it still not work when I have Android selected? Which I do. And which I did. And which I said in the original report that I tried on Android and iOS?

![image](https://github.com/user-attachments/assets/094a65a3-f251-4a96-b871-e6d3029aeb63)

**Comment by aritchie** [comment]
> Also... yeah, I know it doesn't work on Windows. So... why does it still not work when I have Android selected? Which I do. And which I did. And which I said in the original report that I tried on Android and iOS?

Because the tooling still compiles for all TFMs.

**Comment by fooberichu150** [comment]
> > Also... yeah, I know it doesn't work on Windows. So... why does it still not work when I have Android selected? Which I do. And which I did. And which I said in the original report that I tried on Android and iOS?
> 
> Because the tooling still compiles for all TFMs.

Ok. Recommend a little additional documentation to specify that.

But thanks.

**Comment by aritchie** [comment]
> Ok. Recommend a little additional documentation to specify that.

This is free code.  You're welcome to contribute to the docs.  I already state the platforms I support and this was tooling which has nothing to do with me

**Comment by fooberichu150** [comment]
For anyone else newer to .NET Maui and not a complete fucking genius that knows everything, just wrap it in a preprocessor directive:

```
#if IOS || ANDROID
            builder.Services.AddJob(typeof(CheckStatusJob));
#endif
```

**Comment by aritchie** [comment]
WTAF is your problem?  I helped you with your issue.  You're using free code and all you do is make an asshole reply like this?
