### ISSUE TITLE
[Feature Request]: Allow long-press actions on a Shiny notification to bring up one or more Notification actions that can be taken by a user

### ISSUE THREAD

**Issue by edgiardina** [shinyorg/shiny#1537]
### Summary

I would like Local Notifications to be actionable using device platform buttons. This is implemented in LocalNotifcations Plugin, but I'm already using Shiny notifications so it would be nice to pass a Notification action collection to existing Shiny Notification code.

https://github.com/thudugala/Plugin.LocalNotification/wiki/5.-Notification-with-Action

### API Changes

`Shiny.Notifications.Notification` should include a new Property, which takes an IList<NotificationAction>

The `NotificationAction` should contain a Title, and a delegate property where I can pass the code / action

### Intended Use Case

In my app, I use notifications to inform users when a new event is coming up based on their search criteria. We poll this in using a Shiny notification. When a new event comes up, it would be nice if a user could long press the notification and take one of several actions to add the event to their system calendar. I can do that if there's a delegate I can pass. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This already exists.  The sample contains an end-to-end example of how to accomplish this with channels.

Please don't quote other project features.  It isn't a competition.

**Comment by edgiardina** [comment]
> Please don't quote other project features. It isn't a competition.

It was never my intention to compare. Rather, I just wanted to ask for it, because I already use multiple shiny features in my existing Application. If the answer is no, that's ok, I also run OSS projects and know they are a labor of love and there isn't enough bandwidth to do everything.

I apologize for not knowing about the sample that does that. I will look into it. 

Thanks!
