### ISSUE TITLE
Error : Project build error

### ISSUE THREAD

**Issue by Sattasundar** [shinyorg/shiny#154]
After adding the package , getting build error;

**Severity Code Description Project File Line Suppression State
Error Can not resolve reference: System.Threading.Tasks.Extensions, referenced by System.Reactive. Please add a NuGet package or assembly reference for System.Threading.Tasks.Extensions, or remove the reference to System.Reactive.**

**Comment by Sattasundar** [comment]
Please see the above error details.

**Comment by Sattasundar** [comment]
every time the bot close the issue 
?????????????????? @aritchie

**Comment by aritchie** [comment]
1. Quit pinging me - this isn’t a support site
2. Follow the issue template that specifically says what you need to do.
3. Your issue is quite well labelled.  It isn’t a packaging error.  You can find the answer in the RX repo.  Using a newer VS is the answer
