### ISSUE TITLE
Linker Issues

### ISSUE THREAD

**Issue by jamesmontemagno** [shinyorg/shiny#160]
In hanselman.forms I am trying to turn Link All on.

Getting: System.InvalidOperationException: 'A suitable constructor for type 'Shiny.Jobs.JobManager' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.'

Had to add Shiny.Core to the list to skip in linking. Could probably throw a preserve on there to make sure it works properly. 

Additionally, I had to add a  `[Preserve(AllMembers = true)]` to my IJob implementation

**Comment by aritchie** [comment]
It will go beyond that.  Will look into it though.  Thanks
