### ISSUE TITLE
Registering INotificationManager for DI

### ISSUE THREAD

**Issue by munkii** [shinyorg/shiny#161]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.484-beta
## Version of OS(s) listed above with issue
Android 9.0
iOS 13

## Steps to Reproduce
1. Existing XF 4.0.0 project
2. Using FreshMVVM and TinyIOC
3. Created ShinyStartup class
4. Calling `services.UseNotifications<NotificationDelegate>()`
5. Calling `Shiny.AndroidShinyHost.Init(this, new MyApp.Forms.ShinyStartup());` from existing `MainApplication.OnCreate`
6. In a ViewModel I am (perhaps naively) adding INotificationManager to the ctor
## Expected Behavior
I'd want to get it injected into the ViewModel but TinyIOC cannot see it and that is not surprising as I am unable to Register it.
I can see that NotificationModule will Register itself in the Shiny library however how should I access that INotificationManager in my ViewModels?

## Actual Behavior
FreshTinyIoC.TinyIoCResolutionException:** 'Resolve failed: SettingsViewModel - Reason: Resolve failed: INotificationManager

**Comment by aritchie** [comment]
You have 3 options
1) Copy the registrations over from Shiny into your DI container however that is accomplished.  The sample repo demonstrates this

2) Forward calls from your container to the ShinyHost   di.Register<INotificationManager>(() => ShinyHost.Resolve<INotificationManager>());

3) Or use statics CrossNotifications or ShinyHost.Resolve<INotificationManager>();

PLEASE NOTE - Github is intended for issues NOT support requests.

**Comment by munkii** [comment]
Apologies, I wasn't meaning to abuse the bug reporting channel. I honestly thought it could be an issue. There's definitely an issue with the clarity of documentation but I thought it was unfair to report those as it's all still in beta. FWIW for now I have gone with ShinyHost.Resolve().
