### ISSUE TITLE
ConnectionConfig for ConnectIf

### ISSUE THREAD

**Issue by hudaIT** [shinyorg/shiny#162]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Would be cool to make it possible to set ConnectionConfig parameters for the ConnectIf method to. Like it is for Connect and ConnectWait.

## API Changes
ConnectIf(**ConnectionConfig connectionConfig**)

## Intended Use Case
To Stop AutoConnect when connected via ConnectIf.

**Comment by aritchie** [comment]
Why not send a PR for easy additions like this?

**Comment by hudaIT** [comment]
Done #163 :)
