### ISSUE TITLE
Android 10: registering geofence region throws an exception

### ISSUE THREAD

**Issue by tossingc** [shinyorg/shiny#167]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.484-beta

## Version of OS(s) listed above with issue
Android 10 (Pixel 3 XL)

## Steps to Reproduce
1. Check out latest dev branch of this repository
2. Check out latest master branch of shinysamples repository
3. Run Samples-Android-Debug
4. Try to register a new Geofence region

## Expected Behavior
Geofence region successfully registered

## Actual Behavior
Exception thrown

**Comment by tossingc** [comment]
I did try updating the target framework to API 29 and adding the new android.permission.ACCESS_BACKGROUND_LOCATION permission and then updating the code to request that permission if on API level 29 or above:
https://developer.android.com/training/location/receive-location-updates#request-background-location

Still received the exception (GEOFENCE_NOT_AVAILABLE status code 1000)
https://developers.google.com/android/reference/com/google/android/gms/location/GeofenceStatusCodes.html#GEOFENCE_NOT_AVAILABLE

**Comment by tossingc** [comment]
Interesting, I just performed the following, and it appears to have started working:
1. toggle **Google Location Accuracy** off and then back on
2. toggle the top-level **Use location** setting off and then back on

Need to pick this back up in the morning, but it appears to be working after following those steps. 🤷‍♂️

**Comment by aritchie** [comment]
This is usually is something to do with the setup of the device or you haven't requested permission to use the service through RequestAccess.
