### ISSUE TITLE
Container has not been setup - have you initialized the Platform provider?

### ISSUE THREAD

**Issue by jitendrajadav** [shinyorg/shiny#176]
I am getting error `Container has not been setup - have you initialized the Platform provider?`

More detail:
```
  at Shiny.ShinyHost.get_Container () [0x00007] in d:\a\1\s\src\Shiny.Core\ShinyHost.cs:71 
  at Shiny.ShinyHost.Resolve[T] () [0x00000] in d:\a\1\s\src\Shiny.Core\ShinyHost.cs:28 
  at Shiny.AndroidShinyHost.OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x00000] in d:\a\1\s\src\Shiny.Core\Platforms\Android\AndroidShinyHost.cs:45 
  at KegID.Droid.MainActivity.OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x0000a] in <e44df11464e843d78cd73b12b3865c3a>:0 
  at Android.App.Activity.n_OnRequestPermissionsResult_IarrayLjava_lang_String_arrayI (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 requestCode, System.IntPtr native_permissions, System.IntPtr native_grantResults) [0x00038] in <82e50ec67af648c3b9f43b3d70e21b96>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.19(intptr,intptr,int,intptr,intptr)
```

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [x] .NET Standard

## Feature Library

 - [x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library

Core 1.0.0.531-beta
Locations 1.0.0.531-beta

## IDE information
Microsoft Visual Studio Professional 2019
Version 16.4.2
VisualStudio.16.Release/16.4.2+29613.14
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA694
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.4.457.38025
ASP.NET and Web Tools 2019

Xamarin   16.4.000.307 (d16-4@e031886)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.464 (remotes/origin/d16-4@4abf337c3)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.1.0 (d16-4/f2c9364)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: bef1e63
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.8.3.0 (0d8fe21)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

## Version of OS(s) listed above with issue
Android 10 (Q)
Windows 10

## Steps to Reproduce
1. Created Xamarin forms application, Installed Shiny.Core and Shiny.Locations from Nuget manager
2. Run android application, in App.xaml.cs => onstart() I have a depenedcy Service
 `                   var permission = await DependencyService.Get<IPermission>().VerifyStoragePermissions();`
3. getting exception above line 

## Expected Behavior
It should not throw exception run as expected

## Actual Behavior
Getting error
`System.ArgumentException: 'Container has not been setup - have you initialized the Platform provider?`

Note : I am using Prism MVVM Pattern 

![image](https://user-images.githubusercontent.com/1029026/71411240-923dc080-266e-11ea-95e2-ba40fe348d39.png)

**Comment by aritchie** [comment]
1) There is no IPermission in Shiny
2) You haven't even attempted to provide nearly enough detail, but that error means you haven't followed the setup instructions.

**Comment by jitendrajadav** [comment]
Hi @aritchie I am not sure why you close this issue I have given all the information what I have it and "IPermission" it is my custom code where I am getting permission even it is not about getting permission from "IPermission" only but even it is given error not sure how would I fixed it?

I have implemented all the stuff what is documented and even downloaded sample as well and cross checked with it so I am completely block now

**Comment by aritchie** [comment]
I've closed it because this isn't tech support.  You would only get that error because you are missing the bootstrap setup.  If you still feel you've done everything right in your cross checking, then supply an actual SMALL reproducible test case.  Please don't file anything else here until you can provide those details.

**Comment by jitendrajadav** [comment]
Thank you @aritchie for you quick reply problem was
 `#if DEBUG
[assembly: Application(Debuggable = true)]
#else
[assembly: Application(Debuggable = false)]
#endif`
I have written in AssemblyInfo it was required in "MainApplication"
now this problem is solved but unfortunately Shiny.Locations `OnReadingReceived` is not firing I am just attaching demo app please check

Note : some nuget packages is creating issue my observation

[ShinyPrismSample-master.zip](https://github.com/shinyorg/shiny/files/3998538/ShinyPrismSample-master.zip)

**Comment by aritchie** [comment]
Have you asked your user for location permissions?  

As I said earlier, this is not tech support!!!  I'm not looking through your code piece by piece as you learn to use things.  You have to find a bug or crash - then present a case with something other than "this doesn't work".
