### ISSUE TITLE
Setting ManufacturerData to a byte array from string appears to disable server

### ISSUE THREAD

**Issue by logikonline** [shinyorg/shiny#177]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [X] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.531-beta

## Version of OS(s) listed above with issue
8.1 & 9.0

## Steps to Reproduce
To reproduce this, I adjusted the sample project for ease of use.  Make the following changes in the following files.

1. GattServerViewModel.cs
Change the following to pass a string array:

            byte[] abit = System.Text.Encoding.UTF8.GetBytes("--Test--");
            await this.peripheralManager.StartAdvertising(new AdvertisementData
            {
                LocalName = LocalName,
                ManufacturerData = new Shiny.BluetoothLE.ManufacturerData(ushort.Parse("242"), abit)
            });

2. PeripheralItemViewModel.cs
Under the Update function:

                //this.LocalName = ad.LocalName; <-- comment here
                this.TxPower = ad.TxPower;
                if (ad.ManufacturerData != null)
                {
                    this.LocalName = ad.ManufacturerData.CompanyId.ToString() + ": " + System.Text.Encoding.UTF8.GetString(ad.ManufacturerData.Data);
                }

## Expected Behavior
In the previous library, BLE - I was able to pass a string array as long as it was beneath the 26 bytes reserved.  I should be able to read that array

## Actual Behavior
If I pass a string array, the server doesn't appear to start.  If I remove the array, the server will appear.  

Allan, I had implemented the library before contacting you via email - this is why I thought the server was not working.  Thank you for your excellent work on this project, it is much appreciated. 

regards,
Dave

**Comment by aritchie** [comment]
Have you tried disabling the device name and seeing if the manufacturer data can go? 
Is there any error in the console?
Have you checked online to see if there is anything weird with certain devices?

**Comment by logikonline** [comment]
I tried 3 different Android devices, the same ones that work on the old library but I need the IsConnectable that isn't supported on the old Android version.  I am not sure how many different combinations I can try.  If you suggest a few - I will try.

How do I disable the device name?

**Comment by logikonline** [comment]
Can you tell me how to disable the device name?  I do not see how to do this on either the adapter or the server objects.  I provided the steps above on how to reproduce this - could you give me some code back to resolve this?

**Comment by aritchie** [comment]
No offense, this isn't tech support and I don't owe you anything.  I don't know how to resolve your issue because I don't know what it is.  The source code is all open for you to debug yourself.  This is the line you are looking for:   

https://github.com/shinyorg/shiny/blob/f124695ebbda81d1f8462c88ab835d72400dbed4/src/Shiny.BluetoothLE/Peripherals/Platforms/Android/PeripheralManager.cs#L76

**Comment by logikonline** [comment]
I am not trying to ask for tech support, I was reporting a bug which your suggestion above fixed.  I altered the StartAdvertising to allow the bool to disable it.  I just didn't know your library well enough to find that reference.

I appreciate the response.  Have a good day.
