### ISSUE TITLE
Failed in Ble Characteristics.Notify()  after upgrading to 1.0.0.531

### ISSUE THREAD

**Issue by pehlivan38** [shinyorg/shiny#178]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [X] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [X] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ]
HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.531
## Version of OS(s) listed above with issue
Windows10, Android 8.1

## Steps to Reproduce
1. 
2.
3.

## Expected Behavior
First of all thanks for that great work - I'm recently developing a project with Shiny framework.
I had a working code with 1.0.0.484 release. After upgrading to 1.0.0.531 - I need to replace RegisterAndNotify invocation of IGattCharacteristics with Notify() - which is fine - as the latest commits(dated 16 Dec) entitled 'Simplifying BLE' suggests. I have not updated anything else.  but no more reading data from a GattCharacteristics. I subscribed it the same way I did before (similar to ShinySamples) - but do not receive anything.

It is now very hard for me to present any meaningful bug report for why this happens. Everything else is same - just upgraded the package. Is it possible that I missed a related behavioral change that I did not adjust my code or is it some general issue? 

I'm sorry for not being more specific.  
In case it is relevant I can only note the following: after upgrading the built failt in UWP project (not in Android though) because of an AppManifest error due to UWP Background task entry point validation error. I added ActivatableClassId="Shiny.Support.Uwp.ShinyBackgroundTask" for InProcessServer to .appxmanifest file to fix build error. 

## Actual Behavior
I have adjusted the method name only - and expect to see the same behavior. But no more Characteristics reading.

**Comment by hudaIT** [comment]
Same issue for me.

**Comment by aritchie** [comment]
@pehlivan38 There are breaking changes and bugs.  It will happen.  Please add code to show what you are doing.  

@hudaIT "me too"'s are not helpful.  They only add noise - no more in the future please.

**Comment by pehlivan38** [comment]
@aritchie  To make sure I do not waste your time I tried several things, checked for package dependencies but not able to succeed. So here is what I can do to help you in identifying bug:

I will share a simple project that I created back in September to see what I can do with ShinyBle, This is basically your ShinySamples with only BleCentral but with very limited dependency on any other libraries/frameworks. I made it public on Github and made it testable for the bug. (https://github.com/pehlivan38/BlePrototypeBasedOnShiny) 

The project is a very simple&stupid one, just to reproduce bug and served me to understand how Shiny works. It does not even read/write - but just registers a GattCharacteristics with Notify. It works on UWP and Android (never tried for IOS)

**Steps to reproduce bug:** 

1. The project depends on Version 1.0.0.484-beta. And it works perfectly. You may want to double-check. Scan, Connect and then click on a service with Read/Notify capability. Then notify from a peripheral - you will see the first byte as value. I was using a peripheral simulator for battery status - so i was happy with single byte value display. (on your first run, you may need to Stop Scan after your first click on Start - and then Re-Scan again - there is a flaw in UI update which I ignored) The code is a very stupid one - selecting any other service also calls for ToggleNotify method - I'm not sure with the response though. 

2. Just upgrade the package to Version 1.0.0.531. You will get a compiler error in GattCharacteristicViewModel line 69. replace RegisterAndNotify with Notify since this is required by the latest version. 

3. After running the project. Scan/Connect works as it is supposed to - but when you click on a service with Read/Notify capability. It does not enable the notifications on the peripheral (at least on both my simulator and a real device that I'm working on) hence it does not read anything.  

I hope it helps...

**Comment by aritchie** [comment]
Notify does seem to be working fine on Android.  UWP is currently not ready for testing at this time.  Since the sample is essentially a copy of my test code, it doesn't really qualify for a reproducible test case.
