### ISSUE TITLE
GitHub Sponsor Patreon link not working

### ISSUE THREAD

**Issue by GuidoNeele** [shinyorg/shiny#18]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Actual Behavior
GitHub Sponsor Patreon link not working

**Comment by aritchie** [comment]
Thanks for letting me know
