### ISSUE TITLE
Shiny.Sensors causes iOS app to fail with "HealthKit" errors  when only Proximity sensor is used

### ISSUE THREAD

**Issue by kwacks** [shinyorg/shiny#181]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [X] Sensors

## Version of Library
1.0.0.531-beta
## Version of OS(s) listed above with issue
13.2

## Steps to Reproduce
1. Create a Xamarin forms iOS app
2. Initialize only the proximity sensor and listen for events
3. Build it and extract your package  (ipa file) using "unzip [yourpackage.ipa]"
4. In terminal run "otool -L payload/[yourpackage]/[yourapp]

## Expected Behavior
There shouldn't be any references to HealthKit

## Actual Behavior
There is a reference to HealthKit even though it's not used by the app.  It should get linked out since it's not being used. 

Additional information: 
Per the instructions in the common project the Startup file contains
public class MyShinyStartup: ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services) 
        {
                                  services.UseProximitySensor(); 
        }
    }

in Appdelegate
      iOSShinyHost.Init(new MyShinyStartup());

Build settings are set to:
Linker behavior: Link Framework SDKs only
additional mtough arguments : 
tried --linkskip=HealthKit, and --linksdkonly

Note that this problem doesn't occur with the old Plugin.Sensors which I've had to revert to in the meantime. 
Is there a known workaround for this or am I missing something?

**Comment by aritchie** [comment]
This isn't a bug with the library.  I have added a heart rate sensor so HealthKit is brought in as part of that.  If you "link all", it should remove it.  The heart rate sensor isn't available in the old plugin which is why it doesn't require the extra reference.
