### ISSUE TITLE
Beacons dont appear to be working in Xamarin Forms 4.4

### ISSUE THREAD

**Issue by cas8180** [shinyorg/shiny#184]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ x] Core
 - [ ] BluetoothLE
 - [x ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Steps to Reproduce
1. Follow the tutorial from here https://allancritchie.net/posts/shiny-beacons
2. Refactor code to use .WhenBeaconRanged, Also add a DisplayAlert in the subscribe method for UI feedback
3. Create a GUID to be scanned for
3. Download Beacon Simulator for android
4. Try both AltBeacon and iBeacon. Use the GUID from step 3, turn broadcast on
5. Run the app in Android on physical device, in my case pixel 2016 running anroid 10. Ensure bluetooth is enabled

## Expected Behavior
DisplayAlert triggered with UUID

## Actual Behavior
Nothing happens. As a side note I would expect a permissions dialog to pop. But it never does either I am wondering if this could be part of the problem?

**Comment by aritchie** [comment]
Please note that this is a beta project.  This isn't intended to be a support form.  You need to include some form of code. 

Have you wired in all of the permissions checks for the bootstrap?
Have you called RequestAccess?
In your subscribe, are you marshalling back to the main thread?

**Comment by cas8180** [comment]
Thanks for your feedback. I do realize this is beta. However, this project has been in beta for quite some time now. Further, you have several tutorials out there as well as Xamarin Show demonstrations of usage of this library. So I think one could safely assume that this is a form or promotions to use and adopt this toolkit/library. With that being said, I think it is important to maintain working, relevent, updated documentation so that your fellow developers that wish to utilize your hard work can do so in an effective manner. With that being said I have attached the source code you have requested. I do appreciate your feedback whether this is the proper channel/forum not. Kind regards.

[Archive.zip](https://github.com/shinyorg/shiny/files/4020373/Archive.zip)

**Comment by aritchie** [comment]
If you want up-to-date docs, contribute - otherwise they come as I get around to them. 

You have to request permissions using RequestPermissions

**Comment by cas8180** [comment]
@aritchie you are a fucking dick.

**Comment by aritchie** [comment]
Seriously????  I offered you suggestions, looked at your code, and gave you a fix.  You complain about docs on a project that I give away for free and then you call me a fucking dick?  WOW
