### ISSUE TITLE
App will not link against shiny in Android release config.

### ISSUE THREAD

**Issue by pellet** [shinyorg/shiny#190]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Steps to Reproduce
* Use version of library since nullable reference types were added (before 1.0.0.484-beta).

## Expected Behavior
* App will link ok to shiny.

## Actual Behavior
* Android app does not link (it gets caught in a linking loop and never finishes).

This is not an issue with shiny itself but rather a xamarin.android issue, I'm just leaving a note here in case other people run into this issue.  I'm using an older version of shiny(1.0.0.484-beta) until it is fixed.
Here is a link to the issue: https://github.com/xamarin/xamarin-android/issues/3852

**Comment by wagenheimer** [comment]
I can't use newer versions with Xamarin Android. My app fails to initialize. It seems to be related to this bug!
Using (1.0.0.484-beta) everything still works. Is there a fix coming?

**Comment by aritchie** [comment]
@wagenheimer That error has absolutely nothing to do with this issue.  If you are having an issue, please open an issue with a proper test case  and  I'll look into it.

**Comment by JeremyBP** [comment]
Seems to work for me now VS 16.5 has been released

**Comment by DevEddy** [comment]
I can confirm, that it works now!

-- Eddy

**Comment by aritchie** [comment]
Thanks for confirming the fix everyone
