### ISSUE TITLE
WhenDisconnected or WhenStatusChanged do not get triggered with CancelConnection

### ISSUE THREAD

**Issue by hudaIT** [shinyorg/shiny#195]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

The new Ble Plugin does not trigger WhenDisconnected or WhenStatusChanged when you Disconnect your Device with Device.CancelConnection();

Code sample:

```
this.CurrentConnectedDevice.Connect(new ConnectionConfig { AutoConnect = false, AndroidConnectionPriority = ConnectionPriority.High });

this.CurrentConnectedDevice.WhenDisconnected().Subscribe(x =>
            {
                //Do something
            });
this.CurrentConnectedDevice.WhenStatusChanged().Subscribe(stat =>
            {
                //Do something
            });

this.CurrentConnectedDevice.CancelConnection();

```
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ X] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.560-beta

## Version of OS(s) listed above with issue
Android 8.1

## Steps to Reproduce
1. Do **Device.CancelConnection()**
2. Set a breakpoint in **Device.WhenDisconnected().Subscribe(x=>{})** or **Device..WhenStatusChanged().Subscribe(x =>{])**
3. Try to get to the breakpoint

## Expected Behavior
Should get into WhenDisconnected or WhenStatusChanged

## Actual Behavior
Does not get into WhenDisconnected or WhenStatusChanged

**Comment by aritchie** [comment]
Fixed in next release

**Comment by hudaIT** [comment]
@aritchie Thank you!
