### ISSUE TITLE
Notifications - Android App fails to initiate with error "missing setRequiresBatteryNotLow"

### ISSUE THREAD

**Issue by wagenheimer** [shinyorg/shiny#197]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [X] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.531-beta

## Version of OS(s) listed above with issue
Xamarin Forms 4.4.0.1203-nightly

## Steps to Reproduce
Android Application fails to initiate with the error :
"Java.Lang.NoSuchMethodError: 'no non-static method "Landroid/app/job/JobInfo$Builder;.setRequiresBatteryNotLow(Z)Landroid/app/job/JobInfo$Builder;"'"

## Expected Behavior
The application should initiate.

## Actual Behavior
The App closes after the error message.

**Comment by aritchie** [comment]
This was fixed in the latest release

Please make sure when you are filing in the future to include some sort of code example and the actual OS version (not the Xamarin Forms version - this library has nothing to do with Xamarin forms)
