### ISSUE TITLE
Local Notification not working on iOS

### ISSUE THREAD

**Issue by wagenheimer** [shinyorg/shiny#198]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.565-beta

## Version of OS(s) listed above with issue
iOS 13.3

## Steps to Reproduce
1. Please open the attached example and Compile and Run on an iOS device (or simulator)
[ShinyNotificationTest.zip](https://github.com/shinyorg/shiny/files/4066810/ShinyNotificationTest.zip)

2. Click on "Send Notification" button

## Expected Behavior
An Notification is shown on the device after clicking "Send Notification".

## Actual Behavior
No notification or error message are shown!

**Comment by aritchie** [comment]
There was a bug with notifications when a delegate wasn't configured.  This has been fixed in the latest release
