### ISSUE TITLE
CrossSettings Ambiguous Reference

### ISSUE THREAD

**Issue by dahlbyk** [shinyorg/shiny#201]
## Summary

I keep running into **'CrossSettings' is an ambiguous reference between 'Plugin.Settings.CrossSettings' and 'Shiny.CrossSettings'** on a project that's using [SettingsPlugin](https://jamesmontemagno.github.io/SettingsPlugin/). Easy enough to `using` away the error, but I'm curious what the intent of the shim is. It's not working as a drop-in replacement, so I'd like to either fix it or propose it be removed.

https://github.com/shinyorg/shiny/blob/f39ea7ff5eff524a73cb9bb3667624e7f89aa276/src/Shiny.Core/CompatShims.cs#L70-L89

## API Changes

`Plugin.Settings.CrossSettings` code should work as-is, e.g. the starter sample:

```csharp
private static ISettings AppSettings =>
    CrossSettings.Current;

public static string UserName
{
  get => AppSettings.GetValueOrDefault(nameof(UserName), string.Empty); 
  set => AppSettings.AddOrUpdateValue(nameof(UserName), value); 
}
```

## Intended Use Case

Simpler migration!

**Comment by aritchie** [comment]
Agreed - will look into this.  It would be across the board.  I'll probably move all of these statics named Cross to Shiny (ie. CrossSettings = ShinySettings).  

Of course, you could just move to shiny settings ;)

**Comment by dahlbyk** [comment]
> I'll probably move all of these statics named Cross to Shiny (ie. CrossSettings = ShinySettings).

👍 

> Of course, you could just move to shiny settings ;)

That was the idea. When I saw the shim I hoped I could just drop the other package and update some `using`s. That didn't work, thus this issue.

If that's the goal, I can take a crack at building an actual [`Plugin.Settings.ISettings`](https://github.com/jamesmontemagno/SettingsPlugin/blob/master/src/Plugin.Settings/ISettings.shared.cs) shim to return from `Shiny.Settings.CrossSettings.Current`.

**Comment by aritchie** [comment]
Done in dev

**Comment by dahlbyk** [comment]
Missed a Cross:
https://github.com/shinyorg/shiny/blob/dd97fa03a9e570ee833d821edc7fe0ce71f77be4/src/Shiny.Net.Http/ShinyHttpTransfers.cs#L9
Wrong name:
https://github.com/shinyorg/shiny/blob/dd97fa03a9e570ee833d821edc7fe0ce71f77be4/src/Shiny.Nfc/ShinyNfc.cs#L7
