### ISSUE TITLE
PairingRequest crash  Need BLUETOOTH PRIVILEGED permission

### ISSUE THREAD

**Issue by elisabeth-mitton** [shinyorg/shiny#202]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [x] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.184

## Version of OS(s) listed above with issue
Tested on Android API 24

## Steps to Reproduce
1. `await peripheral.PairingRequest("1234");`
2. In Manifest
`	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
	<uses-permission android:name="android.permission.BLUETOOTH" />
	<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
	<uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" />`
3.

## Expected Behavior
Success pairing no crash, no system popup

## Actual Behavior
crash
`[mono] java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 11665 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
[mono] 	at android.os.Parcel.readException(Parcel.java:1665)
[mono] 	at android.os.Parcel.readException(Parcel.java:1618)
[mono] 	at android.bluetooth.IBluetooth$Stub$Proxy.setPairingConfirmation(IBluetooth.java:1641)
[mono] 	at android.bluetooth.BluetoothDevice.setPairingConfirmation(BluetoothDevice.java:1185)
[mono] 	at crc643387a08acbe69b14.ObservableBroadcastReceiver.n_onReceive(Native Method)
[mono] 	at crc643387a08acbe69b14.ObservableBroadcastReceiver.onReceive(ObservableBroadcastReceiver.java:29)
[mono] 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1218)
[mono] 	at android.os.Handler.handleCallback(Handler.java:761)
[mono] 	at android.os.Handler.dispatchMessage(Handler.java:98)
[mono] 	at android.os.Looper.loop(Looper.java:156)
[mono] 	at android.app.ActivityThread.main(ActivityThread.java:6523)
[mono] 	at java.lang.reflect.Method.invoke(Native Method)
[mono] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
[mono] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

And sytem popup opens asking pin just before crashing. 
Is there a way not to display that popup because I don't need it.

Thx!

**Comment by aritchie** [comment]
Please note that this is not a support hub.  Bugs and feature requests only please.

You can and should be trapping all calls in the Subscribe overload OR try/await/catch.  If you look at the underlying source code in android, I only attempt to hack the PIN in directly.  Android can just ignore it and provide the default dialog as it does.  As it is, this doesn't work with most modern flavours of Android and is slated to be removed.
