### ISSUE TITLE
CrossSettings no longer available after update Shiny Core to version 1.0.0.572 beta

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [shinyorg/shiny#204]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] iOS
 - [ x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ x] .NET Standard

## Feature Library

 - [ x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.572
## Version of OS(s) listed above with issue
All

## Steps to Reproduce
1. Update Shiny Core to v1.0.0.572
2. CrossSettings no longer available

## Expected Behavior
How to use CrossSettings in the new version.

## Actual Behavior
CrossSettings no longer available after update Shiny Core to version 1.0.0.572 beta

**Comment by aritchie** [comment]
This is not a bug.  This is an undocumented feature and a beta.  Look through the source code before posting things like this please.  The statics have all been renamed.  This one is ShinySettings now

**Comment by xamarindevelopervietnam** [comment]
Thanks @aritchie , pls document breaking changes.

**Comment by aritchie** [comment]
not during the beta - you are welcome to contribute!!

**Comment by xamarindevelopervietnam** [comment]
thanks, i will give a hand if i can. thanks for great work!
