### ISSUE TITLE
Andriod - Speech Recogition fails to return last terms in phrase

### ISSUE THREAD

**Issue by Todd442** [shinyorg/shiny#205]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [X] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
SpeechRecoginition 1.0.0.573-beta
## Version of OS(s) listed above with issue
Android 9 API 28

## Steps to Reproduce
1. Compile and deploy sample
2. Select Speech
3. Select Continuous Speech (either mode as the same problems
4. Say "Once upon a time" 
5. It will only resolve "Once upon"

## Expected Behavior
Should have resolved all words.

NOTE: Tested this against the built in speech transcription and it works HOWEVER Android does take a moment to resolve the last terms in a phrase. Wondering if perhaps the component is returning too quickly.

## Actual Behavior
Chops off last part of the utterance

**Comment by aritchie** [comment]
The sample is not up for defects here.
