### ISSUE TITLE
Consistent behavior regarding notification sounds across supported platforms 

### ISSUE THREAD

**Issue by cpraehaus** [shinyorg/shiny#210]
This request targets Shiny.Notifications.

## Summary
I would like to have consistent behavior regarding notification sounds across supported platforms in order to use the system default notification sound.

Current situation if no custom sound is specified:
* Android: 
  * Default system sound if priority (Android-specific) is high enough
* iOS:
  * No sound
* UWP:
  * Default system sound

There is currently no way to tell Shiny.Notifications to use system default sound.

## API Changes
There are different approaches to solve this in Shiny.Notifications::
1. API change similar to what I have proposed some time ago in #114
   * This would allow to specify sound type per Notification (not static/globally). Possible values:
     * Default: do not configure sound explicitly and leave it up to the system to decide (if sounds are played or not and which)
     * Silent: play no sound at all 
     * DefaultSystemSound: use default system sound
     * Custom: use the custom sound configured in Shiny
2. Change semantics of existing API to make behavior consistent (see above)
    * Change behaviour of iOS implementation to play system default sound if no custom sound is specified:
        ```
        if (Notification.CustomSoundFilePath.IsEmpty())
            content.Sound = UNNotificationSound.Default;
        else
            content.Sound = UNNotificationSound.GetSound(Notification.CustomSoundFilePath);
        ```

However, option (2) might not fit other use cases so I think option (1) would be better. If you like I can propose a PR for option this.

## Intended Use Case
In my App I have low and high priority notifications. For high priority notifications, the user should also be informed acoustically (if allowed by the user and platform). This is not necessary/wanted for low priority notifications.

Currently, I cannot achieve the desired behaviour with Shiny.

**Comment by aritchie** [comment]
The goal isn't to maintain consistency across platforms.  It is to let the platforms behave as they do out of the box in most cases.  

I will consider this for a future release though.

**Comment by dahlbyk** [comment]
> The goal isn't to maintain consistency across platforms. It is to let the platforms behave as they do out of the box in most cases.

IMO it's good for Shiny defaults to align with to out-of-the-box behavior, but adoption seems likely to depend on having adequate hooks to replicate customization that's supported natively. This is a great opportunity for contribution by people with specific needs (thus https://github.com/shinyorg/shiny/pull/191), but it would be good to have contribution guidance on how to approach additional configuration APIs.

Or (please forgive my cross-platform ignorance) would there be some way to support platform-specific configuration, e.g.

```
interface INotificationConfiguration { } // Marker interface

// In Platforms/iOS
abstract class NotificationConfiguration : INotificationConfiguration {
  public virtual void UpdateContent(UNMutableNotificationContent content) { }
}

// In Platforms/iOS/NotificationManager
if (notification.Configuration is NotificationConfiguration config) {
   config.UpdateContent(content);
}

// In Platforms/Android
abstract class NotificationConfiguration : INotificationConfiguration {
  public virtual void UpdateBuilder(NotificationCompat.Builder builder) { }
}

// In Platforms/Android/Notificationmanager
if (notification.Configuration is NotificationConfiguration config) {
  config.UpdateBuilder(builder);
}
```

I'm fuzzy on exactly how to allow consumers to provide their platform-specific subclasses of the corresponding `NotificationConfiguration`, but it seems like it should be possible?

**Comment by aritchie** [comment]
I'm not sure how I want to do these deep customizations yet.  I actually hate the Android config (it is there for a reason and it works), but it creates a platform binding that has a carrying cost.  

I want to get rid of these platform bindings or at least consider it before I start getting more.  I have a few ideas just not there yet.  I want to get a few release priorities out of the way first.

**Comment by aritchie** [comment]
> There is currently no way to tell Shiny.Notifications to use system default sound. 

You can use the following in the meantime while I figure out how to go about this:
In your appdelegate - Notification.CustomSoundFilePath = UNNotification.Default;

**Comment by aritchie** [comment]
I've released something to dev/myget - give it a try.

**Comment by cpraehaus** [comment]
> > There is currently no way to tell Shiny.Notifications to use system default sound.
> 
> You can use the following in the meantime while I figure out how to go about this:
> In your appdelegate - Notification.CustomSoundFilePath = UNNotificationSound.Default;

Unfortunately this does not work since UNNotificationSound.Default is no string object.

**Comment by cpraehaus** [comment]
Wow, thanks for the quick proposal! Tried out dev branch and it works for me.
I'm using ```NotificationSound.DefaultSystem``` and ```NotificationSound.None```. Up to now I tested on Android 6 and iOS 11.

A few comments:
* NotificationSound.DefaultPriority: UNNotificationSound.DefaultCriticalSound on iOS (see https://docs.microsoft.com/en-us/xamarin/ios/platform/introduction-to-ios12/notifications/critical-alerts):
    * On iOS 11 using DefaultPriority (DefaultCriticalSound) causes an Exception
	* Needs iOS version 12 or higher
	* Requires extra entitlement by Apple (need to fill in online form which is reviewed by Apple)
	* Entitlement needs to be added to plist
	* App needs to request additional notification permission (UNAuthorizationOptions.CriticalAlert)
	* One should be airy with this since it also plays alert when "Do Not Disturb" is enabled.
	* Maybe remove DefaultPriority or map it to DefaultSystem on iOS.
* struct NotificationSound: maybe think about an enum or a flag (``IsCustom``) that tells if NotificationSound specifies a custom sound. In the different platform implementations of NotificationManager you can then perform the checks like this:
```
	if (notification.Sound.IsCustom) 
		// Set custom sound
	else if(notification.Sound.Equals(NotificationSound.None))
		// Set no sound/silent
	else if(notification.Sound.Equals(NotificationSound.DefaultSystem))
		// Set system default sound
	else
		throw new NotSupportedException();
```		
I think this is more maintainable in case new notification sound types are added in the future.

**Comment by aritchie** [comment]
I definitely don't think there is less maintenance cost for the struct for this case, so let's leave that alone.  

I have made things more customizable around critical alerts without killing critical alerts
