### ISSUE TITLE
Cannot write more than once

### ISSUE THREAD

**Issue by eli191** [shinyorg/shiny#212]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [x] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.1182-beta
## Version of OS(s) listed above with issue
Android API 24

## Steps to Reproduce
1. Get one characteristic and `Write(data)`
2. After being notified of the change on another characteristic, call the write method again
3. 

## Expected Behavior
Write every time

## Actual Behavior
Write the first time.
On subsequent calls, `Write` does nothing and no exception is thrown either

Thanks!

**Comment by aritchie** [comment]
Please include some sort of sample code.  If the write is failing, there will be an error.  Do you have a timeout on it?

**Comment by eli191** [comment]
Thanks for your reply!

I have this code to write
```
_log.Debug($"Sending {charVal.ByteArrayToString()}");
_deviceAgent.WriteChar()
                    .SelectMany(x => x.Write(charVal))
                    .Do(x => _log.Debug($"writing"))
                    .Subscribe(_ => { }, e => _log.Debug($"Write error = {e}")
                   );
```
The first time I call this method, I get the log output `writing` as expected and I get the device replying (on the other characteristic I get notifications). Then I need to write again, but nothing happens after the log outputs `Sending XXXX`

As you suggested I have put a timeout like this
`.Timeout(TimeSpan.FromMilliseconds(2_000))`
And now I get printed `Write error = System.TimeoutException: The operation has timed out.`

Do you know why the second write exits in timeout?

Thank you!

**Comment by aritchie** [comment]
This isn't a sample.  This is 4 lines of code.  I really need to see what goes on around it.  Did you use any config in the services.UseBleCentral(...)?  

This call is going to create issues for you anyhow as things may not write in order and you could be flooding it with calls.  If you need things to go in order, you should be looping and awaiting the response before writing the next character

**Comment by aritchie** [comment]
No response from user.  Closing
