### ISSUE TITLE
[Android] GeofenceManager.Status does not check for GPS provider - Leads to StartMonitoring GEOFENCE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by dahlbyk** [shinyorg/shiny#213]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] Android

## Feature Library

 - [x] Locations

## Version of Library

1.0.0.561-beta (don't see anything since in `master` that would help)

## Version of OS(s) listed above with issue

Android 9, 10

## Steps to Reproduce
1. [Disable Location](https://support.google.com/accounts/answer/3467281?hl=en) with Quick Settings or otherwise
2.  ```csharp
    if (geofenceManager.Status == AccessState.Available)
        await geofenceManager.StartMonitoring(region);
    ```

## Expected Behavior

`Status` should have returned `AccessState.Disabled` so I don't try to `StartMonitoring()`.

## Actual Behavior

`GeofenceManager.Status` returns `Available` and `GeofenceManager.StartMonitoring(region)` throws [`GEOFENCE_NOT_AVAILABLE`](https://developers.google.com/android/reference/com/google/android/gms/location/GeofenceStatusCodes.html#GEOFENCE_NOT_AVAILABLE)

`Status` is currently just a permission check:
https://github.com/shinyorg/shiny/blob/378cfb8c387c0c2d647d43f95b3aae74a15c7c39/src/Shiny.Locations/Platforms/Android/GeofenceManagerImpl.cs#L42

It seems like additional effort is needed to [get current location settings](https://developer.android.com/training/location/change-location-settings#get-settings):
- [`LocationSettingsRequest.Builder`](https://developers.google.com/android/reference/com/google/android/gms/location/LocationSettingsRequest.Builder.html#public-methods_1)
- [`LocationSettingsResult.getLocationSettingsStates()`](https://developers.google.com/android/reference/com/google/android/gms/location/LocationSettingsResult.html#getLocationSettingsStates())
- [`LocationSettingsStates.isLocationPresent()`](https://developers.google.com/android/reference/com/google/android/gms/location/LocationSettingsStates.html#isLocationPresent()) and [`isLocationUsable()`](https://developers.google.com/android/reference/com/google/android/gms/location/LocationSettingsStates.html#isLocationUsable())

**Comment by aritchie** [comment]
I actually want to kill off that property and the state management observable.  They don't do what they need to do in a lot of cases.  

Let me see what I can do.  The next public shiny release (nuget) is pinned to the AndroidX production release at this point (as an FYI)

**Comment by dahlbyk** [comment]
While we're on the topic of Android status, I also stumbled on [`ACCESS_BACKGROUND_LOCATION`](https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_BACKGROUND_LOCATION) via [Privacy changes in Android 10](https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location) (also [Receive periodic location updates](https://developer.android.com/training/location/receive-location-updates)). Does this impact Shiny at all?

**Comment by aritchie** [comment]
The current status check should grandfather in, but this is something I'll check especially now that android 10 targets on the table.  It should only impact the GPS implementation directly

**Comment by aritchie** [comment]
This and android 10 permission is ready for the next release
