### ISSUE TITLE
Support for Secure Storage

### ISSUE THREAD

**Issue by lnaie** [shinyorg/shiny#22]
Thanks for the work. I also like the support for the other mvvm frameworks.
But i haven't seen the api for Secure Storage mentioned, so to remove Xamarin Essentials all together:
https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=android .

Thanks

**Comment by aritchie** [comment]
A secure storage API doesn't really fit the scope of this project at the moment.  I'm not looking to replace essentials either.  I am targeting different things in the future.

**Comment by lnaie** [comment]
ok then. thanks
