### ISSUE TITLE
iOS 13 Push Notification Token Updates

### ISSUE THREAD

**Issue by SuavePirate** [shinyorg/shiny#224]
## Summary
Since iOS 13, Apple has made a change to the underlying push notification token structure. Previously, trimming `<>` characters would give you the underlying token needed to send to a push service like Azure Notifications Hub or Firebase. There is a new way structure that requires a new way to get the token out.

## API Changes
This change would require an update to the iOS `PushManager` implementation: https://github.com/shinyorg/shiny/blob/master/src/Shiny.Push/Platforms/iOS/PushManager.cs

And specifically in the `RegisteredForRemoteNotifications` static method to implement the new logic if the devices is >iOS 13. Here is an example of how I access the token now on iOS 13 in other projects:

```csharp
private string ExtractToken(NSData deviceToken)
{
    var length = deviceToken.Length;
    if (length == 0)
        return null;
    var result = new byte[deviceToken.Length];
    System.Runtime.InteropServices.Marshal.Copy(deviceToken.Bytes, result, 0, (int)deviceToken.Length);
    return BitConverter.ToString(result).Replace("-", "");
}
```

## Intended Use Case
Used for registering push notifications on iOS devices on iOS 13 and higher.

**Comment by SuavePirate** [comment]
Happy to implement and PR as well, but wanted to create the issue first to track :)

**Comment by aritchie** [comment]
Fixed for the next released - thanks
