### ISSUE TITLE
[Xamarin.forms][iOS][Location] not working when While APP In Use

### ISSUE THREAD

**Issue by jitendrajadav** [shinyorg/shiny#226]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
Shine.Location 1.0.0.1182

## Version of OS(s) listed above with issue
iOS 6 (12.4)

## Steps to Reproduce
1. Create Xamarin Forms Application
2. Add Shiny.Core and Shiny.Location Packages
3. Update Xamarin.iOS info.plist with `<key>NSLocationAlwaysUsageDescription</key>
	<string>The beacons or geofences or GPS always have you!</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>The beacons or geofences or GPS always have you!</string>
<key>NSLocationWhenInUseUsageDescription</key>
	<string>Your location is recorded with each manifest to better track where you are when scanning.</string>`
4. Run the app and it will ask permission once you tap "**Only while Using App**"
5. It will throw Exception "System.ArgumentException"

## Expected Behavior
It should run as expected 

## Actual Behavior
throwing error like :

> {System.ArgumentException: Invalid State Restricted
>
> at Shiny.GeneralExtensions.Assert (Shiny.AccessState state, System.String message, System.Boolean allowRestricted) [0x0000d] in d:\a\1\s\src\Shiny.Core\Extensions_General.cs:16 
>
> at Shiny.Locations.GpsManagerImpl.StartListener (Shiny.Locations.GpsRequest request) [0x00099] in d:\a\1\s\src\Shiny.Locations\Platforms\iOS\GpsManagerImpl.cs:67 
>
> at KegID.ViewModel.MoveViewModel.OnNavigatedTo (Prism.Navigation.INavigationParameters parameters) [0x002cc] in /Users/slgindia/Projects/kegid-x/KegID/KegID/ViewModel/Move/MoveViewModel.cs:515 }

**Comment by aritchie** [comment]
Since you haven't posted any code, I'm going to guess you are trying to get background GPS permission and your user only gave in-app permissions.  You need to change your StartListener request.

**Comment by jitendrajadav** [comment]
Hi @aritchie thank you for your quick response, this issue is closed so I am not sure where I can post comment so please help me to fix this issue.
Yes I am trying to get Background GPS Permission.
if you want to check code please check here
[ShinyBackground](https://github.com/jitendrajadav/ShinyBackground.git)

**Comment by aritchie** [comment]
There is no issue which is why this is closed.  Look at the source in the shiny project, there is a GpsRequest with a background.  There is also ILocationManager.RequestAccess if you don't want to try/catch your call.

**Comment by jitendrajadav** [comment]
> There is no issue which is why this is closed. Look at the source in the shiny project, there is a GpsRequest with a background. There is also ILocationManager.RequestAccess if you don't want to try/catch your call.

@aritchie Thank you for you reply I am requesting like please check and correct me if anything wrong

`  if (_gpsManager.IsListening)
            {
                await _gpsManager.StopListener();
            }

            await _gpsManager.StartListener(new GpsRequest
            {
                UseBackground = true,
                Priority = GpsPriority.Highest,
                Interval = TimeSpan.FromSeconds(5),
                ThrottledInterval = TimeSpan.FromSeconds(3) //Should be lower than Interval
            });`

**Comment by aritchie** [comment]
@jitendrajadav I have pointed you in a direction and there is no issue.  Please be respectful of my time.
