### ISSUE TITLE
[BLE] Custom service on iOS is not available

### ISSUE THREAD

**Issue by ThumbGen** [shinyorg/shiny#23]
Hello

First of all, congratulations for creating such an amazing library (including its awesome name) :)

I am trying to create a BLE Peripheral (Server) running on an Android/iOS phone, offering a custom service. A bluetooth enabled PC will act as a Central (Client) and consume the custom service.

It works very well on Android, but on iOS only advertising the service works.
Once I connect and list services the service is not listed (tried with my own client but also with some other bluetooth LE browsers).

What is a bit confusing me is this sentence is the documentation:

**On iOS - you need to advertise as well as create a gatt server**

What should I do beside adding the service (and its characteristics) and then starting advertising?

NOTE: The 'default' services which the iPhone offers are available (9 of them) and I can browse and read them. Only my custom one is not present.

Thank you in advance for any idea!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ X] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ X] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of OS(s) listed above with issue

iOS 12.3.1

## Version of Library

1.0.0.238-beta

## Expected Behavior

Offering a custom service via BLE should work on iOS.

## Actual Behavior

Offering a custom service via BLE does not work. Advertising works, but the service is not found by the client.

**Comment by aritchie** [comment]
This seems to be working fine with the latest version.

**Comment by ThumbGen** [comment]
Using 1.0.0.253-beta and bringing registering the service closer to starting advertising (I guess I hit a timing issue there by registering the service very soon and then starting advertising later) => I can list the service and subscribe to notifications but no values are pushed back (same goes for the ShinySamples app).

In the ShinySamples app it hangs in the await this.notifications.Notify, the .Write is never called.

For Android it works, no problems there.

**Comment by ThumbGen** [comment]
I am not sure, but isn't it that the tcs is never 'completed' ? The tcs.SetResult seems to be missing:


```
public async Task Notify(byte[] data, params IPeripheral[] centrals)
        {
            var tcs = new TaskCompletionSource<object>();
            var handler = new EventHandler((sender, args) =>
            {
                this.manager.UpdateValue(
                    NSData.FromArray(data),
                    this.native,
                    null
                );
            });
            this.manager.ReadyToUpdateSubscribers += handler;

            await tcs.Task.ConfigureAwait(false);
            this.manager.ReadyToUpdateSubscribers -= handler;
        }

```
