### ISSUE TITLE
Need to add content to TransferJob class before HTTPTranfer data is sent

### ISSUE THREAD

**Issue by blombas** [shinyorg/shiny#231]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ x] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ x] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.1182
## Version of OS(s) listed above with issue
iOS 12.1

## Steps to Reproduce
1. Upload an image from device using HTTPTransfer
2. An empty exception will be thrown

## Expected Behavior
1. Upload an image from device using HTTPTransfer
2. Api endpoint should be hit and IFormfile data should be received 

## Actual Behavior
We have found that if we attach Shiny project manually to iOS project and add a line to the TransferJob class (after line 127)in upload method where transfer content will be added to message.Content our endpoint will be hit correctly with data. Not sure if it is a bug or we are using the library wrongly. But for now this is the only way we are able to use HttpTransfers

Screenshot will show line added by us and not in original code.
<img width="390" alt="Screenshot 2020-02-28 11 59 46" src="https://user-images.githubusercontent.com/2551828/75543664-a3b29880-5a22-11ea-976b-00aab6ca4d91.png">

**Comment by aritchie** [comment]
Thanks for the bug report.  Please feel free to send a PR in the future.

iOS has a native uploader and should not be using the http client version of the library.  Can you please share how you registered the HTTP transfers in your startup?

**Comment by aritchie** [comment]
No response from user.

**Comment by blombas** [comment]
Here are my Startup class, as mentioned when using the library in normal way I hit OnError exception method, with empty exception.

`
using Microsoft.Extensions.DependencyInjection;
using MyViewApp.Services.Storage.Interfaces;
using Shiny;
using Shiny.Net.Http;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Shiny.Prism;
using Prism.DryIoc;
using MyViewApp.Services.Storage;
using Shiny.Jobs;
using System.Threading;
using MyViewApp.ViewModels;

namespace MyViewApp.DependencyServices
{
    public class MyViewShinyStartup : PrismStartup
    {
        public MyViewShinyStartup() : base(PrismContainerExtension.Current)
        {

        }

        protected override void ConfigureServices(IServiceCollection services)
        {
            // this is where you'll load things like BLE, GPS, etc - those are covered in other sections
            // things like the jobs, environment, power, are all installed automatically
            services.AddSingleton<IPhotosBlobStorageService, PhotosBlobStorageService>();
            services.UseHttpTransfers<MyViewHttpTransferDelegate>();
        
            
        }
    }

    public class MyViewHttpTransferDelegate : IHttpTransferDelegate//, IJob
    {
        // yes - you can inject anything registered with Shiny into the constructor here

        IPhotosBlobStorageService _photosBlobStorageService;

        public MyViewHttpTransferDelegate(IPhotosBlobStorageService photosBlobStorageService)
        {
            
            _photosBlobStorageService = photosBlobStorageService;
        }

        public   Task OnError(HttpTransfer transfer, Exception ex)
        {
			
        }

        public Task OnCompleted(HttpTransfer transfer)
        {
            
        }

        //public Task<bool> Run(JobInfo jobInfo, CancellationToken cancelToken)
        //{
        //    throw new NotImplementedException();
        //}
    }
}

`
Here are my method picking images from Media plugin in viewmodel and enqueue them via HTTPTransfer Request


`
```
async Task OnPickPhotoCommandExecute()
        {
            if (!IsBusy)
            {
                IsBusy = true;
                //var retBool = true;
                try
                {
                    var photoStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Photos);
                    if (photoStatus != PermissionStatus.Granted)
                    {
                        var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Photos });
                        photoStatus = results[Permission.Camera];
                    }
                    if (photoStatus == PermissionStatus.Granted)
                    {
                        if (Connectivity.NetworkAccess == NetworkAccess.Internet)
                        {
                             var files = await CrossMedia.Current.PickPhotosAsync(new PickMediaOptions
                             {
                                 PhotoSize = PhotoSize.Full,
                                 CompressionQuality = 100,
                                 CustomPhotoSize = 100,
                                 SaveMetaData = true,
                                 RotateImage = false,
                             });
                             if (files == null)
                                 return;
                            if (files != null && files.Count > 0)
                            {
                                foreach (var file in files)
                                {
                                    var imgFIle = new ListingPicture() { ListingImage = file.Path, IsSelected = false, IsWideangle = false };
                                    Case.Pictures.Add(imgFIle);
                                }
                                int i = 0;
                                foreach (var file in files)
                                {
                                    var request = new HttpTransferRequest("https://myviewweb.azurewebsites.net/api/Thumbnail/uploader", file.Path, true)
                                    {
                                        HttpMethod = System.Net.Http.HttpMethod.Post,
                                       // UseMeteredConnection = true,
                                    }
                                    ;
                                    var tranfer = await _httpTransferManager.Enqueue(request); ;
                                    ++i;
                                }
                            }
                           // await PageDialogService.DisplayAlertAsync("Image", "Images saved successfully.", "OK");
                        }
                        else
                        {
                            await PageDialogService.DisplayAlertAsync("No internet", "No internet access.", "OK");
                        }
                    }
                    else
                    {
                        await PageDialogService.DisplayAlertAsync("Access denied", "Unable to take photos.", "OK");
                    }
                }
                catch (Exception ex)
                {
                    Crashes.TrackError(ex, new Dictionary<string, string>{
                                       { "Filename", "CaseOpenPageViewModel" },
                                       { "Where","OnPickPhotoCommandExecute" },
                                       { "Issue",ex.Message }
                    });
                }
                finally {
                    IsBusy = false;
                   // retBool = false;
                    GetListingDetail();
                }
            }
        }
```
`

Here are screenshots of how library is referenced manually to iOS and PCL projects

![image (3)](https://user-images.githubusercontent.com/2551828/75751321-82a1be80-5d26-11ea-935f-1d10dc8b7e42.png)
![image (4)](https://user-images.githubusercontent.com/2551828/75751326-83d2eb80-5d26-11ea-94b2-a539dde67b1c.png)

Any help will be appreciated, thanks
