### ISSUE TITLE
[Android] Http downloads can cause app crash when transfer encounters error

### ISSUE THREAD

**Issue by yavor87** [shinyorg/shiny#232]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [x] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of OS(s) listed above with issue
Android 9

## Steps to Reproduce
1. Try to download something from the web which will result in an error
2. App closes with Unhandled Exception

## Expected Behavior
App doesn't crash

## Actual Behavior
App crashes with the following exception:
```
Unhandled Exception:
    System.ArgumentNullException: Value cannot be null.
    Parameter name: uri
    at Shiny.Net.Http.HttpTransfer..ctor (System.String identifier, System.String uri, System.String localFilePath, System.Boolean isUpload, System.Boolean useMeteredConnection, System.Exception exception, System.Int64 fileSize, System.Int64 bytesTransferred, Shiny.Net.Http.HttpTransferState status) [0x00011] in d:\a\1\s\src\Shiny.Net.Http\HttpTransfer.cs:14 
```

**Comment by yavor87** [comment]
The problem occurs, because of a bug in the Android PlatformExtensions. When a `HttpTransfer` is constructed from `ICursor`, the remote uri property is obtained from the wrong column.

https://github.com/shinyorg/shiny/blob/master/src/Shiny.Net.Http/Platforms/Android/PlatformExtensions.cs#L75

Column used: **Native.ColumnLocalUri**
Should be:       **Native.ColumnUri**

In some situations the localUri is null, which in turn makes the uri null, which then causes ArgumentNullException when constructing the HttpTransfer, which in turn crashes the app.

**Comment by aritchie** [comment]
This already fixed for the next release.  Thanks for reporting it though.

**Comment by aritchie** [comment]
You can grab this fix off the dev feed if you want.  A release is about a week away
