### ISSUE TITLE
System.ArgumentException: 'Job identifier defined'

### ISSUE THREAD

**Issue by wagenheimer** [shinyorg/shiny#237]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [X] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1405

## Version of OS(s) listed above with issue
Multiple Android Versions

## Steps to Reproduce
1. Download the Attached Project [Shiny Error Android.zip](https://github.com/shinyorg/shiny/files/4278910/Shiny.Error.Android.zip)
2. Run it on an Android Device
3. It will crash with the error "System.ArgumentException: 'Job identifier defined'" on services.UseNotifications();

## Expected Behavior
The app should execute without error!

## Actual Behavior
The application crash with an error!

**Comment by aritchie** [comment]
Why are you complaining on another issue that there is no fix?  You're using a beta, not the release version.

**Comment by aritchie** [comment]
This is only a problem in the beta and has been fixed.
