### ISSUE TITLE
'Invalid State Denied' on GpsManager.StartListener on android 10 with correct permissions

### ISSUE THREAD

**Issue by nicolashotterbeekx** [shinyorg/shiny#238]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
MyGet: 1.1.0.1407

## Version of OS(s) listed above with issue
Android 10, SDK version 29

## Steps to Reproduce
1. Give the Access_background_location permission 
2. GpsManager.StartListner with UseBackground = true on Android 10

## Expected Behavior
Listner starts

## Actual Behavior
Exception thrown: System.ArgumentException:** 'Invalid State Denied'

## Sugestion
In the file Android\GpsManagerImpl.cs on line 41 shiny is asking permission for ACCESS_BACKGROUND_LOCATION should this not be android.permission.ACCESS_BACKGROUND_LOCATION
(might be wrong, so just a suggestion, anyways thank your sharing this awesome library)

**Comment by aritchie** [comment]
You are correct.  I’ll get that fixed up.  Thanks.

Feel free to send a PR in the future.

**Comment by aritchie** [comment]
Fixed in the latest beta
