### ISSUE TITLE
[Android] HttpTransferDelegate methods are not being called after the transfer is completed if the app is not running

### ISSUE THREAD

**Issue by yavor87** [shinyorg/shiny#239]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [x] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.1182

## Version of OS(s) listed above with issue
Android 9

## Steps to Reproduce
1. Enqueue a download. Make sure the download is running;
2. Close the app;

## Expected Behavior
The methods of the registered IHttpTransferDelegate are being called after the transfer is completed.

## Actual Behavior
The methods of the registered IHttpTransferDelegate are not being called after the transfer is completed.

**Comment by yavor87** [comment]
I am trying to download a chain of files. The workflow is as follows:
1. Download a file.
2. When the file is downloaded, depending on the file contents, start another download.

This works fine when the app is in the foreground. When I close the app then the second file download is not being queued. It turns out that when the app is not running, the transfer delegate methods are not being called. I have run the app with the Shiny source code and confirmed that the BroadcastReceiver is being triggered, but for some reason the it fails to trigger the transfer delegate methods.

[DownloadSample.zip](https://github.com/shinyorg/shiny/files/4293804/DownloadSample.zip)

**Comment by aritchie** [comment]
I have not seen an issue with this.  Have you checked for errors in the Shiny logs?

**Comment by yavor87** [comment]
You can run the sample app I provided. I haven't seen any Shiny error in the logs.

**Comment by aritchie** [comment]
Your sample isn't showing me anything I haven't seen before.

Do you know how to wire into the Shiny logger?  There is a bunch of stuff in Shiny.Core\Logging that can help get you going

**Comment by yavor87** [comment]
This sample shows that the message "## TransferDelegate.OnCompleted" is not being written in the logcat once the app is shutdown.

**Comment by yavor87** [comment]
I have added logging into the broadcast receiver like that:
[gist](https://gist.github.com/yavor87/0c2cff20e153fb457186707e565fca0f)

This generates the following log on my machine when running the provided sample:
```
2020-03-05 19:07:44.771 5385-5385/com.companyname.downloadtestapp I/Shiny: ## HttpTransferBroadcastReceiver.OnReceive. Delegate DownloadSample.TransferDelegate
2020-03-05 19:07:44.782 5385-5385/com.companyname.downloadtestapp I/Shiny: ## HttpTransferBroadcastReceiver.OnReceive. Cursor.MoveToNext()
2020-03-05 19:07:44.855 5385-5385/com.companyname.downloadtestapp I/Shiny: ## HttpTransferBroadcastReceiver.OnReceive. tdelegate.OnCompleted
2020-03-05 19:07:44.908 5385-5385/com.companyname.downloadtestapp I/Shiny: ## HttpTransferBroadcastReceiver.OnReceive. End
```

Notice that the `tdelegate.OnCompleted` is being called and on the correct delegate, but the code inside the delegate is not being executed. If it was executed, the message ## _TransferDelegate.OnCompleted_ should have been logged.

**Comment by aritchie** [comment]
Thank you - that was helpful to finding the problem.  Please try the latest beta.  It should roll out on myget within the hour

**Comment by yavor87** [comment]
Tried version 1.1.0.1417, but the issue persists.

**Comment by aritchie** [comment]
I've been through the test cases and all is working fine.  You can check the sample application out if you want.

**Comment by yavor87** [comment]
I played a bit with the latest code from Dev. Put some logging as in this [gist](https://gist.github.com/yavor87/0c2cff20e153fb457186707e565fca0f). Here is the output on my machine when the app is not running:

```
2020-03-07 16:52:09.355 9345-9345/com.companyname.downloadtestapp V/HttpTransferBroadcastReceiver: ## OnReceive Start
2020-03-07 16:52:09.423 9345-9345/com.companyname.downloadtestapp V/HttpTransferBroadcastReceiver: ## MoveToNext()
2020-03-07 16:52:09.442 9345-9345/com.companyname.downloadtestapp V/HttpTransferBroadcastReceiver: ## OnReceive End
2020-03-07 16:52:09.467 9345-9345/com.companyname.downloadtestapp V/HttpTransferBroadcastReceiver: ## tdelegate.OnCompleted
```

Notice how the `tdelegate.OnCompleted` is called after `OnReceive End`. Also, notice that the `tdelegate.OnCompleted end` is never called. I don't have a clue what is going on.

My transfer delegate `OnCompleted` method is async.

**Comment by aritchie** [comment]
@yavor87 My method in the test sample is also async and is working just fine when I swipe away the app.  OnReceive.End will likely be called before your async method completes, but under the hood, I'm using the BroadcastReceiver.goAsync, so this is by design. 

You are welcome to continue debugging, but I've done what I can from my end at this point.

**Comment by yavor87** [comment]
I am trying to enqueue another download in the delegate. Perhaps that’s
what is breaking the code on my end. Continuing debugging.
