### ISSUE TITLE
Need to add content to TransferJob class before HTTPTranfer data is sent

### ISSUE THREAD

**Issue by blombas** [shinyorg/shiny#242]
IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

[ x] iOS
  Android
  UWP
  watchOS
  tvOS
  Tizen
[ x] .NET Standard
Feature Library

  Core
  BluetoothLE
  Beacons
  Locations
[ x] HTTP Transfers
  Notifications
  Sensors
Version of Library

1.0.0.1182

Version of OS(s) listed above with issue

iOS 12.1

Steps to Reproduce

Upload an image from device using HTTPTransfer
An empty exception will be thrown
Expected Behavior

Upload an image from device using HTTPTransfer
Api endpoint should be hit and IFormfile data should be received
Actual Behavior

We have found that if we attach Shiny project manually to iOS project and add a line to the TransferJob class (after line 127)in upload method where transfer content will be added to message.Content our endpoint will be hit correctly with data. Not sure if it is a bug or we are using the library wrongly. But for now this is the only way we are able to use HttpTransfers

**Comment by blombas** [comment]
This issue has been created before but was closed before I could answer. So reopened a duplicate

https://github.com/shinyorg/shiny/issues/231#issuecomment-593803772

**Comment by aritchie** [comment]
This bug is fixed in dev which is why it was closed.  You also answered before the issue locked itself.  Not sure why you've created a duplicate?

**Comment by blombas** [comment]
Thanks. Was not aware of the fix in dev and read that my bug was closed because inactivity, before I could answer. Got it now, no duplicates.
