### ISSUE TITLE
Multiple Delegates Per Function

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#244]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
The need is arising to allow (and internally resolve) multiple delegates

## API Changes
Follow the summary

## Intended Use Case
Makes the infrastructure easier

This needs to apply to
* GPS
* Geofencing
* Notifications
* Push (? - not sure if this is necessary)
* BluetoothLE
* Beacons (?)

**Comment by betwinam** [comment]
سلام همه چیز عالیه و ما ادامه میدهیم

**Comment by betwinam** [comment]
> # اگر شما پاسخ این نمونه را ندهید - این مسئله به طور خودکار موضوع شما را می پوشاند!
> ## خلاصه
> این نیاز به وجود آمده است که به نمایندگان متعدد اجازه می دهد (و از بین بردن داخلی) برطرف شود
> 
> ## تغییرات API
> خلاصه را دنبال کنید
> 
> ## مورد استفاده موردی
> زیرساخت ها را تبدیل می کند
