### ISSUE TITLE
[Bug] [iOS] BLE Peripheral - Notification broadcasts not working

### ISSUE THREAD

**Issue by ThumbGen** [shinyorg/shiny#25]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ x] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library

1.0.0.253-beta

## Version of OS(s) listed above with issue

iOS 12.3.1

## Steps to Reproduce
1. Start the ShinySamples
2. Start some client which subscribes to notifications
3. Put a breakpoint at the line where the .Notify is called. 

## Expected Behavior

Notify is executed and the app moves on.

## Actual Behavior

Execution hangs inside the Notify method

I am not sure, but isn't it that the tcs is never 'completed' ? The tcs.SetResult seems to be missing:

```
public async Task Notify(byte[] data, params IPeripheral[] centrals)
        {
            var tcs = new TaskCompletionSource<object>();
            var handler = new EventHandler((sender, args) =>
            {
                this.manager.UpdateValue(
                    NSData.FromArray(data),
                    this.native,
                    null
                );
            });
            this.manager.ReadyToUpdateSubscribers += handler;

            await tcs.Task.ConfigureAwait(false);
            this.manager.ReadyToUpdateSubscribers -= handler;
        }

```

**Comment by aritchie** [comment]
@ThumbGen did you test it with this fix?  For purposes of the beta, I'm looking for more than just issues being filed.  If you can't do this, that is perfectly fine, but please wait until a final release.

**Comment by ThumbGen** [comment]
I am so sorry, I've discovered the possible glitch while commuting (statically looking at the code) and I don't own a Mac to test. I will test it tomorrow, first thing I reach the office.

On a side note, AFAIK the purpose of a beta (a feature complete release of a product) is to collect bug reports and user feedback. Unfortunately I don't have the time to help via some useful pull requests (as the mobile app is a very low priority side project for us, sadly) therefore I'm just trying to provide feedback for the workflow I'm considering using inside the app). What you are building here is simply awesome, and I am surprised that you don't have more contributors to help :(

**Comment by aritchie** [comment]
You don't need to be sorry.  What I want people to understand is that you need to do 1 of the following:
1) Contribute
2) Send full test cases that may be gaps I haven't covered
3) Debug errors that they are seeing if not actually fixing them

The purpose of a beta is to give feedback, but it needs to be done well or it just becomes noise detracting from the end goal and can be frustrating for maintainers.  Simply saying that the sample isn't working is not giving me a gap.  I am still coding features and haven't tested everything end-to-end.  

I appreciate the words of support for the library and I truly want to make this awesome for everyone.  The lack of contributors is not uncommon for OSS libraries

**Comment by ThumbGen** [comment]
I fully understand you. Maybe you should paste the 1/2/3 expectations on the main page of the project. Will help people helping you :)

**The fix is unfortunately not working.** (it is required to complete the TCS but does not reach that point). I feel the ReadyToUpdateSubscribers does not get called at all.
I am not familiar with the CoreBluetooth, but there are some hints here: https://forums.developer.apple.com/thread/28365

 I am very sorry that I can't help more :(

**Comment by ThumbGen** [comment]
Hm, reading the CoreBluetooth specifications it seems that you have to directly call the UpdateValue first then monitor its result:
* if 'true' there's nothing else to do, the value was sent
* if 'false' (when internal queue is full) then the ReadyToUpdateSubscribers will be triggered and then you may attempt sending it again

(Source: https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1393281-updatevalue , see the Discussion paragraph)

HTH

**Comment by ThumbGen** [comment]
Unfortunately I am not able to create a proper pull request, but I was able to 'isolate' your Notify method, to use reflection to access the right fields and try a possible fix, and **it works**.

The method below should work:

```
        public async Task Notify(byte[] data, params IPeripheral[] centrals)
        {
            var res = this.manager.UpdateValue(NSData.FromArray(data), this.native, null);
            if (!res)
            {
                var tcs = new TaskCompletionSource<object>();
                var handler = new EventHandler((sender, args) =>
                {
                    this.manager.UpdateValue(NSData.FromArray(data), this.native, null);
                    tcs.TrySetResult(null);
                });
                this.manager.ReadyToUpdateSubscribers += handler;

                await tcs.Task.ConfigureAwait(false);
                this.manager.ReadyToUpdateSubscribers -= handler;
            }
        }
```

This is awesome, I have my BLE based feature working for iOS too. Keep up the amazing work!

**Comment by aritchie** [comment]
This is great - I can work with this.  I'll push this out in the next release.  Thanks @ThumbGen

**Comment by aritchie** [comment]
This will be released in the next beta within the next couple of days.  Thanks again for the effort!  Much appreciated
