### ISSUE TITLE
NotificationSound.None not working as expected

### ISSUE THREAD

**Issue by cpraehaus** [shinyorg/shiny#252]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
Only tested on Android so far.

 - [ ] iOS
 - [ x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ x] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1469

## Version of OS(s) listed above with issue
Android 6.0.3

## Steps to Reproduce
1.  Create a notification and set Notification.Sound to NotificationSound.None

## Expected Behavior
No sound is played with notification.

## Actual Behavior
On Android sound is played with notification.

Maybe the semantics of NotificationSound.None have changed (then please add short doc in the code), but at time of cb32a41778205fefaf45e5d8e05e73be7fcc0509 it worked for me as expected.

I think the default sound is now implicitly set by
https://github.com/shinyorg/shiny/blob/d0cbb27a5d503de57713b3f30ab8842c879f9cb1/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs#L168

I understand NotificationSound.None as *play no sound at all*. Currently it feels more like *do whatever you want* (in my opinion undefined). If that is by intention then please add short doc in the code. It would be very helpful then to have another option *NotificationSound.NoSound* which does exactly what it says, namely to ensure that no sound is played with notification. As stated in #210 it would be important that this behavior then is consistent across platforms, e.g. also the same on iOS.

**Comment by aritchie** [comment]
I'm not sure I understand the issue here?  The behaviour of None is consistent across platforms unless you start messing around with priority.

**Comment by cpraehaus** [comment]
Sorry, you were right: I was setting priority in the AndroidNotificationOptions which overrides the Sound option on the Notification (as intended). Was confused since this worked on the dev branch previously. This issue can be closed then.

BTW: documentation would help a lot, if you need a helping hand on that I could contribute to it.

**Comment by aritchie** [comment]
I do need help with documentation and take pull requests on this project.  Thanks
