### ISSUE TITLE
Excluding Settings from backup

### ISSUE THREAD

**Issue by JeremyBP** [shinyorg/shiny#253]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
I used to save some user settings into shared preferences with Xamarin Essentials and exclude settings from Android auto backup.
Could be cool to get the same option with Shiny, as some settings are so user specific.

## API Changes
May be something like [Essentials](https://github.com/xamarin/Essentials/blob/e5636d3ed521d8f4769d4f75ca9286301b8bb735/Xamarin.Essentials/Preferences/Preferences.android.cs#L153) does with context and shared name, so we could exclude it.

## Intended Use Case
For now, a logged in user who uninstall the app and install it again get all his settings back and it could be a secure issue. With named Shiny settings, we could have choice to exclude it from auto backup.

**Comment by aritchie** [comment]
Set for 1.2 release
