### ISSUE TITLE
Duplicate entries while file upload using httptransfer

### ISSUE THREAD

**Issue by jerryleelajohn** [shinyorg/shiny#254]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 - [ ] iOS
## Feature Library
 - [ ] HTTP Transfers
## Version of OS(s) listed above with issue
XCode 11.3
## Steps to Reproduce
1. Create an api to upload images
2. Add many images into the Http Transfer Manager queue
3. Observe , say out of 5 uploads 3 or more will be duplicate 
## Expected Behavior
1. While uploading 5 images, it should be 5 different images, not duplicate entries expected
## Actual Behavior
1. Out of a number of images being uploaded, one or two images are getting duplicated. Doubting the thread safety of Http Transfer.

**Comment by aritchie** [comment]
I have no idea what you mean here.  Can you please upload some sort of sample.

**Comment by jerryqburst** [comment]
Following code sample shows the scenario where a number of http transfer are created  in a loop. End result is the file upload creates duplicate entries at server side, not distinct ones as per the loop.


   foreach (var file in files)
                                {
                                    Dictionary<string, string> hdr = new Dictionary<string, string>();
                                    hdr.Add("x", x);
                                    hdr.Add("xx", xx);
                                  

                                    HttpTransferRequest request = new HttpTransferRequest("https://xxxxxxxxxx.net/api/xxx/uploader", file.Path, true)
                                    {
                                        HttpMethod = System.Net.Http.HttpMethod.Post,
                                        Headers = hdr,

                                    };
                                    HttpTransfer tranfer = await _httpTransferManager.Enqueue(request);
                                }

**Comment by aritchie** [comment]
I did not reproduce this.  I see all of the uploads going in just fine.  I reinspected the upload code and don't see how what you are saying is even possible since they all use different requests too.
