### ISSUE TITLE
Local Notification doesn't work on iOS 12.4.6 and iOS 13.2.4

### ISSUE THREAD

**Issue by wml2017** [shinyorg/shiny#260]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x ] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1473
## Version of OS(s) listed above with issue
iOS 12.4.6 
iOS 13.2.4

## Steps to Reproduce
1. On MacBook Pro, Update Xcode to 11.4 and also update visual studio 2019 mac community to the newest version. Create a new blank Forms App named as LocalNotification, only check iOS. After the whole solution is generated, update Xamarin.Forms to the newest version 4.5.0.495 (also update Xamarin.Essential to 1.5.2). Then install Shiny.Notifications 1.1.0.1473

2. Use following code to replace App.xaml.cs file

using System;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

using Shiny;
using Shiny.Notifications;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

namespace LocalNotification
{
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            MainPage = new MainPage();
        }

        protected async override void OnStart()
        {
            await SendNotificationNow();
            await ScheduleLocalNotification(DateTimeOffset.UtcNow.AddMinutes(1));
        }

        protected override void OnSleep()
        {
        }

        protected override void OnResume()
        {
        }

        Task SendNotificationNow()
        {
            var notification = new Notification
            {
                Title = "Testing Local Notifications",
                Message = "It's working",
            };
           //return ShinyHost.Resolve<INotificationManager>().Send(notification);
           return ShinyHost.Resolve<INotificationManager>().RequestAccessAndSend(notification);
        }

        Task ScheduleLocalNotification(in DateTimeOffset scheduleDate)
        {
            var notification = new Notification
            {
                Title = "Testing Local Notifications",
                Message = "It's working",
                ScheduleDate = scheduleDate,
            };
           //return ShinyHost.Resolve<INotificationManager>().Send(notification);
           return ShinyHost.Resolve<INotificationManager>().RequestAccessAndSend(notification);
        }
    }

    public class YourStartup : Shiny.ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            // register your shiny services here
            services.UseNotifications(); // set true
        }
    }
}

3. add
            this.ShinyFinishedLaunching(new YourStartup());
into AppDelegate.cs FinishedLaunching method in LocalNotification.iOS  project. After update, AppDelegate.cs will like

using Foundation;
using UIKit;
using Shiny;

namespace LocalNotification.iOS
{
    [Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            //iOSShinyHost.Init(platformBuild: services => services.UseNotifications());
            this.ShinyFinishedLaunching(new YourStartup());

            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            return base.FinishedLaunching(app, options);
        }
    }
}

# Expected Behavior
The first notification should be sent out after the app is executed
The second notification will be sent after 1 minute

## Actual Behavior
The first notification ISN'T sent out
The second is sent out successfully after 1 minute

**Comment by aritchie** [comment]
Samples are all working fine for me.  You'll need to do a little more debugging on your end.  Try/catch your calls to see what may be going on

**Comment by wml2017** [comment]
Thanks for your quick response. I use try/catch, there isn't any exception
            try
            {
                var notification = new Notification
                {
                    Title = "Testing Local Notifications",
                    Message = "It's working",
                };

                await ShinyHost.Resolve<INotificationManager>().Send(notification);                //await SendNotificationNow();
            }
            catch(Exception ex)
            {

            }

I also update all package for your sample. I found your sample uses Shiny.Notification 1.1.0.1487. But my solution uses 1.1.0.1473 (published at 3/17) and can't be updated to 1.1.0.1487 (published at 3/30/2020)

**Comment by wml2017** [comment]
> Samples are all working fine for me. You'll need to do a little more debugging on your end. Try/catch your calls to see what may be going on

Thanks for your quick response. I use try/catch, there isn't any exception
try
{
var notification = new Notification
{
Title = "Testing Local Notifications",
Message = "It's working",
};

            await ShinyHost.Resolve<INotificationManager>().Send(notification);                //await SendNotificationNow();
        }
        catch(Exception ex)
        {

        }
I also update all package for your sample. I found your sample uses Shiny.Notification 1.1.0.1487. But my solution uses 1.1.0.1473 which was published at 3/17) and can't be updated to 1.1.0.1487 (published at 3/30/2020)

**Comment by wml2017** [comment]
Hi Allan,
I find the issue. This notification is only work if the app ISN'T in the foreground (in the background) or iPhone is locked. If this app is in active status, the notification can't be sent out. How to allow the notification can be sent out no matter the app is in foreground or background?

**Comment by aritchie** [comment]
@wml2017 You really need to read the documentation on iOS documentation on notifications.  This has always been the way for iOS.

**Comment by thisismyself** [comment]
But I have an app, where I use Shiny 1.0.0.1182 on iOS 12 and 13.4 (both in Simulator) and I can raise local notifications when the app is in foreground, done just from a button click and the notification comes immediately. 
When I update the same app to Shiny 1.1.0.1473, I cannot raise any notifications in the foreground.

**Comment by wml2017** [comment]
> But I have an app, where I use Shiny 1.0.0.1182 on iOS 12 and 13.4 (both in Simulator) and I can raise local notifications when the app is in foreground, done just from a button click and the notification comes immediately.
> When I update the same app to Shiny 1.1.0.1473, I cannot raise any notifications in the foreground.

Yes, your are right. This sample

https://github.com/brminnick/LocalNotificationsSample

uses Shiny.Notification 1.0.0.1182 and it can sent notifications no matter the app is in foreground or background. But if you update it to the newest version, it doesn't work unless you lock the iPhone or put it in the background. Microsfot's sample also can work in foreground or background. Shiny's background solutions for Xamarin.Forms are very great idea. But they have three big issues: 1). reliability; 2). libraries documentation; 3). every sample involves many other libraries in Shiny's sample app. If Shiny ground can solve these issues, I think it will be one of great solutions for Xamarin.Forms platform

**Comment by aritchie** [comment]
@wml2017 There is no shiny group - it's just me.  Do remember that you use this code for free, so 

Reability is fine - it works for my tests cases.  You are welcome to submit fixes if you find otherwise
Documentation - Again, this is free.  I don't owe it to you.  Why not contribute back to the project?
Samples - I write the apps the way I want.  Don't like it, don't use it.
