### ISSUE TITLE
Add ability to provide custom intent for Shiny Notifications on Android

### ISSUE THREAD

**Issue by jaredballen** [shinyorg/shiny#267]
## Summary
The Android implementation for NotificationMananger does not expose a way to provide an alternative intent for notifications. It always uses the default launch intent for the package that is obtained from Package Manager. It would be useful for Apps with multiple activities, be able to provide an override so that notifications can be further customized.

## API Changes
1. Add a new callback method to AndroidOptions that users can provide a custom implementation for an intent builder. The default implementation should be the implementation that is currently in NotificationMananger.GetLaunchPendingIntent.
2. Modify the GetLaunchPendingIntent method in NotificationMananger to use the intent builder provided by the AndroidOptions instance defined in the notification.
3. There will be some additional work in the NotificationModule class to initial defaults for the new callback method in AndroidOptions.

## Intended Use Case
Take an Android app that contains two activities, A and B. Activity A is the "splash" activity and Activity B is the main app. If the default behavior for the NotificationManager, is to use the app's launch intent for a notification, then the App is essentially restarted, if the user taps on the notification while in the main app activity. Because the splash activity is normally not running when a notification is interacted with, the splash activity receives OnCreate and then starts the main app activity. This is a very abrupt transition for the user.

**Comment by jaredballen** [comment]
I am more than happy to work on this enhancement if it is accepted for development.

**Comment by aritchie** [comment]
You can now provide a custom launch activity type to the android options.  This should be enough to resolve this issue for now.  A new issue can be opened with any bugs around this new scenario.
