### ISSUE TITLE
Error when building Xamarin.Forms iOS app on Azure DevOps using Shiny

### ISSUE THREAD

**Issue by Resultfactory** [shinyorg/shiny#27]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP
 - [X] .NET Standard

## Feature Library

 - [X] Core
 - [ ] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
v1.0.0.252-beta

## Version of OS(s) listed above with issue
iOS 11.4
Xamarin Forms v4.1.0.555618
.NET Standard 2.0

## Steps to Reproduce
1. Setup Xamarin Forms app in Visual Studio 2019
2. Add Shiny.Core and add call  iOSShinyHost.Init to iOS project
3. Setup pipeline in Azure DevOps

## Expected Behavior
Build should finish successful as it does locally

## Actual Behavior
Instead the linker fails: 
Mono.Linker.LoadException: Error while processing references of 'Demo.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Linker.LoadException: Error while processing references of 'Demo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Linker.LoadException: Error while processing references of 'Shiny.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by aritchie** [comment]
I'm sorry - linker and external build systems aren't really bugs with the code here.  

I do build shiny demo's on azure devops without issue.  You should make sure you're using the latest version of mono in the build task

**Comment by Resultfactory** [comment]
Thanks for your reply. I'm using mono version 5.18.1. As far as I can check it is the latest version. Is there a way to compare my build tasks to the ones you are using?

**Comment by Resultfactory** [comment]
I got it to work. Just to share the solution: I had to add a Task before the build task to set the Xamarin SDK 5.18.1. The line is:
/bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1"
Thanks and we're glad we can now use Shiny in our apps. It's great.

**Comment by aritchie** [comment]
Thanks for the feedback.  I'll see about adding that to some sort of doc in the near future
