### ISSUE TITLE
[UWP] [Push] RawNotification Headers are empty

### ISSUE THREAD

**Issue by GuidoNeele** [shinyorg/shiny#270]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [X] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors
 - [X] Push

## Version of Library
1.1.0.1473

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Send windows push notification
2. Payload parameter of OnReceived method on push delegate is empty

## Expected Behavior
Payload filled with data

## Actual Behavior
Payload is empty

We are migrating our app from AppCenter Push to Azure Notification Hub and during testing of the UWP app the payload of the OnReceived method, of the push delegate, is always empty. Looks like the headers of the raw notification are always empty. Maybe the custom headers are being stripped? I guess you are using the headers because it's a key value pair and is easy to convert to a dictionary, which aligns with the other platforms?

An Azure function is used to send notifications via the Azure Notifications Hub. For communication with ANH the Microsoft.Azure.NotificationsHub package is used. The Windows notification is created as follows:

```csharp
public WindowsNotification GetWindowsNotification()
{
      var headers = new Dictionary<string, string>()
      {
        { "X-WNS-Type","wns/raw" }
      };

      if (!this.Silent)
      {
        headers.Add("title", System.Net.WebUtility.UrlEncode(this.Title));
        headers.Add("message", System.Net.WebUtility.UrlEncode(this.Message));
      }

      foreach (KeyValuePair<string, string> item in this.CustomData)
        headers.Add(System.Net.WebUtility.UrlEncode(item.Key), System.Net.WebUtility.UrlEncode(item.Value));

      var payload = "empty";

      return new WindowsNotification(payload, headers);
}
``` 

Am I doing something wrong in creating the notification? It feels a bit counter-intuitive and wrong to use the headers like this.

https://github.com/shinyorg/shiny/blob/d0cbb27a5d503de57713b3f30ab8842c879f9cb1/src/Shiny.Push/Platforms/Uwp/PushManager.cs#L51

I would like to contribute to writing documentation, what's the best way to go about this?

**Comment by aritchie** [comment]
UWP hasn't gone through a lot of testing yet so parts like this are incomplete.

All of the documentation is done through wyam.io - there are are some samples in this actual project, but I'll add a readme in the near future

**Comment by aritchie** [comment]
@GuidoNeele This does seem to be working in my early testing.  Do you have a test notification that you are sending?

**Comment by GuidoNeele** [comment]
Yes I used the code that I added in the issue I call the method GetWindowsNotification() on a Notification object that has Title, Message and several CustomData items set. The notification is sent via SendNotificationAsync() on the NotificationHubClient
```csharp
NotificationOutcome windowsOutcome = await client.SendNotificationAsync(notification.GetWindowsNotification());
```

**Comment by aritchie** [comment]
@GuidoNeele Do you have the raw XML of these requests?

**Comment by GuidoNeele** [comment]
Well it isn't an XML payload I'm sending (RAW notifications can contain anything I believe), my payload is basically empty (string empty) all information is in the Headers. But doing that felt totally weird so it might be that I'm doing something completely wrong. Could we do this the other way around? Do you have an example that you know works, because then I will alter my code so it fits what you are doing.
Are you sending notifications via Azure Notification Hub testpage by any change, because that way headers can't be added?

When we talk about headers I'm thinking request headers right? So e.RawNotification.Headers are the request headers of the notification, or are these headers within the payload?

**Comment by GuidoNeele** [comment]
Did a test yesterday while having the debugger running and Shiny projects attached. Sent a RAW notification from the Azure Notification Hub "Test Send" page and waited for the app to receive the notification. 

![Sending raw notification from Azure Notification hub](https://crisisconnect.nl/assets/images/notification-hub.png)

After receiving it in code I see the following:

![Debugger](https://crisisconnect.nl/assets/images/code.png)

Will test the other versions of Windows test messages tomorrow.

**Comment by GuidoNeele** [comment]
Tried the other options today. Sending the raw notification is the only option that will trigger the PushNotificationBackgroundTaskProcessor.

**Comment by aritchie** [comment]
@GuidoNeele please give the myget version a try to see if this solves things for you

**Comment by GuidoNeele** [comment]
Thanks Allan. I'm on holiday right now so could take a couple of weeks before I post the results.
