### ISSUE TITLE
AppCenterLogging is writing entries twice

### ISSUE THREAD

**Issue by dfarrNTST** [shinyorg/shiny#271]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x ] .NET Standard

## Feature Library

 - [x ] Core
 - [x ] AppCenter Logging

## Version of Library
1.1.0.1473

## Version of OS(s) listed above with issue
iOS, Android

## Steps to Reproduce
1. Create solution
2. Add Shiny NuGets
3. Add latest AppCenter NuGet packages, including Crashes and Analytics
4. UseAppCenterLoggin(keys, true, true)
5. Deploy app through AppCenter
6. Log.Write
7. The log entry shows up twice each time.

## Expected Behavior
The log entry should only show up once.

## Actual Behavior
Thelog entry shows up twice.

**Comment by aritchie** [comment]
Can you please add more detail to this?  Where are you seeing double logs?  A specific delegate?  Are you calling Log.Write manually?

**Comment by dfarrNTST** [comment]
> 
> 
> Can you please add more detail to this? Where are you seeing double logs? A specific delegate? Are you calling Log.Write manually?

Sorry for the delay...we've been trying to narrow it down.  It only appears to be happening in Android and only when we have multiple Android Bindings projects. (Works fine with the same code in iOS)  

We are using UseDebug, UseConsole, and UseAppCenterLogging...we do call Log.Write manually from within our own AppLogger class and we see the double entries in AppCenter and the Console in each of them.  When we debug it we do see that our AppLogger.LogToLoggersAsync method is only called once...it is the one that calls the Shiny.Logging.Log.Write method.  We've verified that there is only one singleton instance of our AppLogger in the DI.  We have verified that we only specify the Use extension methods once at startup, so we aren't doubly adding those.    We've tried removing UseDebug and UseConsole and it doesn't have an effect, still logs twice into AppCenter.  It does this in Debug mode and in Release mode on Android.

If we create a new solution and put in the same setup without Bindings projects...it works fine.  None of our logging is happening in the Bindings projects, so we're not sure why it would be happening with just Android Binding projects being referenced.

It's difficult to create a repro solution since the java code that we are Binding around is a 3rd party SDK we have purchased.

Does this give you any ideas or is there something we can do to further debug it on our side?

**Comment by aritchie** [comment]
I have been through the code to ensure nothing is double logging.  This is also something I have not experienced.  I'm afraid without a reproducible sample, there isn't much I can do to help.

**Comment by dfarrNTST** [comment]
Understood.  We've removed Shiny and are calling AppCenter directly and it resolves the double posting...so we'll just have to go without Shiny for now.

**Comment by aritchie** [comment]
Well that's a shame.  Perhaps you can tell me what you were using Shiny logging for?  Where was the double logging was showing up?  You don't need to log in shiny delegates because I do it for you.  

I really need some sort of details here.

**Comment by dahlbyk** [comment]
> We are using UseDebug, UseConsole, and UseAppCenterLogging...we do call Log.Write manually from within our own AppLogger class and we see the double entries in AppCenter and the Console in each of them. [snip] We've tried removing UseDebug and UseConsole and it doesn't have an effect, still logs twice into AppCenter. It does this in Debug mode and in Release mode on Android.

If you're also seeing double entries in the console, it sounds like you might be initializing Shiny twice. @dfarrNTST, can you share more about how you're initializing Shiny?

**Comment by dfarrNTST** [comment]
@dahlbyk This was the first thing we checked...we are initializing the same way defined in the Shiny github and how we use it in other Xamarin apps.  As mentioned above, this works fine with this same application running on iOS (no double posts)...it only occurs when running this particular Bindings app on Android.

**Comment by dfarrNTST** [comment]
@aritchie We aren't using any delegates, just a wrapper class around Log.Write that we use to filter out log parameters that we send to AppCenter.  This same pattern works in other apps with no double posting...the only different factor for this app is the Bindings projects.  And this same app doesn't double post on iOS...and its the same in other apps where it doesn't double post on iOS or Android, so we believe how we have it coded is fine.

**Comment by dahlbyk** [comment]
> This same pattern works in other apps with no double posting...the only different factor for this app is the Bindings projects. And this same app doesn't double post on iOS...and its coded/initialized the same in other apps we have where it doesn't double post on iOS or Android, so we believe how we have it coded is fine.

Hard to troubleshoot without any sort of repro. Could you try adding something like this after you call `UseAppCenterLogging()`?

```csharp
try
{
    throw new Exception("Shiny!");
}
catch (Exception ex)
{
    Log.Write(ex);
}
```

I'm hoping this will confirm double-initialization in your logs, hopefully with some sort of clue in the stack trace(s) as to what's going on.
