### ISSUE TITLE
Selecting Notification content does nothing when a NotificationCategory are supplied

### ISSUE THREAD

**Issue by jaredballen** [shinyorg/shiny#274]
## Platform

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [X] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1473

## Version of OS(s) listed above with issue
Tested against Android API 25 - 29

## Steps to Reproduce
1. Call UseNotifications in Shiny startup with a NotiifcationDeleglate class and a supply a NotificationCategory.
2. Create a new Notification and set its Category property to the identifier specified in the NotificationCategory from 1.
3. Send the notification created in 2.
4. Tap the notification content when it appears in the Android notification area

## Expected Behavior
Tapping the notification content or on an action in the notification should cause OnEntry to be called in the NotificationDelegate.

## Actual Behavior
OnEntry is not called in the NotificationDelegate when the notification content is tapped.

**Comment by jaredballen** [comment]
The appears to be an issue in the Android NotifcationManager. If a category is supplied with the notification, then SetContentIntent is never called on the notification builder.

**Comment by aritchie** [comment]
Fixed for 1.2
