### ISSUE TITLE
[UWP] NotificationManage.Cancel(int id) does not delete the notification

### ISSUE THREAD

**Issue by bruzkovsky** [shinyorg/shiny#278]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1473

## Version of OS(s) listed above with issue
Win10 1809

## Steps to Reproduce
1. create notification `await _notifications.Send(new Notification{ Id = id, ... });`
2. notification is shown
![image](https://user-images.githubusercontent.com/10390959/78782240-f8dab600-79a1-11ea-9ef7-00006e7fcd95.png)
3. cancel notification `await _notifications.Cancel(id)`
4. .... nothing happens. it was not very effective!

## Expected Behavior
notification should go away

## Actual Behavior
notification stays and inbox is gradually flooding

**Comment by bruzkovsky** [comment]
I will try to put up a PR when I find the time. From looking through the implementation, it seems to be just not implemented.

**Comment by aritchie** [comment]
UWP is still a bit of a second class citizen, but I am working to resolve this.  I can fix this one up pretty quick but it will have to be part of 1.2

**Comment by bruzkovsky** [comment]
Great to hear that! I can wait for 1.2.
