### ISSUE TITLE
UWP - Shiny.Notifications - Publish Release build fails

### ISSUE THREAD

**Issue by BrayanKhosravian** [shinyorg/shiny#281]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [x] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Sensors

## Version of Library
Shiny.Notifications Version: 1.1.0.1473
## Version of OS(s) listed above with issue
Target Version:      Windows 10, 1809 (10.0; Build 17763)
Minimum Version: Windows 10 Fall Creators Update (10.0, Build 16299)

## Steps to Reproduce
1. Create an uwp project
2. import shiny.Notifications 1.1.0.1473
3. Associate with the App store
4. Publish a package

**I only tested it that way for now. But the issue should also occur when enabling the `.Net toolchain compiler` and `optimize code` in the uwp properties. This are the defaul configurations when publishing an app to the microsoft store**

## Expected Behavior
The build/publish should not fail

## Actual Behavior
The publish/build fails with this error message:
![image](https://user-images.githubusercontent.com/35541212/79220572-890e7480-7e54-11ea-8657-bd2f742701ec.png)

**Comment by BrayanKhosravian** [comment]
Some developers had a similar issue with another framework. And it seems like the issue always ocured when a library uses code generation, which is not supported when using the `.NetNativeToolChain`.

**Comment by BrayanKhosravian** [comment]
FYI @bruzkovsky  @gentledepp

**Comment by aritchie** [comment]
I'm sorry - this doesn't actually have anything directly to do with this library.
