### ISSUE TITLE
Shiny Location: Add Support to monoandroid 10 (AndroidX)

### ISSUE THREAD

**Issue by hardikphd** [shinyorg/shiny#282]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Shiny.Core already supports monoandroid 10 but Shiny.Location does not
Due to that we are not able to upgrade Xamarin Forms to 4.5+.

## API Changes
Add Support of monoandroid 10 to Shiny Location Package

## Intended Use Case
We should be able to use latest Xamarin.Forms and Xamarin Essential

**Comment by dansiegel** [comment]
can confirm... looking at the Shiny.Location.csproj it's missing the actual monoandroid10.0 target, but it's already setup with an item group to bring in Xamarin.AndroidX.Core

**Comment by aritchie** [comment]
@hardikphd It doesn't block you from upgrading to XF or AndroidX.  There is a migration package that moves everything in the support packages.  This will come in a future release, but is currently blocked by some missing functionality required for Google Play Services

**Comment by aritchie** [comment]
This is now in the beta channel, but cannot be released until Xamarin moves their nugets out of preview
