### ISSUE TITLE
Azure Notification Hubs getting multiple registrations

### ISSUE THREAD

**Issue by dansiegel** [shinyorg/shiny#287]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors
 - [x] Push

## Version of Library

Shiny.Push.AzureNotificationHubs 1.1.0.1473-beta

## Version of OS(s) listed above with issue

iOS 13.4.1
Android 9

## Steps to Reproduce
1. Install Shiny.Push.AzureNotificationHubs
2. Initialize it in the Startup
3. Go to the Device Registrations after a few times running it.

## Expected Behavior

Each test device should show up once

## Actual Behavior

The Devices are registered repeatedly.

**Comment by aritchie** [comment]
Are you calling RequestAccess each time as well?  I assume so, just want to be sure.

**Comment by dansiegel** [comment]
So the code I have is as follows:

```cs
public class MyStartup : PrismStartup
{
    protected override void ConfigureServices(IServiceCollection services)
    {
        services.UsePushAzureNotificationHubs<PushDelegate>(
            Secrets.NotificationHubsConnectionString,
            Secrets.NotificationHubName
        );
    }
}
```

Then in the service that I need to access the Registration Token I have:

```cs
var access = await _pushManager.RequestAccess();
var token = _pushManager.CurrentRegistrationToken;
```

**Comment by aritchie** [comment]
This should be resolved in the latest beta.
