### ISSUE TITLE
CentralManager WhenStatusChanged not triggered

### ISSUE THREAD

**Issue by lfongaroScp** [shinyorg/shiny#288]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [*] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [*] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
Shiny.BluetoothLE 1.1.0.1473-beta
(downloaded trough NuGet)

## Version of OS(s) listed above with issue
Android 10.
I test it on a Nokia 7 Plus with Android One 10  updated to March 2020.

## Steps to Reproduce
0. Create an App in Xamarin.Android (not Xamarin Forms!) and  register BleCentrail in your custom Application
1. In the MainActivity get a reference to centralManager, check you have the permission to use bluetooth.
2. subscribe to WhenStatusChanged observable

## Expected Behavior
Trigger when bluetooth adapter change status (off/on)

## Actual Behavior
Trigger only one time. If the user enable or disable the bluetooth the observable do not trigger

I am not sure if it is related to #195.

**Comment by aritchie** [comment]
Please include some sort of sample.  Note that your subscription could be getting tombstoned with the activity.  You should be recreating it with onresume

**Comment by lfongaroScp** [comment]
Hi,
I have only one activity when I test it. I simply check if I the app have all needed permissions, if this is true I subscribe to WhenStatusChanged() (if not I asked the permission and redo the check after the user grant it). That's all. 
Unfortunately I have no time to create a sample. For my current project I'm using your old bluetooth library (it does not have this bug)

**Comment by wagenheimer** [comment]
Sorry for bringing this back! 

But for Android.

```
   BleManager.WhenStatusChanged().Subscribe(async stat =>
            {
                System.Diagnostics.Debug.WriteLine("BleManager changed to state " + stat);
            }
```

The Notification is not being called when Disabling/Enabling the Bluetooth on the phone.

**Comment by aritchie** [comment]
@wagenheimer try the delegate version first.  If you are still having an issue, file a proper bug with all of the necessary details please.
