### ISSUE TITLE
Gatt is empty in already connected peripherals

### ISSUE THREAD

**Issue by twsl** [shinyorg/shiny#291]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [x] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1473-beta

## Version of OS(s) listed above with issue
Android 10

## Steps to Reproduce
1. Use BLE central and peripherals
2. Load connected peripherals
3. check peripherals.context.Gatt

## Expected Behavior
Gatt beeing not null or having an exception thrown

## Actual Behavior
Gatt is null, no exception is thrown and further calls like peripheral.DiscoverServices() will fail

---
Load services
```csharp
services.UseBleCentral();
services.UseBlePeripherals();
```

Load connected peripherals
```csharp
_connectedDisposable = _centralManager.GetConnectedPeripherals().Subscribe(scanResult =>
            {
                Console.WriteLine("GetConnectedPeripherals results");
                scanResult.ToList().ForEach(
                 item =>
                 {
                     Console.WriteLine(item.Name);
                     if (!string.IsNullOrEmpty(item.Name))
                     {
                         var vm = new PeripheralItemViewModel(item);
                         Peripherals.Add(vm);
                     }
                 });

                _connectedDisposable?.Dispose();
            });

            if (_centralManager.IsScanning)
                _centralManager.StopScan();
```

**Comment by aritchie** [comment]
You aren't using the library properly at all.  You don't touch the context or the gatt object directly.  You should wait until the docs are done or look at the sample code before using this library

**Comment by twsl** [comment]
I did not intend to use the Gatt object directly. I just got an exception [here](https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Central/Platforms/Android/Peripheral.cs#L90)  and I noticed, that the Gatt property was null.

I did check the sample code, but I guess I'll wait untill docs are done.

**Comment by twsl** [comment]
Seems to be an Android related problem with `this.NativeDevice.connectGatt`

**Comment by aritchie** [comment]
@twsl a few things - this module is in beta. 

- You are welcome to submit PRs
- Your original issue is not an issue.  You still have to issue a connection to the GATT.  Please do not keep posting on a closed issue
- The docs are not done as I’ve said.  I’m one person and this project is quite large.
- This is not a support form.  The code is open for you to participate in fixing and benefiting from the end result
