### ISSUE TITLE
[Bug] Background job UWP not triggered?

### ISSUE THREAD

**Issue by GuidoNeele** [shinyorg/shiny#30]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [X] UWP
 - [ ] .NET Standard

## Feature Library

 - [X] Core (Jobs)
 - [ ] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
V1.0.0.264-beta

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
No steps

## Expected Behavior
Background job to run once every X minutes

## Actual Behavior
Background job never called by system

Should the implementation of jobs for UWP work at the moment or is there still work to be done? We played around with the background jobs for a while but haven't seen the UWP background job run. Saw some TODO comments in the code so was curious if the current implementation actually works for UWP. https://github.com/shinyorg/shiny/blob/379bacfdb6406fbf76b372319e3f5fcc101416e2/src/Shiny.Core/Platforms/Uwp/UwpShinyHost.cs#L32

Thanks! Like the framework.

**Comment by aritchie** [comment]
Hi Guido - I appreciate the interest in Shiny.  During the beta period, I need test cases with bug reports.  Please refrain from questions until the library is out of beta.  Have you debugged the case with the code you've found?
