### ISSUE TITLE
Shiny.BluetoothLE, can't not connection, not trigger Peripheral.WhenStatusChanged

### ISSUE THREAD

**Issue by 92-Theo** [shinyorg/shiny#307]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ O ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ O ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
Shiny.BluetoothLE v1.1.0.1473-beta
## Version of OS(s) listed above with issue
Android 9: LG V30

## Steps to Reproduce
1. Connected  (auto connect) with Peripheral
2. Bluetooth turn off  on Mobile Setting
3. Trigger not working (Peripheral.WhenStatusChanged), but ConnectionState is already changed.
4. Peripheral turn off or Move to a distance not connected to the Peripheral
5. Bluetooth turn on on Mobile Setting
6. Peripheral turn on or Move to a distance connected to the Peripheral
7. It's impossible to connect again.

if I wanna connect
- i have to connect others peripheral and  reconnect
- Restart app

I was tried to test on Anroid10(Galaxy Note 9), Android9(Galaxy Note 8, LG V30)
It only happens on V30.

**Comment by aritchie** [comment]
Please include code samples especially with the beta libraries

**Comment by 92-Theo** [comment]
It's my sample code.

this code i include 'BluetoothAdapter.ActionStateChanged' Receiver.

https://github.com/92-Theo/Demo-Xamarin-Ble-Shiny

**Comment by 92-Theo** [comment]
After turn Bluetooth off and on

I don't think this library has any problems with connectivity.
Because, my equipment is not connected, but other equipment is connected.


However, CentralManager.WhenStatusChanged () and Peripheral.WhenStatusChanged () do not work.

**Comment by 92-Theo** [comment]
> Please include code samples especially with the beta libraries

Hello, There is issue on only LG V30 Mobile when mobile BT turn off.
It's solve that scanning again and connect on scanning peripherals.

But this lib is not solve for me.

How can I solve this issue?

first video is issue and solve :  https://cafe.naver.com/kindplayer

**Comment by aritchie** [comment]
The library can’t solve this issue for you.  The device cache is cleared when the radio is turned off.

Please don’t treat this as a support channel.  I’m not hear to answer how-tos.
