### ISSUE TITLE
Global Logging Variables

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#308]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
As stated in the description

## API Changes
Shiny.Logging.Log.GlobalVariables = Dictionary<string, string> ?

## Intended Use Case
Automatically pass to each log statement as necessary

**Comment by dahlbyk** [comment]
It could be interesting for this to be either a `Func<Dictionary<>>` or resolve one or many `ILogVariableProvider` to allow DI/composition.

**Comment by aritchie** [comment]
I'm a big fan of DI until it gets to logging.  Since there is so many things that can go wrong in the wiring process, I wanted logging to be static.  I also wanted it to be relatively simple.  

I think my goal will be to mix the global vars with the incoming contextual vars and pass them through to the providers, thus negating the need for additional implementation.
