### ISSUE TITLE
[Enhancement] StartupTask as async

### ISSUE THREAD

**Issue by diegostamigni** [shinyorg/shiny#31]
## Summary
Any reason why there's no StartAsync in IStartupTask? Or maybe an additional IStartupAsyncTask ?

## API Changes
IStartupTask.StartAsync or additional IStartupAsyncTask with StartAsync

## Intended Use Case
Some startup tasks can be async.

**Comment by aritchie** [comment]
I've been debating this.  Right now, I'm pretty against doing this because you only get a few seconds in certain background scenarios.  Startups needs to be almost instant (no async).  The jobs themselves can take a bit longer though.

**Comment by aritchie** [comment]
Ya - it is just too dangerous to open this up.  Startup tasks were intended to wire up to external events and such.  They aren't intended for infrastructure initialization because they need to happen without any perf hit.
