### ISSUE TITLE
In Shiny.BluetoothLE.Central manufacturerId have chance to get ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wuhuangjia** [shinyorg/shiny#312]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [V] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [V] BluetoothLE
 - [V] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
Shiny.BluetoothLE
Version="1.1.0.1570-beta" 

## Version of OS(s) listed above with issue
Android 10.0

## Steps to Reproduce
1. Turn on Bluetooth on the phone
2. open your app which using Shiny.BluetoothLE or Shiny.Beacon
3. and sometimes APP will crash

**Comment by wuhuangjia** [comment]
After check the Shiny.BluetoothLE.Central's sourcecode, the ManufacturerSpecificData maybe have to check count is > 0

**Comment by aritchie** [comment]
Please don't post things without full repos.  If the issue already exists in the sample app, I will get to it when I get to it!
