### ISSUE TITLE
Shiny.BLE can not find Epson printer

### ISSUE THREAD

**Issue by hudaIT** [shinyorg/shiny#313]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

Please feel free to close this issue when its irrelevant.
We can not find Epson printer with the shiny ble sample project.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [X] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1570-beta
## Version of OS(s) listed above with issue
Android 10
Android 8.1

## Steps to Reproduce
1. Turn on an epson TM-M30 bluetooth printer
2. Scan for the devices on Central Shiny sample project
3.

## Expected Behavior
TM-M30 bluetooth printer should be found

## Actual Behavior
TM-M30 bluetooth printer can not be found in the list

**Comment by aritchie** [comment]
Please don't open issues just by using the samples ESPECIALLY on the beta components.
