### ISSUE TITLE
UWP Partner Center report "stowed_exception"

### ISSUE THREAD

**Issue by DevEddy** [shinyorg/shiny#317]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [x] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Sensors

## Version of Library
`<PackageReference Include="Shiny.Notifications" Version="1.1.0.1570" />`
## Version of OS(s) listed above with issue
I think everywhere, but I don't know exactly.

## Steps to Reproduce
I don't know exactly know why this is reported in the UWP partner center. App center doesn't report this one. 

## Expected Behavior
No errors are reported, I guess.

## Actual Behavior
Following error is reported viaUWP partner center:
`stowed_exception_system.exception_80070718_cloudmatic.uwp.dll!shiny::jobs::jobmanager.schedulenative`
![image](https://user-images.githubusercontent.com/7648336/82224203-de421800-9923-11ea-802f-41845f88c545.png)
![image](https://user-images.githubusercontent.com/7648336/82224326-00d43100-9924-11ea-9805-f6ecbd68158d.png)

StackTrace:
```
0	System.Private.Interop.dll	System::Runtime::InteropServices::McgMarshal.ThrowOnExternalCallFailed	0x0000000000000021	
1	CloudMatic.UWP.McgInterop.dll	__Interop::ComCallHelpers.Call	0x00000000000000BE	
2	CloudMatic.UWP.McgInterop.dll	__Interop::ForwardComStubs.Stub_4_System.__Canon,_System.__Canon_	0x0000000000000037	
3	Shiny.Core.dll	Shiny::Jobs::JobManager.ScheduleNative	0x00000000000001C7	
4	Shiny.Core.dll	Shiny::Jobs::AbstractJobManager::_Schedule_d__25.MoveNext	0x000000000000004A	
5	SharedLibrary.dll	System::Runtime::ExceptionServices::ExceptionDispatchInfo.Throw	0x0000000000000021	
6	SharedLibrary.dll	System::Runtime::CompilerServices::TaskAwaiter.ThrowForNonSuccess	0x0000000000000070	
7	SharedLibrary.dll	System::Runtime::CompilerServices::TaskAwaiter.HandleNonSuccessAndDebuggerNotification	0x0000000000000038	
8	SharedLibrary.dll	System::Runtime::CompilerServices::TaskAwaiter.ValidateEnd	0x0000000000000017	
9	SharedLibrary.dll	System::Runtime::CompilerServices::TaskAwaiter.GetResult	0x000000000000000B	
10	Shiny.Core.dll	Shiny::JobExtensions::__c__DisplayClass1_0::__RegisterJob_b__0_d.MoveNext	0x00000000000000BE	
```
The app and the notifications are working fine (for me in debug and release). I don't know if it's important for you, just wanted to let you know.

-- Eddy

**Comment by aritchie** [comment]
I need something actionable and reproducible.  The above stack isn't giving me any details for something actionable
