### ISSUE TITLE
SQLite.TableQuery Member access failed to compile expression 

### ISSUE THREAD

**Issue by sunilbraj369** [shinyorg/shiny#318]
Getting SQLite.TableQuery Member access failed to compile expression, while registering Async Table query

public AsyncTableQuery<AppStateEvent> AppStateEvents => this.Table<AppStateEvent>();

i have also checked issues from others and updated to SQLConnection(path,false), deleted any DateTime column in table still getting the same error.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors
 - [x] SQLite

## Steps to Reproduce
1. Just run your Samples project for Xamarin. Just cant boot the sample !
2.
3.

## Expected Behavior
Able to see the App running

## Actual Behavior
App Crashes on startup

**Comment by aritchie** [comment]
Please don’t file bugs against the samples.  They are samples and constantly evolving.

**Comment by sunilbraj369** [comment]
Allan, it is to reproduce that i have mentioned the samples. While using Shiny in my app am facing this issue. Do you have a solution for this yet?

**Comment by aritchie** [comment]
@sunilbraj369 A solution to what?  SQLite isn't used by Shiny.  Don't ask if I have a solution "yet" please.  I'm not here to solve things for you.

**Comment by sunilbraj369** [comment]
Sure,Allan. Uninstalled Shiny from my project after-all it never solves things for us! but just wasting time man.

**Comment by aritchie** [comment]
@sunilbraj369 you're banned from this project.  You're wasting my time.  I have no idea what you programming issue was since there was no stacktrace to work with and certainly, your attitude is quite rude.
