### ISSUE TITLE
[Bug] Android Geofence NullReferenceException

### ISSUE THREAD

**Issue by dahlbyk** [shinyorg/shiny#32]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.268-beta

## Version of OS(s) listed above with issue
9

## Steps to Reproduce
1. Create Geofence with ShinySample

## Expected Behavior
Successful notification.

## Actual Behavior
![Screenshot_20190715-223255](https://user-images.githubusercontent.com/133987/61266453-8e218480-a759-11e9-8c69-7b07f87b854d.png)
(A copy error button in the sample would be handy!)

**Comment by dahlbyk** [comment]
I see you pushed a fix for the NRE. Anything I can do to help troubleshoot?

**Comment by aritchie** [comment]
Fixed for next release.  It will drop on the samples in the next day or so if you want to test it for yourself.  

Thanks for the issue report
