### ISSUE TITLE
Shiny 1.1 Implementation of Shiny.AndroidShinyHost.Init

### ISSUE THREAD

**Issue by burrowj** [shinyorg/shiny#320]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.1
## Steps to Reproduce
1.Create a project NOT using Shiny.ShinyAndroidApplication
2. Add other components as per 
https://allancritchie.net/posts/shiny11

2. In the OnCreate method try and implement Shiny.AndroidShinyHost as per docs
https://shinydocs.azurewebsites.net/docs/gettingstarted

## Expected Behavior
Allow implementation of Shiny.AndroidShinyHost or
ShinyHost.Init as per error

## Actual Behavior
Does not allow Shiny.AndroidShinyHost

An error occurs on startup
Container has not been setup - have you initialized the Platform provider using ShinyHost.Init?

When i try and use ShinyHost.Init there is no Init method on ShinyHost

It seems that the option of not using the Shiny.ShinyAndroidApplication in the case that you already have your own has been disabled.

**Comment by aritchie** [comment]
The docs are not done.  Follow the samples

**Comment by aritchie** [comment]
AndroidShinyHost does exist for Android 9+ targets of you are going with your own application

**Comment by burrowj** [comment]
I am using 10 but will have another look

I did try and find a sample that doesn't use Shiny.ShinyAndroidApplication and couldn't find one.  Maybe you could tell me which one please

**Comment by burrowj** [comment]
I did a search for AndroidShinyHost in all samples provided and could not find one so I assume there are none.  Maybe it would be worth adding one for those not using the Shiny.ShinyAndroidApplication

**Comment by aritchie** [comment]
@burrowj I'm pretty busy with things.  This isn't intended to be a support channel.  You are welcome to scan the source code for what you need.  It all exists.  AndroidShinyHost.Init is there.  You can also look at the ShinyAndroidApplication source code and see how it calls init under the hood.
