### ISSUE TITLE
Android DownloadManager doesn't support http POST

### ISSUE THREAD

**Issue by Csaba8472** [shinyorg/shiny#322]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [x] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1570

## Version of OS(s) listed above with issue
API Level 9 - 29

## Steps to Reproduce
1. Create a HttpTransferRequest, set PostData and HttpMethod
`           new HttpTransferRequest("ur-to-POST", "file")
            {
                PostData = "data",
                HttpMethod = HttpMethod.Post
            };
`
2. Enqueue the request
3. You can see in Charles, that on iOS it will be a POST request but on Android it will be a GET because [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager)'s http method can't be changed.

## Expected Behavior
Both on Android and on iOS http request should be sent as it was set in HttpMethod parameter.

## Actual Behavior
On iOS it behaves correctly but on Android it will be a GET request(because of android API limitation).

**Comment by aritchie** [comment]
If you're telling me that the API from google doesn't support post, what are you expecting me to change here?

**Comment by Csaba8472** [comment]
Please don't take it personal, I really appreciate that you put a lot of effort in shiny! :)

It's an API design question but if you ask me, I'd throw an exception when someone tries to set different http method on android because it is not supported. But it's up to you and if you'd like to I can help somehow.

**Comment by aritchie** [comment]
I'm not taking it personally.  I need actionable things to come in via issues or these just become noise.

I will throw an exception going forward.
