### ISSUE TITLE
Registering for characteristic notifications not working on UWP

### ISSUE THREAD

**Issue by teebrin** [shinyorg/shiny#323]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [x] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [x] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.1182-beta

## Version of OS(s) listed above with issue
Windows 10 Pro 1909 version 18363.836

## Steps to Reproduce
1. Obtain an IGattCharacteristic from a connected IPeripheral
2. Call var notifyHandle = characteristic.Notify().Subscribe(AResultHandler, AnErrorHandler);
3. Keep notifyHandle reference

## Expected Behavior
Should register to device's characteristic notifications

## Actual Behavior
Does not regiser to device's characteristic notifications

Note that it works very well on both Android ans iOS. Looking at Shiny.BluetoothLE source code, it feels like there is a lot of code commented out in https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Central/Platforms/Uwp/GattCharacteristic.cs

**Comment by aritchie** [comment]
It's a beta - it isn't done yet
