### ISSUE TITLE
PerformFetch Delegate

### ISSUE THREAD

**Issue by suppenburger** [shinyorg/shiny#325]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Similar do the other app state delegates which are already available it would be useful to have one for AppDelegate.PerformFetch.

## API Changes
Extend IAppStateDelegate interface

## Intended Use Case
Log when/how often PerformFetch is executed, to know how "reliable" functionality is which depends on it.

**Comment by aritchie** [comment]
The appstate delegate isn't meant for this point of integration.  PerformFetch is also an iOS only event.  I'd suggest plugging your own logging point in there if you are interested in tracking fire times.

**Comment by suppenburger** [comment]
Thank you for the quick response. Because I trigger “critical” jobs in different ways (background fetch, silent notifications, geo fencing), I thought it might be useful to know which of them triggers the job and how often. Can I distinguish if a job was triggered by background fetch or manually?

**Comment by aritchie** [comment]
No - there is no way to distinguish out of the box with Shiny.  You could set some sort of static variable that the job can see.

**Comment by suppenburger** [comment]
Thank you. I guess I will experiment with job parameters. Maybe I can use them for those which are manually triggered.
