### ISSUE TITLE
Getting not yet cached item from SQLite throws an exception

### ISSUE THREAD

**Issue by JeremyBP** [shinyorg/shiny#326]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP

## Feature Library (beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!)

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] Push (beta)
 - [x] SQLite Integration (beta)

## Version of Library
Last

## Version of OS(s) listed above with issue
Last

## Steps to Reproduce
1. services.UseSqliteCache() on Startup
2. var result = this.cache.Get< Foo >(bar);

## Expected Behavior
result should be default(Foo) as we did never set any value for bar key.

## Actual Behavior
throws an exception (Sequence contains no element...)

## Suggested fix
[Here](https://github.com/shinyorg/shiny/blob/36cf3ced65bd5a4cf671b99c08eac3110373555a/src/Shiny.Integrations.Sqlite/SqliteCache.cs#L32) is the problem.
We call the [GetAsync](https://github.com/praeclarum/sqlite-net/blob/9a66dc7a711781cbf5bee8a142d29bd57830203f/src/SQLiteAsync.cs#L730) SQLite method wich throws the exception as it is supposed to do when no object found for this key.
Instead, we should call [FindAsync](https://github.com/praeclarum/sqlite-net/blob/9a66dc7a711781cbf5bee8a142d29bd57830203f/src/SQLiteAsync.cs#L785) wich returns null as expected.

**Comment by aritchie** [comment]
Merged
