### ISSUE TITLE
Getting item from repository cache throws an exception

### ISSUE THREAD

**Issue by JeremyBP** [shinyorg/shiny#330]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP

## Feature Library (beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!)

 - [x] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] Push (beta)
 - [ ] SQLite Integration (beta)

## Version of Library
Last

## Version of OS(s) listed above with issue
Last

## Steps to Reproduce
1. services.UseRepositoryCache() in Startup
2. this.cache.Set< Foo > (fooKey, fooValue); => success
3. then this.cache.Get< Foo >(fooKey); => success
4. restart app
5. this.cache.Get< Foo >(fooKey) => invalid cast exception

## Expected Behavior
Should return fooValue in my example

## Actual Behavior
throws an invalid cast exception as we try to cast to Foo an object wich could be of Foo type (during same session), but also a json serialized string of fooValue (further app sessions).

## Suggested fix
The problem comes from [here](https://github.com/shinyorg/shiny/blob/36cf3ced65bd5a4cf671b99c08eac3110373555a/src/Shiny.Core/Caching/RepositoryCache.cs#L35) with direct cast of an object to T type.
We should check if object is of T type or deserialize it.

**Comment by aritchie** [comment]
Thanks for another great PR
