### ISSUE TITLE
Gps doesn't get location in the background

### ISSUE THREAD

**Issue by JuanNinos** [shinyorg/shiny#339]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1686
## Version of OS(s) listed above with issue

Android 8.0, 9.0 and 10

## Steps to Reproduce
1. Install and setup the Shiny.Locations
2. Use the WhenReading from IGpsManager to trigger the execution of a method
3. Put the app in background

**Heres some code samples from my project**

**Method where i start the gps reading:**

```
 protected async void StartLocationReading()
        {
            try
            {
                if(Shiny.ShinyHost.Resolve<IGpsManager>() != null)
                {
                    await Shiny.ShinyHost.Resolve<IGpsManager>().RequestAccess();

                    await Shiny.ShinyHost.Resolve<IGpsManager>().StartListener(new GpsRequest
                    {
                        UseBackground = true,
                        Priority = GpsPriority.Highest,
                        Interval = TimeSpan.FromSeconds(15),
                        ThrottledInterval = TimeSpan.FromSeconds(3)
                    });

                    gpsDisposable = Shiny.ShinyHost.Resolve<IGpsManager>().WhenReading().Subscribe(LocationWasRead);
                }
            }
            catch (Exception ex)
            {
                App.ErrorLog(ex);
            }
        }
```

**The definition of the method that's called when the gps is read:**

```
private async void LocationWasRead(IGpsReading reading)
{
      //Some code
}
```

**My Shiny Startup Class:**

```
public class ApplicationShinyStartup: ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            services.UseGps();
        }
    }
```

**My android shiny class:**

```
    [Application]
    public class DroidShiny: ShinyAndroidApplication<ApplicationShinyStartup>
    {
        public DroidShiny(IntPtr handle, JniHandleOwnership transfer) : base(handle, transfer)
        {

        }
    }
```

## Expected Behavior

Read the gps location and execute the method, either in foreground or background

## Actual Behavior

For the android versions stated above, the gps stops reading the location and don't execute the method when the app enters in background mode.

This doesn't happen on the android version 7.0 though, it works just fine there. Also, maybe it's good to know that i use emulators for my tests, and my target is android 10.

**Comment by aritchie** [comment]
You use GPS delegates to read in the background.  The WhenReading is for foreground only

**Comment by JuanNinos** [comment]
Thanks for the help! But even with the delegate the same issue occurs, the delegate (named OnReading) is not called when the app is on the background, even with the new android permission for android 10+. It only works on the android 7

```
public class ApplicationShinyStartup: ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            services.UseGps<MyGpsDelegates>();
        }
    }
```

```
 public class MyGpsDelegates: IGpsDelegate
        {

            public Task OnReading(IGpsReading reading)
            {
                    //Do something when in background
            }

        }
```

**Comment by aritchie** [comment]
Read the android documentation please.
