### ISSUE TITLE
[Bug] Geofence events not triggered on Android

### ISSUE THREAD

**Issue by tomglanville** [shinyorg/shiny#34]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.264-beta

## Version of OS(s) listed above with issue
9 (Pie)

## Steps to Reproduce
1. Setup Android for geofencing as per: https://allancritchie.net/posts/shiny-geofencing
2. Alternatively use geofence sample here: https://github.com/shinyorg/shinysamples
3. Run on emulator and change location or run on physical device and mock location

## Expected Behavior
Geofence event triggered (in the example it displays a notification). I have verified that the notifications work in isolation to this issue.

## Actual Behavior
No geofence event triggered.

**Comment by dahlbyk** [comment]
Following on from #32, I can confirm that the NRE error I _was_ getting is gone (which seemed to happen when geofence triggers should have been firing), but I now get nothing at all using 1.0.0.272-beta.

**Comment by dahlbyk** [comment]
@aritchie glad to help troubleshoot this, if you can point me in a direction. Seems likely to be related to the recent async chanages: https://github.com/shinyorg/shiny/commits/master/src/Shiny.Locations/Platforms/Android/GeofenceBroadcastReceiver.cs

**Comment by aritchie** [comment]
@dahlbyk I don't really have any direction to give at this time.  I just have to get in and debug what's going on.

**Comment by dahlbyk** [comment]
Confirmed with Shiny Sample. Thanks for another quick fix!
