### ISSUE TITLE
Use Microsoft.Extensions.Logging.Abstractions instead custom logger abstraction

### ISSUE THREAD

**Issue by Shumigaj** [shinyorg/shiny#340]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
It would be cool to use common logging abstraction [Microsoft.Extensions.Logging.Abstractions.](https://github.com/aspnet/Logging/tree/master/src/Microsoft.Extensions.Logging.Abstractions) 
I can't see any reasons against it:
- The size of the library is small ~48KB;
- It has only one dependency from .NETStandard;
- Application eventually will have the dependency from Microsoft.Extensions.Logging.Abstractions (e.g. after installation of EF Core or other Microsoft libraries that uses logging)

## API Changes
Replace ILogger from Shiny.Core to ILogger from Microsoft.Extensions.Logging.Abstractions.dll
Current implementation can be moved to Shiny.Logging if customers decide it has enough functionality.

## Intended Use Case
- The consumers of your library can use the logging framework that they love and want. For example Serilog has many different small modules that can be combined depending on the requirements of the application (e.g. log to SQLite, file, external service, console NSLog/AndroidLog...). So it is possible to even analyze application performance by logs information. The disadvantage is the abstraction itself has version.

I want to hear your opinion about it because I new in the Xamarin world and can miss something.

**Comment by aritchie** [comment]
There are several arguments against it right now.  

* I still need base implementation for logging (which I could do myself).  
* People tend to pull in Microsoft.Extensions.Logging which has a rather large dependency train behind it.  There are also places that I need logging before DI has finished.  
* Shiny.Logging.Log does allow you to insert your own custom logging as well
* I need logging before DI is finished in a bunch of cases
