### ISSUE TITLE
cannot find RegisterStartupTask in IServiceCollection  

### ISSUE THREAD

**Issue by SalimiHabib** [shinyorg/shiny#342]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] iOS
 - [ x] Android
 - [ x] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

## Feature Library 
startup task

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ x] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2
## Version of OS(s) listed above with issue
android 

## Steps to Reproduce
1.make a new class for startup task 
2.try to use registerstartuptask in shiny startup
3.

## Expected Behavior
extension method not found in shiny core

## Actual Behavior
error in code

**Comment by aritchie** [comment]
Obviously it doesn't exist anymore.  Look at the source code.  This is not a support forum.
