### ISSUE TITLE
Could not install package 'Shiny.Core 1.2.0.1686'.

### ISSUE THREAD

**Issue by fabioaraujoo** [shinyorg/shiny#351]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [X] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1686
## Steps to Reproduce
1 - Search for Shiny no Nuget - VS 2019
2 - Select Shiny.Core
3 - Select Projects IOs, Android, Laptop

## Expected Behavior
Installation complete

## Actual Behavior

Good Morning!

I am trying to start using Shiny and received the following error message when installing Core:

Could not install package 'Shiny.Core 1.2.0.1686'. You are trying to install this package in a project that is intended for '.NETPortable, Version = v4.5, Profile = Profile111', but the package does not contain any assembly references or content files that are compatible with this structure. For more information, contact the author of the package.

"Não foi possível instalar o pacote 'Shiny.Core 1.2.0.1686'. Você está tentando instalar este pacote em um projeto que se destina a '.NETPortable,Version=v4.5,Profile=Profile111', mas o pacote não contém nenhuma referência de assembly ou arquivo de conteúdo que seja compatível com essa estrutura. Para obter mais informações, entre em contato com o autor do pacote."

Is it a known issue? Is there a known solution?

**Comment by aritchie** [comment]
PCL is not supported by this project.  You need .netstandard 2
