### ISSUE TITLE
[Android] [AzureNotifications] Registered tags get reset

### ISSUE THREAD

**Issue by GuidoNeele** [shinyorg/shiny#352]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [X] Push
 - [X] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1686

## Version of OS(s) listed above with issue
All supported Android versions

## Steps to Reproduce
1. Set tags = ["tag1", "tag2"]
2. Request access with tags
3. Push token is received and tags are stored in settings with key "RegisteredTags"
4. Request access again with tags (separate session or right after doesn't matter)
5. Token isn't renewed which is correct (this.IsRefreshNeeded == false) but RegisteredTags is set to null

## Expected Behavior
RegisteredTags should remain the same if push token needs refreshing or not.

## Actual Behavior
RegisteredTags is reset on Android when a request for access is made multiple times.

This problem can be easily fixed by calling base.RequestAccess(tags) instead of base.RequestAccess() (at https://github.com/shinyorg/shiny/blob/be3999fc9e8c1bd1c4323b0af9c6c3343242a0e4/src/Shiny.Push.AzureNotificationHubs/Platforms/Shared/PushManager.cs#L75).

```csharp
#if __ANDROID__
  base.RequestAccess(tags)
#else
  base.RequestAccess()
#endif
```

But doing so raises a question. Is it ideal/wanted to manage tags in Azure Notification Hub and at the same time manage topics in Google Firebase? It shouldn't really matter that it's happening but I did run into an issue where the validation format for topics is different then the validation for tags in Azure Notification Hub. Firebase topics allow [a-zA-Z0-9-_.~%]{1,900} and for Azure NH the tag format is [a-zA-Z0-9-_.@#:]{1,120}.

**Comment by GuidoNeele** [comment]
Was looking at the code some more and saw that https://github.com/shinyorg/shiny/blob/be3999fc9e8c1bd1c4323b0af9c6c3343242a0e4/src/Shiny.Push.AzureNotificationHubs/Platforms/Shared/PushManager.cs#L138 is creating a difference between the registered Firebase topics and Azure NH tags, since the base method isn't called.

**Comment by GuidoNeele** [comment]
Think the best way is to edit https://github.com/shinyorg/shiny/blob/master/src/Shiny.Push/Platforms/Android/PushManager.cs and let RequestAccess(cancelToken) do what it needs to do on Android. That way tags and topics don't interfere with each other and the Android base PushManager can still be used from ANH without issues.

```csharp
public override Task<PushAccessState> RequestAccess(CancellationToken cancelToken = default) {
    var result = await FirebaseInstanceId
                .Instance
                .GetInstanceId()
                .AsAsync<IInstanceIdResult>();

   this.CurrentRegistrationToken = result.Token;
   this.CurrentRegistrationTokenDate = DateTime.UtcNow;
   FirebaseMessaging.Instance.AutoInitEnabled = true;

    return new PushAccessState(AccessState.Available, this.CurrentRegistrationToken);
}

public virtual async Task<PushAccessState> RequestAccess(string[] tags, CancellationToken cancelToken = default)
{
    var state = this.RequestAccess(cancelToken);

    await this.UpdateTags(tags);

    return state;
}
```

**Comment by aritchie** [comment]
This has already mostly been fixed in dev.  Please try the myget package

**Comment by GuidoNeele** [comment]
Sorry didn't see your reply just pushed a pull request. Will try the myget package. Thanks for the quick reply.

**Comment by GuidoNeele** [comment]
Just tried the MyGet package but a null reference exception is thrown on line https://github.com/shinyorg/shiny/blob/be3999fc9e8c1bd1c4323b0af9c6c3343242a0e4/src/Shiny.Push.AzureNotificationHubs/Platforms/Shared/PushManager.cs#L141. 
This is caused by calling base.RequestAccess() from AzureNotifications without the tags. This causes the base method to call RequestAccess(null, cancelToken) which is calling this.UpdateTags(null) on line https://github.com/shinyorg/shiny/blob/48f361cdfe69a5c28029ecc69ccf74a9c374c343/src/Shiny.Push/Platforms/Android/PushManager.cs#L61. UpdateTags() in AzureNotifications PushManager needs a null check on tags.

**Comment by GuidoNeele** [comment]
Thought about it some more. 

If a null check is added to Shiny.Push.AzureNotifications (SPAN) UpdateTags() the method would still be called to soon.

```csharp
 public async Task UpdateTags(params string[] tags)
{
    var install = await this.hub.GetInstallationAsync(this.InstallationId);
    install.Tags = tags?.ToList() ?? new List<string>(); // Change
    await this.hub.CreateOrUpdateInstallationAsync(install);
    this.CurrentRegistrationTokenDate = DateTime.UtcNow;

    this.RegisteredTags = tags;
}
```
This would result in two problems:

- The very first time someone calls SPAN RequestAccess(tags) the InstallationId will be null when updating the tags. Since it's called from the base method before the installation is actually saved. 
- It would result in removing the tags from Azure Notifications Hub when SPAN IsRefreshNeeded() is false in later calls to SPAN RequestAccess(tags). 

Adding a null check on tags (see below) in Shiny.Push.Android (SPA) RequestAccess(), before calling UpdateTags(), also isn't a solution because removing all tags is a valid call. 

```csharp
public virtual async Task<PushAccessState> RequestAccess(string[] tags, CancellationToken cancelToken = default)
{
    ...
    this.CurrentRegistrationToken = result.Token;
    this.CurrentRegistrationTokenDate = DateTime.UtcNow;
    FirebaseMessaging.Instance.AutoInitEnabled = true;

    if(tags != null)  // Change
       await this.UpdateTags(tags);
    ...
}
```

I don't see how you can solve these issues (keeping tags in sync on Azure Notification Hubs) without splitting the SPA RequestAccess() method in two like this:

```csharp
public override async Task<PushAccessState> RequestAccess(CancellationToken cancelToken = default){
    var nresult = await this.notifications.RequestAccess();
    if (nresult != AccessState.Available)
        return new PushAccessState(nresult, null);

    var result = await FirebaseInstanceId
        .Instance
        .GetInstanceId()
        .AsAsync<IInstanceIdResult>();

    this.CurrentRegistrationToken = result.Token;
    this.CurrentRegistrationTokenDate = DateTime.UtcNow;
    FirebaseMessaging.Instance.AutoInitEnabled = true;

    return new PushAccessState(AccessState.Available, this.CurrentRegistrationToken);
}

public virtual async Task<PushAccessState> RequestAccess(string[] tags, CancellationToken cancelToken = default)
{
    var state = await this.RequestAccess(cancelToken);

    await this.UpdateTags(tags);

    return state;
}
```

**Comment by pnda489** [comment]
Hi, 
i just tried your sample. I am also using Azure Notification Hub. 
Your sample is working for me but i can't resolve the IAzureNotificationHub Interface with the ShinyHost to use the "Update" method. Is this by design?

**Comment by GuidoNeele** [comment]
Hi Michael,

Please don't pollute this issue with comments that should be separate issues. 

If Shiny AzureNotifications integration doesn't completely provide what you need then why don't you create a connection with the hub yourself? You can use the InstallationId from Shiny by reading the setting via ISettings["InstallationId"]. 

Please don't post on this issue anymore.

**Comment by pnda489** [comment]
> Hi Michael,
> 
> Please don't pollute this issue with comments that should be separate issues.
> 
> If Shiny AzureNotifications integration doesn't completely provide what you need then why don't you create a connection with the hub yourself? You can use the InstallationId from Shiny by reading the setting via ISettings["InstallationId"].
> 
> Please don't post on this issue anymore.

Sorry for that, just saying that the "dev" Package is working for me beside the resolving of the IAzureNotification interface. It is working for Android and iOS also with updating the tags, though this can help to solve your problem.
But sure, i will stay out of it and no longer "pollute" it
Cheers

**Comment by GuidoNeele** [comment]
I'm sorry I completely misunderstood your comment. It came about as if you were using this issue to get your own question answered.

**Comment by aritchie** [comment]
@pnda489 Not sure what interface you are speaking of.  I do tend to use marker interfaces that are not part of the dependency injection scheme.  

@GuidoNeele while I appreciate that you are trying to help, please let me police the issues as needed.  

The resolution to this issue is to remove the complexity between updating tags and requesting access with tags.  There will be an extension that does this in two steps, but not in the native implementations.

**Comment by GuidoNeele** [comment]
Yes moving it from the native implementations to the extension made it a lot less complex and error prone.
Just tested the myget version and it worked. Thanks!

**Comment by aritchie** [comment]
Thanks @GuidoNeele for the update.  Much appreciated and glad it is fixed.  Trying to get this pushed to production in the next couple of days
