### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by lnaie** [shinyorg/shiny#353]
Leave Your Message Below (don't delete this line though)

Nice work, thanks for that!

I'm testing the Location feature, and unfortunately it appears that the samples are broken, on master, on VS for mac with the latest. It used to work in the early days. :) Sometimes is the nugets, other times some api code changes. I will eventually figure it out, but it will take extra time.

I think this situation could be improved by creating another branch for experiments and keeping the master working. It should also help with adoption. No alpha/beta nuges in master. :)

Thanks again

**Comment by aritchie** [comment]
I'm not worried about adoption.  The samples are mostly my experiments to continue working on the project going forward.
