### ISSUE TITLE
String Settings not persisted

### ISSUE THREAD

**Issue by MarManiak** [shinyorg/shiny#357]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [X] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [X] SQLite Integration

## Version of Library
1.2.0.x

## Version of OS(s) listed above with issue
ALL

## Steps to Reproduce
1. use shinysample project, make sure UseSqliteSettings is active
2. on the settings page, try to change the text value and save the setting

## Expected Behavior
the text should be saved in the "StringValue" field of the "YourText" row

## Actual Behavior
the StringValue field of the YourText row contains a null

## Proposed Fix
The problem appears to be a single missing test in the SetValue method of the SettingStore class.  I did a quick test and duplicated just the Shiny.Integrations.Sqlite project as a child project in my own solution (changed the namespaces to local namespaces) and then changed the dependency to use my local version instead of the nuget package.  The only change I made was to add the following

            else if (value is string v13)
                this.StringValue = v13;

in the SetValue() method and added 

            this.StringValue = null;

to the Reset() method.  With those changes in place, the string settings are being stored as expected in the SQLite database.

**Comment by aritchie** [comment]
Thanks for the issue
