### ISSUE TITLE
Resolving IGeofenceManager in Geofence Delegate causes crash

### ISSUE THREAD

**Issue by layinka** [shinyorg/shiny#36]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [x ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.264-beta 
## Version of OS(s) listed above with issue
Android 8

## Steps to Reproduce
1. Enable Geofence in Startup class 
2. Create a BackgroundJob
3.Try to Resolve IGeofenceManager

## Expected Behavior
Should resolve to Singleton instance of IGeofenceManager

## Actual Behavior
Application crashes

[Stacktrace.txt](https://github.com/shinyorg/shiny/files/3425497/Stacktrace.txt)

**Comment by aritchie** [comment]
Please include proper details like the library version and a stack trace

**Comment by layinka** [comment]
Edited to include library version and stack trace

**Comment by aritchie** [comment]
Please try to always be on the latest version during the beta period before filing issues.  The latest beta on nuget is 1.0.0.280-beta.  There were a bunch of issues fixed in 280.  

Also, please provide as much detail as humanly possible instead of it having to be requested otherwise this becomes noise which doesn't help the purpose of the beta.  Your shiny startup and background job code would be helpful.  Using the geofencemanager in the background job sounds a bit off, so I need to make sure I understand what you're telling me.

**Comment by layinka** [comment]
Alright,

Here is what i am trying to achieve.

I have an application that needs to monitor more than the maximum 50(or 20 on IOS) geofences, I want to use a background job that tracks the users location to update the geofences to the closest 50 anytime the background job runs.

Here is my Shiny Startup code

```
public override void ConfigureServices(IServiceCollection services)
        {
            // custom logging
            Log.UseConsole();
            Log.UseDebug();            
            // create your infrastructure
            services.AddSingleton<PABeacon.PASqliteConnection>();
            services.AddSingleton<CoreDelegateServices>();
            services.RegisterStartupTask<GlobalExceptionHandler>();
            services.AddSingleton<IUserDialogs, UserDialogs>();

            

            services.RegisterSettings<IAppSettings, AppSettings>("AppSettings");

            services.UseBeacons<BeaconDelegate>();

            services.UseGeofencing<GeoFenceDelegate>();
            services.UseNotifications();
            
            var geoFenceJob = new JobInfo
            {

                Identifier = "GeoFenceJob",
                Type = typeof(UpdateGeofencesJob),
                BatteryNotLow = true,
                DeviceCharging = false,
                RequiredInternetAccess = InternetAccess.Any,
                Repeat = true

            };

            services.RegisterJob(geoFenceJob);


            Services = services;
        }
```

and here is the relevant background job code (the constructor)

```
public UpdateGeofencesJob(CoreDelegateServices services)
        {
            this.services = services;
            
            this.notifications = ShinyHost.Resolve<INotificationManager>();

            _conn = ShinyHost.Resolve<PABeacon.PASqliteConnection>() ;
			_geofenceManager = ShinyHost.Resolve<IGeofenceManager>();

        }
```

**Comment by aritchie** [comment]
Please make sure you are always running the latest beta.  I'm constantly fixing and tweaking things during this time frame.

As an FYI, you need to request permissions to use the geofences at some point.  Changing them in the background isn't advised and may result in errors (especially on iOS).

**Comment by layinka** [comment]
I uodated to the latest beta (1.0.0.280-beta) and got this error


> Unhandled Exception:
> 
> System.InvalidOperationException: A circular dependency was detected for the service of type 'Shiny.Locations.IGeofenceManager'.
> Shiny.Locations.IGeofenceManager(Shiny.Locations.GeofenceManagerImpl) -> Shiny.Locations.IGeofenceDelegate(PABeacon.ShinyDelegates.GeoFenceDelegate) -> Shiny.Locations.IGeofenceManager occurred

**Comment by aritchie** [comment]
I see what is happening.  You are sending the geofence manager to your geofence delegate and looking at your previous stack trace, this is what was happening to.  You really shouldn't do this because the delegate is resolved internally on the geofence manager (hence the circular reference).  Is there a particular reason why you're doing it?

**Comment by aritchie** [comment]
So for the next release, you can inject the geofence manager into your geofence delegate.  I'm still curious about your use-case for it though.
