### ISSUE TITLE
[Android] Version 10(Q) throwing error "System.ArgumentException: 'Invalid State Denied'" 

### ISSUE THREAD

**Issue by jitendrajadav** [shinyorg/shiny#365]
Upgrading android 10(Q) while asking "**allow access only when the app is running**" permission it;s throw error like below
"System.ArgumentException: 'Invalid State Denied'"

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

 - [ ] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of OS(s) listed above with issue
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 3.1
VisualStudio.16.Preview/16.7.0-pre.3.1+30223.230
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA694
Microsoft Visual C++ 2019

Visual Basic Tools   3.7.0-3.20312.3+ec4841263590f5456e32728d98097e97c1605e22
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20304.1+7673d5e78eca5bccb77a7e4561c9d9429bdc5f35
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.
VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.422 (master@0a3dcd1)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.468 (remotes/origin/d16-7@2f2289ee2)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.45 (e4142aa)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.4.0.0 (d16-7/de70286)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 87ef555
    Java.Interop: xamarin/java.interop/d16-7@76d1ac7
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   13.20.1.18 (8ffa3d888)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

## Steps to Reproduce
1. Take existing ShinyPrisamSample Application with master branch
2. Upgrade to Version 10(Q) and update all package from Manage NuGet Packages
3. it will ask you to add Xamarin.AndroidX.MediaRouter and run the application

## Expected Behavior
It shouldn't return error 

## Actual Behavior
Throwing erorr
System.ArgumentException
  Message=Invalid State Denied

Please check sample [ShinyPrismSample](https://github.com/jitendrajadav/ShinyPrismSample.git)

Please check error screenshot 
![image](https://user-images.githubusercontent.com/1029026/86330864-ea7cfd00-bc65-11ea-8922-d630a9fc5f95.png)

**Comment by aritchie** [comment]
Nowhere in your code are you using RequestAccess to get permissions from the user
