### ISSUE TITLE
IBleManager scanning while the phone is locked

### ISSUE THREAD

**Issue by bodeg** [shinyorg/shiny#366]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [x] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755

## Version of OS(s) listed above with issue
Android 9.0

## Steps to Reproduce
1. call  IBleManager.Scan
2. lock the phone (screen off/ sleep)
3. new BLE peripheral is not discovered by IBleManager.

## Actual Behavior

**Question**: Should the IBleManager continue scanning when the phone is locked? 
or the BLE is still under work?

Thanks for the great library.
I am trying to move from BluetoothLE.Plugin.

**Comment by aritchie** [comment]
Please read the Android documentation.  Support is given to project sponsors only and the betas (as noted in the issue template) require reproducible samples.  However, this is not a big which the Android docs will tell you
