### ISSUE TITLE
WritingService is not able to Write on IOS

### ISSUE THREAD

**Issue by Codelisk** [shinyorg/shiny#368]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

We have issues on Ios where the WritingService is not able to print on bluetooth printer on ios.

**How we search for WritingService:**

```
private Task SetWritingService()
        {
            WritingService = null;
            try
            {
                serviceScan = CurrentConnectedDevice
                    .DiscoverServices()
                    .Subscribe(OnDiscoverServiceChanged);
            }
            catch (Exception e)
            {
                Crashes.TrackError(e, new Dictionary<string, string> { { "Bluetooth Periperhal Crash", "" + CurrentConnectedDevice?.Name } });
                _userDialogs.AlertAsync(Strings.Bluetooth, Strings.BluetoothConnectionLost);
            }

            return Task.CompletedTask;
        }
```

```
 private void OnDiscoverServiceChanged(IGattService service)
        {
            service.DiscoverCharacteristics()
                .Finally(TrackWritingServiceReference)
                .Subscribe(OnCharacteristicChanged);
        }
```
```
private void OnCharacteristicChanged(IGattCharacteristic characteristic)
        {
            //also tried with characteristic.CanWrite();
            bool canWriteWithoutResponse = characteristic.CanWriteWithResponse() || characteristic.CanWriteWithoutResponse();

            // read, write, or subscribe to notifications here
            if (characteristic == null)
                return;

            WritingService = characteristic;
            if (canWriteWithoutResponse)
            {
                serviceScan.Dispose();
            }
        }
```

**Here is how we write:**

```
public async Task Write(byte[] value)
        {
            try
            {
                if (value?.Length > 0)
                {
                    TaskCompletionSource<bool> tcs = new TaskCompletionSource<bool>();
                    _prismDeviceService.BeginInvokeOnMainThread(async () =>
                    {
                        int counter = 0;
                        List<byte> newByteList = new List<byte>();

                        foreach (byte item in value)
                        {
                            newByteList.Add(item);
                            counter++;
                            if (counter > 10)
                            {
                                try
                                {
                                    await WritingService.Write(newByteList.ToArray(), false);
                                    newByteList = new List<byte>();
                                    counter = 0;
                                }
                                catch (Exception e)
                                {
                                    Crashes.TrackError(e, new Dictionary<string, string> { { "Failed Writing: ", "" + counter } });
                                }
                            }
                        }
                        if (newByteList?.Count > 0)
                        {
                            try
                            {
                                await WritingService.Write(newByteList.ToArray());
                            }
                            catch (Exception e)
                            {
                                Crashes.TrackError(e, new Dictionary<string, string> { { "Failed Writing last: ", "" + counter } });
                            }
                        }
                        tcs.SetResult(true);
                    });
                    await tcs.Task;
                }
                else
                {
                    throw new ArgumentNullException();
                }
            }
            catch (Exception)
            {
                await _userDialogs.AlertAsync(Strings.BluetoothSomethingWrongPlsTryAgain);
            }
        }
```
**It works like it is supposed to work on Android devices, however it doesnt write on ios.**

Thank you very much

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X ] iOS
 - [ ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

## Feature Library
Shiny.BLE

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [X ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755-beta

## Version of OS(s) listed above with issue
all ios

## Steps to Reproduce
1. Scan for Characteristics which can Write (CanWrite())
2. Try to use the WritingService to print on Printer
3.

## Expected Behavior
Should print

## Actual Behavior
Can not print

**Comment by aritchie** [comment]
Questions
1) How do you know that that is the characteristic you write to that will print?  
2) what is the full exception stack trace for the write failure?

**Comment by Legacyorder** [comment]
1. Till now I thought the CanWrite() function tells me whether I can print or not. Would you suggest looking for something else too?

2. Yeah I will attach soon

**Comment by Codelisk** [comment]
1. Till now I thought the CanWrite() function tells me whether I can print or not. Would you suggest looking for something else too?

2. Yeah I will attach soon

**Comment by aritchie** [comment]
1) No.  You have to remember this library has NOTHING to do with printers.  CanWrite is whether or not the characteristics supports it.  You may have many characteristics that support write in a service.  You need to refer to the documentation on your peripheral as this is something I can't help with.

Honestly, the exception is probably irrelevant at this point.  It will likely be the peripheral rejecting the write for some reason.
