### ISSUE TITLE
[External Issue - Shiny.Prism] Locations stopped work after update to 1.2.0.1755

### ISSUE THREAD

**Issue by felipebaltazar** [shinyorg/shiny#369]
Hi! firstly thanks for this amazing library!
I'm a community helper and I created some examples for shiny with Prism, so after updating the package (Shiny.Locations) I got an unexpected behavior... I've linked my repository that can be used to reproduce this issue.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [ ] UWP

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

1.2.0.1755

## Version of OS(s) listed above with issue
- Android 9 | Samsung S8+
- iOS 13.5 | Iphone simulator

## Steps to Reproduce
1. Configure a custom delegate for GPS
2. Call `StartListener`
3. No location updates are shown

To reproduce this issue:

- [Not working at this branch with 1.2.0.1755](https://github.com/felipebaltazar/ShinyAndPrismSample/tree/update-shiny-locations)
- [Working on branch master with 1.1.0.1570](https://github.com/felipebaltazar/ShinyAndPrismSample)

## Expected Behavior

[That can be reproduced at master branch](https://github.com/felipebaltazar/ShinyAndPrismSample)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19656249/87441729-d15f3f00-c5c9-11ea-866c-2c17ab9e9c19.gif)

## Actual Behavior

[That can be reproduced at update-shiny-locations branch](https://github.com/felipebaltazar/ShinyAndPrismSample/tree/update-shiny-locations)

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/19656249/87441947-15eada80-c5ca-11ea-8e0d-8cb32c6da612.gif)

**Comment by aritchie** [comment]
Shiny now uses multiple delegates under the hood which caused some issues for Shiny.Prism which is an external module to this project.  You can follow https://github.com/dansiegel/Prism.Container.Extensions/issues/124

**Comment by aritchie** [comment]
In any case, you are doing  a ton of extra work to show GPS in the foreground.  You should simply use IGpsManager.WhenReading().Subscribe(position => ...) 

You should only use delegates for when your app is in the background

**Comment by felipebaltazar** [comment]
> Shiny now uses multiple delegates under the hood which caused some issues for Shiny.Prism which is an external module to this project. You can follow [dansiegel/Prism.Container.Extensions#124](https://github.com/dansiegel/Prism.Container.Extensions/issues/124)

Thanks! I will check it!

> In any case, you are doing a ton of extra work to show GPS in the foreground. You should simply use IGpsManager.WhenReading().Subscribe(position => ...)
> 
> You should only use delegates for when your app is in the background

Yeah! thanks for your feedback! This is a part of some posts that I'm creating to explain about Observable Pattern and show for some developers some principles (yeah very basic 😁) for `EventAggregator` and `Reactive Extensions`

**Comment by dahlbyk** [comment]
> > Shiny now uses multiple delegates under the hood which caused some issues for Shiny.Prism which is an external module to this project. You can follow [dansiegel/Prism.Container.Extensions#124](https://github.com/dansiegel/Prism.Container.Extensions/issues/124)
> 
> Thanks! I will check it!

There's a relatively simple workaround here: https://github.com/shinyorg/shiny/issues/359.
