### ISSUE TITLE
[Bug] Shiny.Testing is inconsistent

### ISSUE THREAD

**Issue by dansiegel** [shinyorg/shiny#38]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard
 - [x] .NET Core App (Testing)

## Feature Library

 - [x] Core
 - [x] BluetoothLE
 - [x] Beacons
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library

1.0.0.280-beta

## Version of OS(s) listed above with issue

netcoreapp3.0

## Steps to Reproduce

1. Create a Unit Test Project
2. Install Shiny.Testing
3. Write test to validate that your delegates are registered with the container

## Expected Behavior

1. Expected IShinyStartup in the ShinyTestHost
1. Expected IGpsDelegate to be Registered
1. Expected IGeofenceDelegate to be Registered
1. Expected IBeaconDelegate to be Registered
1. Expected IBleAdapterDelegate to be Registered
1. Expected TestGpsManager to be Registered 
1. Expected TestGeofenceManager to be Registered
1. Expected some sort of something to be Registered for BLE
1. Expected some sort of something to be Registered for Beacons

The first issue is stupid simple to fix... the next 4 on the Delegates it would just be good to have some sort of consistency... as for the last few... I might propose that the ShinyTestHost does something like:

```cs
public static void Init(IShinyStartup startup, Action<IServiceCollection> platformBuild = null)
{
    Shiny.Locations.ServiceCollectionExtensions.RegisterGpsPlatform = s => s.AddSingleton<IGpsManager, TestGpsManager>();
    Shiny.Locations.ServiceCollectionExtensions.RegisterGeofencePlatform = s => s.AddSingleton<IGeofenceManager, TestGeofenceManager>();

    InitPlatform(startup, services =>
    {
        // no changes
    });
}
```

This would allow you to update the behavior in the registration calls for the netstandard target so that if the Register action has been set you can invoke it and return true instead of always return false.

## Actual Behavior

1. ShinyTestHost requires something that inherits from ShinyStartup not it's root interface IShinyStartup
1. IGpsDelegate is never registered as the base call to [UseGps is called first](https://github.com/shinyorg/shiny/blob/master/src/Shiny.Locations/Platforms/Shared/ServiceCollectionExtensions.cs#L59-L62) and always returns false for netstandard/netcoreapp 
1. IGeofenceDelegate is registered... as the delegate is registered before we do [any sort of checks to return false](https://github.com/shinyorg/shiny/blob/master/src/Shiny.Locations/Platforms/Shared/ServiceCollectionExtensions.cs#L11-L21) in the registration extension. 
1. IBeaconDelegate is never registered. Like the GpsDelegate, we check the [root registration (Use Beacons)](https://github.com/shinyorg/shiny/blob/master/src/Shiny.Beacons/Platforms/Shared/ServiceCollectionExtensions.cs#L42-L47) first thereby never getting to the AddSingleton for the Delegate
1. IBleAdapterDelegate is registered... In this case the Shiny registration extension is a simple wrapper for [services.AddSingleton](https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Platforms/Shared/ServiceCollectionExtensions.cs#L16-L18) thereby allowing the delegate to be registered...
1. TestGpsManager is not registered as it seems there's no hook to get this automatically as part of the UseGps
1. TestGeofenceManager is not registered for the same reason as the GpsManager
1. Upon further examination of the registration call for the BleAdapterDelegate it makes sense nothing more would be registered here...
1. It seems there are no mocks in place in general for the Beacons yet.

**Comment by aritchie** [comment]
I don't usually test with dependency injection.  Right now, the testing library is a bunch of mocks and it isn't all completed yet.

**Comment by dansiegel** [comment]
I fully understand it's not flushed out yet... obviously the piece I'm most interesting in validating is that the Prism tie in is properly integrating. That said kind of hard when the pieces that are there are a little inconsistent in behavior.

**Comment by aritchie** [comment]
I'm actually going to be removing the ShinyTestHost.  The testing library was only ever designed to be a bunch of mocks.  I don't believe in testing with the DI in place especially when it comes to xplat since the registrations are different anyhow.  The beacon manager will be in place for the next beta.
