### ISSUE TITLE
[Shiny.Jobs] Job stopped work after open camera

### ISSUE THREAD

**Issue by gcomm-trile** [shinyorg/shiny#382]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [x] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755
## Version of OS(s) listed above with issue
Android 10 | Galaxy Note 10+

## Steps to Reproduce
1. Configure a custom delegate for Job (YourFirstJob)
2. Call Schedule(YourFirstJob) => YourFirstJob is running and repeat after 30 seconds. 
3. Call Take Capture (using Xam.Plugin.Media) =>ok
4. YourFirstJob was stopped after step 3.=> Shiny.Logging.Log: don't have anything output
To reproduce this issue: 
[My test](https://github.com/gcomm-trile/shiny_job_test)

## Expected Behavior
Job still running after capture photo using camera
## Actual Behavior
Job was stopped after capture photo using camera

**Comment by aritchie** [comment]
What do you mean "Job was stop"?  Do you have output from the Shiny.Logging.Log?  You need to have a small sample with no external libs if you want me to look at it.  

Honestly, these are two libraries that don't touch on any points.

**Comment by gcomm-trile** [comment]
> What do you mean "Job was stop"? Do you have output from the Shiny.Logging.Log? You need to have a small sample with no external libs if you want me to look at it.
> 
> Honestly, these are two libraries that don't touch on any points.

Thank you for your reply. "Job was stop" means my schedule job was stopped and Shiny.Logging.Log was empty after I take photo from camera. If i don't take photo action, my schedule job still running and repeat. Here is [sample](https://github.com/gcomm-trile/shiny_job_test)

**Comment by aritchie** [comment]
The job will resume.  It’s likely going to the background because it’s running temporarily as a foreground job.  I’m not sure why you feel this is a bug
