### ISSUE TITLE
[Android]Bluetooth LE - Enable Notification doesn't work

### ISSUE THREAD

**Issue by ARobertus** [shinyorg/shiny#383]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [x] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
v1.2.0.1755-beta
## Version of OS(s) listed above with issue
Android 7.0

## Steps to Reproduce
1. Connect to Peripheral using ConnectWait() - works fine
2. Discover all Services & Characteristics - works fine
3. Try to enable notification on a characterisitc with subscribtion with no success - here's the problem

## Expected Behavior
CharacterisitcResultType NotificationSubscribed should be posted

## Actual Behavior

Step 3. Try to Enable Notification
![Shiny_BLE_EnableNotification](https://user-images.githubusercontent.com/68987718/88893294-6d35af80-d246-11ea-89c8-a434a9e43180.PNG)

I don't get any event on this.
After setting the notifications with nordic connect it works fine (once for this connection).

**Comment by aritchie** [comment]
Please read the instructions in the issue template otherwise this will be closed

**Comment by ARobertus** [comment]
Hi, sorry but this is my first issue i wrote.

I uploaded my project:
https://github.com/ARobertus/BLE_Test.git

Did I miss something else?

**Comment by aritchie** [comment]
You aren’t trapping any errors in that subscribe.  Are there any underlying log messages?

**Comment by ARobertus** [comment]
There are no errors or log messages, without the notification enabled i can't receive data from my peripheral right? Maybe i am using the wrong function or somethine else is wrong in my code.

**Comment by aritchie** [comment]
I have no idea.  I don't have your peripheral.  You need to deal with exceptions in your subscribe.  

This is working on my devices right now.  You are doing a bunch of weird things though:

1) You aren't storing the subscription anywhere so it could very well be GC'd
2) while (dump_data.Count == 0) ; is odd and could be blocking the thread from progressing.


Please note that this is not a support area.  You very likely will have to debug your issue and point to a definitive issue.

**Comment by ARobertus** [comment]
Thank you for your help, i will change my code...
it should work so there is at the moment no issue
