### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by sunshineV9** [shinyorg/shiny#387]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

We wanted to implement the bluetooth library into our app, but experiencing issues on our release configuration.
Maybe you can give us a suggestion on how to fix this.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [x] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

Shiny.BluetoothLE: 1.2.0.1755-beta

## Version of OS(s) listed above with issue

Android 9
Android 10

## Steps to Reproduce
1. Set Configuration to Release
1. Set Linker Settings to Sdk Assemblies Only and code shrinker to r8
1. Compile, Deploy and Start App on any Device or Emulator
1. App crashes on direct startup

## Expected Behavior<

- App should start without crash

## Actual Behavior

App crashes with following exception:

`Java.Lang.RuntimeException: 'Unable to get provider androidx.work.impl.WorkManagerInitializer: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer" on path: DexPathList`

**Comment by Csaba8472** [comment]
r8 removes classes under androidx.work, which is a [known issue](https://stackoverflow.com/a/52657305). You can use proguard to keep them.

**Comment by TheObliterator** [comment]
I'm encountering the same issue but unable to resolve.
@Csaba8472 you are spot on here - If I disable R8 linking the app with Shiny Jobs works. I'd be grateful if you could provide more details how to resolve or point me in the right direction as the Shiny lib looks excellent for what I need!

I've tried adding a ProGuard.cfg file to the android project (and set the build properties to ProGuard Configuration) with the following:
-keep class androidx.work.** { *; }

But that doesn't seem to help. 

I've also tried setting the linker to use ProGuard instead but Xamarin tells me its not supported with D8 compiler (and the DX/ProGuard settings are no longer optimum if I understand correctly).

My only solution at the minute is to disable the linker shrinking completely which obviously is less than ideal.

Many thanks

**Comment by TheObliterator** [comment]
Found the solution, its seems a couple of classes needed to be excluded from the R8 pruning - not just the Work class.

For anyone else encountering this problem:
1. Add a new text file ProGuard.cfg to the root of your Android project.
2. Configure the properties of the file and set the Build Action to ProGuard Configuration.
3. Add the following lines to the ProGuard.cfg file:
```
# Force the R8 linker to keep some factory initializer classes used by Shiny
# This configuration step shouldn't be necessary but is required to workaround a known issue with the R8 linker:
# https://github.com/shinyorg/shiny/issues/387
# https://github.com/xamarin/xamarin-android/issues/4908
# https://stackoverflow.com/questions/52657196/android-work-manager-could-not-instantiate-worker/52657305#52657305

-keep class androidx.lifecycle.ProcessLifecycleOwnerInitializer
-keep class androidx.work.impl.WorkManagerInitializer
```
4. I also had to add the Xamarin.AndroidX.RecyclerView NuGet package to my Android project to avoid a build error whilst linking (you may not need to do this).
5. Clean and rebuild the project and you should be good to go.

Hopefully this is helpful to anyone else encountering the issue.
Finally, huge thanks to the Shiny authors. I'm using the job scheduler and its saved me a ton of time!
