### ISSUE TITLE
[Bug] BluetoothAdapter.ActionStateChanged does not work anymore (API 26)

### ISSUE THREAD

**Issue by ThumbGen** [shinyorg/shiny#39]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ X] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library

independent

## Version of OS(s) listed above with issue

Starting with Android 8.0 (API 26)

## Steps to Reproduce
1. Try to use the .WhenStatusChanged method

## Expected Behavior

When switching Bluetooth On and Off on the phone, the handler should be called.

## Actual Behavior

The handler is not called at all.

For details see: [Documentation](https://developer.android.com/guide/components/broadcast-exceptions)

I found no alternative to this yet :(

**Comment by aritchie** [comment]
On the adapter or the device?  I don’t understand what isn’t working for you

**Comment by aritchie** [comment]
And if you’ve found no alternative to this problem, what are you suggesting I do with this

**Comment by ThumbGen** [comment]
Hm, I think this can be closed, I need to try on more adapters to be sure. Sorry.
