### ISSUE TITLE
services.UseBleHosting() Does Not Inject IBleHostingManager

### ISSUE THREAD

**Issue by eopeter** [shinyorg/shiny#391]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X ] iOS
 - [ ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [X ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [X] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.1940

## Version of OS(s) listed above with issue
13.5

## Steps to Reproduce
1. IN Shiny Sample, Attempt to Access GATT Server link
2.
3.

## Expected Behavior
Should load the GATT Server page in Shiny Sample

## Actual Behavior
Does not load and no message displayed. In my App, I get an error that cannot find IBleHostingManager

**Comment by aritchie** [comment]
This is not ready for prime time yet and is actively being worked on
