### ISSUE TITLE
[Android] [BluetoothLE] Write to GattCharacteristic fails when should succeed

### ISSUE THREAD

**Issue by rogerjak** [shinyorg/shiny#392]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [x] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.1956-beta

## Version of OS(s) listed above with issue

Android

## Steps to Reproduce
1. Connect to peripheral
2. Get a service/characteristic
3. Write to the characteristic

## Expected Behavior
Success

## Actual Behavior
Exception

The bug is in this commit:  "Fixed signed writes" da70979c744707a7cb279845d860c69932400e9c
src/Shiny.BluetoothLE/Platforms/Android/GattCharacteristic.cs
You seem to have inverted the "if (args.IsSuccessful)" code (line 47-57).

**Comment by aritchie** [comment]
Fixed in next build - thanks
