### ISSUE TITLE
iOS Background Jobs crashes on distribution profiles

### ISSUE THREAD

**Issue by Kiitoksia** [shinyorg/shiny#398]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [x] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755
## Version of OS(s) listed above with issue
13.6
12.4

## Steps to Reproduce
1. Create a project utilising scheduled background jobs. 
2. Distribute in release mode, with a distribution certificate.
3. Call IJobManager.Run(job)

## Expected Behavior
Job successfully runs in background.

## Actual Behavior
Device instantly crashes.  Upon looking at the device log, the only log that seems relevant is
```
Can't get most elevated app state from dictionary {
    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "com.COMPANY.YOUR.APP";
    SBApplicationStateKey = 0;
    SBApplicationStateProcessIDKey = 911;
    SBApplicationStateRunningReasonsKey =     (
                {
            SBApplicationStateRunningReasonAssertionIdentifierKey = Resume;
            SBApplicationStateRunningReasonAssertionReasonKey = 10000;
        },
                {
            SBApplicationStateRunningReasonAssertionIdentifierKey = "Shared Background Assertion 2 for com.COMPANY.YOUR.APP";
            SBApplicationStateRunningReasonAssertionReasonKey = 4;
        }
    );
}
```

The same code will however work in a development certificate.

**Comment by aritchie** [comment]
Don't have the linker work on Shiny.  This is something you need to configure with pretty much every Xamarin app

**Comment by Kiitoksia** [comment]
Sorry I should have clarified, the linker was set to 'Don't Link' for this.  Is this incorrect?

**Comment by Kiitoksia** [comment]
Unsure whether I should open a new thread for this, but I finally managed to get an actual native stack trace for this.  This seems the most related data.

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x187f87654 __exceptionPreprocess + 224 (NSException.m:199)
1   libobjc.A.dylib               	0x187ca9bcc objc_exception_throw + 56 (objc-exception.mm:565)
2   CoreFoundation                	0x187e8a6ec +[NSException raise:format:arguments:] + 96 (NSException.m:146)
3   Foundation                    	0x1882d016c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 128 (NSException.m:231)
4   BackgroundTasks               	0x1b20a21dc -[BGTaskScheduler _unsafe_registerForTaskWithIdentifier:usingQueue:launchHandler:] + 620 (BGTaskScheduler.m:0)
5   BackgroundTasks               	0x1b20a1f24 -[BGTaskScheduler registerForTaskWithIdentifier:usingQueue:launchHandler:] + 168 (BGTaskScheduler.m:171)
```

I am calling the scheduled tasks like so (in foreground).
```
IJobManager manager = ShinyHost.Resolve<IJobManager>();
await manager.Schedule(new JobInfo(typeof(WebSyncService), nameof(WebSyncService)) { Repeat = true });
            
            if (Xamarin.Forms.Device.RuntimePlatform == Xamarin.Forms.Device.iOS)
            {
                // iOS does not start these jobs at schedule time, run them now
                await manager.Run(nameof(WebSyncService));         
            }
```
Would this be incorrect?  This seems to be an iOS 13 exclusive issue.  Could not replicate issue on iOS 12 anymore.

**Comment by aritchie** [comment]
If this is happening during a release mode vs a dev mode, it has nothing to do with the library.  If you believe otherwise, than you need to provide a full reproducible sample & stack trace, not a native crash.
