### ISSUE TITLE
Huawei Support

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#399]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Now that the bindings have been made by another OSS community member, should Shiny add support?

## API Changes
None

## Intended Use Case
Lots

**Comment by DevEddy** [comment]
That would be awesome, especially for geofencing and push 🎉

**Comment by aritchie** [comment]
Unfortunately, this just isn't something I'm ever going to implement.  Happy to take PR's, but this is being closed in the meantime
