### ISSUE TITLE
Where is it ICentralManager and Shiny.BluetoothLE.Central  

### ISSUE THREAD

**Issue by sgermosen** [shinyorg/shiny#401]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [* ] iOS
 - [* ] Android
 - [ *] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [* ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2
## Version of OS(s) listed above with issue
android 8 doenst run the app
ios 10 doenst run the app

## Steps to Reproduce
1. Migrate from version 1.1 to 1.2
2. Try to compile
3. Look what happend

## Expected Behavior
find  the Central library

## Actual Behavior
doenst worl

I was migrating from version Shiny.BluetoothLE 1.1 to 1.2 and those namespaces dont appear

**Comment by sgermosen** [comment]
ICentralManager _centralManager = Shiny.ShinyHost.Resolve<ICentralManager>();
dont work any more

**Comment by aritchie** [comment]
Beta components are not finalize and subject to changes. Use at your own risk and be prepared to either look through the source or review the samples

**Comment by sgermosen** [comment]
Obviously I know the risk, but, I just want yo know, where do You move that functionality, because on your doc still are with central manager,

**Comment by aritchie** [comment]
IBleManager - please don't use this as a support forum in the future.  This is OSS and docs are being worked on.  It's a one man project, so you are always welcome to contribute.

**Comment by sgermosen** [comment]
Thanks, I Will contribute almost with xamples of implementations, great project thanks to much
