### ISSUE TITLE
Null exception on android in shiny.core

### ISSUE THREAD

**Issue by pellet** [shinyorg/shiny#403]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [x] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755
## Version of OS(s) listed above with issue
Android 5.1, on an Arbor IOT-500-I doubt you have access to one of these devices.

## Steps to Reproduce
Not sure on how to reproduce.

## Expected Behavior
Shiny initializes without crashing

## Actual Behavior
Shiny crashes app due to unexpected null exception-yey for android.

I've attached a stack trace below.
I think I can fix the issue by doing a null check on the 'AllPendingJobs' list, and not trying to enumerate it if it's null, and just returning null by using the elvis operator.
Strangely enough my IDE warns me the conditional operator is unnecessary since the 'AllPendingJobs' list is known to not be null.  I guess this vendor decided to implement the API wrong. :(

[stracktrace.txt](https://github.com/shinyorg/shiny/files/5192928/stracktrace.txt)

**Comment by aritchie** [comment]
Core will only use AndroidX in the next major release so this won't be an issue anymore.
