### ISSUE TITLE
its posible print image trow blutooth with shiny?

### ISSUE THREAD

**Issue by parrafo28** [shinyorg/shiny#405]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as many details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

Where its the link to buy you a coffee? because I surely will buy you one, 

look, I was testing your Bluetooth service, and everything it's awesome, but, now I want to print image or pdf, I try to send it as an array of byte, but nothing looks to work, so,  first, its possible print image with your library?

and second, it's possible than you send me a sample of this? if you like I buy you the coffee first :D

**Comment by aritchie** [comment]
Hi @parrafo28 - There is no way I can help you here since BLE is only the connection and data transport layers.  You still need to work with the protocol on the printer which I wouldn't know.  You'll have to read the specifications of how the protocol works there.  Best of luck

**Comment by parrafo28** [comment]
thanks, I will check it more exhaustly
