### ISSUE TITLE
Notification Sound Scheduler

### ISSUE THREAD

**Issue by cgould16** [shinyorg/shiny#410]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Hi! I love your plugins and was just wondering if you could add in scheduled sounds to be played, even if the app is terminated.  I am currently scheduling notifications, and I think it would be nice to be able to schedule an alarm sound, for my timer app!

## API Changes
Im not sure what all would be needed, but it might be able to be completed, through the jobs scheduler.  Or even a duration parameter for the sound setting in the notification class.

## Intended Use Case
This would be for timer apps or alarm clock apps.  Anything where the user wants to play a sound at a specific time!

**Comment by aritchie** [comment]
This already exists as a configuration value you can pass to a notification

**Comment by cgould16** [comment]
@aritchie Thanks aritchie! I am a huge fan of your plugins.  Do you have any documentation where I can reference this?  Thank you for everything!
