### ISSUE TITLE
The time interval does not work on ios.

### ISSUE THREAD

**Issue by LyckanSv** [shinyorg/shiny#411]
## Description
It is set for 20 seconds but the location is received every 1 second

## Platform
 - [X] iOS
 - [ ] Android
 - [ ] UWP

## Feature Library

 - [ ] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755
## Version of OS(s) listed above with issue
iOS 13.6

## Steps to Reproduce
1. Set the GPSRequest interval to 20 seconds
2. Execute

## Expected Behavior
That the location is sent as close to the established time interval.

## Actual Behavior
Location is sent every 1 second

**Comment by aritchie** [comment]
It isn't implemented on 1.2
