### ISSUE TITLE
Http transfers - notification visibility

### ISSUE THREAD

**Issue by bares43** [shinyorg/shiny#413]
## Summary
Hi. Android offers this notification visibility in it's download manager [https://developer.android.com/reference/android/app/DownloadManager.Request#setNotificationVisibility(int)](https://developer.android.com/reference/android/app/DownloadManager.Request#setNotificationVisibility(int)). You can set whether download progress should be visible as system notification or not. However, I haven't found any way how to achieve this using Shiny. I know Shiny uses this download manager as well, but there is no way how to set this notification visibility. So maybe adding some `NotificationVisibility` enum to `HttpTransfer` could be a way? Then set NotificationVisbility in Android's `HttpTransferManager`. Only problem is that this will work only on Android.

If you are ok with this idea, I can make a PR on this.

## API Changes
Add `NotificationVisibility` enum to `HttpTransfer`

## Intended Use Case
For showing download progress in system notification.

**Comment by aritchie** [comment]
This is being considered for 2.0, but in a different API factor that could enable better customization and UWP support.

**Comment by bares43** [comment]
I think this enum could have 4 states: `Nothing`, `ShowWhenCompleted`, `ShowWhenInProgress`, `ShowAlways`. Maybe these states could be handled properly in UWP later. Or do you think that some completely different API would be better?

**Comment by aritchie** [comment]
I'm working on something a bit different since I have the ability to do foreground notifications with progress now plus I need this for uploads as well as downloads

**Comment by bares43** [comment]
Ok, so I guess I can close this issue :)
