### ISSUE TITLE
Didn't find class "android.app.NotificationChannel" on path: DexPathList

### ISSUE THREAD

**Issue by AbdellahOusrhireDev** [shinyorg/shiny#417]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Shiny.Notifications 1.0.2.1755
## Version of OS(s) listed above with issue
Android 7.0 Phone with App Targeting Android 10 Q

## Steps to Reproduce
1. Target Android 10
2. Build App
3. Attempt to show a notification

## Expected Behavior
Notification shows

## Actual Behavior
An exeption is generated with stack trace 

```
NotificationManager.DoNotify (Builder builder, Notification notification)
d:/a/1/s/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs, line 196
Java.Lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList
```

**Comment by aritchie** [comment]
This is resolved for the next major release
