### ISSUE TITLE
Custom Notification Sound not playing

### ISSUE THREAD

**Issue by cgould16** [shinyorg/shiny#418]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] iOS
 - [ x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ x] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755
## Version of OS(s) listed above with issue

ios14
android api 30

## Steps to Reproduce
1. Create a notification.
2. Create a notification sound, with type set to custom and CustomPath set to an embedded file that is an mp3
3. Put notification sound in notification

## Expected Behavior
I was expecting a custom sound to play, when my notification went off. I know the sound works, because I can play it with other plugins.  String sound = "TaskTrackerReal.Sounds.AlarmSound.mp3" is my path.

## Actual Behavior
The default notification sound plays.

## Test Case
Assert.True(notificationSound.Type!=NotificationSoundType.Default)

**Comment by aritchie** [comment]
What version of the library?  What OS versions?  Please fill out the full template.
Please include a test case as well

**Comment by cgould16** [comment]
im not sure what you were looking for in a test case, but thank you for your patience! I updated it above

**Comment by aritchie** [comment]
This is working fine for me on Android and iOS.

**Comment by cgould16** [comment]
@aritchie do i need to use a different file type than mp3?
