### ISSUE TITLE
Shiny is saving and loading random properties in IOS Preferences 

### ISSUE THREAD

**Issue by obader** [shinyorg/shiny#426]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [X ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Lastest on nuget

## Version of OS(s) listed above with issue
All Version

## Steps to Reproduce
1. 
2.
3.

## Expected Behavior
Do nothing
![Screen Shot 2020-09-28 at 8 22 08 PM](https://user-images.githubusercontent.com/434222/94465307-5ec52f00-01c8-11eb-8dcc-61e2162d6eaf.png)

## Actual Behavior

Shiny is saving random properties in IOS Preferences and loading them on app restart.

**Comment by aritchie** [comment]
Objects that are registered with shiny (through startup) that implement INotifyPropertyChanged are automatically saved to preferences.

**Comment by obader** [comment]
thanks, any way to disable this feature on certain objects
