### ISSUE TITLE
Android scheduled local notifications don't appear unless you background the app

### ISSUE THREAD

**Issue by REXiator** [shinyorg/shiny#429]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.2247

## Version of OS(s) listed above with issue
Android 9.0 (at least)

## Steps to Reproduce
1. Get the Samples project (not -Debug) (https://github.com/shinyorg/shinysamples)
2. Update target to Android 11.0 
3. Update Shiny.Core and Shiny.Notifications to 2.0.0.2247 (pre-release)
4. Run app on Android device (I used an emulator with Android 9.0)
5. Go to local notifications section in the hamburger menu
6. Schedule a notification for the future, e.g. 1 min from now
7. Wait in app until scheduled time

## Expected Behavior
A notification is displayed by the Android notification system with the desired title and message at the desired time.

## Actual Behavior
Nothings happens until you background the app, at which point the notification is displayed. Doesn't matter if you wait 1 second or 1 hour after the scheduled time, it will get displayed only when you background the app.

**Comment by REXiator** [comment]
Oh, and in the latest stable release (1.2.0.1755) scheduled notifications don't work at all on Android, whether you leave the app open, background it or close it. Would it be best if this were filed as a new bug report, or can it piggyback on this one?

**Comment by aritchie** [comment]
The sample app is using a new version and is not complete yet, though jobs are working just fine for me.  Please don't file bugs on the sample, only your own existing code.

Scheduled notifications won't work until the jobs which on most android flavours isn't until the app goes to the background.  If you send an immediate notification, this will work just fine.  You can use foreground jobs (a feature in shiny) if you need things fired while the app is running

**Comment by REXiator** [comment]
Okay, sorry. My bad. Either way, scheduled notifications currently don't work at all with the latest stable release (1.2.0.1755) if you follow the steps I provided in my last post. It seems as though that will be fixed in the upcoming 2.0.0.x release (at least to the extent that it works when the app is backgrounded), so that's very nice to know. Out of curiosity, is there an ETA for that release?

Furthermore: How would you then go about implementing cross-platform notifications that are scheduled while the user is using the app, but might occur while the user still is in the app or might just as well occur after the user has left it? It seems like an awful lot of work to create an abstraction for checking whether there are scheduled notification foreground jobs that have to be converted to background jobs, and very likely the code will be very much platform-dependent...

**Comment by aritchie** [comment]
I'm using 1.2 for scheduled jobs in a current project just fine.  Please provide a sample of a place where it isn't working.  It isn't enough to say "I setup Android" because there is almost always a step missing in my experience of supporting this.  As for v2, I don't give ETA on this.  When it's done is all I will say.

As for your question about the abstraction, I would suggest looking over the code.  Scheduled jobs isn't something you get out of the box for any of the other platforms outside of iOS.

If you want to use jobs in the foreground, in the shiny startup file, you can add services.UseJobForegroundService(...)

**Comment by REXiator** [comment]
Fair enough. Here's a link to a VS2019 solution that reproduces the issue: https://we.tl/t-hQHJcjFEOM

This is the code I add for the Android application:

    #if DEBUG
        [Application(Debuggable = true)]
    #else 
        [Application(Debuggable = false)] 
    #endif
        public class MainApplication : ShinyAndroidApplication<CustomShinyStartup>
        {
            public MainApplication(IntPtr handle, JniHandleOwnership transfer) : base(handle, transfer)
            {
            }
        }



This is the custom shiny startup file:

    public class CustomShinyStartup : ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            services.UseNotifications();
            AndroidOptions.DefaultSmallIconResourceName = "icon";
        }
    }

This is how I've modified the MainActivity:

    [Activity(Label = "NotificationTest", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode | ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize )]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            LoadApplication(new App());

            this.ShinyOnCreate();
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            this.ShinyRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            this.ShinyOnNewIntent(intent);
        }
    }

And this is the MainPage code-behind:

    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }
        
        protected override async void OnAppearing()
        {
            base.OnAppearing();

            await Task.Delay(5000);

            var manager = ShinyHost.Resolve<INotificationManager>();
            var state = await manager.RequestAccess();
            await manager.Send(new Notification
            {
                Title = "Test title",
                Message = "Test message",
                ScheduleDate = DateTimeOffset.UtcNow + TimeSpan.FromSeconds(90)
            }).ConfigureAwait(false);
        }
    }
    

Listed Android permissions:
- ACCESS_NETWORK_STATE
- FOREGROUND_SERVICE
- WRITE_EXTERNAL_STORAGE
- READ_EXTERNAL_STORAGE

Android min SDK version: 21
Android target SDK version: 30

Installed Nugets are:
- NETStandard.Library 2.0.3
- Shiny.Core 1.2.0.1755
- Shiny.Notifications 1.2.0.1755
- Xamarin.Essentials 1.5.3.2
- Xamarin.Forms 4.8.0.1451

The rest is Xamarin.Forms template boilerplate. Running this will result in a notification being posted to the service but never being shown, whether you leave the app on or close it. Removing the ScheduleDate will make things work, but then scheduling will obviously have to be made custom.

**Comment by aritchie** [comment]
There is no issue.  The scheduled job has to kick in which can take up to 15 mins.  The firing time is not precise enough to go background and run 90 seconds later.

**Comment by alexshikov** [comment]
Hey @aritchie . Just wanted to clarify:

> The scheduled job has to kick in which can take up to 15 mins.

Is it a limitation of the Android or that's a specific of Shiny implementation?
