### ISSUE TITLE
Why is my custom sound not working?

### ISSUE THREAD

**Issue by cgould16** [shinyorg/shiny#430]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)
Hi Allan.  I am working on a timer application, and wanted to use custom sounds with shiny notifications.

I have a sounds folder in my generic, xamarin bundle with mp3 files, and I am passing in a string that looks like "TaskTrackerReal.sounds.AlarmSound" into the custom sounds path.

        NotificationSound notificationSound = new NotificationSound
             {
                Type = NotificationSoundType.Custom,
                CustomPath = notifSound
             };
        notification = new Notification
            {
                Id = notifId,
                Title = TimerText,
                Message = TimerText + " is completed.",
                ScheduleDate = scheduledTime,
                Sound = notificationSound

            };

Here is my code for the notification and sound.  The notification fires off, but the sound is just the default sound.  I am also interested in changing the duration of the sound and adding vibration that is continuous.  Is this a possibility?

Do you also have any functionality for a specific page being opened, when the notification is clicked, by the user?

Thank you and please let me know if there is anything else you need to know

**Comment by aritchie** [comment]
Please submit a sample.  You likely aren't putting the sounds in as proper resources or you're using a different path. 

You can't have continuous vibration on iOS for sure, perhaps a longer vibration of Android, but I have never tried it.  This isn't something I would ever support even if it was possible though.

You can use the INotificationDelegate.OnEntry(...) and navigate using whatever navigation platform you have.  With Android, you can also set a custom activity using the Notification.Android options to control that.  You lose parts of the INotificationDelegate when you do this though.

**Comment by cgould16** [comment]
public string sound = "TaskTrackerReal.Sounds.AlarmSound.mp3";
        //Pass in name of sound from picker
        public void createSound(string choice)
        {
            
            if (choice.Equals("Digital Sound"))
            {
                sound = "TaskTrackerReal.Sounds.AlarmSound.mp3";
            }
            else if(choice.Equals("Gentle Sound"))
            {
                sound = "TaskTrackerReal.Sounds.GentleAlarm.mp3";
            }
            else if(choice.Equals("Harsh Sound"))
            {
                sound = "TaskTrackerReal.Sounds.HarshAlarm.mp3";
            }
            else
            {
                sound = "TaskTrackerReal.Sounds.AlarmSound.mp3";

            }
        }

Im new to github and an undergrad CS major, so I think this is what you mean by a sample. This is my string initialization method  I know the path is right because I used another plugin to play the sound before and it works.  I have it compiled as an embedded resource. Thanks for bearing with me. This project is supposed to allow me to learn to work on these projects, so I am very green here.

**Comment by aritchie** [comment]
An embedded resource in shared netstandard project?  If so, that isn't supported.  Only the native path is supported (file system based).

No problem about being green - by sample, it means a full compilable sample project.  If that was supplied, I would have seen the issue right away.  In any case, you have the answer.  You have to put these in the native paths for android & ios.  Please take a look at the sample

**Comment by cgould16** [comment]
@aritchie should this still be an embedded resource in the native path??

**Comment by aritchie** [comment]
No - you have to use the native resourcing.  Embedded resources are a .NET thing.  iOS is a bundle resource and android requires you dump it in the resources/raw folder which should mark it as an AndroidResource automatically
