### ISSUE TITLE
Bluetooth manufacturer data returning empty SparseArray on Android 10

### ISSUE THREAD

**Issue by mathewssj** [shinyorg/shiny#431]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ X] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755-beta
## Version of OS(s) listed above with issue
Android 10

## Steps to Reproduce
1. Range a beacon on an Android 10 device
2. When the beacon is found the app crashes
3.

## Expected Behavior
Ranged beacon data returned

## Actual Behavior
App crash

Hi Allan,
I raised this bug a while ago and you closed it as there was no reproducible sample which is fair enough, as I realise this is open source. In that spirit, I downloaded the code and found the source of the problem myself and managed to fix it. As I know you plan to release a new version soon I thought I would share my fix with you as it is a one liner you can incorporate very easily.

In Shiny.BluetoothLE project:
Platforms\Android\Internals\AdvertisementData.cs
I added the line as below:

`this.manufacturerData = new Lazy<ManufacturerData?>(() =>
            {
				/* Added this line to prevent crash when ManufacturerSpecificData is an empty array on Android 10 */
                if (this.result.ScanRecord.ManufacturerSpecificData.Size() == 0)
                  return null;

                var manufacturerId = (ushort)this.result.ScanRecord.ManufacturerSpecificData.KeyAt(0);
                if (manufacturerId == 0)
                    return null;

                var data = this.result.ScanRecord.GetManufacturerSpecificData(manufacturerId);
                return new ManufacturerData(manufacturerId, data);
            });`

This fixed my problem. Hope this helps.

Regards,
Simon.

**Comment by aritchie** [comment]
Hi Simon.  There was an issue with addata parsing some time ago in the dev branch which seems to already have included this.  This is part of the reason I don't take standard issue filings with betas because the work is either in-flight or needs better details.
