### ISSUE TITLE
[Preview Branch] Crash in Uwp. Radio variable is NULL

### ISSUE THREAD

**Issue by DigitalNut** [shinyorg/shiny#435]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [X] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [X] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Preview Branch Oct 20
## Version of OS(s) listed above with issue
UWP Windows version 2004  (Build 19041.572)

Thanks for the Library!
Xamarin Forms app shared with Android and UWP. Under Android app runs with out issues. On UWP app crashes.

Side Note: I had to change Shiny.Support.Uwp.csproj 'RootNamespace' from Shiny.Support.Uwp to Shiny otherwise Visual Studio 2019 would not create the DLL's. Errors with namespace issue on Shiny.Support.Uwp winmdobj file.

## Steps to Reproduce
1. Enable Bluetooth / Location settings required to run on each platform
2. Init Shiny bluetooth as described for each platform
2. Call IBleManager.RequestAccess() - On Android returns Available, on UWP returns Unknown
3. Call TrySetAdapterState(True)

## Expected Behavior
Radio is initialed when BLE library is initialized. I have to 'force' a Scan e.g. 'ScanForUniquePeripherals' call for the radio variable to be initialized. So makes having the same code in Xamarin forms a little tricky.

## Actual Behavior
When calling RequestAccess() (radio is null). Crash in SetAdapterState in UWP as the radio variable is NULL. File BleManager.cs (BLE\Platforms\Uwp)

**Comment by aritchie** [comment]
This is fixed in the latest preview.  Please follow the issue template in the future and include a full stacktrace and/or reproducible sample.
