### ISSUE TITLE
Detection of iBeacon "compatible" manufacturers

### ISSUE THREAD

**Issue by sersanchus** [shinyorg/shiny#439]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [X] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

2.0.0.2349-preview

## Version of OS(s) listed above with issue

Android 10

## Steps to Reproduce

1. Try to detect an iBeacon compatible beacon from https://www.proximipro.com/ based on nRF51822 chipset.
2. 
3.

## Expected Behavior

Normal detection of beacon with the exact region defined.

## Actual Behavior

The beacon is not detected as a iBeacon. The function IsBeacon is expecting 23 bytes of manufacturer data but 24 are used in this case. More sophisticated detection algorithm of iBeacons can be used based on the iBeacon packet structure.

**Comment by aritchie** [comment]
Please provide some form of test case for me like the packet you say is "compatible" with ibeacon.

**Comment by sersanchus** [comment]
I've opened a new pull request (#445 ) with my version of the solution and modified the existent unit tests.
The beacon raw data that was failing was this:

`
        [InlineData(
            "02-15-A7-AE-2E-B7-1F-00-41-68-B9-9B-A7-49-BA-C1-CA-64-00-01-00-40-C5-58",
            "A7AE2EB7-1F00-4168-B99B-A749BAC1CA64",
            1,
            64,
            Proximity.Immediate
        )]
`

The last byte (58) exceds the 23 bytes limit because is a manufacturer optional byte. I've searched on google and it seems to me that is related to the term 'mfg reserved'.

**Comment by aritchie** [comment]
This now exists as part of 2.2
