### ISSUE TITLE
Shiny Notifications setup an intent

### ISSUE THREAD

**Issue by csousa96** [shinyorg/shiny#440]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Let's take a mobile application on Android. It's not possible to add a desired intent for the notifications. Right now, if i'm not  mistaken, all we can do is to define the launch activity type on the AndroidOptions class. But even with the activity type defined,  it makes the application open from scratch, losing the state that the application had before the notification was clicked.

## API Changes
And idea would be to add a method, on AndroidOptions, that makes possible for us to provide the desired intent

## Intended Use Case
Take an application (where this app would be in the background) wich is using location tracking in the background and uses the notifications to show the user that the app is tracking his location. If the user clicks in the notification the app will open once again, and all the data on the interface will be reseted, because clicking the notification is like booting the app all over again.

**Comment by aritchie** [comment]
I don't want to add every config option in the world especially on this area since it can break others portions of the integration
