### ISSUE TITLE
Sample application is not working 

### ISSUE THREAD

**Issue by viveknegi51288** [shinyorg/shiny#444]
Hi all,

@dahlbyk  @kpespisa  @aritchie @jamesmontemagno @dylanberry 

Can you please check your sample application is not working.

Can you help me to provide some code snippet to run a job every 5 min whenever the application on background in xamarin forms

**Comment by aritchie** [comment]
This user has been banned for abusing this forum and OSS in general.  If they spent some time reading actual OS docs, they would know this isn't possible
