### ISSUE TITLE
Notifications Action Type

### ISSUE THREAD

**Issue by JuanNinos** [shinyorg/shiny#446]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [X] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

2.0.0.2278

## Version of OS(s) listed above with issue

Android 10.0

## Steps to Reproduce
1. Install the Shiny.Locations (2.0.0.2278) and the Shiny.Notifications nugget in a Xamarin.Forms project
2. Setup the project to use the location in background
3. With the method RegisterCategory that can be accessed from the INotificationManager, add a new Category that has the action type of none
4. When the user allows the usage of the location in background, a notification will automatically show up saying Shiny is tracking your location
5. Click the shiny notification

## Expected Behavior

The NotificationActionType has 4 types: Destructive, None, OpenApp and TextReply. I Added the type none using the method refered above (RegisterCategory). If i'm not mistaken these will change the type of action that the notification will have. For example, the OpenApp will open the application when the notification it's clicked. My goal choosing the type None was to do nothing when the user clicked the notification, since i don't want the app to be opened again.

Heres the code that i used to modify the INotificationManager to add the ActionType:

```
public INotificationManager SetShinyNotificationActionType(INotificationManager myINotificationManager)
        {
            NotificationAction ActionDefault = new NotificationAction("DoNothingAction", "InformativeNotification", NotificationActionType.None);
            NotificationCategory CategoryShiny = new NotificationCategory(Android.App.Notification.CategoryService, ActionDefault);
            myINotificationManager.RegisterCategory(CategoryShiny);
            return myINotificationManager;
        }
```

## Actual Behavior

The Notification Manager gets the correct Action Type, but it keeps having the action of opening the application on click.

**Comment by aritchie** [comment]
You can't control the foreground notifications with actions right now
