### ISSUE TITLE
[Preview Branch] BluetoothLE - Android - Crash when passed in characteristics does not exist in GATT service

### ISSUE THREAD

**Issue by DigitalNut** [shinyorg/shiny#448]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [x] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Preview Branch - Nov 5, 2020
## Version of OS(s) listed above with issue
Android 11

## Steps to Reproduce
1. Call WhenKnownCharacteristicsDiscovered with known Service UUID but with a Characteristics UUID that does not exist in the service.

## Expected Behavior
Failed to find characteristics in service

## Actual Behavior
Crash on line 87 ob.OnNext in function DiscoverServices() in file shiny\src\Shiny.BluetoothLE\Platforms\Android\Peripheral.cs
Crash actually happens in file Android\GattCharacteristic.cs because passed in param 'BluetoothGattCharacteristic native' is NULL in function:
```
public GattCharacteristic(IGattService service,
                                  PeripheralContext context,
                                  BluetoothGattCharacteristic native)
                            : base(service,
                                   native.Uuid.ToString(),
                                   (CharacteristicProperties)(int)native.Properties)
```

This is called from Android\GattService.cs function GetKnownCharacteristics:
```
        public override IObservable<IGattCharacteristic> GetKnownCharacteristics(params string[] characteristicIds)
            => Observable.Create<IGattCharacteristic>(ob =>
            {
                var cids = characteristicIds.Select(UUID.FromString).ToArray();
                foreach (var cid in cids)
                {
                    var cs = this.native.GetCharacteristic(cid);                  <---- cid is a valid UUID, but does not exist in the service
                    var characteristic = new GattCharacteristic(this, this.context, cs);    <---- Crash here as 'cs' is null
                    ob.OnNext(characteristic);
                }
                ob.OnCompleted();

                return Disposable.Empty;
            });
```
Needs something like a check that the returned value from this.native.GetCharacteristic is valid e.g.:

```
        public override IObservable<IGattCharacteristic> GetKnownCharacteristics(params string[] characteristicIds)
            => Observable.Create<IGattCharacteristic>(ob =>
            {
                var cids = characteristicIds.Select(UUID.FromString).ToArray();
                foreach (var cid in cids)
                {
                    var cs = this.native.GetCharacteristic(cid);
                    if (cs != null)
                    {
                        var characteristic = new GattCharacteristic(this, this.context, cs);
                        ob.OnNext(characteristic);
                    }
                }
                ob.OnCompleted();

                return Disposable.Empty;
            });
```

**Comment by aritchie** [comment]
Please submit a PR next time if you have a known fix.  

Please also include the actual nuget version since things are fixed preview to preview.

**Comment by DigitalNut** [comment]
Hi, I will submit a PR next time.  Thanks for the great job!
