### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by aismaniotto** [shinyorg/shiny#450]
Leave Your Message Below (don't delete this line though)
Amazin library, congratulations!!!

One doubt: it's possible to the `JobInfo` create the job from Autofac container? If no, it's possible to set as singleton, to avoid create the class again every time the periodic run?

Thanks for the package!!

**Comment by aritchie** [comment]
Please don’t abuse this area for support questions!!!  


The jobinfo is only a descriptor, the jobinfo type is hydrated from the container.  Even if the container says it is a singleton, most of the time when the job runs (especially on Android), the container is being rebuilt anyhow.
