### ISSUE TITLE
Shiny.Locations in background keeps active when the app is closed

### ISSUE THREAD

**Issue by JuanNinos** [shinyorg/shiny#452]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

I tested in the Shiny.Locations 2.0.0.2278 and Shiny.Locations 2.0.0.2349-preview, with the same versions of the Shiny.Notifications and Shiny.Core

## Version of OS(s) listed above with issue

Android 10

## Steps to Reproduce
1. With the gpsmanager, request access and start listening for GPS changes, with the option for use in background set as true
2. A shiny notification will show up right after, saying that we're tracking the location
3. Kill the app through the phone/emulator

## Expected Behavior

Closing the application would stop the shiny location service and close everything related to the app

## Actual Behavior

The shiny service keeps running, and the application, even if it's not opened on the phone/emulator anymore, it's still running (i figured this out since i could still debugg it after the app was closed). Another indicator of this is that the shiny notification that show us that we're tracking the phones location it's still up and running, and the method associated with the gps change event it's still hit if we do a breakpoint on it.
Closing the application from the Stop Debugging button in visual studio makes this issue go away, everything is properly closed. But as said previously, if we kill the app through the device, this one seems like it keeps running even if we can't see the app opened anymore.

**Comment by aritchie** [comment]
This is not a bug. If you want it to stop, call stoplistener

**Comment by JuanNinos** [comment]
Yes, it's true that to stop it i just need to call the stoplistener. But if the user closes the app out of nowhere, the service should be stoped automatically since the application was killed right? I shouldn't need to stop the listener by myself since i don't even know if theres any event or method that is triggered when the app is killed

**Comment by aritchie** [comment]
The service is sticky for many reasons.  This will not be changing for now.
