### ISSUE TITLE
"The name 'iOSShinyHost' does not exist in the current context" with latest package

### ISSUE THREAD

**Issue by buzzware** [shinyorg/shiny#455]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP

I am building this with Visual Studio for Mac OSX.

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [X] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

2.0.0.2356-preview package

## Version of OS(s) listed above with issue

all

## Steps to Reproduce
1. Checkout the branch 2.0.0.2356-preview-iOSInaccessible and attempt to build the project  Shiny.Device.Tests.iOS https://github.com/buzzware/shiny/blob/2.0.0.2356-preview-iOSInaccessible/tests/Shiny.Device.Tests/Shiny.Device.Tests.iOS/iOSShinyHost-inaccessible-bug.txt
2.
3.

## Expected Behavior

It should build

## Actual Behavior

It fails finding the symbol iOSShinyHost

**Comment by aritchie** [comment]
No it shouldn’t.  iOSShinyHost doesn’t exist in 2.0.

**Comment by buzzware** [comment]
I don't understand why Shiny.Device.Tests.iOS.csproj compiles from source on the preview branch then.

So what replaces iOSShinyHost? Is any init call required? Is there a sample app or documentation for V2?

**Comment by aritchie** [comment]
There will be a call, but nothing is documented yet.  The sample app is located here: https://github.com/shinyorg/shinysamples and is always against the latest.
