### ISSUE TITLE
[v2][Android] Custom sound 

### ISSUE THREAD

**Issue by cpraehaus** [shinyorg/shiny#461]
# Custom sound is broken on Android in 2.0.0 pre-release (dev branch)

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

## Feature Library

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Shiny.Notifications 2.0.0.2356-preview (also with v2.0.0.2285-preview)

## Version of OS(s) listed above with issue
* Android 8 to 11

## Steps to Reproduce
1. Send notification with custom sound (like done in shinysamples with "notification.mp3")

## Expected Behavior
Android notification **plays custom sound**.

## Actual Behavior
Android notification **plays default sound**.

Actually there are two problems:

**Problem 1:** custom sound path is not correctly mapped to resource URI.
The system cannot find the sound resource, e.g. on Android 6:
```
MediaPlayer Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /raw/alarm_siren
MediaPlayer Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: /raw/alarm_siren
RingtonePlayer error loading sound for /raw/alarm_siren
RingtonePlayer  java.io.IOException: setDataSource failed.
RingtonePlayer error loading sound for /raw/alarm_siren
RingtonePlayer  java.io.IOException: setDataSource failed.
```

Shiny passes sound path given by the user in ``Notification.Sound.CustomPath`` directly to ``Uri.Parse()`` which obviously leads to an URI that cannot be correctly mapped to a resource by Android.

**Problem 2:** Since Android 8 (Oreo) the sounds are tied to the notification channel when the channel is created. The user can override the sound in the App notification settings anytime. To change the sound programmatically you have to e.g. uninstall and reinstall the app.

Shiny currently configures the sound on the notification channel **after** the channel was created. This has no effect even when calling ``NotificationManager.CreateNotificationChannel()`` again. Deleting the notification channel before recreating it also does not help.

**Comment by cpraehaus** [comment]
The following patch works for me, although of course it only works as long as the custom sound does not change.
This seems to be an Android constraint and should be accepted as such. Although it should be possible to delete notification channel it did not work in my experiments on Android 9.

```patch
diff --git a/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs b/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs
index d0bc6034..c3b39c53 100644
--- a/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs
+++ b/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs
@@ -209,6 +209,27 @@ namespace Shiny.Notifications
         public virtual Android.App.Notification CreateNativeNotification(Notification notification)
             => this.CreateNativeBuilder(notification).Build();
 
+        private int GetRawResourceIdByName(string rawName) => this.context.AppContext
+            .Resources
+            .GetIdentifier(
+                rawName,
+                "raw",
+                context.AppContext.PackageName
+            );
+
+        private Android.Net.Uri GetSoundResourceUri(string soundResourceName)
+        {
+            // TODO: maybe strip file extension and leading slash to allow user
+            // to specify custom sounds like "notification.mp3" or "/raw/notification.mp3"
+            var resourceId = GetRawResourceIdByName(soundResourceName);
+            var resources = this.context.AppContext.Resources;
+            return new Android.Net.Uri.Builder()
+                .Scheme(ContentResolver.SchemeAndroidResource)
+                .Authority(resources.GetResourcePackageName(resourceId))
+                .AppendPath(resources.GetResourceTypeName(resourceId))
+                .AppendPath(resources.GetResourceEntryName(resourceId))
+                .Build();
+        }
 
         protected virtual void CreateChannel(Notification notification)
         {
@@ -229,18 +250,18 @@ namespace Shiny.Notifications
                 if (!d.IsEmpty())
                     channel.Description = d;
 
-                this.manager.CreateNotificationChannel(channel);
-            }
+                // Set initial sound attributes for channel when it is created
+                if (this.context.IsMinApiLevel(26) && (notification.Sound?.IsCustomSound() ?? false))
+                {
+                    var attributes = new AudioAttributes.Builder()
+                        .SetUsage(AudioUsageKind.NotificationRingtone)
+                        .Build();
 
-            if (this.context.IsMinApiLevel(26) && (notification.Sound?.IsCustomSound() ?? false))
-            {
-                var attributes = new AudioAttributes.Builder()
-                    .SetUsage(AudioUsageKind.NotificationRingtone)
-                    .Build();
+                    var uri = GetSoundResourceUri(notification.Sound.CustomPath);
+                    channel.SetSound(uri, attributes);
+                    channel.EnableVibration(notification.Android.Vibrate);
+                }
 
-                var uri = Android.Net.Uri.Parse(notification.Sound.CustomPath);
-                channel.SetSound(uri, attributes);
-                channel.EnableVibration(notification.Android.Vibrate);
                 this.manager.CreateNotificationChannel(channel);
             }
         }
@@ -345,7 +366,7 @@ namespace Shiny.Notifications
                     break;
 
                 case NotificationSoundType.Custom:
-                    var uri = Android.Net.Uri.Parse(notification.Sound.CustomPath);
+                    var uri = GetSoundResourceUri(notification.Sound.CustomPath);
                     builder.SetSound(uri);
                     break;
 

```

**Comment by aritchie** [comment]
Submit a PR please

**Comment by aritchie** [comment]
This code has been moved into being part of the new channels api.  Thank you for the PR
