### ISSUE TITLE
HTTP Transfers - Allow pause/resume

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#474]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Add ability to pause/resume

## API Changes
iOS supports this for downloads.  Android does not.

## Intended Use Case
Check feasibility

**Comment by Hackmodford** [comment]
My feature request would also solve this issue.
https://github.com/shinyorg/shiny/issues/485

**Comment by aritchie** [comment]
Closing as this isn't something I need for the immediate future and not a focus for 3.0
