### ISSUE TITLE
HTTP Transfers - Progress notification

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#475]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Android offers this out of box.  iOS will not allow us to do anything here.  UWP can piggyback on persistent notifications.

## API Changes
Unknown

## Intended Use Case
Subject line

**Comment by Hackmodford** [comment]
My feature request would also solve this.
https://github.com/shinyorg/shiny/issues/485

**Comment by aritchie** [comment]
This only solves for android and not necessarily the other platforms properly.  This is also still being debated if it is a complexity I want to take on for this project right now

**Comment by Hackmodford** [comment]
I have experience needing to download large files in the background on iOS and Android. So yes, this would only solve it for Android as iOS wouldn't allow you to have a notification that displays progress.

**Comment by aritchie** [comment]
Closing as this isn't something I need for the immediate future and not a focus for 3.0
