### ISSUE TITLE
iOS 13 Background Task

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#48]
## Summary
Use the iOS13 Background Task

## API Changes
The iOS background task requires registering their individual namespace in the info.plist which is less than ideal.  It does allow triggering based on charging & network state.

## Intended Use Case
This is quite a bit better of a setup than background fetch.  

## This should not be taken on by the community

**Comment by EDMIStephen** [comment]
Hi @aritchie. This is showing as Done in vNext. Is that really the case and if so when is it likely to be released? I would love to be able to use this as my app has a minimum requirement of iOS 13 and the finite amount of time to work of 30 seconds is less than the 60ish seconds I need.

Many thanks.

**Comment by aritchie** [comment]
@EDMIStephen This isn't needed which is probably and isn't necessary as I'm able to accomplish the same with background fetch currently.  You'll still only get 30 seconds either way.

**Comment by EDMIStephen** [comment]
Thanks for taking the time to reply. Would using the new Background Task in iOS 13 not remove the limitation of only running for 30 seconds? This seems to imply they can "run tasks requiring minutes to complete". Having said that I haven't tried it myself and am relying on Apples documentation.
https://developer.apple.com/documentation/backgroundtasks

**Comment by aritchie** [comment]
Hmm interesting.  Their docs aren't very helpful as usual, but I'd be willing to take a look again for a future release

**Comment by aritchie** [comment]
Now implemented in dev
