### ISSUE TITLE
IOIO Support

### ISSUE THREAD

**Issue by nick5454** [shinyorg/shiny#483]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Support for IOIO boards. IOIO boards are used to control machines in store like beverages. Currently only IOIOLib does. Is there a plan to add this kind of support?

## API Changes
The ability to communicate via BLE to these boards

## Intended Use Case
It would be nice to wrap communication to these boards, probably via Reactive. These are used in a lot of beverage machines.

I was curious, are you interested in looking at this?

**Comment by aritchie** [comment]
If it supports BLE, it already works with it.  You just need to know the characteristics and byte formats it produces.
