### ISSUE TITLE
HTTP Transfers - Alternative Android Download Manager

### ISSUE THREAD

**Issue by Hackmodford** [shinyorg/shiny#485]
## Summary
Ability to use a different download manager for background downloads in Android.

## API Changes
none

## Intended Use Case
The stock Android download manager always downloads files to an external download directory. If something such as the [Novoda Download Manager](https://github.com/novoda/download-manager) or [Fetch](https://github.com/tonyofrancis/Fetch) were used, we could download straight to internal storage of the android app. This can be helpful if you do not want the files to be seen/modified by the end user.

**Comment by aritchie** [comment]
This already exists with HttpClientHttpTransferManager but is not yet fully tested
