### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by Codelisk** [shinyorg/shiny#489]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
I thought it would maby fit the library, since iOS 14 has got widgets, to create a cross platform widget solution.
Honestly i dont know anything about the iOS 14 widgets and whether there are commonalities to the Android ones and therefore if it even would make sense to have a cross platform solution.

## API Changes
Whole new API

## Intended Use Case
Make it easier to create widgets

I will need iOS 14 widgets in the near future so when this idea would make sense for Shiny i would try to help implementing this feature as far as my capabilities allow me.

**Comment by aritchie** [comment]
Unfortunately, UI isn't something Shiny will touch.  Shiny focuses on all the other stuff that Xamarin Forms doesn't touch.  This is best to bring forward to the XF team (and one they should investigate)
