### ISSUE TITLE
iOS 14 geofence not working all the time, works fine on iOS 13 or lower.

### ISSUE THREAD

**Issue by thenewguy133** [shinyorg/shiny#494]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS 
 - [ ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [X] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755

## Version of OS(s) listed above with issue
iOS v14. 
Geofence did determine state as well as enter/exit not triggering all the time. Works fine about 10% of the time. Other 90% did determine state never gets called and enter/exit thus does not trigger. Location is set to "always" and "precise location" is set to on.

## Steps to Reproduce
1. User opens app for the first time.
2. User is prompted for location permission and says using while in app. User then goes to settings and selects always and verifies precise location is turned on.
3. User opens app again. User logs in which stores currently location of their lat, long.
4. User clicks the home button, putting the app to sleep. In the on sleep event "await this.geofences.StartMonitoring" is called with a new geofence using the stored lat, long of users location.
5. User is inside the geofence so did determine state should fire and the state of inside should be hit. 
6. Did determine state only fires sometimes 10%. If it does enter/exit work fine. If it does not enter/exit never work.

## Expected Behavior
Did determine state will be entered and the enter/exit will show when entering and exiting the geofence.
 
## Actual Behavior
Did determine state is only hit about 10% of the time, other 90% geofence state never changes. Is iOS 14 supported on version 1? Same code works 100% of the time on iOS 13 and below, so it seems to be an iOS 14 specific issue.

**Comment by aritchie** [comment]
Calling async methods when the app is going to sleep isn't always going to work as the OS won't wait for the completion since the method isn't async itself
