### ISSUE TITLE
Callback for BleManager Registration Failed

### ISSUE THREAD

**Issue by wagenheimer** [shinyorg/shiny#499]
## Summary
There are situations where the BleManager ScanForUniquePeripherals function stops working.
The console shows this error:

```
01-27 10:11:43.161 D/BluetoothAdapter(19019): BLE support array set: 010011
01-27 10:11:43.161 D/BluetoothLeScanner(19019): Start Scan with callback
01-27 10:11:43.166 D/BluetoothLeScanner(19019): onScannerRegistered() - status=133 scannerId=0 mScannerId=0
01-27 10:11:43.166 D/BluetoothLeScanner(19019): Registration failed, unregister scannerId = 0
01-27 10:11:43.166 D/BluetoothLeScanner(19019): Scan failed, reason: app registration failed
```

Whenever this happens, it only works again after the cell phone is restarted.

The problem is that there is no way to detect that this error has occurred to be able to show a message to the user asking him to restart the phone.

My suggestion is to add a CallBack to be able to detect when this error "Registration failed, unregister scannerId = 0" occurs.

## API Changes
Add a CallBack to BleManager when it fails to register the scanner.

## Intended Use Case
Show a dialog to the user telling to restart the phone when the scanner is not connectable anymore.

**Comment by aritchie** [comment]
There is no API to be able to catch such an event.  Does the Scan method throw an exception in the observable (it must)?  What's the full stack trace on it?  Is there a reproducible test case?

**Comment by wagenheimer** [comment]
There is no Exception. I added a Try-Catch but the Exception does not happen. 
It only shows the messages on the console.

After I got this error on my App, the Shiny Sample App will show the same error when searching for devices, and will only work again after restarting the phone.

There exists a ScanCallback
https://developer.android.com/reference/android/bluetooth/le/ScanCallback.html#SCAN_FAILED_APPLICATION_REGISTRATION_FAILED

Would it be possible to subscribe to this?

**Comment by aritchie** [comment]
A try/catch around an observable won't do anything.  You have to use the error portion of the subscribe function.

You are correct in that I can use that method in scancallback to trigger the error into the observable.  This will be updated in the preview
