### ISSUE TITLE
Bluetooth Classic

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#50]
## Summary
Use Bluetooth classic to connect to peripherals

## API Changes
iOS 13 looks to support most (if not all) of the necessary functions for classic bluetooth.  UWP & Android are already fully supported.

## Intended Use Case
Provided

## This should not be taken on by the community

**Comment by twsl** [comment]
Is there any progress to check out?

**Comment by aritchie** [comment]
@twsl no

**Comment by aritchie** [comment]
Moved to experiments - unknown if this will ever turn into anything
