### ISSUE TITLE
Firebase PushDelegate => OnEntry not fired on tap

### ISSUE THREAD

**Issue by Codelisk** [shinyorg/shiny#513]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

I tried Firebase push notifications with the newest **2.0.0.2476-preview** nuget.

Evrything is working fine so far, except i dont know why the OnEntry(PushEntryArgs args) method in my PushDelegate is not working when i tap on a notification.

Here is a little clip demonstrating what i believe i have to do to get the OnEntry method triggered:

https://user-images.githubusercontent.com/51824173/107737943-f48bd180-6d05-11eb-8366-0a39b7d7b646.mp4

Here is a github repo of the my project:
https://github.com/Codelisk/ShinyFirebasePushSample

**Comment by aritchie** [comment]
Is this from an app cold start?  You are missing the OnCreate hook in the activity.  As a side note, if you are intending to do navigation in OnEntry, Prism likely won't be ready yet by the time this delegate fires in a cold start.

Please note that support was intended for the STABLE release for which firebase does not have one.  2.0 is also still under heavy development and needs a lot of docs to be added.

**Comment by Codelisk** [comment]
Thank you ShinyOnCreate was the missing part OnEntry is now triggered!

One last question then i am done :D
How would you navigate to another page when a Notification is pressed?

**Comment by github112it** [comment]
I've managed to get this working using this:
```
public Task OnEntry(PushEntryArgs args)
        {
            var route = args.UserInfo.TryGetValue("route", out string value) ? value : default;
            if (!string.IsNullOrWhiteSpace(route))
            {
                Device.BeginInvokeOnMainThread(async () =>
                {
                    try
                    {
                        var app = (App)Prism.PrismApplicationBase.Current;
                        await app.NavigateAsync(route);
                    }
                    catch (Exception navigateException)
                    {
                        Log.Write(navigateException);
                    }
                });
            }

            return Task.CompletedTask;
        }
```
where `NavigateAsync` is a simple method meant to access the `NavigationService` without needing to inject it into current delegate:
```
public Task NavigateAsync(string route) => NavigationService.NavigateAsync(route);
```
Please note that I have no idea if this is the right way to do it.

**Comment by Codelisk** [comment]
@github112it Thank you very much!

What i forgot to mention is that i wanted to navigate to another page when the app is closed and i press on the notification, do you know whether that works also?

**Comment by aritchie** [comment]
Navigation is something well outside of this library.  You shouldn't do UI things in the delegate like this.

**Comment by Codelisk** [comment]
@aritchie but is there an entry point where i can catch that I tapped on a Notification when the app is closed? The OnEntry is not the right place for this what i have seen

**Comment by github112it** [comment]
> @github112it Thank you very much!
> 
> What i forgot to mention is that i wanted to navigate to another page when the app is closed and i press on the notification, do you know whether that works also?

In my **_limited_** testing, on iOS it seems to have Prism ready on that point in the delegate, even on a cold start.

On Android I had a different approach:

1. First I added a new parameter on the App ctor and a new setter/getter:
```
public string StartRoute { get; set; }

public App(IPlatformInitializer initializer = null, string startRoute = null) : base(initializer)
{
    StartRoute = startRoute;
}
```

2. In the Android project MainActivity.cs:
```
protected override void OnCreate(Bundle savedInstanceState)
{
    ... [clipped for brevity]

    LoadApplication(new App(startRoute: Intent?.Extras?.Get("route")?.ToString() ?? null));

    this.ShinyOnCreate();
}
```

3. In the entry point (MainPage):
```
public override async void OnAppearing()
{
    ... [check authentication beforehand maybe?]

    var app = (App)Prism.PrismApplicationBase.Current;
    if (!string.IsNullOrEmpty(app.StartRoute))
    {
        var route = app.StartRoute;
        app.StartRoute = null;
        await app.NavigateAsync(route);
        return;
    }

    ... [anything else]
}
```

Usually the same should be done on iOS as well, but I haven't yet figured out how to mess with `DidReceiveRemoteNotification` without breaking stuff.

Again, I must stress the fact that I'm in no way sure if this is the right way to do it. I'm really new with Xamarin.
