### ISSUE TITLE
Android GetCharacteristics() invalid cast exception

### ISSUE THREAD

**Issue by jormenjanssen** [shinyorg/shiny#517]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [X] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.2487-preview

## Version of OS(s) listed above with issue
Android 10

## Steps to Reproduce
1. Open the Shiny example app
2. Go to bluetooth client test
3. Connect to a device (in my example i had to go back to another device in the scan list and then the issue appears)

` ` `  at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
  at System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () [0x00040] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:52 
  at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1+_[TSource].LoopRec (System.Reactive.Concurrency.IScheduler scheduler) [0x00031] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:86 ```

## Expected Behavior
`IObservable<IList<IGattCharacteristic>> GetCharacteristics();` in `IGattService` to return observeable list of characteristics. 
Discovered the bug in my own app and then reproduced it in the Shiny example app.

![Screenshot_20210217-113557](https://user-images.githubusercontent.com/1651000/108196296-3effba80-7119-11eb-868c-6ec35825d653.png)

## Actual Behavior
Invalid cast exception on Android.
Workaround possible using GetKnownCharacteristic()

**Comment by aritchie** [comment]
Please only file examples with your code.  If the bug is in the sample, it means it is already known because it is likely still being worked on
