### ISSUE TITLE
Bluetooth LE - latest preview version issue

### ISSUE THREAD

**Issue by p-mobile** [shinyorg/shiny#525]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)
I tried to use this one to integrate bluetooth in my project. In sample application i see its using older version of package. When we upgrade to latest preview version its throwing error for missing dependencies. Can you please provide me working sample for latest version of bluetooth LE?

**Comment by aritchie** [comment]
READ THE ISSUE TEMPLATE!!!  This is only for active project sponsors or OSS contributors.
