### ISSUE TITLE
Add IsFromMockProvider to IGpsReading 

### ISSUE THREAD

**Issue by RedCaplan** [shinyorg/shiny#526]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Feature to check if the location comes from gps provider or mock location app

#### Shiny.Locations/IGpsReading.cs
```C#
bool IsFromMockProvider {get;}
```
#### Shiny.Locations/Platforms/Android/GpsReading.cs 
```C#
public bool IsFromMockProvider  => this.location.IsFromMockProvider;
```
#### Shiny.Locations/Platforms/macOS+iOS/GpsReading.cs 
```C#
public bool IsFromMockProvider  => DeviceInfo.DeviceType == DeviceType.Virtual
```
#### Shiny.Locations/Platforms/Uwp/GpsReading.cs 
We can use PositionSource but there is no guarantee that all unknown or obfuscated PositionSources are mocked
```C#
public bool IsFromMockProvider  => false;
```
#### Shiny.Locations/Platforms/Tizen/GpsReading.cs 
Is there a way to check is gps mocked? With the tizen location manager we can only check if a mock location is enabled, but it may not help determine if each location is mocked.
```C#
public bool IsFromMockProvider  => false;
```

## Intended Use Case
As an example, I would like to use a custom gps delegate that would not perform any action if the gps data were received from mock provider

**Comment by aritchie** [comment]
This isn't something I want to add at this time since it only applies to Android.
