### ISSUE TITLE
[iOS] App Store Connect finds references of NSLocationAlwaysUsageDescription, NSLocationWhenInUseUsageDescription when Shiny.Notifications and Shiny.Core are solely used

### ISSUE THREAD

**Issue by gsgou** [shinyorg/shiny#527]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [+] iOS

## Feature Library

 - [+] Core
 - [+] Notifications

## Version of Library

 1.2.0.1755

## Version of OS(s) listed above with issue

iOS 14.4

## Steps to Reproduce

Add Shiny.Notifications Version 1.2.0.1755 as .net standard project
Add Shiny.Core Version 1.2.0.1755 in iOS project

## Expected Behavior

No reports from App Store Connect that
Your app has one or more issues.

Is it solved in a preview Version?

## Actual Behavior

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by aritchie** [comment]
This is not a bug.  Link out what you don't need.  Core shares some location code for beacons and locations

**Comment by aritchie** [comment]
Version 2 will have a separate common library to remove location from core

**Comment by gsgou** [comment]
Thanks for your Feedback @aritchie. 
Is location already removed from the Core in v2 Preview?
Link All and skipping the ones with issues will be a painful process.

**Comment by aritchie** [comment]
No - it is not separated yet.

**Comment by gsgou** [comment]
@aritchie there is a similar issue when a user wants to use local notifications only but no push with
the App Store Connect analysers reporting: ITMS-90078: Missing Push Notification Entitlement.
Looks like moving interface IAppDelegatePushNotificationHandler out of Core would bring more flexibility.
https://stackoverflow.com/questions/14722664

I noticed you already created Shiny.Locations.Common,
thanks a lot for providing us such a powerful lib.

**Comment by aritchie** [comment]
It doesn't make anything more flexible.  Warnings around location are something I watch because of Apple.  Warnings around push notifications only don't worry me, so I won't be moving those out right now.  If you are really only using Shiny for notifications, you really are taking a lot into a project for minimal gain.  Notifications was meant as a addin for everything else.

**Comment by gsgou** [comment]
Personally i ll use in a project Notifications (also IPersistentNotification which haven't seen in other lib in), Settings,
adding soon Background Jobs and Geofencing without planning at all push notifications. So shiny is irreplaceable!
I do understand the point and your focus, location has a different severity in warnings for partners. Again thank you.
