### ISSUE TITLE
BluetoothLE GATT Server (API Controller Style)

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#53]
## Summary
This is being considered so that GATT Server setup can be vastly simplified.

## API Changes
TBD

## Intended Use Case
More details to be provided via specifications

**Comment by melvyniandrag** [comment]
I'd love to see this happen, or, better yet, contribute. Been looking at the shiny src and samples and can't figure out how to start a gatt server. In the Samples/BlePeripherals directory there is a MainViewModel that takes two params, an IPeripheralManager and IUserDialogs. I have about one day experience with Xamarin Forms but it looks like I need a Binding Context. I need to create a new MainViewModel() in MainPage.xaml.cs, but have no idea what params to pass to it.

The code compiles and runs but I the UI buttons don't do anything, which makes me think I need a binding context.

Looks like your old ACR plugin had a catch-all CrossBleAdapter that had a simple method to start a server CreateGattServer() but my grep results make it look like CrossBleAdapter.Current is gone in shiny.

Could you give a heads up if that sample code with the shiny library is working now? Maybe I'm banging on something that isn't even supposed to run wondering why it wont start!

**Comment by aritchie** [comment]
Hi @melvyniandrag I appreciate the interest in Shiny.  I'm not really doing support during the beta since things can/will change and I haven't finished documentation at all.  For now, the interface you are looking for is Shiny.BluetoothLE.Peripherals.IPeripheralManager and that is injected into the pages where you need to use it.

To my knowledge, most of the peripheral mode is working for what is complete so far.  I'm not sure what platform is giving you the problem and I have no details to go off, but in any case, the answers you need are above.

That being said, please don't post support requests in the roadmap features.

**Comment by aritchie** [comment]
As for this particular feature - this is something that is being looked at for a future version and I haven't fully decided on a specification yet, so this wouldn't likely be something the community would take on until that time.

**Comment by melvyniandrag** [comment]
Thanks for the quick and helpful response. Ill keep on eye on shiny throughout the beta phase and probably stick with the old ACR BLE plugin until this reaches stable. Sorry to clutter this thread with a support request, I wouldn't take it the wrong way at all if you deleted our conversation for the sake of consistency and tidiness.

**Comment by aritchie** [comment]
You definitely don't need to be sorry - you are welcome to post feedback and suggestions here as you work with the library.  I would recommend using the plugin for now if you are looking to use it in a production project.  The upgrade path to Shiny will be mostly straight forward.
