### ISSUE TITLE
Tapping "Don't Allow" crashes on iOS 14.4

### ISSUE THREAD

**Issue by gcadmes** [shinyorg/shiny#533]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] iOS
 - [ ] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

## Feature Library
Shiny.BluetoothLE 

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ x] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.2508-preview
## Version of OS(s) listed above with issue
=== Visual Studio Community 2019 for Mac ===

Version 8.8.10 (build 2)
Installation UUID: 4454862f-e0a7-4135-8114-aed86c176f82
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.103/Sdks
SDK Versions:
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.0.101
	2.1.505
	2.1.302
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.0.1
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.9
	2.1.2
	2.0.5
	2.0.0
	1.1.2
	1.0.5

=== .NET Core 3.1 SDK ===

SDK: 3.1.406

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/gregcadmes/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.0 rc1

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/gregcadmes/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:34:58 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:35:22 UTC

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.4.0.10 (Visual Studio Community)
Hash: a4c70e7d0
Branch: xcode12.4
Build date: 2021-02-17 17:40:51-0500

=== Xamarin.iOS ===

Version: 14.10.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:23-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Build Information ===

Release ID: 808100002
Git revision: f81ffa2444a28c09f173849935ec9ee0195a5b17
Build date: 2021-02-18 12:02:12-05
Build branch: release-8.8
Xamarin extensions: f81ffa2444a28c09f173849935ec9ee0195a5b17

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

## Steps to Reproduce
1. Create Xamarin.IOS native app
2. Invoke Scan so as to initiate the BLE prompt
3. Click "Don't allow"

## Expected Behavior
Gracefull exit & error handling

## Actual Behavior
After clicking "Don't Allow", the app crashes.
This even after wrapping the BleManger.Scan in a try/catch.

"  at Shiny.BluetoothLE.BleManager+<>c.<Scan>b__11_0 (Shiny.AccessState access) [0x00004] in /_/src/Shiny.BluetoothLE/Platforms/ios+tvos/BleManager.cs:95 \n  at System.Reactive.Linq.ObservableImpl.Do`1+OnNext+_[TSource].OnNext (TSource value) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:38 \n--- End of stack trace from previous location where exception was thrown ---\n\n  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:19 \n  at System.Reactive.ExceptionHelpers.Throw (System.Exception exception) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:16 \n  at System.Reactive.Stubs+<>c.<.cctor>b__2_1 (System.Exception ex) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:16 \n  at System.Reactive.AnonymousSafeObserver`1[T].OnError (System.Exception error) [0x00010] in <3ad0cc868be642ac8d0c22906bb12ddb>:0 \n  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0 \n  at System.Reactive.Linq.ObservableImpl.Buffer`1+TimeHopping+_[TSource].OnError (System.Exception error) [0x0001c] in <3ad0cc868be642ac8d0c22906bb12ddb>:0 \n  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0 \n  at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0 \n  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0 \n  at System.Reactive.Linq.ObservableImpl.SelectMany`2+ObservableSelector+_[TSource,TResult].OnError (System.Exception error) [0x00011] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:887 \n  at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:60 \n  at System.Reactive.Linq.ObservableImpl.Do`1+OnNext+_[TSource].OnNext (TSource value) [0x0000f] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:42 \n  at System.Reactive.AutoDetachObserver`1[T].OnNextCore (T value) [0x00002] in /_/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs:61 \n  at System.Reactive.ObserverBase`1[T].OnNext (T value) [0x0000d] in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:34 \n  at Shiny.RxExtensions.Respond[T] (System.IObserver`1[T] ob, T value) [0x00000] in /_/src/Shiny.Core/Extensions_Rx.cs:94 \n  at Shiny.BluetoothLE.BleManager+<>c__DisplayClass5_0.<RequestAccess>b__1 (Shiny.AccessState _) [0x0001b] in /_/src/Shiny.BluetoothLE/Platforms/ios+tvos/BleManager.cs:34 \n  at System.Reactive.AnonymousObserver`1[T].OnNextCore (T value) [0x00000] in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:67 \n  at System.Reactive.ObserverBase`1[T].OnNext (T value) [0x0000d] in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:34 \n  at System.Reactive.Subjects.Subject`1[T].OnNext (T value) [0x0002a] in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:147 \n  at Shiny.BluetoothLE.Internals.CentralContext.UpdatedState (CoreBluetooth.CBCentralManager central) [0x0003d] in /_/src/Shiny.BluetoothLE/Platforms/ios+tvos/Internals/CentralContext.cs:136 \n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 \n  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:178 \n  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 \n  at sharelinkpro1k.iOS.Application.Main (System.String[] args) [0x00001] in /Users/gregcadmes/Projects/extron-seahawks-mobile/iOS/Main.cs:12 "

**Comment by aritchie** [comment]
You can’t try/catch around an observable!  This isn’t a bug.

**Comment by gcadmes** [comment]
@aritchie You can't read? I mentioned that I already applied a try/catch.  Your issue is 'unhandled'. 
How bout this, delete your test app, re-install it on an iPhone running iOS 14.4, when you get the OS prompt, click "Don't Allow" and watch your test app crash.

So, should I re-create this or create a new one?

**Comment by aritchie** [comment]
> @aritchie You can't read? I mentioned that I already applied a try/catch.  Your issue is 'unhandled'  How bout this, delete your test app, re-install it on an iPhone running iOS 14.4, when you get the OS prompt, click "Don't Allow" and watch your test app crash.  So, should I re-create this or create a new one?

I've reposted your rude comment for clarity :)

1) I can read just fine.  It was you who didn't read what I said.  You cannot try/catch around an observable, you catch in the subscribe.  https://github.com/shinyorg/shiny/blob/dev/samples/Samples/BluetoothLE/AdapterViewModel.cs#L102 - Your test case passes perfectly here.  

2) Did you follow the issue template for the beta?  Did you post reproducible sample and a stack trace?  NO!!

3) "So, should I" just ban you for your rude comments?  "How bout this" be nice when you aren't educating yourself on the use of the APIs before making a comment like this

**Comment by aritchie** [comment]
This is not how you behave in OSS.  The author deleted all of their comments knowing they were so far in the wrong it was insane - no issued apology... no thank you.... just pure unaccountability.  The author of this issue has been removed from ever posting here again.  As has the user who decided to +1 his comment
