### ISSUE TITLE
Geofence not triggering after rebooting device

### ISSUE THREAD

**Issue by rajuntech** [shinyorg/shiny#534]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [x] Locations

 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Steps to Reproduce
1.Integrated shiny core as described in docs
2. Created geofence 
3. added   uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"   in android manifest

## Expected Behavior
After rebooting device geofence should trigger if user enter into region without manually starting the app

## Actual Behavior
when app up and running its working fine, when app is closed also no issue, After rebooting device geofence not trigger if user enter into region without manually starting the app

**Comment by aritchie** [comment]
People didn't like their apps being spun up because of the library.  I've been looking up ways to make this part of v2.  You are best to add a blank broadcast receiver with the receive boot intent for now

**Comment by rajuntech** [comment]
Thanks @aritchie ,
In your docs you mentioned <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" /> permission for jobs so will they start after reboot ?

**Comment by aritchie** [comment]
Docs haven't been updated.

**Comment by rajuntech** [comment]
Ok Thanks

**Comment by rajuntech** [comment]
> workmanager.

Jobs are also not triggering after reboot

**Comment by aritchie** [comment]
They work fine for me.  You should research WorkManager for more details on this subject.
