### ISSUE TITLE
Moved functionality thant it's not indicated on the documentation

### ISSUE THREAD

**Issue by sgermosen** [shinyorg/shiny#535]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)
I collaborated in the past, I hope it still be valid jejeje

I have this piece of code on the 1.2 version of Shiny.BluetoothLe

Now Im moving to 2.0 but this method "WhenAnyCharacteristicDiscovered" it doesn't work, and on the documentation it still the example of the 1.1 version

 void ConnectPrinter(IPeripheral selectedPeripheral)
        {
            if(!selectedPeripheral.IsConnected())
                selectedPeripheral.Connect();

            _perifDisposable = selectedPeripheral.**WhenAnyCharacteristicDiscovered**().Subscribe((characteristic) =>
            {
                //System.Diagnostics.Debug.WriteLine(characteristic.Description); //this is not suppported at this momment, and no neccesary I guess
                if (characteristic.CanWrite() && !characteristic.CanRead() && !characteristic.CanNotify())
                {
                    IsReadyToPrint = true;
                    _savedCharacteristic = characteristic;
                    System.Diagnostics.Debug.WriteLine($"Writing {characteristic.Uuid} - {characteristic.CanRead()} - {characteristic.CanIndicate()} - {characteristic.CanNotify()}");
                    _perifDisposable.Dispose();
                }
            });
        }
      

I hope than if you can help me it will be great, :D

**Comment by aritchie** [comment]
Shiny 2.0 is not yet released and thus the documentation has not been released either.  I also don't take issue reports for documentation... only PR's since this is OSS not a product.  

Lastly, please note, that this area is meant for project sponsors or OSS maintainers.

**Comment by sgermosen** [comment]
With "I Colaborate" I really mean than I buy you two coffes once, some month ago, jeje, but it;s ok, I will wait until the final release, thanks

**Comment by aritchie** [comment]
I'm sorry.  That's not how this works.  Time is money, the source code is already given away for free, and a lot of people are constantly sending me messages asking for personal support.  This is open source, you can go through the project to get your own answers in less time than it takes to open a support request.  

It's these types of requests that really drain OSS maintainers and cause projects to die which is why the model had to change.
