### ISSUE TITLE
How to do run long background task (Signal R for pushing notification)

### ISSUE THREAD

**Issue by arivera12** [shinyorg/shiny#536]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [x] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

Latest

Hi,  

I am trying to create a background task that runs a parts from the main app so apps stay connected to the signal r hub even if the app is closed. 

I tried using Jobs and got them working successfully with the hub and receives notification but they only work while the app is not closed. 

Is there any component which handles long background running services per platform so we can still receive notifications? 

I know that ios doesn't allow long running process but android should work.

I read this [article](https://allancritchie.net/posts/shinyjobs)  that talks about shiny jobs from you but I could not make it as backgrounding job when the app is closed.

Thanks for this awesome library!

**Comment by arivera12** [comment]
What?!....

**Comment by aritchie** [comment]
Jobs only run for 30 seconds on iOS while in the background.  Android can give you anywhere between 1-2 minutes.

Please note that this is NOT a support forum

**Comment by arivera12** [comment]
@aritchie thanks for the head notes!
