### ISSUE TITLE
Use GooglePlayServiceGpsManager when ServiceMissing???

### ISSUE THREAD

**Issue by HausBJB** [shinyorg/shiny#541]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.0.2542-preview

## Steps to Reproduce
1.Go To  shiny/src/Shiny.Locations/Platforms/Shared/GpsModule.cs
2. Line 31
3.
![image](https://user-images.githubusercontent.com/53478848/111479182-07445c80-8731-11eb-90e6-68334d1f2c38.png)

**Comment by aritchie** [comment]
Send PR's for stuff like this in the future please
