### ISSUE TITLE
[Preview][Android] Local Notifications with Channel not applying actions

### ISSUE THREAD

**Issue by Codelisk** [shinyorg/shiny#544]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

I tried to figure out how I can implement Actions into my Push Notifications. Something like that:
![image](https://user-images.githubusercontent.com/51824173/111960982-b8ac0f00-8af0-11eb-9388-80819ffe5975.png)

However I was not able to get it working (only tried on Android) and surfed the code a little. 
I found that in the NotificationManager_Channels.cs
![image](https://user-images.githubusercontent.com/51824173/111961104-e4c79000-8af0-11eb-98b2-484090db8b24.png)

and saw that the ApplyChannel method never seems to be used in the project.

Is that the right method which should be applied for Notification Actions to work? If so and you want me to I could try to create a PR for that. Of course, if you know that Action Types are working for Android already and I did something wrong just let me know and I will try some other things

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [X ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.2542-preview
## Version of OS(s) listed above with issue
Android 9 and 10

## Steps to Reproduce
1. Set a channel:
```
var c = new Channel();
            c.Identifier = "benach";
            c.Importance = ChannelImportance.Critical;
            c.Actions = new List<ChannelAction>
            {
                new ChannelAction
                {
                    Identifier="o",
                    Title="OKAY",
                    ActionType= ChannelActionType.OpenApp
                },
                new ChannelAction
                {
                    Identifier="t",
                    Title="Text Reply",
                    ActionType= ChannelActionType.TextReply
                }
            };
            await NotificationManager.CreateChannel(c);
            await NotificationManager.SetChannels(c);
```
            
2.
Send a Push Notification with a ChannelId OR a normal Notification:
```
await NotificationManager.Send(new Notification
            {
                Channel = "benach",
                Title = "Test",
                Message = "Hallo",
            });
```
3. Look how the Notification is shown

## Expected Behavior

![image](https://user-images.githubusercontent.com/51824173/111961104-e4c79000-8af0-11eb-98b2-484090db8b24.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/51824173/111961870-dd54b680-8af1-11eb-9626-de98ad4719b6.png)

## Sample
Be careful Sample is a bit messy :)
https://github.com/Codelisk/ShinyFirebasePushSample

**Comment by aritchie** [comment]
Push has nothing to do with this.  The bug is 100% in the notifications library which has be resolved for the next preview release.
