### ISSUE TITLE
Local Notification not working on Android 7.1

### ISSUE THREAD

**Issue by sunsiz** [shinyorg/shiny#547]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [*] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [*] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1755
## Version of OS(s) listed above with issue
Android 7.1

## Steps to Reproduce
1. Clone this repo https://github.com/brminnick/LocalNotificationsSample
2. Upgrade all packages and change Android SDK version to 10 Q (default is 11, i have installed 10), set Target Android Version too Android 10.0 (API Level 29 -Q).
3. Check Deploy in Solution Properties -> Configuration Properties -> Configuration (otherwise it wont deploy).
4. Debug it on Android 7.1 (I tested on my phone and emulator. It works well on Android 9 emulator).

## Expected Behavior
Display notifications.

## Actual Behavior
Throw blow errors:
Java.Lang.ClassNotFoundException: 'Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/com.minnick.localnotificationssample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.minnick.localnotificationssample-1/lib/arm64, /data/app/com.minnick.localnotificationssample-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /data/downloads, /data/priv-downloads]]'

On the internet some people says before Android Oreo there is no Notification Channel, so you should avoid create channel if it's blow Android 8. Maybe that's the reason. Please check it and give asolution.

**Comment by aritchie** [comment]
Sounds like the tooling broke or something because 1.2 used to compile fine for that OS as I wouldn't use notification channels in the execution path for them.

In any case, in 2.0 which is near release, I don't plan to support lower than Android 8 since we are into v12 betas at this point

**Comment by sunsiz** [comment]
I have tried some days with this Notification plugin and never make it work on Android 7.1 (works well on Android 9). So i tried that example repo and still won't work. at the end figured out if write Application class like blow it also throw exception:

[Application]
    public class MainApplication : Shiny.ShinyAndroidApplication<YourNamespace.YourShinyStartup>

Instead simply write like this it will compile fine and run

    public class MainApplication : Application

But still not showing notification on Android 7.1 (Android 9 still show notification).
At first i thought maybe I'm using it wrong way, so tried different usages on the internet without succeed.
What should I do? using the older version?

**Comment by aritchie** [comment]
You should fork this project and patch it to your needs if you require anything below 8.1

**Comment by sunsiz** [comment]
Thanks for information and your great work. It worked on 1.0.0.1182
