### ISSUE TITLE
AndroidForegroundService cannot change title and message

### ISSUE THREAD

**Issue by HausBJB** [shinyorg/shiny#548]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

There is no possibility to change the this.service.title and this.service.message
shiny/src/Shiny.Notifications/Platforms/Android/AndroidForegroundService.cs
![image](https://user-images.githubusercontent.com/53478848/112367547-5b73b180-8cda-11eb-80a2-d2058a9134fd.png)

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [x ] Locations
 - [ ] HTTP Transfers
 - [ x] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Steps to Reproduce
1.
2.
3.

**Comment by aritchie** [comment]
ok - this is the second time you have abused this forum today.  No reproducible sample, what you are trying to accomplish, or actual exception.  This is in preview... you can either 
a) wait until it is released 
b) follow the issue template FULLY
c) send PRs

This does work fine but hasn't been documented how to do it yet.

**Comment by HausBJB** [comment]
Hello ok i'm sorry i don't know what i did wrong. I didn't ask for anything and that should only be information and any information helps. i have only briefly tested the library and do not use it, so i have no advantage in helping you.
