### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#55]
## Summary
Support macOS

## API Changes
This is contigent on multitargeting in vs4mac due to mac support not be available on windows VS

## Intended Use Case
TBD

**Comment by RLittlesII** [comment]
@aritchie What would it take to get local notifications working for macOS?

**Comment by aritchie** [comment]
@RLittlesII A base implementation would be pretty easy... by base I mean - send a notification.  Not sure about scheduled notifications and customization.  I'll take a look though.

**Comment by RLittlesII** [comment]
Just let me know if you accept PR's I've got some other logging mac stories to do and wouldn't mind digging into the API's to learn more.

**Comment by aritchie** [comment]
@RLittlesII I absolutely do take PRs.  I managed to get the mac sample app up and running.

**Comment by kcrandall** [comment]
I would love this👍. Especially Bluetooth packages. NFC would be cool too but would require interfacing with external readers over USB, probably too much work, but worth putting up an issue for it.

**Comment by janusw** [comment]
> I would love this👍. Especially Bluetooth packages.

+1 for BLE on Mac 👍

https://github.com/aritchie/bluetoothle apparently has Mac support, but it's not working for me on Big Sur (crash in native code). Are there any chances to see BLE on Mac in shiny anytime soon?

**Comment by aritchie** [comment]
@janusw Maybe through Mac Catalyst?  I don't have a professional need for it at all right now.

**Comment by dansiegel** [comment]
@janusw if you hire @aritchie to build it out for you then he'll have a selfish professional need to do it 😆

**Comment by janusw** [comment]
> @janusw Maybe through Mac Catalyst? I don't have a professional need for it at all right now.

Huh, too bad. Since bluetoothle's ReadMe says that it's moving to shiny, I was hoping you'd port over that part as well. In principle bluetoothle's feature set is sufficient for my purpose (if it weren't for the Big Sur bug).

Actually my main targets are iOS & Android, though. So yeah, maybe Catalyst is an option.

**Comment by aritchie** [comment]
I moved what I needed and wanted to support.  macOS didn't fit into any of those buckets, so it did move. Fork the BLE one and fix it then

**Comment by janusw** [comment]
> Fork the old repo and fix it then

Huh, I'm not really keen on forking and maintaining a dead repo. Maybe I'd rather go with  [xamarin-bluetooth-le](https://github.com/xabre/xamarin-bluetooth-le) then. It seems to have a similar problem with Big Sur, but at least it's not completely dead ...

**Comment by aritchie** [comment]
I've gotten rid of all the useless +1 comments.  FYI - starting every comment with a huh is condescending... just saying

macOS will come with 1 of the following
1. when I'm damn well ready to add it
2. when someone contributes it
3. when I'm doing it on a professional project.

**Comment by aritchie** [comment]
Since maccatalyst is coming with net6, I'm going to be dropping out of the macOS category.  If anyone has an absolute need for full mac, feel free to comment, but it is unlikely that I'll be adding this
