### ISSUE TITLE
IGpsManager.GetLastReading() failed on the second call

### ISSUE THREAD

**Issue by KevinHu-au** [shinyorg/shiny#557]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

Hi Allan,
Can I have you advise on one of the problem I got on Android when the app was calling IGpsManager.GetLastReading()?

The environment basics:
- Shiny 1.2.0.1755
- Android Device: Samsung A20 (Android 10.0)
- Xamarin.Android: 11.2.2.1
- Permissions in AndroidManifest: Background Location/CoarseLocation/FineLocation/MockLocation etc.

If "Allow all the time" is granted to the app, then it works perfectly. 
But if "Allow only while using the app" is granted to the app, the first call to IGpsManager.GetLastReading() will get the user current location correctly, but it throws an exception for the second and further calls to IGpsManager.GetLastReading().

I have checked the source code of Shiny library, I can see that the GpsRequest has UseBackground with value of true by default, and then it will call ActivityCompat.RequestPermissions with background location and fine location permissions in AndroidContext.RequestAccess() method.

I am confused with two questions:
1.  Why the first call will get location reading correctly even the app is authorised with "Allow only while using the app"?
2. Why the second and later calls all failed with exception (was thrown by "access.Assert()" as background location access is not granted)?

BTW, I checked the latest code for this part. Seems like same as the 1.2.0.1755.

Appreciate your time to answer my support questions.

Regards,
Kevin Hu

**Comment by aritchie** [comment]
This was a bug that was actually corrected in the preview only a couple of days ago.  Can you share your stack trace and version just to confirm?

**Comment by KevinHu-au** [comment]
@aritchie , Thanks for your response. I will do it next week after the Easter Holiday.

**Comment by KevinHu-au** [comment]
@aritchie , The version I am using is 1.2.0.1755. Please have the stack trace as below:
<img width="1344" alt="Screen Shot 2021-04-06 at 1 38 49 pm" src="https://user-images.githubusercontent.com/8989917/113655822-e17df800-96dd-11eb-9e69-d9f57aee9ae1.png">

**Comment by KevinHu-au** [comment]
@aritchie BTW, I saw the changes in the 'preview' branch. Do you have a plan for the next release?

**Comment by aritchie** [comment]
I can't see the stacktrace properly from a screenshot.  You need to copy it out from the console.
Also, is this the latest preview?

**Comment by KevinHu-au** [comment]
I got the copy of the stacktrace as below. Thanks

System.ArgumentException: Invalid State Denied
  at Shiny.GeneralExtensions.Assert (Shiny.AccessState state, System.String message, System.Boolean allowRestricted) [0x0000d] in /Users/kevinhu/Source/shiny/src/Shiny.Core/Extensions_General.cs:16
  at Shiny.Locations.GpsManagerImpl.<GetLastReading>b__12_0 () [0x0007b] in /Users/kevinhu/Source/shiny/src/Shiny.Locations/Platforms/Android/GpsManagerImpl.cs:40

**Comment by aritchie** [comment]
This was fixed in 2.0

**Comment by KevinHu-au** [comment]
Thanks @aritchie
