### ISSUE TITLE
WASM/Uno/Blazor

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#56]
## Summary
Support standard WASM .NET platform so Shiny can work with either Blazor or Uno.

## API Changes
TBD

## Intended Use Case
TBD

**Comment by TopperDEL** [comment]
UNO would be great!

**Comment by drannex42** [comment]
Any updates on this?

**Comment by aritchie** [comment]
WASM work has moved to a different repo for consideration in the long term.  https://github.com/shinyorg/wasm
