### ISSUE TITLE
Generator fails to add base.OnCreate to SplashActivity

### ISSUE THREAD

**Issue by dansiegel** [shinyorg/shiny#564]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [x] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

latest 2.0 preview

## Version of OS(s) listed above with issue

AndroidX

## Steps to Reproduce
1. Add the Shiny Generators to an Android Project
2. Have a Splash Activity

## Expected Behavior
App should launch

## Actual Behavior
App fails to launch with Android error that super.OnCreate was not called... in C# terms... the Generator fails to add a call to base.OnCreate in the generated OnCreate of the SplashActivity

**Comment by aritchie** [comment]
Thanks for the fix!
