### ISSUE TITLE
Shiny: .NET MAUI compatibility

### ISSUE THREAD

**Issue by nitinjs** [shinyorg/shiny#567]
## Summary
shiny is compatible with .net maui? 
will it work seamlessly across windows, android, mac and ios?

## Intended Use Case
I want to use shiny BLE api in .net maui project, I wonder if it is compatible
and will it run on android/ios/macos/windows without any issues?

**Comment by aritchie** [comment]
No idea - .NET MAUI is no where near ready, so this project will not be looking at it until a later date
