### ISSUE TITLE
[Android] BLE Pairing

### ISSUE THREAD

**Issue by softlion** [shinyorg/shiny#575]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [X] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

using source code / dev branch.

## Version of OS(s) listed above with issue

Android 6

## Steps to Reproduce
1. Try to manually pair a scanned android device
2. Add breakpoint in ManagerContext.DeviceEvent()
3. Add a case:
```csharp
                case BluetoothDevice.ActionBondStateChanged:
                    var bondState = intent.GetIntExtra(BluetoothDevice.ExtraBondState, (int)Bond.None);
                    var pBoundState = peripheral.Native.BondState;
                    var areEqual = pBoundState == boundState;
                    break;
```

## Expected Behavior
areEqual is true

## Actual Behavior
areEqual is false, and peripheral.Native.BondState is still None.  
But bondState is "Pairing".

## Consequence
The code in Peripheral.PairingRequest is wrong. The observable with this line:
```
.Where(x => this.Context.NativeDevice.BondState != Bond.Bonding)
```
will pass when the bonding is still in progress, and that will cancel the bonding every time.

**Comment by aritchie** [comment]
It looks like your were banned off my repos a long time ago for VERY good reasons:  https://github.com/aritchie/deviceinfo/issues/28  

Please continue to stay respectful and I'll remove the ban going forward.

**Comment by aritchie** [comment]
Note that Android 6 will not officially be supported in Shiny 2, only 8+

**Comment by softlion** [comment]
Tested on android 6 does not mean it is fixed on android 7+.

i still feel the same about your repos, no change. I understand you don’t like that. Me neither.

**Comment by aritchie** [comment]
@softlion You are human scum man.  Rude, entitled, etc.  You will never be welcome in any project I'm apart of again.
