### ISSUE TITLE
[Android] Code generation issue

### ISSUE THREAD

**Issue by enny1170** [shinyorg/shiny#578]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x ] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [x] Core (Jobs, Settings, Initialization)
 - [x] Locations (GPS, Geofencing, Motion Activity)
 - [x] HTTP Transfers
 - [x] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [x] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.0.0.0.2639
## Version of OS(s) listed above with issue
none

## Steps to Reproduce
1. Create a XamainForms Project with Android and Ios
2. Fallow the Quickstart adding Startup.cs to Shared Project and Attributes to MainActivity in the android Project like this:
   [assembly: Shiny.ShinyApplication(
    ShinyStartupTypeName ="BeetControl.Startup",
    XamarinFormsAppTypeName ="BeetControl.App")]
namespace BeetControl.Droid
{
3. click on Build for the Android Project

## Expected Behavior
Build should be finished without Error

## Actual Behavior
Build failed with fallowing Errors:
2>"C:\Users\install\source\repos\BeetControl\BeetControl\BeetControl-Expert.Android\BeetControl-Expert.Android.csproj" (Rebuild;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies Ziel) (1) ->
2>(CoreCompile Ziel) -> 
2>  C:\Users\install\source\repos\BeetControl\BeetControl\BeetControl-Expert.Android\Shiny.Generators\Shiny.Generators.AndroidApplicationSourceGenerator\MainApplication.cs(8,30,8,37): error CS0116: Member, wie z. B. Felder oder Methoden, können nicht direkt in einem Namespace enthalten sein.
2>  C:\Users\install\source\repos\BeetControl\BeetControl\BeetControl-Expert.Android\Shiny.Generators\Shiny.Generators.AndroidApplicationSourceGenerator\MainApplication.cs(8,22,8,23): error CS1514: { erwartet.
2>  C:\Users\install\source\repos\BeetControl\BeetControl\BeetControl-Expert.Android\Shiny.Generators\Shiny.Generators.AndroidApplicationSourceGenerator\MainApplication.cs(9,1,9,2): error CS1022: Typ- oder Namespacedefinition oder Dateiende erwartet.

sorry my system is setup in german.

I can't find the files in this error message so what can i do to find the reason

regards Enrico

**Comment by aritchie** [comment]
I need a reproducible sample please.  I can't read german, so I can't really tell by the stacktrace.

You can also wire it up manually in the meantime

**Comment by aritchie** [comment]
You can't see this file: C:\Users\install\source\repos\BeetControl\BeetControl\BeetControl-Expert.Android\Shiny.Generators\Shiny.Generators.AndroidApplicationSourceGenerator\MainApplication.cs ?

I believe the problem is the assembly name which is used when RootNamespace isn't present.  The dash (-) isn't valid as a namespace.  

Please send that file or the reproducible case.  You can also try renaming the project (ensuring that the assembly name also is void of the dash) and clean/build.  Sometimes you need restart VS when doing this as source generators are new.

**Comment by enny1170** [comment]
Hello, you are right. The - in the ProjectName was the reason. I have renamed the Project. 
The root namespace 'BeetControl.Droid' was already without the dash. So i'm guess the Code-Generater does not use the root namespace set in the project. After change Project and Assembly Name to BeetControlExpert.Android the Build was successful.
I will create an Example to reproduce it in the next few hours and send it to you.

**Comment by enny1170** [comment]
Yes the Assembly Name will be used for the namespace. See attached Test project
[ShinyTest.zip](https://github.com/shinyorg/shiny/files/6431949/ShinyTest.zip)

**Comment by aritchie** [comment]
This is fixed for the next patch which will be next time some week.  Thanks for the report

**Comment by enny1170** [comment]
Thank you for this great Lib and support
