### ISSUE TITLE
[Feature Request]: MAUI Support

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#580]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
* Shim to MAUI lifecycle events
* Keep reference to MAUI service collection to allow for state restorable services (may need a marker on this now) and startable services that trigger when apphost builds collection
* Support apphost builder.  Despite marketing from MSFT, it won't be UseShiny :)

## API Changes
Hopefully none - it should be shimmed, but may involve apphostbuilder integration

## Intended Use Case
Work with MAUI and .NET 6

**Comment by aritchie** [comment]
This is on pause temporarily until MAUI is much more stable.

**Comment by aritchie** [comment]
Current challenges with MAUI
* detecting service provider (is ready) to bind objects and run IShinyStartupTasks

**Comment by drewid** [comment]
Things looking any better on stability?

**Comment by berhir** [comment]
MAUI will reach RC status soon (hopefully it won't be postponed again). Is this feature request still "Blocked"? Do you have plans to provide a preview version with MAUI support before MAUI reaches GA?

**Comment by aritchie** [comment]
@berhir please be respectful of the code of conduct. This is not a product.  I'm not under a timeline.  You can already shim Shiny into MAUI very easily but you have to compile to .NET 6 yourself.

The tooling for MAUI is still very rough, so I'm not investing time into it yet.  Once I feel it is at a state that I can work with it, I will unmark the "blocker".

**Comment by berhir** [comment]
Sorry, it was not my intention to be disrespectful and I didn't expect a detailed timeline. It's just that I noticed that this issue is "In-Progress" in the v3 project, and I was curious if you are actively working on it.

I fully understand your decision that MAUI is not yet stable enough to invest in it.

Thank you for providing this information, it helps me to better plan our MAUI migration.

**Comment by aritchie** [comment]
For anyone that continues to try and pressure for a MAUI release - 1) STOP, I don't owe you an answer or anything.  2) The task is here, it is going to happen.  3) I can't test iOS properly (due to native libs like firebase) or full backgrounding without VS4mac which is still nowhere near ready

**Comment by aritchie** [comment]
The initial work and integration for MAUI is done on dev and will be released to alpha soon
