### ISSUE TITLE
HttpTransferRequest does not send file-content

### ISSUE THREAD

**Issue by TopperDEL** [shinyorg/shiny#59]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [X] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
v1.0.0.301-beta
## Version of OS(s) listed above with issue
Irrelevant

## Steps to Reproduce
1. Create a HttpTransferRequest providing a file from Android local storage (Image from Gallery)
2. Get the HttpTransferManager and Enqueue
3. See the request complete without any Bytes transfered

## Expected Behavior
The file gets transfered to my Webapi-Controller

## Actual Behavior
The request gets sent, but the Content is empty.

**Comment by TopperDEL** [comment]
May you give a quick hint at how an Upload would work? The docs stop at the interesting step - enqueing a new HttpTransfer into the injected IHttpTransferManager.

**Comment by aritchie** [comment]
Please provide a SMALL test case for this issue as it looks to be working just fine for me.

**Comment by TopperDEL** [comment]
Cannot reproduce it currently, sorry. I think it Was an error on my side. You May close this issue.
