### ISSUE TITLE
Shiny Push notification  to have it's own nuget . Would you consider it?

### ISSUE THREAD

**Issue by developer9969** [shinyorg/shiny#590]
## Summary
We have been badly bitten by appcenter no longer providing support for push notifications. We have not used Shiny before as what we had with essential was just fine , however your inclusion of push notification and the ability to be provider agnostic is great!.

Could you please consider to create a Shiny.Notifications nuget package as I guess this will be extremely popular with many that want to use just this feature of shiny?

Is shiny linker safe?

## API Changes
Move the Notification side of it in its own package

## Intended Use Case
To use shiny as a way to switch between push notification providers. We are currently using onesignal , but we could move to AzureHub etc...

Many thanks

**Comment by aritchie** [comment]
I’m not really sure what you are requesting? There already is a package called Shiny.Notifications that is used for local notifications (and internally by push)

**Comment by developer9969** [comment]
oh. I must have missed it! I thought It was one big package including them all. Apologies!!!

**Comment by aritchie** [comment]
No worries.  Glad you found what you need :)
