### ISSUE TITLE
Build error caused by 'Shiny.Generators.AndroidActivitySourceGenerator'

### ISSUE THREAD

**Issue by GavinFangCN** [shinyorg/shiny#591]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

## Feature Library

 - [x] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.0.0.2639

## Version of OS(s) listed above with issue
android 10.0

## Steps to Reproduce
1. follow https://shinylib.net/quickstart to install nuget packages
2. change 'main activity' be partial.

## Expected Behavior
build succeed.

## Actual Behavior
got error when I tried to integrate speed recognition to android: 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1501	No overload for method 'Init' takes 2 arguments	{dir}\Shiny.Generators\Shiny.Generators.AndroidActivitySourceGenerator\SplashActivity.cs	20	Active

ps. it seems the error was caused by 'global::Rg.Plugins.Popup.Popup.Init(this, savedInstanceState);',  the only method I can find in 'Rg.Plugins.Popup(2.0.0.1)' is Rg.Plugins.Popup.Popup.Init(Context context)

**Comment by aritchie** [comment]
Can you please submit a small reproducible sample

**Comment by aritchie** [comment]
Nevermind - I found it.  Thanks for the issue report
