### ISSUE TITLE
[Beacons] Android.Util.AndroidRuntimeException: 'Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by psmysupport** [shinyorg/shiny#594]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [x] Beacons
 - [ ] SQLite Integration

## Version of Library

2.0.0.2639

## Version of OS(s) listed above with issue

Android 10

## Steps to Reproduce
1. Set up Shiny with boilerplate 
2. Set up Android permissions in xml.
3. In ConfigureServices in your ShinyStartup class use: services.UseBeaconMonitoring<GovisitBeaconMonitorDelegate>();
4. Set up Singleton where you use: await ShinyHost.Resolve<IBeaconMonitoringManager>().StartMonitoring(new BeaconRegion("MySupportBeacon", uuid));

## Expected Behavior

That project can run and monitor a beacon without throwing an exception. 

## Actual Behavior

It takes about 0 - 20 seconds but this exception is thrown: 

Android.Util.AndroidRuntimeException: 'Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fae91b2 u0 com.companyname.beacongovisittest/crc641134d8fea1f9be25.ShinyBeaconMonitoringService}'

[GitHub link.txt](https://github.com/shinyorg/shiny/files/6546607/GitHub.link.txt)
[Output.txt](https://github.com/shinyorg/shiny/files/6546609/Output.txt)
[StackTrace.txt](https://github.com/shinyorg/shiny/files/6546610/StackTrace.txt)

**Comment by aritchie** [comment]
This usually means the notification library couldn't find something like an icon.  By looking at the test project you've provided, that would also seem to suggest this.  Try doing something like await ShinyHost.Resolve<INotificationManager>().Send(...) - you'll get a cleaner error this way

**Comment by psmysupport** [comment]
await ShinyHost.Resolve().Send(); ???

I just get red underline if I do that.

If you were referring to nofication.Send()? That works, no problem.  

![image](https://user-images.githubusercontent.com/69150775/119666353-965aa880-be35-11eb-8c9b-396e3bc25c40.png)
rline under Resolve if I do this.

**Comment by aritchie** [comment]
The github markdown removed the resolve to INotificationManager, but if the notification is working, there is something else going on.  I'll try out your test project.

**Comment by psmysupport** [comment]
I think I've found out what's wrong. In my custom BeaconMonitorDelegate where I implement the IBeaconMonitorDelegate and get OnStatusChanged.

You only get those 5 seconds in the background but OnStatusChanged keeps being hit again and again until the 5 seconds are spent and the app crashes. 

Do you know any way around this problem?

**Comment by aritchie** [comment]
That isn't the problem.  Please review the issue template (do not ask for workarounds or timelines).  I will look at your test project when I have some time.  You can also try preview versions as they are released.

**Comment by aritchie** [comment]
This is fixed in the latest preview
