### ISSUE TITLE
Monitoring beacons - OnExit always called right after OnEntry even when staying in region.

### ISSUE THREAD

**Issue by joeweininger** [shinyorg/shiny#596]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [X] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.2710

## Version of OS(s) listed above with issue
Android 10

## Steps to Reproduce
1.  Setup Beacon Monitoring
2. Start monitoring a region 
3. Come into that region 

## Expected Behavior
Region Enter fires

## Actual Behavior
Region enter fires and immediately after that region exit fire.

I think the issue is in this file shiny/src/Shiny.Beacons/Platforms/android+uwp/BackgroundTask.cs

```
async Task CheckStates(IList<Beacon> beacons)
        {
            var copy = this.GetCopy();
            var maxAge = DateTime.UtcNow.Subtract(TimeSpan.FromSeconds(20));  **// this will always be in the past**

            foreach (var state in copy)
            {
                foreach (var beacon in beacons)
                {
                    if (state.Region.IsBeaconInRegion(beacon))
                    {
                        state.LastPing = DateTime.UtcNow; **//this is now**
                        if (state.IsInRange == null)
                        {
                            state.IsInRange = true;
                        }
                        else if (!state.IsInRange.Value)
                        {
                            state.IsInRange = true;
                            if (state.Region.NotifyOnEntry)
                            {
                                await this.core.Services.RunDelegates<IBeaconMonitorDelegate>(
                                    x => x.OnStatusChanged(BeaconRegionState.Entered, state.Region)
                                );
                            }
                        }
                    }
                }
            }
            foreach (var state in copy)
            {
**//on first entry everything is true. LastPing will always be > maxAge. Seems maxage is setup wrong should be in the future not past?**
                if (state.IsInRange != null && state.IsInRange.Value && state.LastPing > maxAge)
                {
                    state.IsInRange = false;
                    if (state.Region.NotifyOnExit)
                    {
                        await this.core.Services.RunDelegates<IBeaconMonitorDelegate>(
                            x => x.OnStatusChanged(BeaconRegionState.Exited, state.Region)
                        );
                    }
                }
            }
        }
```

**Comment by aritchie** [comment]
This will be fixed in an upcoming preview
