### ISSUE TITLE
Add ability to add Scan Filter on Android. 

### ISSUE THREAD

**Issue by joeweininger** [shinyorg/shiny#597]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
On Android if the phone is asleep neither monitoring or ranging will work unless there is a scan filter setup. This was a change going forward from Android 8+. I prepose adding the ability to add scan filter when monitoring and ranging so it will continue to work when the phone is asleep.

## API Changes
I have some working code with the changes, just not sure where I added it is the correct place?

https://github.com/joeweininger/shiny/commit/a38d4afb9bf22736aba25d743c4696e3e7e03de5

Example of usage for monitoring 

```
var monitoring = ShinyHost.Resolve<Shiny.Beacons.IBeaconMonitoringManager>();
var beaconRegion = new Shiny.Beacons.BeaconRegion("AllBeaconMonitoring", Guid.Parse("MyGuid"), null, null);
await monitoring.StopAllMonitoring();
monitoring.SetScanFilter(new List<string>() { "MyServiceGuid" });
await monitoring.StartMonitoring(beaconRegion);
```

Example of usage for ranging

```
  ranging = ShinyHost.Resolve<IBeaconRangingManager>()
   .WhenBeaconRanged(new BeaconRegion(
    "AllBeaconRanging",
   Guid.Parse(Constants.Bluetooth.Proximity.Uuid)
  ), new List<string>() { "MyServiceGuid"})
 .Subscribe(beacon =>
 {
//do stuff when we find the beacons
Debug.WriteLine($"Found Beacon {beacon.Minor}. RSSI - {beacon.Rssi}");
});
```

## Intended Use Case
I have a bluetooth gate I would like to auto open when my phone is in my pocket. I setup monitoring and when OnEntry is called I then begin ranging for better accurate. When I'm about -50 RSSI I connect to the lock and open it.

**Comment by aritchie** [comment]
This isn't something I want to open up at all.  While you can technically cheat and do ranging in the background on android, it isn't something I want to support.  The monitoring should be working fine if the foreground service is running, if it isn't, please report an issue with all of the necessary information (model of phone, sample, etc)
