### ISSUE TITLE
Beacon scanning on Android does not work with Major of 0

### ISSUE THREAD

**Issue by joeweininger** [shinyorg/shiny#602]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [x] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.2710

## Version of OS(s) listed above with issue
Android 11

## Steps to Reproduce
1. Create a beacon region with a guid, major = 0, and minor = your number.
2. Start Monitoring

## Expected Behavior
Region Enter will fire

## Actual Behavior
Region entered never fires. 

Example fix below.

If create a region with major = 0 it turns it into null. I added a null check to change it back to 0.

`public static bool IsBeaconInRegion(this BeaconRegion region, Beacon beacon)
        {
            if (!region.Uuid.Equals(beacon.Uuid))
                return false;

            if (region.Major == null && region.Minor == null)
                return true;

            if ((region.Major ?? 0) != beacon.Major) // If create a region with major = 0 it turns it into null. I added a null check to change it back to 0
                return false;

            if (region.Minor == null || region.Minor == beacon.Minor)
                return true;

            return false;
        }`

**Comment by aritchie** [comment]
This isn't how beacons work.  You must supply a major before you can supply a minor.  Major and minors have to be between 1-65535
