### ISSUE TITLE
Container.Resolve<ILogger>() fails

### ISSUE THREAD

**Issue by IustinT** [shinyorg/shiny#603]
ONLY active OSS maintainers of other projects OR project sponsors can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)
THERE IS NO SUPPORT ON PREVIEW/BETA VERSIONS!  

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

Unable to resolve ILogger from DI container in Xamarin.Forms app with Prism.DryIoc.Forms, Shiny 2.0.0.2639, Prism.Magician 8.0.171-beta.

This is probably something I'm doing wrong but after hours of debugging and looking through the Shiny source code I just can't figure it out and I hope you can assist.

The Prism.Magician creates the App.Logger property that is resolved by calling Container.Resolve<ILogger>() but the problem is the container does not have any ILogger service registered.

IServiceCollection in ShinyStartup ConfigureServices does have an entry for Microsoft.Extensions.Logging.ILogger`1 but the container does not resolve the Microsoft.Extensions.Logging.ILogger`1 entry when using Container.Resolve<ILogger>().

I've added a test project if it helps.
[PrismIocFormsTest.zip](https://github.com/shinyorg/shiny/files/6603977/PrismIocFormsTest.zip)

**Comment by aritchie** [comment]
All loggers have to be "named" in some sense, so by that - all loggers are usually named by generic type or key, so when you inject a logger, it is always with a generic.  If you need to call a logger outside of raw dependency injection, you can use something like:

```cs
ShinyHost.Container.Resolve<ILogger<MyClass>>();

// or

ShinyHost.LoggerFactory.CreateLogger("your named value");
```

**Comment by IustinT** [comment]
This makes more sense now. I've added a manually created logger to make Prism.Magician happy and I've moved on. Thank you.
