### ISSUE TITLE
Activity called onPause and onResume when start a scan

### ISSUE THREAD

**Issue by lufo88ita** [shinyorg/shiny#605]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [x] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.0.0.2639

## Version of OS(s) listed above with issue
Android 10
Android 11
(at least)

## Steps to Reproduce
1. Open the sample I attached, run it 
2. Grant all the permission.
3. Click on the only button "Click here to start!' that will appear 
2. In the new window click on the only button "Start scan"

## Expected Behavior
The app start a scan and print the name of the device in range without triggering lifecycle event.

## Actual Behavior
The activity call OnPause and then OnResume.

I am not so skilled, but my guess the problem is in the method RequestAccess() (is called in the chain inside Scan())
https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Platforms/Android/BleManager.cs

My guess is it trigger an unwanted request to the OS thus trigger the activity lifecycle OnPause/OnResume. Maybe is possible to check if the permission is granted without performing a request, but is my guess. As I said I am not very skilled.

[SampleAndroid.zip](https://github.com/shinyorg/shiny/files/6617745/SampleAndroid.zip)

**Comment by aritchie** [comment]
What is the actual bug this is causing though? 

I request permissions before starting any of the features because users always forget and then file issues.  In the next release, I'll be checking the permission beforehand, but the plan is to leave the actual permission request if it hasn't been granted.

**Comment by lufo88ita** [comment]
"What is the actual bug this is causing though?"
Potentially an infinite loop if someone put inside onResume the call to Scan(). In my case I struggle to understand way a call in a fragment trigger a onPause() / onResume() in my main activity.

"I request permissions before starting any of the features because users always forget and then file issues. In the next release, I'll be checking the permission beforehand, but the plan is to leave the actual permission request if it hasn't been granted."
I mostly agree with you. I do not fully understand your code, so I don't know if it is possible to do something like this (it's pseudo-code, not actual code!):
```
if(ContextCompat.CheckSelfPermission(this, Manifest.Permission.AccessFineLocation) !=  Android.Content.PM.Permission.Granted) {
  //actual behavior
} else {
 return Granted;
}
```

regards,

**Comment by aritchie** [comment]
This code request already exists in the 2.1 preview.

> Potentially an infinite loop if someone put inside onResume the call to Scan()
I try to ensure I only check permissions when the permission has not already been requested.  Thus, after the onresume, the value will already be set and the permission check will either pass or fail without calling for onresume again.  This is why I'm asking if there is an actual bug you are facing, not a hypothetical one.

> In my case I struggle to understand why a call in a fragment trigger a onPause() / onResume() in my main activity.
I'm not trying to be rude, but I only have so much time in a day and debating hypothetical bugs or explaining how code works in a free/open project just isn't a valid use of that time.  You are welcome to browse the code, submit full issues, or even PRs and I'm happy to take a look at them.

**Comment by lufo88ita** [comment]
> "This code request already exists in the 2.1 preview."

Thanks for the information.

Regards,

**Comment by aritchie** [comment]
@lufo88ita This isn't an appropriate comment.  I've tried to ask you if you had an actual problem and you've only given me a potential issue.  Do you have an actual issue?  If so, do you have a reproducible test case?  I have tested for the case you've mentioned and it works fine as I already stated it would.

**Comment by lufo88ita** [comment]
Maybe the problem is that my native language is not english, but I have some trouble to understand the whole discussion.
I try to be more clear and add one more sample. 
1) Open the sample I attach and run it. Click on the button.
2) You will see the TextView rapidily populate with "On resume activity! Scan start!" + "On pause activity scan end! "

if you check the file ScanActivity.cs you will see the reason: there is a call to start a scan in OnResume() and a call to stop the scan in OnPause().

In my real app (which is more, more bigger than this sample of course) I have more code in OnResume() and OnPause() in the activities and fragments insime app. Code that I don't want to be called everytime the user want to start a Scan.

My workaround for now: I move much code as possible from OnResume to OnStart (and from OnPause to OnStop of course) which is not called when the scan start. That's all.

I will wait the release of 2.1 which, if I understand, has a different behavior.

If I fail to explain you what is the issue, feel free to ignore this message, maybe another user will explain better the problem. I don't want to waste your time or cause a flame.

[SampleAndroid.zip](https://github.com/shinyorg/shiny/files/6623776/SampleAndroid.zip)
