### ISSUE TITLE
[Android] BleManager.WhenStatusChanged does not publish events

### ISSUE THREAD

**Issue by KirylAkulich1** [shinyorg/shiny#606]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.0
## Steps to Reproduce
namespace Shiny.BluetoothLE
{
    [BroadcastReceiver(
        Name = "com.shiny.bluetoothle.ShinyBleAdapterStateBroadcastReceiver",
        Enabled = true,
        Exported = true
    )]
    [IntentFilter(new[] {
        BluetoothAdapter.ActionStateChanged
        //Intent.ActionAirplaneModeChanged
    })]
    public class ShinyBleAdapterStateBroadcastReceiver : BroadcastReceiver
    {
        readonly Lazy<IMessageBus> messageBus = new Lazy<IMessageBus>(() => ShinyHost.Resolve<IMessageBus>());
        //android.intent.action.AIRPLANE_MOD

        public override void OnReceive(Context context, Intent intent)
        {
            switch (intent.Action)
            {
                case BluetoothAdapter.ActionConnectionStateChanged:
                    var newState = intent.GetIntExtra(BluetoothAdapter.ExtraState, -1);
                    this.messageBus.Value.Publish(newState);
                    break;
            }
        }
    }
}

## Expected Behavior
Monitor for status changes with adapter(on/off/permissions).
## Actual Behavior
Do nothing.As I understand, it's impossible to publish state, because actions in InterntFilter and in switch-case  are different.  Actually, implicit cast to State is needed for newState variable.

**Comment by aritchie** [comment]
Thanks

**Comment by aritchie** [comment]
If you see something that doesn't work, send a PR please.  

This isn't fully complete anyhow as I'm working on other stuff.  It will be in a near future preview

**Comment by KirylAkulich1** [comment]
Actually, There is no sense to register broadcast receiver with attribute, because ,as I understand, it doesn't work for Android 8.0+ (https://developer.android.com/guide/components/broadcasts#receiving-broadcasts)
