### ISSUE TITLE
Azure notification Hubs does not work on Android 11

### ISSUE THREAD

**Issue by enny1170** [shinyorg/shiny#608]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ x] Core (Jobs, Settings, Initialization)
 - [ x] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [x ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.2741

## Version of OS(s) listed above with issue
11

## Steps to Reproduce
1. create a new xamarin forms app, add nugets for shiny and shiny azure notification hub
2. init shiny acording to the guide
3. request for Permissions in Android app

## Expected Behavior
User will be asked for Permissions and returns with access or not

## Actual Behavior
Got a exception
see file below
[push_exception.txt](https://github.com/shinyorg/shiny/files/6649639/push_exception.txt)

**Comment by aritchie** [comment]
This means something isn't setup correctly.

You're either missing the google-services.json or you haven't specified it as a google task in the android project

**Comment by enny1170** [comment]
I gues i lost now.
I setup the azure push service as described in the guides on shiny.net.

Ther are no additional steps for Android. So sorry, but i don’t understand you hints in your answer.
In IOS it will work. Asks me for permission without exception.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Allan ***@***.***>
Gesendet: Montag, 14. Juni 2021 17:56
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [shinyorg/shiny] Azure notification Hubs does not work on Android 11 (#608)


This means something isn't setup correctly.

You're either missing the google-services.json or you haven't specified it as a google task in the android project

**Comment by aritchie** [comment]
The docs are far from perfect and still a work in progress.  They also don't cover 100% of the OS configuration since this is covered by the azure docs themselves.  What you need is covered here: https://shinylib.net/push/native
