### ISSUE TITLE
BluetoothLE

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#61]
## Summary
BLE is such a large scope of work - this just needs to get done.

## API Changes
None

## Intended Use Case
Continued efforts on bringing Tizen into Shiny

**Comment by JasonBunting** [comment]
I am new to all of this and found that the docs on Shiny's BLE stuff referenced something called the CrossBleAdapter and yet I couldn't find it anywhere in Shiny. I assume this isn't anywhere near ready and I should use Plugin.BluetoothLE?

**Comment by aritchie** [comment]
The library is 95% done.  It just isn't documented because it is just me doing the work.  

Please don't hijack feature requests in the future.

**Comment by abenzakour** [comment]
Hello, 
Any news about documentation ? 
We really need it to make Bluetooth working

**Comment by aritchie** [comment]
@abenzakour This is OSS.  You can contribute.  Otherwise, it is done when it is done.  If you really need it, you can pay me for the time and I'll get it done.

**Comment by aritchie** [comment]
Mac & Tizen are being left out of scope for now
