### ISSUE TITLE
Build fails when a static class has the same name as part of the namespace

### ISSUE THREAD

**Issue by JeremyBP** [shinyorg/shiny#621]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP

## Feature Library

 - [x] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.2757

## Version of OS(s) listed above with issue
Android 11
iOS 14

## Steps to Reproduce
1. Create a brand new blank XF project (e.g. "TestShiny")
2. Configure it all with Shiny including  ```[assembly: Shiny.ShinyApplication(ShinyStartupTypeName = "TestShiny.Startup",XamarinFormsAppTypeName = "TestShiny.App")]```
=> it should build correctly

3. Create a static class into the standard project with the same name as part the namespace (e.g. "TestShiny" for a "TestShiny" namespace) and built it => it should fail with messages:
`\TestShiny\TestShiny\TestShiny.Android\Shiny.Generators\Shiny.Generators.AndroidApplicationSourceGenerator\MainApplication.cs(17,37,17,44): error CS0426: The type name 'Startup' does not exist in the type 'TestShiny'`
`\TestShiny\TestShiny\TestShiny.Android\Shiny.Generators\Shiny.Generators.AndroidActivitySourceGenerator\MainActivity.cs(25,39,25,42): error CS0426: The type name 'App' does not exist in the type 'TestShiny'`

## Expected Behavior
It should build, ignoring the static class

## Actual Behavior
Build fails

Here is a sample project. Just comment out the static class to make the build pass and leave it to make the build fail.
[TestShiny.zip](https://github.com/shinyorg/shiny/files/6731318/TestShiny.zip)

**Comment by JeremyBP** [comment]
My workaround btw was to write:

```csharp
using TestShiny;

[assembly: Shiny.ShinyApplication(
    ShinyStartupTypeName = nameof(Startup),
    XamarinFormsAppTypeName = nameof(App)
)]
```

**Comment by aritchie** [comment]
So this should be the workaround to use for now:

```csharp
[assembly: Shiny.ShinyApplication(
    ShinyStartupTypeName = "global::TestShiny.Startup",
    XamarinFormsAppTypeName = "global::TestShiny.App"
)]
```

I'll ensure it is there for the global is added by default
