### ISSUE TITLE
Location permission dialog not showing Android 10

### ISSUE THREAD

**Issue by Dipannita20** [shinyorg/shiny#623]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [x] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.2757
## Version of OS(s) listed above with issue
Android 10

## Steps to Reproduce
1. Created new XF project, installed NuGet Packages
2. MainActivity added
          `[assembly: Shiny.ShinyApplication(
                ShinyStartupTypeName = "testproject.SampleStartup",
                XamarinFormsAppTypeName = "testproject.App"
            )]`
3. Added permissions in AndroidManifest
4. Created SampleStartup  to configure services
5. On ViewModel `ShinyHost.Resolve<IGeofenceManager>().RequestAccess(); ` , 

## Expected Behavior
Show location permission dialog

## Actual Behavior
Not showing location permission dialog
[testproject.zip](https://github.com/shinyorg/shiny/files/6734293/testproject.zip)

**Comment by aritchie** [comment]
This is fixed in the latest patch.  Thank you for reporting it.
