### ISSUE TITLE
Build Issues on fresh Master download.

### ISSUE THREAD

**Issue by FIELDPOINT** [shinyorg/shiny#626]
Just downloaded Master Sample Code and tried running Samples.sln. I get a ton of build errors, not sure what I am doing wrong 

![image](https://user-images.githubusercontent.com/43620315/124342723-fad6f900-db93-11eb-8ccd-1271ae90b37c.png)

VS Version is Version 16.10.2

**Comment by aritchie** [comment]
Please note that issues must use the issue templates and that I don't officially support the samples.  You are likely missing the appropriate UWP installs
