### ISSUE TITLE
[Enhancement] CanRead, CanWrite, CanUpdate (For BLE Characteristics)

### ISSUE THREAD

**Issue by dgerchcovich** [shinyorg/shiny#629]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
This is an awesome package. Allot of work looks like has been put into it, and thank you for making all this open source.
I just have a very basic feature request, and I'm wondering if it's possible for you to add 3 properties as given in the request Title above. These properties, will expose whether a characteristic's value can be read, written to, or updated. 

## API Changes
3 Properties: **CanRead, CanWrite, CanUpdate**

## Intended Use Case
When I make a ble connection, I want to know whether I can read, write or update a characteristics value

**Comment by aritchie** [comment]
This already exists when you have an IGattCharacteristic.  There is a Properties property and a bunch of extensions

**Comment by dgerchcovich** [comment]
Can I ask which properties you need to access to read these values? I could not find this on the documentation, and it will help. Thank you

**Comment by dgerchcovich** [comment]
Can you please provide an example here. If you can, thank you.
