### ISSUE TITLE
[Bug] Android 4.4 Job Scheduler Exception

### ISSUE THREAD

**Issue by wolfet** [shinyorg/shiny#63]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.307-beta

## Version of OS(s) listed above with issue
v4.4 - KitKat
Should be any Android version with API level less than 21 - Lollipop

## Steps to Reproduce
1. Call AndroidShinyHost.Init on an Android device with Android 4.4

## Expected Behavior
Shiny should initialize without any exceptions on Android 4.4.

## Actual Behavior
A null reference exception is thrown in the Shiny.Jobs.ServiceExtensions class in StopJobService and StartJobService because the call to NativeScheduler returns null. According to [this page](https://developer.android.com/reference/android/app/job/JobScheduler), JobScheduler was introduced in API level 21.

![image](https://user-images.githubusercontent.com/9417091/62672550-2e3d8880-b969-11e9-9d50-72b5bc05435a.png)

Making the two changes in my screenshot below from the Shiny.Core > Jobs > Platforms > Android > ServiceExtension.cs file provided a workaround for me to avoid the exception.

![image](https://user-images.githubusercontent.com/9417091/62672588-55945580-b969-11e9-9a50-bfb146fd2fc2.png)

**Comment by aritchie** [comment]
Shiny only supports android 5x and above.
