### ISSUE TITLE
Notifications possibility to create a notification with custom button text

### ISSUE THREAD

**Issue by Codelisk** [shinyorg/shiny#638]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
What I would like to accomplish:
Send a push notification with data paramaters _Btn1Text_ and _Btn2Text_. According to the value in these 2 parameters I would like to show 2 buttons. One with the text of _Btn1Text_ and one with the text of _Btn2Text_

I haven't seen a possibility to do that without manipulating the Channels. At the moment i accomplish the behavior by doing this:
```
            await NotificationManager.RemoveChannel("Channel1");
            await NotificationManager.AddChannel(
                Channel.Create(
                    "Channel1",
                    ChannelAction.Create(notification.Data["Btn1Text"]),
                    ChannelAction.Create(notification.Data["Btn2Text"])
                ));
```
Which doesn't seem ideal.

## API Changes
To be honest, I don't really have a good idea how to accomplish that, I guess one way would be to extend the 
NotificationManager.Send API but I dont know if that fits or is a good way of doing it.

## Intended Use Case
Possibility to Send Notifications with dynamic Button And TextReply Text.

**Comment by aritchie** [comment]
Channels is the only way to do this.  I would encourage you to take a look at the underlying mechanisms for each platform to understand why this is the way it is.  There are good reasons for why the platforms do this.  

You also don't want to really be manipulating channels due to the way Android manages them.  You need to focus on a small subset of statically named channels.

**Comment by Codelisk** [comment]
Okay understood thank you.
However if I need something like that the code I posted above is a good way to achive that or would you try to achive that another way? For example not always removing and adding the channel but just changing it?

**Comment by aritchie** [comment]
Channels weren't meant to updated much, if at all.  You need to create them or destroy them (as in, they won't be used anymore) because they show up under the Android settings screen for your app.
