### ISSUE TITLE
[Android] ShinyLifecycleTask OnForeground/OnBackground not being called

### ISSUE THREAD

**Issue by GuidoNeele** [shinyorg/shiny#640]
ONLY active OSS maintainers of other projects OR ACTIVE project sponsors can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR THIS WILL BE CLOSED!
THERE IS NO SUPPORT ON PREVIEW/BETA VERSIONS!  

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

Hi Allan,

I'm struggling to get the `ShinyLifecycleTask` working. The `OnForeground` and `OnBackground` methods are never called. The `StartupTask` class is registered and the `Start` method is being called so setup should be right. I also tried the Shiny Sample app to figure out what's happening and it looks like the lifecycle events (see code below) are never triggered. Am I correct in the assumption that `OnForeground` needs to be called when the app is visible on screen and `OnBackground` when the app is not visible on screen?

https://github.com/shinyorg/shiny/blob/b33f1ac410861b47a2518e5e9c660f4a15e3c7ca/src/Shiny.Core/Platforms/Android/AndroidPlatform.cs#L66-L79

Thanks in advance,

Guido

**Comment by GuidoNeele** [comment]
BTW While searching for an answer I was browsing the source code and found this line of code. The Paused state is fired in `OnActivityResumed`, looked a bit odd to me.

https://github.com/shinyorg/shiny/blob/b33f1ac410861b47a2518e5e9c660f4a15e3c7ca/src/Shiny.Core/Platforms/Android/ActivityLifecycleCallbacks.cs#L41-L45

**Comment by GuidoNeele** [comment]
Got the events triggered by modifying Shiny.AndroidPlatform in the Shiny.Core project. I added the `Export` attributes after reading the following StackOverflow article https://stackoverflow.com/questions/49644709/xamarin-android-architecture-components-not-getting-callbacks-for-lifecycle-eve. On the `Samples.Android` project I also added a reference to Mono.Android.Export.

```csharp
[Lifecycle.Event.OnResume]
[Export]
public void OnResume()
{
    this.Status = PlatformState.Foreground;
    this.stateSubj.OnNext(PlatformState.Foreground);
}

[Lifecycle.Event.OnPause]
[Export]
public void OnPause()
{
    this.Status = PlatformState.Background;
    this.stateSubj.OnNext(PlatformState.Background);
}
```

**Comment by aritchie** [comment]
Thank you for reporting this.  They will be released in a preview later today

**Comment by GuidoNeele** [comment]
Great, Thanks Allan! Will try tomorrow and let you know the result.

**Comment by GuidoNeele** [comment]
Tried it and it's working now. Thanks again Allan for the quick fix!
