### ISSUE TITLE
Avoid android access_background_location permission 

### ISSUE THREAD

**Issue by enny1170** [shinyorg/shiny#652]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
During publishing our app in playstore Google denied the app because background location permission is requested. This permission is not on my Manifest so i guess this will added during compilation.

## API Changes
Please privide a possibility to avoid the Addition for this permission, so a User can select which permission will be requestet.

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by aritchie** [comment]
This is not described well enough for a bug or a feature request

**Comment by enny1170** [comment]
Hello,

we have used shinylib with useGps() in our xamarin forms Project, and published both (iOS and Android) to the stores.
The app is working fine. But Google decined the app because the app wants ACCES_BACKGROUND_LOCATION permission.
There are asking for a Change without this permission. But we do not have it in our manifest. I think this will automaticaly added by shiny during build.
The Question is , is there a way, to use the gpsmanager/gpslistener functionality without this permission ? So mybe a Option to prevent the Addition of this permission can be helpfull.

Regards Enny

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Allan ***@***.***>
Gesendet: Dienstag, 20. Juli 2021 22:51
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [shinyorg/shiny] Avoid android access_background_location permission (#652)


This is not described well enough for a bug or a feature request
