### ISSUE TITLE
[Android] Notifications are not auto-registered for use with background GPS causing foreground service to fail

### ISSUE THREAD

**Issue by josbol** [shinyorg/shiny#653]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [X] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.69 (also tested with 2.2.0.2801-preview)

## Version of OS(s) listed above with issue
Android 9.0 (Target API Level 29)

## Steps to Reproduce
1. Create new Project and add _services.UseGps();_ to ConfigureServices in Startup Class
2. In ViewModel of the MainPage add [assembly: GenerateStaticClasses("ShinyStatics")] below the usings and add the following Command:

```Csharp
_ = await ShinyStatics.ShinyGps.RequestAccess(new GpsRequest { UseBackground = true });
                _ = ShinyStatics.ShinyGps.WhenReading().Subscribe(onNext => Debug.WriteLine(onNext.Position.Latitude));
                await ShinyStatics.ShinyGps.StartListener(new GpsRequest { UseBackground = true, Interval = new TimeSpan(0, 0, 10), Priority = GpsPriority.Highest, ThrottledInterval = new TimeSpan(0, 0, 5), MinimumDistance = Distance.FromMeters(50) });
```
3. Create and link a button in the MainPage with the command created in step 2
4. Add the following information to  AndroidManifest.xml. Copied from the Sample project, so it has more than actually being used.
```
<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29" />
	<application android:label="AppTest1.Android" android:theme="@style/MainTheme"></application>
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
  <uses-permission android:name="android.permission.BLUETOOTH" />
  <uses-permission android:name="android.permission.BATTERY_STATS" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.BIND_MIDI_DEVICE_SERVICE" />
  <uses-permission android:name="android.permission.READ_CALENDAR" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.NFC" />
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
  <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
  <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
```
5. Run the Android Emulator
6. In the location settings, create any route ex: 8190 Murray Ave, Gilroy, CA 95020, USA to 25536-25726 Airline Hwy, Paicines, CA 95043, USA)
7. In the location settings, press Play Route
8. In the app, press the button created in step 3

## Expected Behavior
A repeated printing of latitudes to the debug screen (Output), even after switching to a different application.

## Actual Behavior
The application starts printing the latitudes, but several seconds after pressing the button, the app crashes with the following messages and stacktrace in the debug screen.
```
[0:] 36.92018
[libc] Requested dump for tid 19573 (nyname.apptest1)
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.apptest1, PID: 19573
[AndroidRuntime] android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d5b69df u0 com.companyname.apptest1/crc6461f3faed59cf0423.ShinyGpsService}
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:193)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6669)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
**Android.Util.AndroidRuntimeException:** 'Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d5b69df u0 com.companyname.apptest1/crc6461f3faed59cf0423.ShinyGpsService}'
```
When lowering the target API Version to 25, the problem disappears.

## Remarks
The attached project contains an IOS target as well, but it has not been tested.

## Sample project
[AppTest1.zip](https://github.com/shinyorg/shiny/files/6858189/AppTest1.zip)

**Comment by aritchie** [comment]
Ensure your notifications isn't erroring.  ShinyNotifications.Send() something - if that errors, then your foreground service will fail as well

**Comment by josbol** [comment]
Adding the notification service solved the problem. Thanks! 

Since this detail is not in the documentation (referring to https://shinylib.net/locations/gps ), would you accept a PR fixing the example?

**Comment by aritchie** [comment]
No worries.  It is actually a defect anyhow as notifications should be auto-registered if you aren't already using them.  PR's for docs are always taken though :)
