### ISSUE TITLE
[iOS] LocationService: Interval and ThrottledInterval not being respected

### ISSUE THREAD

**Issue by josbol** [shinyorg/shiny#657]
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [X] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.69 

## Version of OS(s) listed above with issue
Iphone 11 Emulator, IOS 14.5 on MacOS 11.4 (Big Sur). The project itself is ran from Visual Studio on a Windows 10 x64 Laptop.

## Steps to Reproduce
1. Create new Project and add _services.UseGps() and services.UseNotifications()_ to ConfigureServices in Startup Class
2. In ViewModel of the MainPage add [assembly: GenerateStaticClasses("ShinyStatics")] below the usings and add the following Command:

```Csharp
//Stopping a previous GPS Listners. Only seems to be needed on iOS?
await ShinyStatics.ShinyGps.StopListener();
_ = await ShinyStatics.ShinyGps.RequestAccess(new GpsRequest { UseBackground = true, Interval = new TimeSpan(0, 0, 10), Priority = GpsPriority.Highest, ThrottledInterval = new TimeSpan(0, 0, 5), MinimumDistance = Distance.FromMeters(50) });
_ = ShinyStatics.ShinyGps.WhenReading().Subscribe(onNext => Debug.WriteLine($"at {DateTime.Now} {onNext.Position.Latitude} {onNext.Position.Longitude}"));
await ShinyStatics.ShinyGps.StartListener(new GpsRequest { UseBackground = true, Interval = new TimeSpan(0, 0, 10), Priority = GpsPriority.Highest, ThrottledInterval = new TimeSpan(0, 0, 5), MinimumDistance = Distance.FromMeters(50) });
```
3. Create and link a button in the MainPage with the command created in step 2
4. In the Info.plist editor: Enable Background modes and subsequently Background fetch, Background processing and Location Updates.
5. Add the following information to Info.plist manually.
```xml
<key>NSLocationAlwaysUsageDescription</key>
<string>Say something useful here that your users will understand</string>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>Say something useful here that your users will understand</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>Say something useful here that your users will understand</string>  
```
5. Run the iOS Emulator
6. In the emulator select: Debug > Location > Freeway drive
8. In the app, press the button created in step 3

## Expected Behavior
A repeated printing of positions to the debug screen (Output), with an average interval of 10 seconds, having a minimum interval of 5 seconds and having a minimum distance of 50 compared to the last reported position.

## Actual Behavior
The application starts printing the positions seemingly as fast as the coordinates change (approximately once per second), ignoring the specified intervals. 

Another curious problem occurs when the coordinates are set to Debug > Location > Apple (Lat 37.33233141 Long -122.0312186). In this case an event keeps being triggered, even although the position doesn't change at all. This seems to happen only with these specific coordinates. 

On Android everything seems to work perfectly.

## Remarks
This might be a possible duplicate of  #411, however that report mentions an older version of Shiny (1.2).

##Project
[AppTest1 - iOS Intervals.zip](https://github.com/shinyorg/shiny/files/6865110/AppTest1.-.iOS.Intervals.zip)

**Comment by aritchie** [comment]
iOS doesn't respect intervals when in the foreground

**Comment by josbol** [comment]
Ok, we'll implement some form of throttling in our code, thanks!
