### ISSUE TITLE
Push Notifications received but not displaying on Android Phone

### ISSUE THREAD

**Issue by killer-frog** [shinyorg/shiny#664]
# PLEASE READ
## ISSUES MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

I have added push notifications to my android app, and the push received event in the PushDelegate fires but no notification is ever displayed.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library

 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ x] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ x] Push - Firebase
 - [ ] Sensors
 - [ ] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
2.1.0.2769

## Version of OS(s) listed above with issue
10

## Steps to Reproduce
1. Set up push for android as per instructions

``` c#
        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            if (DeviceInfo.Platform == DevicePlatform.iOS)
            {
                services.UsePush<PushDelegate>();
            }
            else
            {
                services.UseFirebaseMessaging<PushDelegate>();
            }
        }
```

2. Create Push Delegate
``` c#
    public class PushDelegate : IPushDelegate
    {
        public Task OnEntry(PushNotificationResponse response)
        {
            Analytics.TrackEvent($"[PushDelegate-OnEntry]: {response.Text}");
            Debug.WriteLine($"[PushDelegate-OnEntry]: {response.Text}");
            return Task.CompletedTask;
        }

        public Task OnReceived(PushNotification notification)
        {
            Analytics.TrackEvent($"[PushDelegate-Received]: {notification.Notification?.Title}");
            Debug.WriteLine($"[PushDelegate-Received]: {notification.Notification?.Title}");
            return Task.CompletedTask;
        }

        public async Task OnTokenChanged(string token)
        {
            Analytics.TrackEvent($"[PushDelegate]: TokenChanged (AV4 : {AddViewApplication.UsingAv4})");
            Analytics.TrackEvent($"[PushDelegate]: TokenChanged {token}; using AV4 {AddViewApplication.UsingAv4}");
            Debug.WriteLine($"[PushDelegate]: TokenChanged {token}; using AV4 {AddViewApplication.UsingAv4}");
         }
    }
```

3. Add Shiny to Main Activity

``` c#
using Android.App;
using Android.Content.PM;
using Shiny;


[assembly: ShinyApplication(
    ShinyStartupTypeName = "AddView.Mobile.AppStartUp",
    XamarinFormsAppTypeName = "AddView.Mobile.App"
)]

namespace AddView.Mobile.Droid
{
    [Activity(Label = "AddView", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation,
        ScreenOrientation = ScreenOrientation.Portrait)]
    public partial class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
    }
}
```

4. Add Permissions to manifest

``` xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="0.0.0" package="com.xxxx.xxxxx">
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.USE_FINGERPRINT" />
	<uses-feature android:name="android.hardware.location" android:required="false" />
	<uses-feature android:name="android.hardware.location.gps" android:required="false" />
	<uses-feature android:name="android.hardware.location.network" android:required="false" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
	<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
	<application android:label="AddView.Mobile" android:icon="@mipmap/icon" android:allowBackup="false">
		
	</application>
</manifest>
```

5. Request Push Access

``` c#
        public async Task<string> RequestAccess()
        {
            if (_deviceInfo.DeviceType == DeviceType.Virtual) return string.Empty;


            var result = await _pushManager.RequestAccess();

            if (result.Status != AccessState.Available && !string.IsNullOrWhiteSpace(result.RegistrationToken))
            {
                return string.Empty;
            }

            await RegisterForNotifications(result.RegistrationToken);  // Server Registration

            return result.RegistrationToken;
        }
```

6. Send Push Notification

## Expected Behavior

A notification should be displayed when I swipe down to see notifications

## Actual Behavior
Debug & AppCenter Statement shows that Push Delegates `OnReceived` fires
No push notification is displayed to the user

**Comment by aritchie** [comment]
If you're using firebase, use firebase.  You shouldn't be doing an if on that.

**Comment by wcoder** [comment]
@aritchie 
Looks like it's a native way to add push notification in general:
- iOS - Native
- Android - Firebase Cloud Messaging

Why we should force use Firebase for both?

**Comment by aritchie** [comment]
That's the whole purpose of Shiny is to manage the cross platform for you.  Firebase is used as the native mechanism on Android with just UsePush.  The only reason to reference the firebase package is because you are using firebase with iOS as well.

**Comment by killer-frog** [comment]
I had that before, I have now changed it to  be:

``` c#
        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            services.UsePush<PushDelegate>();
        }
```

It works fine on iOS but just won't work on Android.  

So with the above it is just the same, OnReceived in the PushDelegate fires but no notification.  

Interestingly - but on Android OnTokenChanged event in the delegate never fired, which was why I added the server registration logic into where the request access was.

**Comment by aritchie** [comment]
OnTokenChanged only fires outside of RequestAccess.  This is something firebase can occasionally do.  

If OnReceived is firing, it means you are likely missing the necessary notification data.  Please provide the message being sent through firebase or take a look at how the code processes the native messages here: https://github.com/shinyorg/shiny/blob/b33f1ac410861b47a2518e5e9c660f4a15e3c7ca/src/Shiny.Push/Platforms/Android/PushManager.cs#L65

**Comment by killer-frog** [comment]
so the message that is sent is :
```  json
"{ "data" : {"message":"Hello World"} }"
```

And in the OnReceived method the pushnotification.Data contains the message in the dictionary but the notification is null.

**Comment by aritchie** [comment]
You don't have any notification data in that packet.  Data is custom and can be anything.

**Comment by killer-frog** [comment]
thanks for the help, as a work around I added this ti my PushDelegate and it worked perfectly.  If it helps someone else then great.

``` c#
        public async Task OnReceived(PushNotification notification)
        {
            if (notification.Notification == null && notification.Data.TryGetValue("message", out var message))
            {
                var notificationService = ShinyHost.Resolve<INotificationManager>();
                var result = await notificationService.RequestAccess();

                if (result == AccessState.Available)
                {
                    await notificationService.Send("AddView", message);
                }
          }
```

**Comment by aritchie** [comment]
You don't need a workaround at all.  You just need to send the notification data as per the firebase instructions.

https://firebase.google.com/docs/cloud-messaging/concept-options
