### ISSUE TITLE
[Bug] Adding Shiny Core to Existing Project

### ISSUE THREAD

**Issue by tpitman** [shinyorg/shiny#67]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [X] Core
 - [X] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.334-beta
## Version of OS(s) listed above with issue
iOS 9+
Android 6+

## Steps to Reproduce
1. Have existing Visual Studio 2019 for Mac cross platform project for iOS and Android
2. Add Shiny NuGet package for BluetoothLE
3. Add example AndroidShinyHost.Init call from getting started
4. Create MyDelegateClass from getting started
5. Add services.UseBleCentral<MyDelegateClass>() to MyStarted Class from getting started
6. Note that there is an error the UseBleCentral doesn't exist. Checked all references and they seem to be there
7. Note that there is an error in thee Android project that AndroidShinyHost doesn't exist

## Expected Behavior
I downloaded the samples github repo and they all seem to be defined. When I look in the Object Browser in the samples projects Shiny.Core has a lot more classes than when I look at it in mine and yet the nuget references look the same.

## Actual Behavior
missing classes and extension methods.

**Comment by aritchie** [comment]
Please supply a reproducible sample.

**Comment by tpitman** [comment]
I created a brand new project and imported everything and made the classes and one of the problems is the same the other is different. I have attached a zip file with the solution in it. You can see the errors.

[BLETest.zip](https://github.com/shinyorg/shiny/files/3494581/BLETest.zip)

**Comment by aritchie** [comment]
1) AndroidShinyHost.Init is required to be inside of an AndroidApplication like the sample and the readme.  You are also missing the permission wireup in the main activity.

2)There is no method services.UseCentral with a generic delegate yet.  There will be a in future beta.  Please take a look at the intellisense and the sample
