### ISSUE TITLE
[Bug] Invalid notification (no valid small icon), while sending notification

### ISSUE THREAD

**Issue by forlayo** [shinyorg/shiny#68]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [X] Notifications
 - [ ] Sensors

## Version of Library
1.0.0.332-beta

## Version of OS(s) listed above with issue
Android 9

## Steps to Reproduce
1. Send a notification, like notifications.Send("Hola", "Manolo");

## Expected Behavior
Notification with title "Hola" and body "Manolo" appears.

## Actual Behavior
Nothing appears on phone, and exception pops up with this details:

```
Java.Lang.IllegalArgumentException
 Message=Invalid notification (no valid small icon): Notification(channel=pluginnotificationId pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
```

**Comment by aritchie** [comment]
Change the icon - notification.Android.SmallIconResourceName . 

I use "notification" resource by default.
