### ISSUE TITLE
[Feature Request]: Change peripheral name to advertised name

### ISSUE THREAD

**Issue by BaseCrusher** [shinyorg/shiny#681]
### Summary

I have recently written a ble application for my raspberrypi in order to test some functionality of my xamarin app. I then realized, that while Android displays the advertised name as the peripheral name, iOS takes a diffrent approach. 

As stated in the [Apple Developer Forum](https://developer.apple.com/forums/thread/72343) iOS reads the bluetooths name instead of the advertised one.

This isn't essentially a bug, but it brings some inconsistency between the to implementations.
My suggstion would be to either change that in iOS so that it reads the advertised name (This makes sense, since it is theoreticly possible that one bluetooth adapter has multiple peripherals running on it) or to atleast give the user the option to select, which name should be used. This could be passed as an additional Property in the scan settings. 

### API Changes

Either adding a new property to the scan settings that lets the user decide what name should be used when running the scan on iOS. Or change the name completly to display the advertised name.

Maybe it wouldn't be a bad idea to deliver the advertised data with the peripheral when a peripheral is detected.

### Intended Use Case

As stated above this would allow to read the advertised name, which can be diffrent than the adapters name.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I think ScanResult.AdvertisementData.LocalName

**Comment by BaseCrusher** [comment]
Oh, I did not see that this was already the case. For reasons I still have to use an older version of the library. 

Thank you very much for the quick reply and I apologize for the inconvinience.
