### ISSUE TITLE
[Enhancement] Sample HTTP Transfers Xamarin.Forms

### ISSUE THREAD

**Issue by moreirawebmaster** [shinyorg/shiny#69]
## Summary
Please provide a sample HTTP Transfers using in Xamarin.Forms

## API Changes
Xamarin.Forms

## Intended Use Case
Please provide a sample HTTP Transfers using in Xamarin.Forms

**Comment by aritchie** [comment]
There is a sample repo you can look at https://github.com/shinyorg/shinysamples 

Please use github issues for actual issues and feature requests!
