### ISSUE TITLE
[Bug]: Shiny source generators seem not to be running when using a empty Xamarin Forms Project with the required changes.

### ISSUE THREAD

**Issue by wagenheimer** [shinyorg/shiny#706]
### Component

Core (Jobs, Settings, Initialization)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] UWP

### Steps To Reproduce

I'm sorry to be reporting once again a problem that might be something I'm doing wrong, but I'm really not able to use Shiny on a new project.
If I can find the cause, I promise to write a Blog Post explaining the step by step for those starting with Shiny to help other beginners who may also have difficulties.

In Visual Studio 16.11.2 create a new Project - "Mobile App (Xamarin.Forms)"  - ShinyVoice

![image](https://user-images.githubusercontent.com/315513/131366314-c0ffc746-e82b-49e4-9bd8-907b657605cc.png)

On the New Mobile App choose Black (An Empty App with a Single Initial Screen) and check only Android.
![image](https://user-images.githubusercontent.com/315513/131366478-f97220dc-fadc-4ed0-bb81-dd86db883303.png)

Manage NuGet packages on the project and add Shiny 2.2.0.2829 and Shiny.SpeechRecognition 2.2.0.2829.

On the main project, let's add ShinyVoiceStartUp.cs and on it services.UseSpeechRecognition();

```
using Microsoft.Extensions.DependencyInjection;
using Shiny;

namespace ShinyVoice
{
    public partial class ShinyVoiceStartup : ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            // this is where you'll load things like BLE, GPS, etc - those are covered in other sections
            // things like the jobs, environment, power, are all installed automatically

            services.UseSpeechRecognition();
        }
    }
}
```

Let's change AssemblyInfo.cs to make Shiny works.

```
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]

[assembly: Shiny.ShinyApplication(
    ShinyStartupTypeName = "ShinyVoice.ShinyVoiceStartup",
    XamarinFormsAppTypeName = "ShinyVoice.App"
)]
```

On MainActivity.cs let's change the MainActivity class to Partial;

`public partial class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity`

Let's put a breakpoint on services.UseSpeechRecognition() and debug the application:
![image](https://user-images.githubusercontent.com/315513/131368120-e9699142-06ec-4de3-af7b-ebb0aea8d848.png)

It will fail with :

`Please add a reference to Mono.Android.Export.dll when using ExportAttribute or ExportFieldAttribute.	ShinyVoice.Android	`		

Then let's add the missing referent and try to debug again.

I attached the project here for testing.
[ShinyVoice.zip](https://github.com/shinyorg/shiny/files/7078069/ShinyVoice.zip)

### Expected Behavior

The app runs and stops on the breakpoint indicating that Shiny has successfully started.

### Actual Behavior

The application runs and does not stop at the breakpoint.

If during the code I try to use :

`CrossSpeechRecognition = Shiny.ShinyHost.Resolve<Shiny.SpeechRecognition.ISpeechRecognizer>();`

System.ArgumentException: 'ServiceProvider has not been setup - have you initialized the Platform provider using ShinyHost.Init?'

### Exception or Log output

There is nothing strange on Log output or any exception until I really try to use some Shiny service.

```
Build started...
1>------ Build started: Project: ShinyVoice, Configuration: Debug Any CPU ------
1>ShinyVoice -> C:\Users\wagen\source\repos\ShinyVoice\ShinyVoice\ShinyVoice\bin\Debug\netstandard2.0\ShinyVoice.dll
2>------ Build started: Project: ShinyVoice.Android, Configuration: Debug Any CPU ------
2>  ShinyVoice.Android -> C:\Users\wagen\source\repos\ShinyVoice\ShinyVoice\ShinyVoice.Android\bin\Debug\ShinyVoice.Android.dll
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

IMPORTANT DETAIL, when compiling, a Shiny Warning appeared once saying that the code could not be generated because of Microsoft.CodeAnalysis package was not found.

But this error only appeared once and I couldn't make it appear again. I don't know if it's related to the problem.

I tried to install Nuget Microsoft.CodeAnalysis but this causes other dependency errors that I couldn't resolve and prevents even compilation of the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
ShinyApplication belongs in the head project where code needs to be generated.
