### ISSUE TITLE
[Bug]: iOS PushDelegate OnReceived not called

### ISSUE THREAD

**Issue by Codelisk** [shinyorg/shiny#709]
### Component

Push - Firebase

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [X] iOS 14
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] UWP

### Steps To Reproduce

1. Create a PushDelegate
```
public class PushDelegate : IPushDelegate
    {
        public async Task OnEntry(PushNotificationResponse response)
        {
            Console.WriteLine("OnEntry");
        }

        public async Task OnReceived(PushNotification notification)
        {
            Console.WriteLine("RECEIVED");
        }

        public async Task OnTokenChanged(string token)
        {
            Console.WriteLine("TOKEN: " + token);
        }

        public async Task OnTokenRefreshed(string token)
        {
        }
    }
```
2. Register Firebase PushDelegate:
```
public partial class SyphoneStartup : ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            services.UseFirebaseMessaging<PushDelegate>();
        }
    }
```
3. Request Access and get Token:
```
async void Button_Clicked(System.Object sender, System.EventArgs e)
        {
            var token = await pushManager.RequestAccess();
            Console.WriteLine("Token from RequestAccess: " + token.RegistrationToken);
            label1.Text = "Token: " + token.RegistrationToken;
        }
```
4. Send a data request:
```
 {
   "message":{
      "token":"drtmSgK9SELgvDKcNV3j0U:APA91bHzBf0ETK7ilZq8l758nSvpHxcd3PWH0SE8ROok8ePidcdVYROtsK8K3QFUX3ZdbNzr4OdPaRAHLM5tylbDCOFV8WuS3N981TaAC8NISIQUsZbAQVTznl4yo84DkfDlaoYyeGyc",
       "data":{
           "pushid":"956"
       }
   }
}
```

5. See if OnReceived gets called in the PushDelegate

Version of the nuget:
2.3.0.2855-preview

nugets used:

```
<PackageReference Update="Shiny" Version="2.3.0.2855-preview" />
<PackageReference Update="Shiny.Core" Version="2.3.0.2855-preview" />
<PackageReference Update="Shiny.Push.FirebaseMessaging" Version="2.3.0.2855-preview" />
```

last known working version:
2.2.0.2829

### Expected Behavior

OnReceived should be called

### Actual Behavior

OnReceived is not called

### Exception or Log output

Additional information:

When we put a notification tag into the notification and keep data in it, the notification is shown, but onReceived is still not being called

I added a sample which contains the code I mentioned above, unfortunately I had to disguise it so i dont know if it is useful
[pushTest.zip](https://github.com/shinyorg/shiny/files/7082471/pushTest.zip)

**If this issue is still worked on feel free to close it**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
It isn't done.

**Comment by appimpact** [comment]
@aritchie We are not able to receive any notifications in Xamarin.iOS although Xamarin.Android is working.
As per your instructions to check previous issues before opening new one, can you please explain what did you mean by "It isn't done".

Does this mean that Shiny.Push.FirebaseMessaging is currently not working on Xamarin.iOS?

**Comment by aritchie** [comment]
@appimpact This issue was closed because the author filed against a preview which shouldn't have done because it was well known this component was under heavy dev at the time.

That being said, you definitely do need to look at other issues to see what might have already been mentioned by others, but understand - I am not here as tech support or to explain things.  The code is free and open to look at.  If you need help beyond this, I do offer professional consulting which can be found on my github profile.
