### ISSUE TITLE
[Feature Request]: Push Notification server side ASP.NET Core

### ISSUE THREAD

**Issue by KSemenenko** [shinyorg/shiny#713]
### Summary

Hi!
Love your library, and agree that you need something universal for Push Notifications.
I've used Azure PushNotification, AppCenter Push as well, and now I realize I want my own service for push notifications.
How do you see me adding code to send pushes from the server?
Then you and I can synchronize the message format of these pushes and make them universal.
no more pain of formats :)
what do you think? is it suitable for this framework?

### API Changes

no

### Intended Use Case

I want to send pushes from the server, but I don't want to use any services.
I want to use this library on the server and on the client.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
You can't do something universal since the OS push mechanisms is what everything implements down to.  

This library is focused on client, but I do have a push provider for the server that I may release in the long term under the Shiny banner.
