### ISSUE TITLE
iOS Pair

### ISSUE THREAD

**Issue by Balaji-Android** [shinyorg/shiny#714]
### Question

IPeripheral.IsPairingRequestsAvailable() is always false for iPhone devices, but IPeripheral.Connect() working. So how to make pairing from ios device to BLE device.

Pair process working fine in Android, same we need in ios, Please suggest how to achieve in iOS (Pairing process).

### Code of Conduct

- [X] I agree

**Comment by aritchie** [comment]
This area is for sponsors or active OSS maintainers only.  Please be respectful of this as it says right on the template.  All of your answers are in the source code or ios documentation anyhow
