### ISSUE TITLE
[Bug]: AppDelegate.ReceivedRemoteNotification not called when using Shiny for Local Notifcations

### ISSUE THREAD

**Issue by munkii** [shinyorg/shiny#715]
### Component

Notifications

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [X] iOS 14
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] UWP

### Steps To Reproduce

Configure your iOS XF app to register for and receive remote notifications **without** using the Shiny libraries for example by calling your own ASP.Net WebApi

From your ShinyStartup class call UseNotifications so that you can still use Shiny to do local notifcations.

### Expected Behavior

I expected that notifications pushed to the device from a remote source such as Azure Notification Hub would appear on the device (they do) AND that the AppDelegate override of ReceivedRemoteNotification would be called.

### Actual Behavior

The remote notifcation does appear on the device but our ReceivedRemoteNotification does not get called.

If I continue calling Shiny's ShinyFinishedLaunching on startup but comment out the call to `services.UseNotifications` our ReceivedRemoteNotification override starts being called again.

We have an exisitng issue in our app that means the OnReceived method in out INotifcationDelegate does not called on iOS. This might be related.

I have also created a couple SO questions on the issue [here ](https://stackoverflow.com/questions/69103875/using-shiny-for-local-notifcations-whilst-using-our-own-registration-code-for-re)and [here](https://stackoverflow.com/questions/69121716/shiny-notificationdelegate-onreceived-not-being-called-on-ios). 

I appreciate that the use of Shiny for Local Notifcations but not for Push might not be a supported scenario, https://stackoverflow.com/questions/69103875/using-shiny-for-local-notifcations-whilst-using-our-own-registration-code-for-re

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
You are using ReceivedRemoteNotification which is for the "old" way of catching remote notifications in the foreground.  Shiny.Notifications uses a UNUserNotificationCenterDelegate which I believe intercepts and stops that method.  You can implement the Shiny notification delegate to work with the notification or use Shiny.Push.AzureNotificationHubs.

You can also use: DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler) which is a better method to handle remote notifications anyhow since it is needed for background processing.

**Comment by munkii** [comment]
Hopefully there is enough in this repo, https://github.com/munkii/PushDemoWithShiny. The readme.md explains how to break it/ fix it to show the repo

**Comment by aritchie** [comment]
You still have this implemented though:

        public override void ReceivedRemoteNotification(
            UIApplication application,
            NSDictionary userInfo)
            => ProcessNotificationActions(userInfo);

You need to switch to DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action completionHandler)

**Comment by munkii** [comment]
I did that as per your suggestion in our actual app and that did not solve the issue. I was trying to leave this sample as close to the MS tutorial as possible.

I've pushed a change to the repo that is now implementing DidReceiveRemoteNotification. Again that gets called if I do **not** configure Noitifications but doesn't if i do

**Comment by aritchie** [comment]
I'm not going to invest a ton of time into this because I've verified that it is working on samples & integration tests with both notifications and push with azure.  The only hooks that local notifications installs is the https://github.com/shinyorg/shiny/blob/dbfda1c44c06705f7076846bb2eaf9106cbcf03d/src/Shiny.Core/Platforms/Apple/AppleLifecycle.cs#L32

The only thing I noticed is that your info.plist is missing the necessary UIBackgroundModes.

**Comment by munkii** [comment]
I totally understand your position. The scenario of using Shiny for Local Notifcations but something else for Push is unlikely and understandable that it is not supported.

EnsureNotificationDelegate does look like the reason why my DidReceiveRemoteNotification is not called.

FWIW I already had the UIBackgroundModes in our app and have added those to the repro repository, same issue. 

Thanks for looking into it.

**Comment by aritchie** [comment]
My point here is that method (DidReceiveRemoteNotification) IS being called in my sample repository and the integration tests where push and local notifications are being used.  It isn't a case of it not being supported.

**Comment by munkii** [comment]
it **IS** being called in your Shiny Samples, yes I understand that. 

What I meant was what seemed to be unsupported and also an unlikely use case was an app using Shiny for Local Notifcations and then trying to roll their own including their own Register, Registered and Received endpoints for Push.

That is what we are trying to do. We are only trying to do this because we want to secure the registering and tags behind a remote API.

**Comment by aritchie** [comment]
You can use Shiny.Push if you only need the native push token and then you can push that to your backend.

Are you sending content-available=1 or any sort of data in the payload?

**Comment by munkii** [comment]
Sorry for the delay in replying but I was off working on other stuff (one man team).

>>You can use Shiny.Push if you only need the native push token and then you can push that to your backend.<<
I'll look at trying to do that today

"content-available=1" is just needed for background updates right? Assuming that's correct,  no right now we don't need to request the app to pull updated data in background. When you say "data in the payload" can you give me an example?
