### ISSUE TITLE
[Bug]: KeyValue Store "settings" does not store values

### ISSUE THREAD

**Issue by gsgou** [shinyorg/shiny#724]
### Component

Core (Jobs, Settings, Initialization)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [X] iOS 14
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [ ] Android 11
- [ ] UWP

### Steps To Reproduce

```
   [ObjectStoreBinder("settings")]
    public class AppSettings : ReactiveObject, IAppSettings
    {
        [Reactive] public string SomeString { get; set; }
        [Reactive] public bool SomeBool { get; set; }
        [Reactive] public int SomeInt { get; set; }
    }
```
Last known working version for the above code: v**2.0.0.2639**

### Expected Behavior

Value property changes persist

### Actual Behavior

Value property changes do not persist

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
It's working fine for me in a few projects.  You should be seeing something in the logs.  Is a binding failing?

**Comment by gsgou** [comment]
AppSettings are bound correctly, i don't see anything peculiar in the logs. I ll investigate a bit further and report to you.

2021-09-19 12:24:26.384 XXX.iOS[1210:584401] Information: Successfully bound model - XXX.Services.AppSettings
2021-09-19 12:24:26.401 XXX.iOS[1210:584401] Information: Successfully bound model - Shiny.Power.PowerManagerImpl
2021-09-19 12:24:26.413 XXX.iOS[1210:584401] Information: Successfully bound model - Shiny.Net.ConnectivityImpl

**Comment by gsgou** [comment]
It looks like ObjectStoreBinder.OnPropertyChanged() is not called in my case for versions later then v2.0.0.2639.
I don't know yet the reason behind it.

**Comment by gsgou** [comment]
I have a workaround in case makes sense to you what breaks it after v2.0.0.2639.
Looks to relate on registration changes from ShinyServiceCollection to StartupModule and CreateServiceProvider().
Its my DI issue not Shiny, After i ll finish urgent deliverables on an active project i can provide a reproducible sample here.

```
readonly IAppSettings _appSettings;

public SettingsPageViewModel(IParameterViewStackService viewStackService, IAppSettings appSettings)
			: base(viewStackService)
		{
                     _appSettings =
		         //appSettings; // DOES NOT INVOKE ObjectStoreBinder.OnPropertyChanged()
			//Locator.Current.GetService<IAppSettings>(); // DOES NOT INVOKE ObjectStoreBinder.OnPropertyChanged()
			ShinyHost.Resolve<IAppSettings>(); // DOES THE JOB
			...
		}
		
    public static class MicrosoftDependencyInjectionExtensions
    {
        public static IServiceCollection AddServices(this IServiceCollection serviceCollection)
        {
            serviceCollection.AddSingleton<IAppSettings, AppSettings>();
            ...
            return serviceCollection;
        }
    }
    
    public class XYZStartup : ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            services
                ...
                .AddServices()
                .UseMicrosoftDependencyResolver(); // from Splat
        }
    }
```

**Comment by aritchie** [comment]
I'm sorry, but I can't cover absolutely every possible integration out there.  In this case, it looks like Shiny is doing what it is suppose to do, but Shiny's services aren't being put into your other container.  Not sure why, but it is outside of the scope of Shiny.  You can take a look at https://github.com/shinyorg/framework to see how I integrate with Prism (and RX to a degree).

**Comment by gsgou** [comment]
Thanks @aritchie for the link and the elegant APIs provided.  ll leave a comment here when i figure out how ro access the service from my MsDi container at a later time.
