### ISSUE TITLE
[Enhancement] Shiny Sample for default Xamarin Forms MVVM instead  Prism & RX 

### ISSUE THREAD

**Issue by ivoryguard** [shinyorg/shiny#73]
## Summary
Please, add Shiny Sample for default Xamarin Forms MVVM instead  Prism & RX 

## API Changes
Recent XF is not bad without external MVVM framework like MVVMLight or Prism.
So, many developers use default visual studio template of Xamarin Forms.

## Intended Use Case
Shiny Sample which Prism & RX framework are not used.

**Comment by aritchie** [comment]
There are no "feature requests" for the samples.  I'm sorry you don't want to use RX or Prism, but those are the frameworks of choice here.

**Comment by ivoryguard** [comment]
> There are no "feature requests" for the samples. I'm sorry you don't want to use RX or Prism, but those are the frameworks of choice here.

Can I use Shiny at my Xamarin Forms app which does not use Prism and RX?

**Comment by aritchie** [comment]
Prism & RXUI are not required, nor is Xamarin Forms.  Shiny does use RX for certain functionality like sensors and bluetooth if you intend to use those. 

I would encourage you to look through the library and sample code before using Shiny.

**Comment by ivoryguard** [comment]
> Prism & RXUI are not required, nor is Xamarin Forms. Shiny does use RX for certain functionality like sensors and bluetooth if you intend to use those.
> 
> I would encourage you to look through the library and sample code before using Shiny.

Thank you for the reply. I am already looking shiny and shiny sample sources. Because Prism does not support XF 4 AppShell yet, I do not adopt it. 

Shiny sample is good. However, viewmodels may be initialized automatically by Prism&DI, it is hard to find how objects are initialized and passed to ViewModels, without learning Prism.

In addition, Background uploading does not work. Is it not shiny issue, but server issue?

Best regards.

**Comment by ivoryguard** [comment]
> Prism & RXUI are not required, nor is Xamarin Forms. Shiny does use RX for certain functionality like sensors and bluetooth if you intend to use those.
> 
> I would encourage you to look through the library and sample code before using Shiny.

However, according to your documentation and sample, Prism may be required to inject IHttpTransferManager to ViewModel. Your source does not define the attributes for Xamarin Dependency Service and I cannot use it for DI.
