### ISSUE TITLE
[Feature Request]: Beacon monitoring permanent notification choice.

### ISSUE THREAD

**Issue by psmysupport** [shinyorg/shiny#732]
### Summary

When using BeaconMonitoring a permanent notification shows up. You can choose the title and the message of the notification but your unable to remove the notification no matter what. It also results in a 1 number character always being on the app icon so users keep thinking there's an important notification even though there isn't and where I work a customer is dissatisfied by that at least.  

So as an update I would like if you can choose whether the notification needs to be permanent.  

### API Changes

In the class: ShinyAndroidForegroundService

protected virtual void SendNotification()
        {
            this.builder ??= new NotificationCompat.Builder(this.Context.AppContext)
                            .SetChannelId(NotificationChannelId)
                            .SetSmallIcon(this.AndroidNotifications.GetSmallIconResource(null))
                            .SetOngoing(true); // HERE YOU WOULD SHOULD BE ABLE TO CHOOSE THE BOOL VARIABLE INSTEAD OF 
                                                               IT BEING HARCODED

            this.builder
                .SetProgress(
                    this.Service.Total,
                    this.Service.Progress,
                    this.Service.IsIndeterministic
                )
                .SetContentTitle(this.Service.Title ?? "Shiny Service")
                .SetTicker("..")
                .SetContentText(this.Service.Message ?? "Shiny service is continuing to process data in the background");

            if (this.notificationId == null)
            {
                this.notificationId = ++idCount;
                this.StartForeground(this.notificationId.Value, this.builder.Build());
            }
            else
            {
                this.AndroidNotifications.NativeManager.Notify(this.notificationId.Value, this.builder.Build());
            }
        }

### Intended Use Case

I'm trying to use your NuGet package in a project but the customer does not want a permanent notification. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
The notification has to be persistent in order for the foreground service to remain live.  It is an Android requirement
