### ISSUE TITLE
[Feature Request]: Badge character control for permanent notification on Android - BeaconMonitoring

### ISSUE THREAD

**Issue by psmysupport** [shinyorg/shiny#734]
### Summary

When using BeaconMonitoring a permanent notification shows up. By Android requirement it needs to be there but what about the badge number on application icon? Is it possible for it not to set that 1 character number for the permanent notification only. Users, I'm told, keep thinking they need to open the app to remove the badge and doesn't understand why it doesn't go away.

### API Changes

Shiny.Beacons

### Intended Use Case

For the user not to keep thinking that there is an unread notification or something they need to do in the app because the badge doesn't go away. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This has been added for a future release
