### ISSUE TITLE
[Bug]: Geofence not getting registered on Pixel 3XL Android 11 Java.Lang.Exception

### ISSUE THREAD

**Issue by Dipannita20** [shinyorg/shiny#738]
### Component

Locations (GPS, Geofencing, Motion Activity)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] UWP

### Steps To Reproduce

On Pixel 3XL Android 11 geofence isn't triggering at all, on checking the logs found below exception.
Could you tell what does this exception implies?
\"exception[0].Type\":\"Java.Lang.Exception\",\"exception[0].StackTrace\":\" at Shiny.Locations.GeofenceManagerImpl.Create (Shiny.Locations.GeofenceRegion region) [0x000fc] in <673dcb0703094599b9429ba\"}"

**App is using Shiny Locations 1.0.0.484-beta**

Note on other device SAMSUNG Android 11 geofence working properly

### Expected Behavior

Geofence should registered

### Actual Behavior

Geofence not getting registered

### Exception or Log output

\"exception[0].Type\":\"Java.Lang.Exception\",\"exception[0].StackTrace\":\" at Shiny.Locations.GeofenceManagerImpl.Create (Shiny.Locations.GeofenceRegion region) [0x000fc] in <673dcb0703094599b9429ba\"}"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I don't support old versions of the library especially betas.  Update it.  If you are still having problems, make sure you include the full stack trace and a reproducible sample

**Comment by Dipannita20** [comment]
I appreciate your response, live users are facing this issue, upgrade will take time. It will be helpful if you look into below log and comment. Thanks again for your time.

Shiny.Locations
GeofenceManagerImpl.Create (Shiny.Locations.GeofenceRegion region)
Shiny.Locations
GeofenceManagerImpl.StartMonitoring (Shiny.Locations.GeofenceRegion region)
Ambassador.Mobile.Services
RegisterGeofenceRegionsService.RegisterGeofenceRegionsImpl ()
com.google.android.gms.common.api.ApiException: 13:
com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:4)
com.google.android.gms.common.internal.zai.zaf(Unknown Source:2)
com.google.android.gms.common.internal.zaj.onComplete(Unknown Source:6)
com.google.android.gms.common.api.internal.BasePendingResult.zaa(Unknown Source:172)
com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source:131)
com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.setResult(Unknown Source:36)
com.google.android.gms.internal.location.zzba.zza(Unknown Source:22)
com.google.android.gms.internal.location.zzan.dispatchTransaction(Unknown Source:47)
com.google.android.gms.internal.location.zzb.onTransact(Unknown Source:22)
android.os.Binder.execTransactInternal Binder.java:1159
android.os.Binder.execTransact Binder.java:1123

**Comment by aritchie** [comment]
I have no idea what the issue could be.  I'm guessing ApiException 13 is missing background permissions which 1.0 didn't have support for new android 10 stuff which again means, you have to update.
