### ISSUE TITLE
When trying to call ShinyHost.Resolve<IGpsManager>(); its giving error

### ISSUE THREAD

**Issue by nitwill** [shinyorg/shiny#739]
### Component

Locations (GPS, Geofencing, Motion Activity)

### What platform(s) are effected?

- [ ] iOS 12
- [X] iOS 13
- [X] iOS 14
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] UWP

### Steps To Reproduce

When trying to execute
ShinyHost.Resolve<IGpsManager>()

Error: ServiceProvider has not been setup - have you initialized the Platform provider using ShinyHost.Init?

I have already implemented:
[assembly: ShinyApplication(
    ShinyStartupTypeName = "GoExpense.ShinyAppStartUp",
    XamarinFormsAppTypeName = "GoExpense.App"
)]
in AppDelegate

### Expected Behavior

Should get initialized

### Actual Behavior

Not initializing ShinyHost

### Exception or Log output

-		$exception	{System.ArgumentException: ServiceProvider has not been setup - have you initialized the Platform provider using ShinyHost.Init?
  at Shiny.ShinyHost.get_ServiceProvider () [0x00007] in /_/src/Shiny.Core/ShinyHost.cs:19 
  at Shiny.ShinyHost.Resolve[T] () [0x00000] in <c8ca43a7d0954031a0c8ab5e134aa7b3>:0 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
You've obviously done something wrong from the setup.  You need to provide a reproducible sample because you haven't provided anywhere near enough detail!!

**Comment by aritchie** [comment]
No response from user and no information in order to help.
