### ISSUE TITLE
[Bug]: Private property setter being called in generic (non-Shiny) class

### ISSUE THREAD

**Issue by olicooper** [shinyorg/shiny#740]
### Component

Core (Jobs, Settings, Initialization)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [ ] Android 11
- [ ] UWP

### Steps To Reproduce

I am using the basic Shiny.Framework application with a page that loads a service via DI. I use `App : FrameworkStartup` and add a service in `ConfigureServices` like so `services.AddSingleton<IMyMqttClient, MyMqttClient>();`.

Originally I had `services.UseSqliteStore()` and `services.AddSingleton<SqliteConnection>()` but disabled these during testing. This didn't change anything.

```csharp
public class MyMqttClient : INotifyPropertyChanged, IMyMqttClient
{
    string myProperty?;
    public string? MyProperty 
    {
        get => this.myProperty;
        // This is being called during app startup before the ViewModel that uses this service has been constructed
        private set => this.SetProperty(ref this.myProperty, value);
    }

    protected bool SetProperty<T>(ref T backingStore, T value,
        [CallerMemberName] string propertyName = "",
        Action? onChanged = null)
    {
        if (EqualityComparer<T>.Default.Equals(backingStore, value))
            return false;

        backingStore = value;
        onChanged?.Invoke();
        OnPropertyChanged(propertyName);
        return true;
    }

    public event PropertyChangedEventHandler? PropertyChanged;
    protected void OnPropertyChanged([CallerMemberName] string propertyName = "")
    {
        if (PropertyChanged != null)
            PropertyChanged.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
```

### Expected Behavior

I would like to be able to opt-in by using Shiny interfaces (rather than Microsoft ones) or using the `ObjectBinderAttribute` above the classes I need it applying to. You could even add something like `services.UseObjectStore(ObjectBinderStoreOptions options)` in `ConfigureServices` so it is close to where you register other services.

I don't see any documentation on how to disable / selectively enable this functionality, is this something that exists?

### Actual Behavior

I haven't opted in or out of using `ObjectStoreBinder`/`ObjectBinderAttribute` and I am using the basic `INotifyPropertyChanged` not `Shiny.NotifyPropertyChanged` - but the object store was applied transparently, so it left me scratching my head for a long time wondering why my private setter was getting set anyway.

### Exception or Log output

Looks like it is something to do with reflection in [ObjectStoreBinder](https://github.com/shinyorg/shiny/blob/dbfda1c44c06705f7076846bb2eaf9106cbcf03d/src/Shiny.Core/Stores/ObjectStoreBinder.cs#L79)

![image](https://user-images.githubusercontent.com/22296715/135355092-a21de179-49e6-4505-8b77-cbbd53213f6c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is something that is built in to the framework right now and won't be moving until v3.  If you make the properties private set, the framework will ignore them

**Comment by olicooper** [comment]
Thanks for the response, unfortunately making them private set (as seen in the example) does not work. I'm not sure why and this is what made it so confusing when debugging. 

I can see where you have the check..
https://github.com/shinyorg/shiny/blob/dbfda1c44c06705f7076846bb2eaf9106cbcf03d/src/Shiny.Core/Stores/ObjectStoreBinder.cs#L99-L105

This is my code and the reflection result:

```csharp
public interface IMyMqttClient : INotifyPropertyChanged
{
    bool IsConnected { get; }
}
public interface MyMqttClient : NotifyPropertyChanged, IMyMqttClient
{
    public bool IsConnected
    {
        get => isConnected;
        private set => SetProperty(ref this.isConnected, value);
    }
    private bool isConnected = false;
}
```

![image](https://user-images.githubusercontent.com/22296715/135456510-c05a01c8-f2f8-466f-9683-b4cf566fa952.png)

I think you might need this instead to function as you suggest it should:
https://stackoverflow.com/a/3762475/2634818

So maybe this?
```csharp
.Where(x =>
    x.CanRead &&
    x.CanWrite &&
    (x.GetSetMethod()?.IsPublic ?? false)
```
