### ISSUE TITLE
Can't build release 2.2, question and suggestions

### ISSUE THREAD

**Issue by mjmeans** [shinyorg/shiny#750]
### Question

So I downloaded the releases 2.2 version and extracted to C:\temp\shiny. I opened the readme file and since I'm just wanting to run the samples without doing any azure stuff I made a simple secrets.json file 
```
{
    "AzureNotificationHubFullConnectionString": null, // full endpoint that allows sending messages
    "AzureNotificationHubListenerConnectionString": null, // a listen only connection string
    "AzureNotificationHubName": null, // your test hub name
    "GoogleCredentialProjectId": null, // Firebase project ID
    "GoogleCredentialPrivateKeyId": null, // for testing firebase (leave blank otherwise)
    "GoogleCredentialPrivateKey": null, // for testing firebase (leave blank otherwise)
    "GoogleCredentialClientId": null, // for testing firebase (leave blank otherwise)
    "GoogleCredentialClientEmail": null, // for testing firebase (leave blank otherwise)
    "GoogleCredentialClientCertUrl": null, // for testing firebase (leave blank otherwise)
    "AppCenterKey": null // Your appcenter key for android/ios (leave blank if not using)
}
```

Anyway, I then right click on solution and restore nuget packages. Next I set the Samples.Android pacakge as the startup project and rebuild. I get numerous error messages referring to various type and namespaces in several Shiny.* projects referring to (uap 10.0.17763). So I then go into Visual Studio Installer and add the Windows SDK 10.0.17763 (which isn't the the current default version installed by VS 2019 installer).

I then get `No certificate found with the supplied thumbprint: B7A8D9E845F2D03EFC8ACC5659849FE4C3650E1A Samples.UWP`. I've searched all files the project for this thumbprint and it doesn't exist anywhere. What do I do about this?

I suggest: 

1. Adding a `secrets-empty.json` file like above to the repo for people to use as a quickstart with a note in readme
2. Add a note in the readme about what to do to either download the SDK needed or to retarget all the projects to use the current SDK. I think most people don't want numerous (and definitely not all) Windows SDK versions installed.  And after they review the samples and decide to use the library in their own applications would likely be using NuGet and will no longer need any older SDKs installed.

### Code of Conduct

- [X] I agree

**Comment by aritchie** [comment]
This area is meant for OSS maintainers or project supporters.  Please be respectful of this as it does say this in the issue template.  The current samples are more for show & tell then run & test.  I also don't take issues on the samples or docs - PR's are always welcome.  

There is a new samples repo located here that is a work-in-progress: https://github.com/shinyorg/samples

**Comment by aritchie** [comment]
The samples build fine if you know what you're doing.  I'm also not looking for supporters, but if people expect me to support them then in cases like this & they aren't already contributing to open source, then they should expect to contribute in some form.  This project has almost a million downloads overall, so I don't think faith is a factor any longer.
