### ISSUE TITLE
[Bug]: UWP sample app crash on builder.Register() at RegisterNative at JobManager

### ISSUE THREAD

**Issue by Makeshet** [shinyorg/shiny#756]
### Component

Core (Jobs, Settings, Initialization)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] UWP

### Steps To Reproduce

 1. Download the source.
 2. Build and run Samples.UWP

### Expected Behavior

UWP main page shows

### Actual Behavior

Get to the statement:
// TODO: this periodically crashes
builder.Register();
at RegisterNative at class JobManager and crash.
replace with:
 try {
                builder.Register();
            }
            catch (Exception Exception) {
                Console.WriteLine(Exception.Message);
            }

### Exception or Log output

Exception.Message:
Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
![image](https://user-images.githubusercontent.com/500151/136969030-54cbd5ed-333f-49a2-b0e9-321e19e4b658.png)

Exception.StackTrace:
   at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()
   at Shiny.Jobs.JobManager.RegisterNative(JobInfo jobInfo) in H:\Xamarin_Samples\Shiny_LIbrary\shiny\src\Shiny.Core\Jobs\Platforms\Uwp\JobManager.cs:line 8
[crash_log.txt](https://github.com/shinyorg/shiny/files/7330519/crash_log.txt)
4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I'm closing this because the samples are setup for internal dev/debugging work and don't offer real world case, nor should issues be filed against samples. 

Lastly, UWP is likely switching to a sponsor only model in the very near future.
