### ISSUE TITLE
[Bug]: System.ArgumentException: Job type not found - did you delete/move this class from your library? Type Name:  JOB-NAME

### ISSUE THREAD

**Issue by KSemenenko** [shinyorg/shiny#762]
### Component

Jobs

### What platform(s) are effected?

- [ ] iOS 12
- [x] iOS 13
- [X] iOS 14
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [X] Android 11
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. Create and register a Job.
2. update and run the application
3. do not uninstall the application
4. delete or rename the Job.
5. restart the application

### Expected Behavior

If there is no Job, at least do not crash the application.

### Actual Behavior

Application crash 1 minute after running RunAll()

### Exception or Log output

PersistJobInfo.Assert ()
System.ArgumentException: Job type not found - did you delete/move this class from your library? Type Name: Shiny.Jobs.UpdateLocationJobCharged, App.Mobile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Shiny.Jobs.Infrastructure
PersistJobInfo.Assert ()
Shiny.Jobs.Infrastructure
PersistJobInfo.FromPersist (Shiny.Jobs.Infrastructure.PersistJobInfo job)
Shiny.Jobs
AbstractJobManager.Run (System.String jobName, System.Threading.CancellationToken cancelToken)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KSemenenko** [comment]
And the crash happens somewhere in Shiny at a time when I can't wrap it in try-catch
about a minute after starting the application and calling RunAll();

**Comment by aritchie** [comment]
That unfortunately doesn't help.  Do you have a reproducible sample then?
