### ISSUE TITLE
[Feature Request]: Controlled Store Binding

### ISSUE THREAD

**Issue by gsgou** [shinyorg/shiny#781]
### Summary

As a user i would like that some of my registered singletons can opt-out from being bound with IObjectStoreBinder to a KeyStore.

### API Changes

Maybe an attribute as [ObjectStoreBinder("none")]
or other means in some of the following methods:
StartupModule.Init
StartupModule.DoBindables
IObjectStoreBinder.Bind

### Intended Use Case

Currently my workaround is to use Unbind(object) after initialization.
I want to ensure that some of interfaces do not persist their values with the default store
or implement another custom persistance flow.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Anything that implements INotifyPropertyChanged & is a singleton that is registered to Shiny is bound.

This is something that is being consider for 3.0, but it isn't promised.

**Comment by gsgou** [comment]
I understand is far away from prio.  
Thanks for taking it into consideration.

In the meantime Unbind () and removing a public setter where possible are some ways to workaround It.
