### ISSUE TITLE
[Bug] iOS: Shiny.Net.Http upload straight to onError

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#782]
### Discussed in https://github.com/shinyorg/shiny/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **GuidoNeele** November  3, 2021</sup>
I'm setting up background uploads using Shiny.Net.Http. Everything is working fine on Android but when uploading files on iOS the `IHttpTransferDelegate` `OnError` method is called straightaway with a "cancelled" exception (only a message no stacktrace). 

I've added the following code to `AppDelegate.cs`:
```csharp 
public override void HandleEventsForBackgroundUrl(UIApplication application, string sessionIdentifier, Action completionHandler)
{
      this.ShinyHandleEventsForBackgroundUrl(sessionIdentifier, completionHandler);
}
```

I think that's the only setup that needs to be done for iOS is that correct or am I missing something? 

Thanks in advance!

Guido</div>

**Comment by aritchie** [comment]
There is an untested fix in preview - I would wait on testing for now

**Comment by GuidoNeele** [comment]
Thanks Allan! I'll try and test the new build when it's out.

**Comment by GuidoNeele** [comment]
Did run into an issue with `IHttpTransferDelegate.OnCompleted` not being called. Looks like `NSUrlSessionDownloadDelegate.DidSendBodyData` is not called when the file has been completely uploaded, it's only called during upload for progress reporting. Apple developer docs indicate that `NSUrlSessionDownloadDelegate. DidCompleteWithError` is called when upload is finished.

DidSendBodyData - https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1408299-urlsession
DidCompleteWithError - https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1411610-urlsession

https://github.com/shinyorg/shiny/blob/fb6ff63e07f2d15e2ff8156ec43ea4bf29013108/src/Shiny.Net.Http/Platforms/iOS/ShinyUrlSessionDelegate.cs#L67-L96

**Comment by aritchie** [comment]
Latest preview seems to be showing this working well.  I'm going to push 2.4 now, but feel free to comment back if you are still having issues.
