### ISSUE TITLE
[Bug]: BluetoothLE method GetConnectedPeripherals()

### ISSUE THREAD

**Issue by Avots** [shinyorg/shiny#793]
### Component

BluetoothLE Client

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Version 2.3.0.2936-preview.
1- Once connected, I search for bluetooth and it returns connected status. 
2- If searching a second time, it returns connected, but the status is disconnected.

![image](https://user-images.githubusercontent.com/79453107/140516083-1091ace0-5dd6-42b0-abad-8887af795b07.png)

### Expected Behavior

Always connected when searching
peripheral.Status == Shiny.BluetoothLE.ConnectionState.Connected

### Actual Behavior

peripheral.Status == Shiny.BluetoothLE.ConnectionState.Disconnected

### Code Sample

    var peripherals = await this.manager.GetConnectedPeripherals();
    foreach (var peripheral in peripherals)
    {
        //peripheral.Status == Shiny.BluetoothLE.ConnectionState.Disconnected
    }

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is because you haven't connected to the device in YOUR app.  If the GATT is null, you can't perform any operations against the device. 

https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Platforms/Android/Internals/PeripheralContext.cs#L36

**Comment by Avots** [comment]
Sorry, but I plugged in and read the sensor.
My sensor only connects when I read a feature
What I did was look again for the sensor connected to bluetooth.
That made everything work.
Do the search again this is where the problem occurs.(Bluetooth connected)

**Comment by Avots** [comment]
> This is because you haven't connected to the device in YOUR app. If the GATT is null, you can't perform any operations against the device.
> 
> https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Platforms/Android/Internals/PeripheralContext.cs#L36

Sorry, but I plugged in and read Characteristics the sensor.
My sensor only connects when I read a Characteristics
What I did was look again for the sensor connected to bluetooth.
That made everything work.
Do the search again this is where the problem occurs.(Bluetooth connected)

**Comment by aritchie** [comment]
What do you mean by search?  This is why I ask for very specific steps to reproduce with a sample.  I have no idea what you're talking about now.  Please be respectful of this in the future as it is a HUGE waste of time trying to figure what you are doing.

If by search, you mean - scan.  Scan completely destroys all instances it is tracking.  You have to be responsible for holding an instance you are connected to

**Comment by Avots** [comment]
Sorry my English, I use google translation. Forgive me if I'm wrong again.
Step by step.

1 - Connect the sensor to bluetooth and load the characteristics.
2 - Use the GetConnectedPeripherals method:
var peripherals = await this.manager.GetConnectedPeripherals();
foreach (var peripheral in peripherals)
{
     //Only Connected
     //peripheral.Status is ConnectionState.Connected - OK
}
3 - Use the GetConnectedPeripherals method again:
var peripherals = await this.manager.GetConnectedPeripherals();
foreach (var peripheral in peripherals)
{
     //Only Connected
     //peripheral.Status is ConnectionState.Disconnected
}
