### ISSUE TITLE
Is it possible to change the PairingState of a device ?

### ISSUE THREAD

**Issue by TechWatching** [shinyorg/shiny#8]
## Feature Library

 - [x] BluetoothLE

## Question
Does this library allows to change the pairing state of a device ? In particular, I would like to be able to set the PairingState from Paired to NotPaired

**Comment by aritchie** [comment]
Sorry about that - the new bot is a little aggressive still.  

You cannot unpair a device via code.  Please note that the BLE library here is still in early beta.

**Comment by TechWatching** [comment]
Okay thanks for the quick answer :).
