### ISSUE TITLE
[Bug]: PushDelegate OnReceived not run for iOS (Runs fine for Android)

### ISSUE THREAD

**Issue by killer-frog** [shinyorg/shiny#802]
### Component

Push - Native

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [X] iOS 14
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Add PushDelegate and use `service.UsePush<Delegate>()` to register it
Open the App.
Send Push Notification to App

using the latest version from nuget (2.3.0.2906).

This also does not work on iOS 15 (not available in your selection above)

### Expected Behavior

When the app receives a push notification, the OnReceived member of the Push delegate should be run

### Actual Behavior

The push notification is received, On iOS OnReceived is not run (runs for android)

I have found a work around, by adding the following to the AppDelegate but It feels a little dirty.

``` csharp

        partial void OnPostFinishedLaunching(UIApplication app, NSDictionary options)
        {
            CachedImageRenderer.Init();
            var ignore = typeof(SvgCachedImage);
            
            ShinyHost.Resolve<AppleLifecycle>().RegisterForNotificationPresentation(async notification =>
            {
                if (app.ApplicationState == UIApplicationState.Active)
                {
                    MessagingCenter.Send(nameof(AppDelegate), Constants.AlarmReceived);
                }
            });
        }
```workaround

### Exception or Log output

_No response_

### Code Sample

Push Delegate
``` csharp

        public async Task OnReceived(PushNotification notification)
        {
            Analytics.TrackEvent("Push-Received");
            FreshIOC.Container.Resolve<IMessagingCenter>().Send(nameof(App), Constants.AlarmReceived);
        }

```

Registered for push in App Startup

``` csharp
    public class AppStartUp : ShinyStartup
    {
        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            services.UsePush<PushDelegate>();
        }

        public override void ConfigureLogging(ILoggingBuilder builder, IPlatform platform)
        {
            builder.AddAppCenter(
                "ios=xxxxx-xxx-xxxxxxx-xxx;android=xxx-xxx-xxxx",
                LogLevel.Error);
            base.ConfigureLogging(builder, platform);
        }
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Are you sending content-available: 1 and how have you wired appdelegate?

**Comment by killer-frog** [comment]
Hi,

We don't set content-available to 1 as this is when the application is on the foreground and we are not interested in waking the App from the background to do this.

My App Delegate is:

``` csharp

[assembly: ShinyApplication(
    ShinyStartupTypeName = "AddView.Mobile.AppStartUp",
    XamarinFormsAppTypeName = "AddView.Mobile.App"
)]
namespace AddView.iOS
{
    [Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        partial void OnPostFinishedLaunching(UIApplication app, NSDictionary options)
        {
            CachedImageRenderer.Init();
            var ignore = typeof(SvgCachedImage);
            
            ShinyHost.Resolve<AppleLifecycle>().RegisterForNotificationPresentation(async notification =>
            {
                if (app.ApplicationState == UIApplicationState.Active)
                {
                    MessagingCenter.Send(nameof(AppDelegate), Constants.AlarmReceived);
                }
            });
        }
    }
}

```

**Comment by aritchie** [comment]
That's how OnReceived works on iOS though.  If you don't send content-available:1, it doesn't process the event for on the iOS side

**Comment by killer-frog** [comment]
ok - the documentation I read on content-available said it was for silently waking the app from the background to refresh data, rather than being concerned with the App being in the foreground. (my use case is the app is in the foreground)

In your code, in the `IPushDelegate(18)` it says: if your app is **in the background** you need to pass content-available:1

Adding my refresh code to the `RegisterForNotificationPresentation` calls seems to work fine while feeling a little wrong.

Do you want me to create a PR to fix the summary comment in the `IPushDelegate`?

**Comment by aritchie** [comment]
It is silently waking the app with content-available = 1.  That is the event and the section that Shiny.Push is covering.  I've heard your request for the code "feeling wrong", but that is the way it works right now and will continue to do so.  I am looking into ways to cover both a background experience and a foreground experience in the future (there is already a feature request that I've entered)
