### ISSUE TITLE
[Bug]: Getting exception on ShinyJobWorker

### ISSUE THREAD

**Issue by Dipannita20** [shinyorg/shiny#805]
### Component

Jobs

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. Create XF project, install shiny core, shiny jobs
2. Initialize the job in shiny startup file `var job = new JobInfo(typeof(RefreshGeofenceRegionsJob),
                nameof(RefreshGeofenceRegionsJob))
            {      
                RequiredInternetAccess = InternetAccess.Any,
                Repeat = true
            };
            services.RegisterJob(job);`
3. Build the app, observe exception

### Expected Behavior

Should not be any exception as I am building the app first time.

### Actual Behavior

Exception thrown
[WM-WorkerWrapper] java.util.concurrent.CancellationException: Task was cancelled.
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
[WM-WorkerWrapper] 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:300)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
[WM-WorkerWrapper] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[WM-WorkerWrapper] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[WM-WorkerWrapper] 	at java.lang.Thread.run(Thread.java:923)

### Exception or Log output

[WM-WorkerWrapper] java.util.concurrent.CancellationException: Task was cancelled.
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
[WM-WorkerWrapper] 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:300)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
[WM-WorkerWrapper] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[WM-WorkerWrapper] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[WM-WorkerWrapper] 	at java.lang.Thread.run(Thread.java:923)

### Code Sample

[App2.zip](https://github.com/shinyorg/shiny/files/7579068/App2.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This is not an issue.  It is trapped and totally managed by shiny.
