### ISSUE TITLE
[Bug]: this.ShinyOnCreate method not accessible from versions 2.3.0.2906 on Xamarin.Android project

### ISSUE THREAD

**Issue by appimpact** [shinyorg/shiny#815]
### Component

Core (Settings, Startup)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Updated Shiny from 2.3.0.2906 to 2.3.0.2958/2.4.0.2960.

After update, this.ShinyOnCreate method (and all other methods from AndroidHooks) is no longer accessible on Xamarin.Android projects:

Xamarin.iOS project is working as expected.

Happens on all projects, including an empty project created from Prism template pack.

### Expected Behavior

Methods should be accessible the same way they used to in previous versions.

### Actual Behavior

Methods are no longer accessible.

### Code Sample

![image](https://user-images.githubusercontent.com/34662138/142911172-268ad193-650e-44c3-a383-5b3f4b075ab7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please review the release notes in the future (although the latest 2.3 should have been filed as 2.4).  https://shinylib.net/release-notes/v240

The major android target is now 11.

**Comment by appimpact** [comment]
Thank you for the quick response.

We did check release notes, but GitHub is showing only 2.3, which is the reason why we missed on this:
https://github.com/shinyorg/shiny/releases

Issue has been resolved, keep up the excellent work!
