### ISSUE TITLE
[Feature Request]: Platform Specific Dependency Injection

### ISSUE THREAD

**Issue by Guitarnivore** [shinyorg/shiny#816]
### Summary

Adding native services that implement a common interface could be useful. This allows shared code to implement platform specific versions of the same method from an injected object.

For example, an interface Interface could be implemented in the iOS project by iOSImpl, and the Android project by AndrtoidImpl. Then in the native projects, the implementation is added to the service collection that is passed through in a method. Now when Interface is injected on Android, the Android version is obtained while on iOS the iOS version is.

### API Changes

One way to do this is to have a partial method that can be implemented in the AppDelegate or MainActivity like so:

```
namespace MyApp.iOS
{
	// Setup performed by Shiny
	[Register("AppDelegate")]
	public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
	{
		partial void NativeServices(IServiceCollection services)
                {
			services.AddTransient<IInterface, iOSImpl>();
                }
         }
}
```

Then ShinyFinishedLaunching can run that method using the same service collection passed into the startup.

### Intended Use Case

For platform specific implementations of interfaces that can be called from shared code.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
This already exists.  In iOS, in FinishedLaunching you can do the following

```csharp
this.ShinyFinishedLaunching(new YourStartup {
  RegisterPlatformServices = (services) => {
    // register here
  };
});
```

On Android, you will have to manually create the application and call ShinyOnCreate with the same arg types.

**Comment by Guitarnivore** [comment]
Thanks for your help! Sorry I was unable to see this earlier.
