### ISSUE TITLE
[Bug]: OnEntry is never called with Shiny.Push.FirebaseMessaging

### ISSUE THREAD

**Issue by appimpact** [shinyorg/shiny#817]
### Component

Push - Firebase

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

We are using Shiny.Push.FirebaseMessaging .

We have followed the instructions to integrate Shiny with Android hooks:
1) In MainApplication:

```
        public override void OnCreate()
        {
            this.ShinyOnCreate(new AppStartup());
            Xamarin.Essentials.Platform.Init(this);
            base.OnCreate();
        }

```

2) In MainActivity:

```
        protected override void OnCreate(Bundle savedInstanceState)
        {
            this.ShinyOnCreate();

            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Xamarin.Forms.Forms.Init(this, savedInstanceState);

            LoadApplication(new App(new PlatformInitializer()));
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            this.ShinyOnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            this.ShinyOnActivityResult(requestCode, resultCode, data);
        }

        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            this.ShinyOnNewIntent(intent);
        }
```

3) In AppStartup.cs:

```
    public class AppStartup : Startup
    {
        public override void ConfigureServices(IServiceCollection services, IPlatform platform)
        {
            services.UseJobs(true);
            services.UseFirebaseMessaging<AppPushDelegate>();
        }
    }

```
These are the things that are working:
1) OnTokenRefreshed is working as expected and we are able to refresh tokens
2) OnReceived is working as expected when app is running and we are able to extract values from Data property 
3) When push notification is sent through Firebase with token acquired through Shiny, notification is displayed on phone tray
4) When notification is tapped while application is not running, application is started properly

What we are reporting as a bug is that OnEntry is not called when notification is tapped, so that we can access Data and extract information required to initialize application properly.

As far as we are familiar, Data should be available within the Intent that is generated in OnCreate method of MainActivity. We expected that Shiny would extract that data and make it available in OnEntry method.

This is how we form the payload (we use FirebaseAdmin NuGet package):

```
                Message notificationMessage = new()
                {
                    Token = "xxxxx-token-value-xxxxx",
                    Notification = new FirebaseAdmin.Messaging.Notification
                    {
                        Body = "xxxxx-message-body-xxxx",
                        Title = "xxxx-title-xxxxx"
                    },
                    Data = new Dictionary<string, string>()
                    {
                        { "entryId", "14" ) }
                    }
                };
                notificationMessage.Android = new AndroidConfig
                {
                    Priority = Priority.High,
                    Notification = new AndroidNotification 
                    {
                         ChannelId = "app_main_channel",
                         Body =  "xxxxx-message-body-xxxx",
                         Title = "xxxx-title-xxxxx"
                    }
               };
```

Since there is nothing else left in documentation, we would appreciate clarification if OnEntry is really intended to be called when notification is tapped, and if yes, is there anything you see that we are missing that might be the cause of this.

We are using latest Xamarin.Forms and Xamarin.Android as well as latest non-preview versions of Shiny.Push.FirebaseMessaging and Shiny.

Thank you!

### Expected Behavior

OnEntry should be called when notification is tapped in tray, and data sent as notification payload should be accessible.

### Actual Behavior

OnEntry is never executed so there is no way to access the data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please read existing issues before opening new ones.  This has already been filed.

**Comment by Codelisk** [comment]
https://github.com/shinyorg/shiny/issues/656
