### ISSUE TITLE
[Bug]: XamlC error XFC0000 : Cannot resolve type "FrameworkApplication".

### ISSUE THREAD

**Issue by SalimiHabib** [shinyorg/shiny#818]
### Component

Core (Settings, Startup)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

just fresh install and using FrameworkApplication in App.xaml ans App.cs

### Expected Behavior

not to show this error

### Actual Behavior

show  this error at build time  but  no error in runtime just at build time 
and code run 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
It seems I banned you from the Shiny repository some time ago for not following issue templates.  I see that this still hasn't improved - this is not the framework repository NOR is framework considered "ready".  The repo readme on it even says "COMING SOON".
