### ISSUE TITLE
[Bug]: Write to IManagedPeripheral fails.

### ISSUE THREAD

**Issue by fg-qlogic** [shinyorg/shiny#827]
### Component

BluetoothLE Client

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [X] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. Create a ManagedPeripheral.
2. Write data.

### Expected Behavior

Data should be sent to peripheral.

### Actual Behavior

No data is sent.

It looks like there is a missing `Switch` after the call to `Write` [here](https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Managed/ManagedPeripheral.cs#L137). The same goes for `WriteBlob`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Can you please provider a much more complete test case.  There is a lot that can happen up to this point.

**Comment by fg-qlogic** [comment]
I'll create a new sample app since I unfortunately can't share the one app I'm working on currently. I'll get back to you on that later.

In the meantime here is a snippet where I'm calling `Write` and a hacky workaround.

```cs
// _peripheral is an instance of IManagedPeripheral that it's connected.

// This doesn't work.
await _peripheral.Write(serviceId, writeId, data);

// This works.
var gattChar = await _peripheral.Peripheral.GetKnownCharacteristic(serviceId, writeId, true);
await gattChar.Write(data, true);
```

Looking at the `ManagedPeripheral.Write` implementation on the line I linked to earlier, we see that the type of `x` in the final select is an `IObservable` and it is never selected. This seems to prevent the actual write from happening. (I'm fairly new to C# and Rx so correct me if I'm wrong.)

The implementation of `ManagedPeripheral.Read` do have the `Switch` and that one works.

Thanks for an otherwise awesome library!

**Comment by aritchie** [comment]
This should be fixed in the latest preview version
