### ISSUE TITLE
[Bug]: Application crash afther conceded location permission all time - Just Release Mode.

### ISSUE THREAD

**Issue by MichaelRodrigueess0s1** [shinyorg/shiny#829]
### Component

Locations (GPS, Geofencing, Motion Activity)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1) Create the GpsRequest and make access Request to access all time.
2) Afther concedess permission start to listening monitoring.
3) close the app.

### Expected Behavior

Application continuos monitoring the location afther the application are closed by user.

### Actual Behavior

Application crashe when method Manager.RequestAccess(request)) is call

### Exception or Log output

I cant get the log because the application crashe just in release mode.

### Code Sample

using MVVMCoffee.ViewModels;
using Shiny;
using Shiny.Locations;
using System;
using Xamarin.Forms;

namespace EvJus.Mobile.ViewModels
{
	public class PrisonerInformationViewModel : BaseViewModel
	{
		readonly IGpsManager Manager;

		public Command StartMonitoringGPS { get; }
		public Command RequestLocationAcessCommand { get; }

		public PrisonerInformationViewModel()
		{
			Manager = ShinyHost.Resolve<IGpsManager>();

			var currentRequestListener = Manager.CurrentListener;

			if (currentRequestListener.IsNullOrDefault())
			{
				AccessGrantedType = "Sem acesso! forneça as permissões necessárias";
			}

			RequestLocationAcessCommand = new Command(ExecuteRequestLocationAcess);
		}

		private string accessGrantedType;

		public string AccessGrantedType
		{
			get { return accessGrantedType; }
			set { SetProperty(ref accessGrantedType, value); }
		}

		private async void ExecuteRequestLocationAcess(object obj)
		{
			var request = CreateRequest();
			var access = (await Manager.RequestAccess(request));
			if (access != AccessState.Available)
			{
				AccessGrantedType = "Sem permissões suficientes";
				return;
			}

			AccessGrantedType = "Permissões concedidas";

			try
			{
				//await Manager.StartListener(request);
			}
			catch (Exception ex)
			{
				AccessGrantedType = ex.ToString();
			}
		}

		private GpsRequest CreateRequest()
		{
			GpsRequest request = new GpsRequest();
			request.Interval = new TimeSpan(0, 1, 0);
			request.Priority = GpsPriority.Highest;
			request.ThrottledInterval = new System.TimeSpan(0, 0, 5);
			//request.UseBackground = true;
			Manager.Title = "EVjus";
			Manager.Message = "Monitoramento ativo";
			return request;
		}
	}
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
You have to get a log or I can’t help with your issue.  It is likely you’ve delinked something that is required

**Comment by MichaelRodrigueess0s1** [comment]
i dont now how i'm get the log because the crash happen ony in release mode when im startup the application using debug mode the crasy does not happen. i''m using version 2.0.0.2639. i'm try update the version to try fix the bug, but when i'm update the packages the new error appear. my Android application not recognize the Shiny when i try use 2.4+ version.

**Comment by MichaelRodrigueess0s1** [comment]
![image](https://user-images.githubusercontent.com/10400985/144726237-487d60f4-adc8-4d9f-804b-cc97dae1660e.png)

**Comment by aritchie** [comment]
2.4 uses a major target of Android 11.  You can see this on the nuget package.  It means your head app needs to also target android 11 in order to pickup the nuget package.

You are experiencing a linker issue.  You need to read up on some of the articles about to use this.  If it works in debug, but not in release - there is a likely a dependency library being stripped away by the compiler that Shiny needs.  It could also be stripping away something from another library that you use.  You can collect logs from the device log.  VS4mac is also good at seeing them, but all of this is external to this actual library.  You need to read up on all of it under the Microsoft docs.

**Comment by MichaelRodrigueess0s1** [comment]
ok, thanks for the path of stones. I'm trying to study the fix here. if you want you can close this one.
