### ISSUE TITLE
[Bug]: Application crashed afther Start listener using Background mode alltime .

### ISSUE THREAD

**Issue by MichaelRodrigueess0s1** [shinyorg/shiny#839]
### Component

Locations (GPS, Geofencing, Motion Activity)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

I'm created a viewmodel and 2 buttons, one get Request access location and anothe execute start monitoring like this:

    Command to execute request acess
	public async void ExecuteRequestAcessCommand()
		{
			var request = new GpsRequest { BackgroundMode = GpsBackgroundMode.Realtime };
			State = await Manager.RequestAccess(request);
			AcessText = (State).ToString();
		}

Command to execute GPS monitoring:
public async void ExecuteStartMonitoringGPS()
		{
			var listener = Manager.CurrentListener;

			if (!listener.IsNullOrDefault())
			{
				await Manager.StopListener();
			}
			else
			{

				if (State != AccessState.Available)
				{
					await Alert("Permissões insuficientes");
					return;
				}
				else
				{
					var request = new GpsRequest
					{
						BackgroundMode = GpsBackgroundMode.Realtime,
						Priority = GpsPriority.Normal,
						Interval = ToInterval(50),
						ThrottledInterval = ToInterval(5),
						Precise = true,
						MinimumDistance = Distance.FromMeters(1)
					};

					try
					{
						await Manager.StartListener(request);
						var current = Manager.CurrentListener;
						await Alert("Monitoramento iniciado!");
					}
					catch (Exception e)
					{

						await this.Alert(e.Message);
					}
				}
			}
		}

all other parts like startup, APP, mainApplication are just like the tutorials

### Expected Behavior

1) When i'm execute request persmission my android concedess all time permission

2) when i'm execute ExecuteStartMonitoringGPS my application start monitoring GPS.

### Actual Behavior

1) When i'm execute request persmission my android concedess all time permission

2) when i'm execute ExecuteStartMonitoringGPS my application crash and close.

### Exception or Log output

Thread finished: <Thread Pool> #6
The thread 0x6 has exited with code 0 (0x0).
Information: Job Start
Information: Job Success
Information: Job Start
Information: Job Success
The thread 0x5 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #5
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.evjus.mobile, PID: 23828
[AndroidRuntime] android.app.RemoteServiceException: Bad notification for startForeground
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:250)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7848)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
[me.evjus.mobil] Checksum mismatch for dex base.apk
[me.evjus.mobil] Could not add methods to the existing profiler. Clearing the profile data.
**Java.Lang.RuntimeException:** 'Bad notification for startForeground'

### Code Sample

using EvJus.Mobile.Views;
using Shiny;
using Shiny.Locations;
using System;
using System.Threading.Tasks;
using Xamarin.Forms;
using System.Diagnostics;

namespace EvJus.Mobile.ViewModels
{
	public class PrisonerInformationViewModel : EvViewModelBase
	{
		readonly IGpsManager Manager;
		private AccessState State;

		public Command StartMonitoringGPS { get; }

		internal void OnDisappearing(PrisonerInformationPage prisonerInformationPage, EventArgs empty)
		{
		}

		internal void OnAppearing(PrisonerInformationPage prisonerInformationPage, EventArgs empty)
		{
		}

		public Command GetLastOrCurrent { get; }
		public Command RequestAccess { get; }
		public Command ToggleUpdates { get; }

		private string acessText;

		public string AcessText
		{
			get { return acessText; }
			set { SetProperty(ref acessText, value); }
		}

		public PrisonerInformationViewModel()
		{
			Manager = ShinyHost.Resolve<IGpsManager>();
			StartMonitoringGPS = new Command(ExecuteStartMonitoringGPS);
			RequestAccess = new Command(ExecuteRequestAcessCommand);
		}

		public async void ExecuteRequestAcessCommand()
		{
			var request = new GpsRequest { BackgroundMode = GpsBackgroundMode.Realtime };
			State = await Manager.RequestAccess(request);
			AcessText = (State).ToString();
		}

		public async void ExecuteStartMonitoringGPS()
		{
			var listener = Manager.CurrentListener;

			if (!listener.IsNullOrDefault())
			{
				await Manager.StopListener();
			}
			else
			{

				if (State != AccessState.Available)
				{
					await Alert("Permissões insuficientes");
					return;
				}
				else
				{
					var request = new GpsRequest
					{
						BackgroundMode = GpsBackgroundMode.Realtime,
						Priority = GpsPriority.Normal,
						Interval = ToInterval(50),
						ThrottledInterval = ToInterval(5),
						Precise = true,
						MinimumDistance = Distance.FromMeters(1)
					};

					try
					{
						await Manager.StartListener(request);
						var current = Manager.CurrentListener;
						await Alert("Monitoramento iniciado!");
					}
					catch (Exception e)
					{

						await this.Alert(e.Message);
					}
				}
			}
		}

		static TimeSpan ToInterval(int value)
		{
			var ts = TimeSpan.FromSeconds(value);
			return ts;
		}

		private async Task<AccessState> RequestLocationAcess() => await Manager.RequestAccess(new GpsRequest
		{
			BackgroundMode = GpsBackgroundMode.Realtime
		});
	}
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
[AndroidRuntime] android.app.RemoteServiceException: Bad notification for startForeground

You are likely missing an icon that the notification mechanism can't pickup.  You can try await Shiny.ShinyHost.Resolve<Shiny.Notifications.INotificationManager>().Send("test"); <= catch the exception here.  It will explain what is missing
