### ISSUE TITLE
Documentation - BluetoothLE

### ISSUE THREAD

**Issue by aritchie** [shinyorg/shiny#85]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Shiny.BluetoothLE - https://shinydocs.azurewebsites.net/docs/ble/

## API Changes
None

## Intended Use Case
None

**Comment by pravincarvalho** [comment]
@aritchie I've used Plugin.BluetoothLE quite a bit and am keen to try out Shiny. I can work on the docs as I make use of the BluetoothLE functionality. 
Any tips on where you would like me to start or how to contribute?
