### ISSUE TITLE
[Feature Request]: Xamarin.AndroidX.Work.Runtime upgrade 2.7.0

### ISSUE THREAD

**Issue by Dipannita20** [shinyorg/shiny#852]
### Summary

**Notice conflict with another package which require  Xamarin.AndroidX.Work.Runtime  >=2.7.0** 
Shiny.Jobs 2.4.1.2971 requires Xamarin.AndroidX.Work.Runtime (>= 2.5.0 && < 2.6.0)

**Could you please upgrade Xamarin.AndroidX.Work.Runtime  to 2.7.0, it is also required to target Android 12**

Or could you confirm will it have impact on the shiny jobs if Xamarin.AndroidX.Work.Runtime  to 2.7.0 is used

### API Changes

Shiny.Jobs  Xamarin.AndroidX.Work.Runtime to 2.7.0

### Intended Use Case

Target Android 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I don't generally accept feature requests for library updates.  I try to stay close to Xamarin forms in terms of versioning.  2.7 isn't required for Android 12.  You can use the existing version that Shiny uses just fine.

I can't confirm if 2.7 will work fine with shiny as I haven't updated it.
