### ISSUE TITLE
[Bug]: Ble - when subscribing to a characteristic write, OnError is never called if writing WithoutResponse

### ISSUE THREAD

**Issue by krobotics** [shinyorg/shiny#871]
### Component

BluetoothLE Client

### What platform(s) are effected?

- [X] iOS 12
- [X] iOS 13
- [X] iOS 14
- [X] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Writing a large number of blobs, to a characteristic without response, may eventually stop transferring data to the target device. This does not occur 100% of the time but is reasonable reproducible.  

No error is ever returned if subscribing to the write (code sample below).

I reviewed the Shiny source code and saw that WriteWithResponse has an EventHandler, This can handle errors. WriteWithoutResponse calls two possible functions and neither have any event handling for possible errors, therefore ob.OnError is never called.

I work around this by adding a timeout to the subscribe, but a real error would probably be better.

I checked the Android Platform and the Write is handled differently, so no issues there. 

### Expected Behavior

I would expect an error if the Platform experiences an error

### Actual Behavior

No Errors ever returned

### Exception or Log output

Nothing to log.

### Code Sample

``` 
var otapDataCharacteristic = await target.GetKnownCharacteristicAsync(guids.OTAP_SERVICE.ToString(), guids.OTAP_DATA_CHARACTERISTIC.ToString());

...

var sub=otapDataCharacteristic
                .Write(chunkData.ToArray(), false)
                .Subscribe(
                res => Console.WriteLine($"Chunks Left {chunks} -seq {seqNumber}"),
                ex => Console.WriteLine($"Write Error {ex.Message}"));
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
You should ALWAYS add a timeout to direct writes and reads to a peripheral.  I don't do this for the user because the OS doesn't do it for the user.  RX also easily handles this with Timeout as you noted. 

The problem with Write without response, is that I have no way of telling if it was successful or failed on iOS because peripheral.WroteCharacteristicValue is not called for that type of write on iOS.  This is why adding a timeout is so important.

**Comment by krobotics** [comment]
Thanks for the feedback, I can confirm this from https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518747-writevalue 

There is no way to handle any 'no response' errors gracefully. Therefore this is not a bug, I will close it.
