### ISSUE TITLE
Notification Sound not working in Android 7.0

### ISSUE THREAD

**Issue by Abby1991** [shinyorg/shiny#88]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Sensors

## Version of Library 
1.0.0.300-beta
## Version of OS(s) listed above with issue
Android 7.0 - API 24

## Steps to Reproduce
1. Create a notification and send it:
Notification nm = new Notification
            {
                Title = "Immediate",
                Message = "This is a immediate test notification",
            };
            notifications.Send(nm);

## Expected Behavior
Notification should appear with sound

## Actual Behavior
Notification is appearing but without sound

**Comment by aritchie** [comment]
You didn't set a sound on the Sound property
