### ISSUE TITLE
[Bug]: Bluetooth crash when debugging on iOS and writing to GattCharacteristic

### ISSUE THREAD

**Issue by micke-inor** [shinyorg/shiny#889]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [ ] iOS 12
- [X] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Steps to Reproduce:

Scan for devices.
When a device found stop scanning.

Connect to Bluetooth Device.
Get known GattCharacteristic
Write data to GattCharacteristic

----------------------------------------------------------------------------
Tested in VS2019, VS2022 and VS2022 preview.

Tested on
* iPhone X OS: 15.2.1
* iPhone 8 OS: 15.1
* IPad Air 2 OS: 13.7

Nuget Packages:
* Shiny 2.4.2.2996
* Shiny.BluetoothLE 2.4.2.2996
* Shiny.Core 2.4.2.2996
* Shiny.Framework 2.0.0.131
* Xamarin.Essentials  1.7.0
* Xamarin.Forms 5.0.0.2291

----------------------------------------------------------------------------

### Expected Behavior

Data written to GattCharacteristic or a catchable error.

### Actual Behavior

Application crash, it seems that it trying to allocate ~5Gigabyte ram.

### Exception or Log output

[0:] Connection Begin
[0:] ConnectAsync on Mainthread
[0:] CanWriteWithResponse: True
[0:] CanWriteWithoutResponse: False
[0:] CanRead: True
2022-01-21 14:39:28.507 Xamarin.PreBuilt.iOS[2402:579905] Xamarin.iOS: Received unhandled ObjectiveC exception: NSInvalidArgumentException *** NSAllocateMemoryPages(4974550952) failed

2022-01-21 14:39:28.507 Xamarin.PreBuilt.iOS[2402:579905] error: * Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mono/mini/mini-exceptions.c:452

=================================================================
	Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

	0x102c941e0 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info

	0x102c8ac5c - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash
	0x102c93728 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : sigabrt_signal_handler
	0x1f25c3c10 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x1f25d1378 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x18cab8f50 - /usr/lib/system/libsystem_c.dylib : abort
	0x102e1cff8 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : _ZL12log_callbackPKcS0_S0_iPv

	0x102dfd974 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : monoeg_g_logv_nofree

	0x102dfd9fc - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : monoeg_assertion_message

	0x102c87f40 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_get_generic_context_from_stack_frame
	0x102c87b3c - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_find_jit_info_ext

	0x102dfda48 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : monoeg_log_default_handler

	0x102c88fa8 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : unwinder_unwind_frame

	0x102c8a0cc - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_exception_internal
	0x102c89274 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_exception

	0x102e380c4 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : interp_throw

	0x102e37918 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full

	0x102e2ce1c - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : interp_entry_from_trampoline

	0x102c58978 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : native_to_interp_trampoline

	0x102e19cac - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : xamarin_throw_ns_exception

	0x18451d088 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>

	0x102e1d3cc - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : _ZL17exception_handlerP11NSException
	0x181c75cc0 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x19a435e28 - /usr/lib/libobjc.A.dylib : <redacted>
	0x19a536f58 - /usr/lib/libc++abi.dylib : <redacted>
	0x19a539efc - /usr/lib/libc++abi.dylib : __cxa_rethrow
	0x19a431cac - /usr/lib/libobjc.A.dylib : objc_exception_rethrow
	0x181b7b554 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x19d70638c - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal

	0x18429b958 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain

	0x102e39bb0 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : do_icall

	0x102e382e4 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper

	0x102e2f1d8 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full

	0x102d4e000 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_try_invoke_array

	0x102d47984 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked

	0x102e2d768 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x102c9ae70 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke

	0x102cf74f0 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_InternalInvoke

	0x102d07780 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_InternalInvoke_raw

	0x102e39bb0 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : do_icall

	0x102e382e4 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
	0x102e2f1d8 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full

	0x102e2d768 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke

	0x102c9ae70 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x102d47984 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked

	0x102d4cbf8 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked

	0x102c7f850 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec

	0x102e2b834 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : xamarin_main

	0x102c474f4 - /private/var/containers/Bundle/Application/528F78AD-6171-49D2-8E01-F3E597501549/ConSoft.iOS.app/Xamarin.PreBuilt.iOS : main
	0x1035b5aa4 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1b912f964):0x1b912f954  
ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)..
....
0x1b912f964  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91 
 ...T.#...{......
0x1b912f974  34 ee ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6 
 4........{...._.
0x1b912f984  c0 03 5f d6 7f 23 03 
d5 fd 7b bf a9 fd 03 00 91  .._..#...{......

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Runtime:ThrowNSException <0x00016>
	  at ObjCRuntime.Runtime:throw_ns_exception <0x0000a>
	  at ObjCRuntime.Runtime:throw_ns_exception <0x00032>
* Assertion: should not be reached at /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mono/mini/mini-exceptions.c:452

### Code Sample

using Shiny.BluetoothLE;
using System;
using System.Diagnostics;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Essentials;

namespace Sample
{
    class TestBle
    {

        public static async Task TestConnectAndWriteAsync(IPeripheral peripheral)
        {
            IGattCharacteristic gattCharacteristic;

            ConnectionConfig config = new ConnectionConfig()
            {
                AutoConnect = false,
            };

            try
            {
                await peripheral.ConnectAsync(config);
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"ConnectAsync ex {ex}");
                return;
            }

            try
            {
                /* Uuid must be changed to match the peripherials  */
                gattCharacteristic = await peripheral.GetKnownCharacteristicAsync(
                    "86db8288-2144-4f43-802b-927c4cdda45c", "8d39449c-5cbd-4407-bf96-05b234be3ecd");
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"ConnectAsynce ex {ex}");
                return;
            }

            /* Just to check if we are on mainthread */
            if (MainThread.IsMainThread)
            {
                Debug.WriteLine("ConnectAsync on Mainthread");

            }

            /* Write out some information about Gatt Characteristic */
            Debug.WriteLine($"CanWriteWithResponse: {gattCharacteristic.CanWriteWithResponse()}");
            Debug.WriteLine($"CanWriteWithoutResponse: {gattCharacteristic.CanWriteWithoutResponse()}");
            Debug.WriteLine($"CanRead: {gattCharacteristic.CanRead()}");

            await Task.Delay(500);

            try
            {
                //Write some data - This will crash the debug session.
                for (var i = 0; i < 10; i++)
                {
                    await Task.Delay(500);
                    await gattCharacteristic.WriteAsync(Encoding.ASCII.GetBytes("led=on"), true);

                    await Task.Delay(500);
                    await gattCharacteristic.WriteAsync(Encoding.ASCII.GetBytes("led=off"), true);
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
            }
        }
    }
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by micke-inor** [comment]
I have downloaded the app "nRF Connect" on iOS to verify both my phone and the Bluetooth device working.
I can write and read to characteristic as expected. And in my case i see a led on the device light up also.

**Comment by aritchie** [comment]
This will happen when you are missing the necessary permissions in your info.plist.  What does your startup look like?  Did you include a delegate?

**Comment by micke-inor** [comment]
This is my info.plist

[code]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>MinimumOSVersion</key>
	<string>9.0</string>
	<key>CFBundleDisplayName</key>
	<string>Sample App</string>
	<key>CFBundleIdentifier</key>
	<string>com.samplecompany.sample</string>
	<key>LSSupportsOpeningDocumentsInPlace</key>
	<string>YES</string>
	<key>CFBundleShortVersionString</key>
	<string>1.04.04</string>
	<key>UIAppFonts</key>
	<array>
		<string>Fonts/CustomFont.ttf</string>
	</array>
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>mailto</string>
    </array>
	<key>CFBundleName</key>
	<string>SampleApp</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>To read/write Device configurations and log data.</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>To read/write Device configurations and log data.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>To read/write Device configurations and log data via Bluetooth.</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>CFBundleVersion</key>
	<string>10404001</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>We store only related to the Device and no personal information.</string>
	<key>UTImportedTypeDeclarations</key>
	<array>
		<dict>
			<key>UTTypeDescription</key>
			<string>Device Configuration</string>
			<key>UTTypeIdentifier</key>
			<string>com.sample.tcf</string>
			<key>UTTypeConformsTo</key>
			<array>
				<string>public.data</string>
			</array>
			<key>UTTypeTagSpecification</key>
			<dict>
				<key>public.filename-extension</key>
				<array>
					<string>tcf</string>
					<string>TCF</string>
				</array>
			</dict>
		</dict>
	</array>
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeName</key>
			<string>Device Configuration</string>
			<key>LSHandlerRank</key>
			<string>Default</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.inorprocess.tcf</string>
			</array>
		</dict>
	</array>
	<key>NFCReaderUsageDescription</key>
	<string>Configure Device over NFC</string>
	<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
	<array>
		<string>D2760000850101</string>
	</array>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/AppIcon.appiconset</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
</dict>
</plist>
[/code]

**Comment by micke-inor** [comment]
I have get "PermissionStatus.Granted" from Xamarin permission LocationWhenInUse from Xamarin.Essentials.

Also iOS give me status "CBManagerAuthorization.AllowedAlways" when creating CreateCBCentralManager.
[iOS permissionsService Bluetooth.zip](https://github.com/shinyorg/shiny/files/7916926/iOS.permissionsService.Bluetooth.zip)

(if you click allow on the two dialogs on the phone)

**Comment by micke-inor** [comment]
The app is uninstalled for test, else iOS will cache permission and probably info.plist will not be applied again for Hot Restart.

Remove line NSBluetoothPeripheralUsageDescription and NSBluetoothAlwaysUsageDescription give error:
2022-01-21 23:41:04.235 Xamarin.PreBuilt.iOS[2640:705867] Critical: NSBluetoothPeripheralUsageDescription needs to be set - you will likely experience a native crash after this log .... And then a long log...

**Comment by aritchie** [comment]
@micke-inor I tried this exact code last night without issue.  There has to be something missing?  Hot Restart has some issues right now and the native crash doesn't seem to suggest BLE is the direct issue here.  Can you try this on a VS4mac environment?

**Comment by micke-inor** [comment]
I suspect Hot Restart also, i can get the Bluetooth to crash with same behavior.
I will test with VS4Mac when i get back to work and can fetch a Macbook Air with me.

**Comment by micke-inor** [comment]
I can get xamarin-bluetooth-le to crash also, so it not shiny i think..
I close the issue for now.

**Comment by michalholis** [comment]
@micke-inor Did you by any chance had an oppurtunity to test this issue on mac? I'm experiencing the same problems. I'm deploying with hot restart on physical device, so I I'm wandering if hot restart could be the issue. Thanks for the reply.
