### ISSUE TITLE
[Bug]: Cannot get notifications from BLE heart rate sensors when using the ManagedPeripheral

### ISSUE THREAD

**Issue by swlasse** [shinyorg/shiny#902]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

**Setup:**
1. Create new "Hello World" Xamarin Forms Project
2. Configure the project to use the latest stable release of Shiny ( https://www.nuget.org/packages/Shiny/2.4.2.2996 )
3. Scan for Heart Rate (HR) peripherals using the Managed Scanner in Shiny
4. Try to listen for notifications using the following setup:

```
// Constants
private const string HrServiceUuid = "0000180d-0000-1000-8000-00805f9b34fb";
private const string HrCharacteristicUuid = "00002a37-0000-1000-8000-00805f9b34fb";

// Create managed peripheral from the found HR peripheral
var managedPeripheral = new ManagedPeripheral(peripheral, RxApp.MainThreadScheduler);

// Subscribe to notifications on the managed peripheral
managedPeripheral
    .WhenAnyNotificationReceived()
    .SubOnMainThread(characteristicResult =>
    {
        // ISSUE: This code/callback is not invoked
        Debug.WriteLine($"== HR data from managed peripheral: {characteristicResult.Data[1]}");
    });

// Enable notifications (automatically connects to device if not already connected)
await managedPeripheral.EnableNotifications(true, HrServiceUuid, HrCharacteristicUuid);
```

**More context:**

I have tried to implement the following two changes in the `ManagedPeripheral` type and it seems to resolve this issue (please see the `=== START ===` and `=== END ===` comments in the following):

Added `.Switch()` in the constructor:
```
public ManagedPeripheral(IPeripheral peripheral, IScheduler? scheduler = null)
{
    ...

    this.Peripheral
        .WhenConnected()
        .Do(_ => this.notifyDispose = new CompositeDisposable())
        .Select(_ => this.RestoreNotifications())
        // === START ===
        .Switch()
        // === END ===
        .Subscribe()
        .DisposedBy(this.coreDispose);

    ...
}
```

Added `RestoreNotifications()` in the `EnableNotifications()` method:
```
public IObservable<Unit> EnableNotifications(bool enable, string serviceUuid, string characteristicUuid, bool useIndicationIfAvailable = false) =>
            this.GetChar(serviceUuid, characteristicUuid)
                .Select(x => x.EnableNotifications(enable, useIndicationIfAvailable))
                .Switch()
                .Do(_ =>
                {
                    var info = this.GetInfo(serviceUuid, characteristicUuid);
                    info.IsNotificationsEnabled = enable;
                    info.UseIndicationIfAvailable = useIndicationIfAvailable;
                })
                // === START ===
                .Select(_ => RestoreNotifications())
                .Switch();
                // === END ===
```

However, I am not sure if this is the right way forward (?)

As far as I can tell, the code in the current stable release is calling `RestoreNotifications()` when the peripheral is connected. That works well when handling reconnects, however, because `EnableNotifications()` calls `this.GetChar(serviceUuid, characteristicUuid)` a connection is made to the peripheral _before_ the HR characteristic has been added to the `characteristics` collection and _before_ `GattCharacteristicInfo.IsNotificationsEnabled = true` has been set - which in turn causes the HR characteristic not to be monitored.

**Please note:** I might have misunderstood the intended purpose and logic of the `ManagedPeripheral` and there might definitely be a better way to resolve this. In any case, I just wanted to make you aware that there might be an issue here.

Thanks for all your hard work on this project. I understand a lot of free time has gone into this, and I think you have done a great job.

Please feel free to reach out if something is unclear or if I can help you investigate this in any way.

### Expected Behavior

I am expecting the `managedPeripheral.WhenAnyNotificationReceived()` callback to be invoked.

### Actual Behavior

The `managedPeripheral.WhenAnyNotificationReceived()` callback is not invoked.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Thank you for the in-depth bug report and potential fixes.  I wish they all came in like this.  I will look to get these implemented right away.  It will be on nuget today under the 2.5 preview.

**Comment by swlasse** [comment]
Thank you very much for your swift reply and implementation of this. I have just tested the new version: `2.4.3.2998-preview` and I am now getting notifications from BLE heart rate sensors when using the `ManagedPeripheral`. Should we go ahead and close this issue?
