### ISSUE TITLE
[Bug]: Ble readrssi doesn't work on Android

### ISSUE THREAD

**Issue by ygl-rg** [shinyorg/shiny#913]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [X] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. connected a peripheral
2. try to call await peripheral.ReadRssi().ToTask(token)

### Expected Behavior

get the current rssi value

This function works fine on iOS

### Actual Behavior

got nothing besides of timeout exception

### Exception or Log output

when I read the following codes

https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE/Platforms/Android/Peripheral.cs

I noticed

```
public override IObservable<int> ReadRssi()
        {
            this.AssertConnection();

            return this.Context.Invoke(
                this.Context
                    .Callbacks
                    .ReadRemoteRssi
                    .Take(1)
                    .Select(x =>
                    {
                        if (x.IsSuccessful)
                            throw new BleException("Failed to get RSSI - " + x.Status);

                        return x.Rssi;
                    })
            );
        }
```

 Is "x.IsSuccessful" or "!x.IsSuccessful" ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
The readrssi call gets out into the execution queue.  It only generally times out if there are many read/writes going on at the same time.  Are you doing any other operations at the same time?


You are correct about the other issue.  I'll get that sorted out for the next preview

**Comment by ygl-rg** [comment]
Hi aritchie

     I called ReadRssi after a successful connection. I didn't do any read/write at that time.

**Comment by aritchie** [comment]
It should be resolved in the latest preview version on nuget

**Comment by aritchie** [comment]
No reply from user - closing as per internal testing
