### ISSUE TITLE
Generators not being created.

### ISSUE THREAD

**Issue by Colipe1** [shinyorg/shiny#916]
### Component/Nuget

Shiny.Core (Settings, Startup)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. Open the Beacons Sample app (this seems to be happening for me on the other samples too) on Visual Studio 2019 version 16.11.10.
2. Build the Android project

### Expected Behavior

The new files should be automatically generated when the project builds.

### Actual Behavior

None of the analyzer files are generated when the project builds. Instead, I get the warnings shown in the output below.

### Exception or Log output

>CSC : warning CS8032: An instance of analyzer Shiny.Generators.AndroidActivitySourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.AndroidApplicationSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.iOSAppDelegateSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.StaticClassSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
3>CSC : warning CS8032: An instance of analyzer Shiny.Generators.UwpSourceGenerator cannot be created from C:\Users\cshipe\.nuget\packages\shiny\2.5.0.2985-preview\analyzers\dotnet\cs\Shiny.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

### Code Sample

This is happening with the sample projects. I am using version 2.4.3.3003 of Shiny.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
As per the code of conduct, issues are not taken for the samples. 

This is obviously a tooling issue with VS2019 since 2022 compiles them just fine.
