### ISSUE TITLE
[Bug]:  Characteristics returned from GetAllCharacteristicsAsync() don't trigger Notify()

### ISSUE THREAD

**Issue by mphill** [shinyorg/shiny#923]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

```
  var characteristics = await device.GetAllCharacteristicsAsync();

  foreach (var characteristic in characteristics)
  {
      if (characteristic.CanNotify())
      {
          characteristic.Notify().Subscribe(data =>
          {
              Debug.WriteLine(data.Data[0]);

          });
      }
  }
```

For this to work, you must write the code as such:

```
  device.GetAllCharacteristics().Subscribe(characteristics =>
  {
      foreach (var characteristic in characteristics)
      {
          if (characteristic.CanNotify())
          {
              characteristic.Notify().Subscribe(data =>
              {
                  Debug.WriteLine(data[0]);
              });
          }
      }
  });
```

### Expected Behavior

Notify will fire when data is received from the BLE device

### Actual Behavior

When characteristics are loaded from GetAllCharacteristicsAsync, Notify will never fire.

### Exception or Log output

N/A

### Code Sample

See steps to reproduce

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
I just tried this on a sample and it worked fine.  https://github.com/shinyorg/samples/blob/main/BluetoothLE-Functions/Sample/MainViewModel.cs

**Comment by mphill** [comment]
Looking at your example code. One potential source of the issue is I connected to the device immediately before calling GetAllCharacteristicsAsync.  Maybe there is a timing issue?

**Comment by aritchie** [comment]
I connect just before requesting the characteristics here as well.  Is there more to this test case that may be missing?

**Comment by mphill** [comment]
Perhaps it’s the device I’m using.   I have a work around for now and I’ll continue to do more investigating.  If I find something obvious I’ll open a PR.
