### ISSUE TITLE
[Bug]: iOS Interval not respected in Background 

### ISSUE THREAD

**Issue by bb281** [shinyorg/shiny#937]
### Component/Nuget

GPS, Geofencing, Motion Activity (Shiny.Locations)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

1. Set the GPS Request to Background Realtime. Set the Interval to be 30 seconds
2. Once you close the app, iOS usually triggers a second permissions prompt stating "Allow "[your app]" to also use your location even when you are not using the app?"
3.  Select "Change to Always Always Allow".
4. Breakpoint and Observe the OnReading fires continuously not respecting the Interval setting.

I've seen in the comments section that iOS does not respect the interval in the Foreground. However, for iOS, I also get this behavior for the Background where the OnReading fires every second. As a workaround, I wait a specific time period before processing the GPS reading. Anyone else observing this behavior for the Background where the Interval is not respected in the Background? Appreciate any feedback/insight. Thanks

### Expected Behavior

In the Background, I expect iOS to respect the interval and OnReading fires accordingly.

### Actual Behavior

In the background, iOS does not respect the interval and OnReading fires continuously (< 1 sec).

### Code Sample

My GPS Request:
`_gpsRequest = new GpsRequest { BackgroundMode = GpsBackgroundMode.Realtime, Priority = GpsPriority.Highest, Interval = TimeSpan.FromMinutes(5), ThrottledInterval = TimeSpan.FromSeconds(9) }`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Looks like Apple deprecated all of this in iOS 13, 14 was an "allowed" timeframe and as of 15, it is just ignored.  

https://developer.apple.com/documentation/corelocation/cllocationmanager/1620547-allowdeferredlocationupdates

https://developer.apple.com/documentation/corelocation/cllocationmanager/1423830-deferredlocationupdatesavailable

**Comment by bb281** [comment]
I'm not sure where you are seeing it as "allowed" timeframe in 13 and 14 and ignored in 15 in the links above.

The change below doe not make a call to AllowDeferredLocationUpdatesUntil
https://github.com/shinyorg/shiny/commit/54b86c51700501602b9f7fbceb6f8da1f8ff7447

Also, it seems like the latest commit, the throttle interval or distance params are not being used and the distanceFilter set to none.

I tried setting the distance parameter and observed it does not respect it. Appreciate any insight on what's the best way to filter based on distance. Or is this not possible now?

Thank you

**Comment by aritchie** [comment]
Those values are used in the delegate where they are supposed to be used, but now that apple has removed the functionality, there are no filters

**Comment by bb281** [comment]
Hi - The resulting functionality is that iOS continuously polls in the background at a polling interval < 1 sec. I imagine this leads to significant battery drain. This does not seem like a viable solution for backgrounding with GPS. Do you know if this is being addressed with Apple? I appreciate any additional feedback.

**Comment by aritchie** [comment]
I would suggest researching their documentation.
