### ISSUE TITLE
[Bug]: Characteristic UUIDs are partly not complete

### ISSUE THREAD

**Issue by bluekuen** [shinyorg/shiny#938]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [X] iOS 12
- [X] iOS 13
- [X] iOS 14
- [X] iOS 15
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

We just switched from ACR.Plugins.Bluetooth LE to shiny and now have several problems with the characteristics on iOS. 
We implemented Http over BLE protocol following the bluetooth specification and there we need several characteristics for the communication. We assigning following characteristics:

                    CharacteristicHeader = await _service
    .GetKnownCharacteristic(CharacteristicHeaderString)
    .Timeout(to)
     .ToTask();

                    CharacteristicBody = await _service
    .GetKnownCharacteristic(CharacteristicBodyString)
    .Timeout(to)
     .ToTask();

                    CharacteristicStatusCode = await _service
    .GetKnownCharacteristic(CharacteristicStatusCodeString)
    .Timeout(to)
     .ToTask();

                    CharacteristicControlPoint = await _service
    .GetKnownCharacteristic(CharacteristicControlPointString)
    .Timeout(to)
     .ToTask();**

**

Now the strange thing is that only one is assigned. After severe investigation i found out that the characteristic UUID is not complete: 

```
_characteristics = await _service.GetCharacteristics().Where(list => list.Count == 6).ToTask();
foreach(var characteristic in _characteristics)
{
    logger.Debug("characteristic:" + characteristic.ToString());
}
```

2022-03-07 09:36:23.615 MyAppS[730:154040] 2022-03-07 09:36:23.6155 DEBUG characteristic:2ab6
2022-03-07 09:36:23.616 MyApp[730:154040] 2022-03-07 09:36:23.6155 DEBUG characteristic:2ab7

2022-03-07 09:36:23.616 MyAppS[730:154040] 2022-03-07 09:36:23.6161 DEBUG characteristic:2ab8
2022-03-07 09:36:23.616 MyApp[730:154040] 2022-03-07 09:36:23.6161 DEBUG characteristic:2ab9
2022-03-07 09:36:23.616 MyApp[730:154040] 2022-03-07 09:36:23.6161 DEBUG characteristic:2aba
2022-03-07 09:36:23.616 MyApp[730:154040] 2022-03-07 09:36:23.6161 DEBUG characteristic:00000100-710e-4a5b-8d75-3e5b444bc3cf

### Expected Behavior

Characteristics get assigned

### Actual Behavior

Only one characteristc has the correct UUID

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Those UUIDs are complete.  They are 16bit and taken straight from what the OS provides.  This is why the change from GUID to string was made the library.
