### ISSUE TITLE
Null Reference Exception in Android when using Xamarin Shell while navigating using the device back button

### ISSUE THREAD

**Issue by dominioncfg** [shinyorg/shiny#95]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [x] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [x] Locations
 - [ ] HTTP Transfers
 - [x] Notifications
 - [ ] Sensors

## Version of Library
Shiny.Core: 1.0.0.357-beta
Shiny.Locations: 1.0.0.357-beta
Shiny.Notifications: 1.0.0.357-beta
## Version of OS(s) listed above with issue
Android 5.0
Android 9.0 (Emulator)

## Steps to Reproduce
1.Run the App (needs to be Xamarin Forms Shell)
2.Tap on the Device Back Button
3.Null Reference Exception

## Expected Behavior
The app should go to the background

## Actual Behavior
        Hi Allan, I've created a Hello World example using Shiny and it worked just fine, I was able to use the combo Locations + Notifications without any problem, now this hello word was using the classic await Navigation.PushAsync(...); Then I integrated Shiny again in my actual App (Is using the new Shell approach) and I noticed that started crashing whenever I navigated back of the app using the back button, then after hours of making sure that I did the setup properly in my actual app what I did is basically add Xamarin forms Shell to the hello world example and I get the exact same error: A null reference exception in a background thread. Also I think that the problem is in the core library because I tried to disable this:
        services.UseGeofencing<MyGeofenceDelegate>();
        services.UseNotifications();
 and the  issue remains.

**Comment by aritchie** [comment]
You need to supply an exception with a full stack trace please.  Some sort of sample would also be nice.  Shiny doesn’t execute anything when the app switching between foreground/background

**Comment by dominioncfg** [comment]
Actually the issue is because I updated Xamarin.Forms
