### ISSUE TITLE
[Bug]: Cannot get notifications from some BLE characteristics with WhenNotificationReceived() from ManagedPeripheral

### ISSUE THREAD

**Issue by gsgou** [shinyorg/shiny#958]
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What platform(s) are effected?

- [X] iOS 12
- [X] iOS 13
- [X] iOS 14
- [X] iOS 15
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

Call:
FAILS:
_managedPeripheral
                .WhenNotificationReceived(serviceUuid, characteristicUuid)
                .SubOnMainThread(data =>
                {
                    System.Diagnostics.Debug.WriteLine($"== HR data from managed peripheral: {data[0]}");
                });
 WORKS:               
_managedPeripheral
                .WhenAnyNotificationReceived()
                .SubOnMainThread(characteristicResult =>
                {
                    System.Diagnostics.Debug.WriteLine($"== HR data from managed peripheral: {characteristicResult.Data[0]}");
                });
 WORKS:               
 _managedPeripheral
                .WhenAnyNotificationReceived()
                .Where(x =>
                    x.Characteristic.Service.Uuid.Equals(serviceUuid, StringComparison.InvariantCultureIgnoreCase) &&
                    x.Characteristic.Uuid.Equals(characteristicUuid, StringComparison.InvariantCultureIgnoreCase))
                .Select(x => x.Data)
                .SubOnMainThread(data =>
                {
                    System.Diagnostics.Debug.WriteLine($"== HR data from managed peripheral: {data[0]}");
                });

### Expected Behavior

Data shown in "Application Output"

### Actual Behavior

Data not shown in "Application Output"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please submit a PR in the future for something you have solved.

**Comment by gsgou** [comment]
Thanks i will.
