### ISSUE TITLE
[Bug]: IPlatform methods inside the compiler directive MONOANDROID are not found in Android project on v2.5.0

### ISSUE THREAD

**Issue by gsgou** [shinyorg/shiny#959]
### Component/Nuget

Shiny.Core (Settings, Startup)

### What platform(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [X] Android 8
- [X] Android 9
- [X] Android 10
- [X] Android 11
- [X] Android 12
- [ ] UWP (Sponsors ONLY)

### Steps To Reproduce

IPlatform methods inside the compiler directive MONOANDROID are not found in Android on v2.5.0
for example:
ShinyHost.Resolve<IPlatform>().**OnRequestPermissionsResult**(requestCode, permissions, grantResults);
Activity.**ShinyOnRequestPermissionsResult**(requestCode, permissions, grantResults);

### Expected Behavior

Activity.OnRequestPermissionsResult is found in assembly in Android project

### Actual Behavior

Activity.OnRequestPermissionsResult is not found in assembly in Android project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please follow the code of conduct.  

> Issues are only taken for the latest STABLE version of the library - preview versions of the library can be discussed on the SponsorConnect Discord channel available to sponsors only

**Comment by gsgou** [comment]
Thanks fyi Alan
