### ISSUE TITLE
[Feature Request]: Make IGattCharacteristic.SubscribedCentrals an ObservableCollection

### ISSUE THREAD

**Issue by rhinohq** [shinyorg/shiny#981]
### Summary

Currently, the `Shiny.BluetoothLE.Hosting.IGattCharacteristic.SubscribedCentrals` is an `IReadOnlyList<IPeripheral>`. I propose changing this to an `ObservableCollection<IPeripheral>` so that developers know when a device has unsubscribed/disconnected.

Looking through the code, this seems technically feasible and likely would not cause a breaking change for the majority of developers. Raising an event when add or removing from the `IReadOnlyList<IPeripheral>` could also be an option, however.

I am happy to pick up this work if a conclusion is met.

### API Changes

`IGattCharacteristic.SubscribedCentrals: IReadOnlyList<IPeripheral>` would become `IGattCharacteristic.SubscribedCentrals: ObservableCollection<IPeripheral>`.

OR

`public event EventHandler<CharacteristicSubscriptionEventArgs> OnCharacteristicSubscription` would be added to `IGattCharacteristic` where `CharacteristicSubscriptionEventArgs` looks as follows:

`public class CharacteristicSubscriptionEventArgs`
`{`
    `public IPeripheral Peripheral { get; set; }`
    `public bool Subscribed { get; set; }`
`}`

### Intended Use Case

Currently, there is no way of knowing when a device has disconnected. This will remedy that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
https://github.com/shinyorg/samples/blob/bdaf209fdf09d8a2f561c8c1fb0a07b5792e7832/BluetoothLE-Hosting/Sample/MainViewModel.cs#L171

https://github.com/shinyorg/shiny/blob/master/src/Shiny.BluetoothLE.Hosting/IGattCharacteristicBuilder.cs#L8
