### ISSUE TITLE
[Feature Request]: Question concerning  Mobile Backgrounding Question

### ISSUE THREAD

**Issue by BicycleMark** [shinyorg/shiny#993]
### Summary

Hello Mobile Devs:
   on Mobile platforms do we have executable code that runs in separate process space for BackGrounding?

As analogous to Windows Service? As Analogous to Unix systemctl daemons? meaning they run each and every time the system is started.

If the answer is yes:
   1) Are they allowed to send visual alerts? 
   2) can they take it one step farther and launch an app
   3) Does Shiny do this.

Mark Wardell

### API Changes

just a question

### Intended Use Case

just a question

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritchie** [comment]
Please use the discussions forum in the future and follow the code of conduct within this project.

These questions are better answered by looking at the OS documentation than this project.  The answer isn't a straight forward yes/no.  Background jobs in Shiny are not running constantly like a daemon.  They react to system events.

1. Yes - you can use local or push notifications
2. If the user clicks on the notification
3. Shiny support several system events as well as having packages for both local & push notifications
